    public boolean isRequired()
            case WMIConstants.CIM_UINT16:


            case WMIConstants.CIM_REAL32:
    }
        super(wmiClass, attribute);
            }
    @Override
    }
            case WMIConstants.CIM_UINT64:
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
    @Nullable

                return DBIcon.TYPE_UNKNOWN;
    @Nullable

    }
    }
import org.jkiss.wmi.service.WMIConstants;
            case WMIConstants.CIM_BOOLEAN:
    }
    {
    @NotNull
    {
    {
        return element.getType();
        return element.getTypeName();
            case WMIConstants.CIM_UINT8:
    {
        return getPropertyImage(element.getType());
 * See the License for the specific language governing permissions and
    public int getTypeID()
    }
            if (maxLengthQ instanceof Number) {
    public boolean isAutoGenerated()
    {
    @Override

    @Override
    @Override
        return false;
 *
    }
    public String getFullTypeName() {
                return DBPDataKind.STRING;
 *
    public DBPDataKind getDataKind()
    }
    public Integer getPrecision()
import org.jkiss.code.NotNull;
    }

    public String getTypeName()

            case WMIConstants.CIM_SINT8:
        return 0;
    {
 *
            case WMIConstants.CIM_SINT32:
            case WMIConstants.CIM_REAL64:
            log.warn(e);
        return getFlagQualifier(WMIConstants.Q_Key) || getFlagQualifier(WMIConstants.Q_CIM_Key);
        return CommonUtils.toString(element.getValue());
                return DBIcon.TYPE_BOOLEAN;
        return getDataKindById(element.getType());
    {
/*
                return DBPDataKind.NUMERIC;
        try {
import org.jkiss.wmi.service.WMIException;
            case WMIConstants.CIM_UINT16:
 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.wmi.service.WMIObjectAttribute;
    @Override
import org.jkiss.dbeaver.model.meta.Property;
    public long getTypeModifiers() {
        return 0;
            case WMIConstants.CIM_BOOLEAN:
import org.jkiss.dbeaver.DBException;
        switch (type) {
import org.jkiss.code.Nullable;
 * You may obtain a copy of the License at
    {
            case WMIConstants.CIM_SINT16:
 * limitations under the License.

public class WMIClassAttribute extends WMIClassElement<WMIObjectAttribute> implements DBSEntityAttribute, DBPImageProvider
            case WMIConstants.CIM_UINT32:
    @Property(viewable = true, order = 10)
            case WMIConstants.CIM_SINT8:
            case WMIConstants.CIM_UINT64:
    public boolean isKey() throws DBException
    public static DBPImage getPropertyImage(int type)

            case WMIConstants.CIM_CHAR16:
}
        } catch (WMIException e) {
        }

                return ((Number) maxLengthQ).longValue();
    public int getOrdinalPosition()
                return DBIcon.TYPE_NUMBER;
    @Property(viewable = true, order = 20)
            case WMIConstants.CIM_SINT16:
            case WMIConstants.CIM_DATETIME:
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            case WMIConstants.CIM_UINT32:
    @Nullable
    @Override
package org.jkiss.dbeaver.ext.wmi.model;

    public long getMaxLength()


    public String getDefaultValue()
 * Class property

            case WMIConstants.CIM_CHAR16:
    @Override
        switch (type) {
import org.jkiss.utils.CommonUtils;
            default:
/**
    public static DBPDataKind getDataKindById(int type)
        return DBUtils.getFullTypeName(this);
    public Integer getScale()
 */
    @Override
            case WMIConstants.CIM_UINT8:
 * DBeaver - Universal Database Manager

    public DBPImage getObjectImage()
 */
{
import org.jkiss.dbeaver.model.*;
            case WMIConstants.CIM_SINT32:
    @NotNull
        }
    {
            default:

 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
    @Override
            case WMIConstants.CIM_STRING:
    {

    @Override
    protected WMIClassAttribute(WMIClass wmiClass, WMIObjectAttribute attribute)
            case WMIConstants.CIM_SINT64:
    }
            Object maxLengthQ = getQualifiedObject().getQualifier(WMIConstants.Q_MaxLen);
            case WMIConstants.CIM_REAL64:
    }
                return DBPDataKind.BOOLEAN;
                return DBIcon.TYPE_STRING;
        return 0;
    @Override
        return 0;
 *     http://www.apache.org/licenses/LICENSE-2.0
    @Override
    {
    {
    }
            case WMIConstants.CIM_REAL32:

                return DBPDataKind.DATETIME;
    private static final Log log = Log.getLog(WMIClassAttribute.class);
                return DBIcon.TYPE_DATETIME;
    }
    }
    {
 * Licensed under the Apache License, Version 2.0 (the "License");
                return DBPDataKind.OBJECT;
        }
    @NotNull
 * you may not use this file except in compliance with the License.
    @Override
    {
            case WMIConstants.CIM_STRING:
    }
        return false;
        return 0;
    }
            case WMIConstants.CIM_DATETIME:

 * distributed under the License is distributed on an "AS IS" BASIS,
            case WMIConstants.CIM_SINT64:

import org.jkiss.dbeaver.Log;
    {
