    @NotNull
    {
 *
    @Nullable
    }
            // Init meta properties
 * DBeaver - Universal Database Manager

        public boolean isAutoGenerated() {
            throw new DBCException(e, session.getExecutionContext());
 * you may not use this file except in compliance with the License.
    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
        @Override
            return attribute.getTypeName();
        public String getTypeName()
    // Meta property

        @Override
    }
        @Override
        private MetaProperty(WMIObjectAttribute attribute, int index)
            return null;

            } else {

        return null;
        }
        } catch (WMIException e) {
import org.jkiss.code.NotNull;
            return row.getValue(properties.get(index).getName());
    @Override
        return null;
    {
            return attribute.getName();
    }

                throw new DBCException("Column index " + index + " out of bounds (" + properties.size() + ")");
/*
    public String getEntityName()

                properties = Collections.emptyList();
        {
    {
    @Override
                metaObject = rows.iterator().next();
            return attribute.getType();
            return false;


        return true;
            return 0;
            }
    private class MetaProperty implements DBCAttributeMetaData,DBPImageProvider
        return classObject == null ? null : classObject.getName();
        while (position-- > 0) nextRow();
public class WMIResultSet implements DBCResultSet, DBCResultSetMetaData, DBCEntityMetaData
    private WMIObject row;
        @Override
    public boolean moveTo(int position) throws DBCException
 *

                return null;

                }
    }
        row = iterator.next();
        if (!this.iterator.hasNext()) {
            return row.getValue(name);
    }
        this.iterator = rows.iterator();
    @Override
        }

        }
    }
    }
            return false;
            return 0;
    public WMIResultSet(@NotNull DBCSession session, WMIClass classObject, Collection<WMIObject> rows) throws WMIException
        return null;
        @Nullable
        }
        this.classObject = classObject;

{
    @NotNull
        @NotNull
    @Override
import org.jkiss.utils.CommonUtils;
        for (WMIObject row : rows) {
            this.index = index;
        return true;
    {
    {
        {
            }
    }
                    if (!prop.isSystem()) {
        {
 * Unless required by applicable law or agreed to in writing, software
 * Copyright (C) 2010-2025 DBeaver Corp and others
    public DBCSession getSession()

        @NotNull

    @Override
    }
        }
    @Override
        @NotNull

            throw new DBCException("Can't read value qualifiers");
import org.jkiss.dbeaver.model.DBPImageProvider;
        } catch (WMIException e) {
        @Nullable
    private Iterator<WMIObject> iterator;
        @Override
 * limitations under the License.
    }
    {
        return properties;
        {
            return WMIResultSet.this;
import org.jkiss.dbeaver.model.exec.*;
    private Collection<WMIObject> rows;
        try {
        this.session = session;
    // DBCTableMetaData
    @Override
        }
            return attribute.getTypeName();
    @Override
        }
    }
    @Nullable
                metaObject = null;

    @Override
    {
    public boolean nextRow() throws DBCException

/**
        @Override
        public DBPDataKind getDataKind()
        @Override
    }
        @Override
        public Integer getPrecision()
        }
    public Object getFeature(String name) {
        }
        {
 * You may obtain a copy of the License at

    public String getSchemaName() {

        return statement;

            this.attribute = attribute;
 * See the License for the specific language governing permissions and

    @Override

        @Override
                for (WMIObjectAttribute prop : props) {
        {
            if (metaObject == null) {
        @NotNull
        public boolean isRequired()
    public DBCStatement getSourceStatement()
 */
            } else if (!rows.isEmpty()) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    {
        @Override

        this.statement = new LocalStatement(session, "");
    @NotNull

import org.jkiss.dbeaver.model.data.DBDValueMeta;

        this.iterator = rows.iterator();
                Collection<WMIObjectAttribute> props = metaObject.getAttributes(WMIConstants.WBEM_FLAG_ALWAYS);
    private final DBCStatement statement;

        }
        @Override
        @Override
        {
        return this;
        }
        return null;
        {
        public DBPImage getObjectImage()
    }
            }
        }
    /////////////////////////////////////////////////////////////
            }
    }

            if (classObject != null) {
            return false;
import java.util.*;
    public void close()
        {
        public int getTypeID()
 */

        {
        @Override
            return new WMIValueMeta(qualifiers);
        }


        public String getEntityName()
        {
        @Override
            return false;
    public Object getAttributeValue(String name) throws DBCException {
        }
        public long getTypeModifiers() {
        this.rows = rows;
        {
    /////////////////////////////////////////////////////////////

            WMIObject metaObject;
    }
    // DBCResultSetMetaData
    {
    @Override
    @Override
            throw new DBCException(e, session.getExecutionContext());

        } catch (WMIException e) {

 *
import org.jkiss.dbeaver.DBException;
        rows.clear();

        }
        @Override
 * Licensed under the Apache License, Version 2.0 (the "License");
        this.row = null;
    private WMIClass classObject;
        private final WMIObjectAttribute attribute;
        }
    public DBDValueMeta getAttributeValueMeta(int index) throws DBCException
            return WMIClassAttribute.getDataKindById(attribute.getType());


    public DBCResultSetMetaData getMeta() throws DBCException
        public String getLabel()
        }

        {
    @Nullable

    {
        }
 *     http://www.apache.org/licenses/LICENSE-2.0
        @NotNull
import org.jkiss.dbeaver.model.DBPDataKind;
                metaObject = classObject.getClassObject();
        public String getName()
    public List<? extends DBCAttributeMetaData> getAttributes()
package org.jkiss.dbeaver.ext.wmi.model;
                int index = 0;
    {

            if (index >= properties.size()) {

    /////////////////////////////////////////////////////////////
    @NotNull
    public DBDValueMeta getRowMeta() throws DBCException
 * WMI result set
    }

        try {
    private DBCSession session;
        public int getOrdinalPosition()
        {

        row = null;
import org.jkiss.code.Nullable;
            if (CommonUtils.isEmpty(qualifiers)) {
        @Override
        private final int index;
        public long getMaxLength()
import org.jkiss.wmi.service.*;
        public Integer getScale()
        public Object getSource() {
        }
        }
    public String getResultSetName() throws DBCException {
            return 0;
            Collection<WMIQualifier> qualifiers = row.getQualifiers();
                    }
        @Nullable
    @NotNull
        }
    @Override
            row.release();
        }

            } else {
    public String getCatalogName() {
                properties = new ArrayList<>(props.size());


        @Override
            return index;
        public String getFullTypeName() {

    {
    }
import org.jkiss.dbeaver.model.DBPImage;
        @Nullable
    @Override
}
    @Override
        }
    private List<DBCAttributeMetaData> properties;
            return classObject == null ? null : classObject.getName();
    public Object getAttributeValue(int index) throws DBCException
        return null;
        {
    }
        }
        }
        public boolean isReadOnly()
        {
            return attribute.getName();
        return session;
        try {
            return 0;

            return WMIClassAttribute.getPropertyImage(attribute.getType());
    {
import org.jkiss.dbeaver.model.impl.local.LocalStatement;
        public DBCEntityMetaData getEntityMetaData()
        @Override
                        properties.add(new MetaProperty(prop, index++));
