/**
import org.jkiss.dbeaver.model.DBPEvaluationContext;

    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, @Nullable String tableName, @Nullable String tableType, @Nullable JDBCResultSet dbResult) {
        return new HiveTableColumn(table, columnName, typeName, valueType, sourceType, ordinalPos, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
 * DBeaver - Universal Database Manager
            return false;
                    tableType,
        boolean autoIncrement,
 * Copyright (C) 2010-2026 DBeaver Corp and others
import org.jkiss.code.Nullable;
 * distributed under the License is distributed on an "AS IS" BASIS,
 * limitations under the License.
                    String ddl = sql.toString();
import org.jkiss.code.NotNull;
                        ddl = ddl.replace("CREATE VIEW", "CREATE OR REPLACE VIEW");
        GenericDataSource dataSource = sourceObject.getDataSource();
    ) {
    }
    public GenericTableIndex createIndexImpl(@NotNull GenericTableBase table, boolean nonUnique, String qualifier, long cardinality, String indexName, DBSIndexType indexType, boolean persisted) {
        } catch (SQLException e) {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read Hive view/table source")) {
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
    }
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
import org.jkiss.dbeaver.model.DBPDataSource;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                        }
 *

        String typeName,
 * HiveMetaModel
                    tableName,
import org.jkiss.dbeaver.model.sql.format.SQLFormatUtils;

import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
import org.jkiss.dbeaver.model.struct.DBSObject;
/*

        String columnName,
            return new GenericView(
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
package org.jkiss.dbeaver.ext.hive.model;
import org.jkiss.dbeaver.model.DBUtils;
 * You may obtain a copy of the License at
                        sql.append(line).append("\n");
        if (dataSource instanceof JDBCDataSource) {
    @NotNull
{
    public boolean supportsNotNullColumnModifiers(DBSObject object) {
    @Override
        int valueType,
    }
    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject, @NotNull Map<String, Object> options) throws DBException {
 * you may not use this file except in compliance with the License.
    @Override

 *
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        }
        return false;
public class HiveMetaModel extends GenericMetaModel
                    return ddl;
            {
 *
}
    }
import org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource;
    }
import org.jkiss.dbeaver.model.struct.rdb.DBSIndexType;
import org.jkiss.dbeaver.ext.generic.model.*;
        boolean notNull,
            throw new DBDatabaseException(e, dataSource);
        long charLength,
                        String line = dbResult.getString(1);
                            continue;
        int radix,
    @Override
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {

    @Override
                    container,
    @Override
import org.jkiss.dbeaver.DBException;
    public HiveMetaModel() {
 * Licensed under the Apache License, Version 2.0 (the "License");

 *     http://www.apache.org/licenses/LICENSE-2.0
                    }
        } else {
    }
        return new HiveIndex((HiveTable) table, indexName, persisted, "", indexType.getName(), null);
    @Override
        long columnSize,
        return getTableDDL(monitor, sourceObject, options);
        }
        @NotNull DBRProgressMonitor monitor,
        String remarks,
        super();
                        if (line == null) {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import java.util.Map;
    @NotNull
        Integer precision,
    }
                }
                    while (dbResult.next()) {
    public GenericTableColumn createTableColumnImpl(
                "SHOW CREATE TABLE " + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL)))
        int ordinalPos,
        return new HiveDataSource(monitor, container, this);
        DBPDataSource dataSource = object.getDataSource();

        String defaultValue,
        }
            return ((JDBCDataSource) dataSource).isServerVersionAtLeast(3, 0);
import java.sql.SQLException;
        boolean autoGenerated
    @Override
        @NotNull GenericTableBase table,
                    if (sourceObject.isView()) {
                    }
 * See the License for the specific language governing permissions and

        Integer scale,

        if (tableType != null && isView(tableType)) {
    public boolean supportsTableDDLSplit(@NotNull GenericTableBase sourceObject) {
    }
            }
    @Override
    @NotNull
        int sourceType,
 */

import org.jkiss.dbeaver.model.DBPDataSourceContainer;
    }
        @Nullable JDBCResultSet dbResult,
                    dbResult);
                    StringBuilder sql = new StringBuilder();
        return new HiveTable(container, tableName, tableType, dbResult);

 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.DBDatabaseException;
 */
                        return SQLFormatUtils.formatSQL(sourceObject.getDataSource(), ddl);
