public class HiveTableColumn extends GenericTableColumn {

 * you may not use this file except in compliance with the License.
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
package org.jkiss.dbeaver.ext.hive.model;
 *
    }
 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
 */

 * Licensed under the Apache License, Version 2.0 (the "License");
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and

/*
 *
    public HiveTableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) {
 * DBeaver - Universal Database Manager
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
}
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Copyright (C) 2010-2024 DBeaver Corp and others
 * limitations under the License.
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
 * You may obtain a copy of the License at
