        long minValue = JDBCUtils.safeGetLong(dbResult, "MIN_VALUE");
                            "SYSOBJECTS SCH_OBJ,\n" +
                    "AND TABTRIG_OBJ_INNER.SCHID = SCH_OBJ_INNER.ID " +
            case PROCEDURE -> DamengConstants.ObjectType.PROCEDURE;
    @Override
        JDBCPreparedStatement dbStat = session.prepareStatement("SELECT " +
        return switch (dbResult.getString(DamengConstants.TYPE$)) {
                "GROUP BY\n" +
        List<GenericTableConstraintColumn> columns = new ArrayList<>(columnNameList.size());

            "AND SCH_OBJ.NAME = ?");
        }
    }
        DamengConstants.ObjectType objectType = switch (procedureType) {
            "\nFROM " +
    }
                "TABTRIG_OBJ_INNER.NAME AS TRIGGER_NAME, TAB_OBJ_INNER.NAME AS OWNER,* " +
    @Override
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    public boolean supportsDatabaseTriggers(@NotNull GenericDataSource dataSource) {
                "AND CONS_OBJ.PID = TAB_OBJ.ID\n" +
        return true;
                dbStat.setString(2, table.getName());
    public GenericTableConstraintColumn[] createConstraintColumnsImpl(@NotNull JDBCSession session, @NotNull GenericTableBase parent, @NotNull
                    "TABTRIG_OBJ_INNER.NAME " +
        if (name == null) {
        Integer precision,
    }

                "SYSCONS.VALID,\n" +
                            "SYSOBJECTS PROC_OBJ,\n" +
                }
                            "PROC_OBJ.VALID\n" +
        return new DamengDataTypeCache(container);
import java.util.List;
            "\nWHERE SEQ_OBJ.SCHID = SCH_OBJ.ID " +
    public GenericTableBase createTableImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @NotNull GenericMetaObject tableObject, @NotNull JDBCResultSet dbResult) {
                "OR SYSINDEXES.ID IS NULL)\n" +
        if (CommonUtils.isEmpty(name)) {

        Integer scale,
                        DBSProcedureType routineType = DBSProcedureType.PROCEDURE;
        return true;
    @Override
import java.util.Map;
 * Licensed under the Apache License, Version 2.0 (the "License");

    public DamengSchema createSchemaImpl(@NotNull GenericDataSource dataSource, GenericCatalog catalog, @NotNull String schemaName) throws DBException {

        @NotNull JDBCResultSet dbResult

        dbStat.setString(1, forParent.getName());
                charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
    }
                                JDBCUtils.safeGetString(dbResult, "NAME"),
                                JDBCUtils.safeGetString(dbResult, "NAME"),
            "SEQ_OBJ.INFO1 & 0x00FF00 IS_ORDER," +
                "AND TAB_OBJ.SCHID = SCH_OBJ.ID\n" +
                    tableName,
import java.sql.SQLException;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
                dbStat.setString(1, table.getSchema().getName());
                "AND CONS_OBJ.SUBTYPE$ = 'CONS'\n" +
public class DamengMetaModel extends GenericMetaModel {

        return new DamengDataSource(monitor, container, this);
                            "AND SF_CHECK_PRIV_OPT(UID(),\n" +
                "SYSCONS SYSCONS\n" +
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
    @Override
            "SYSOBJECTS SCH_OBJ " +
            case UNKNOWN -> null;
        return new GenericContainerTrigger(container, name, null);
    @Override
    @Override
                "WHERE " +
            return null;
                dbStat.setString(1, container.getName());
        }
        String name = JDBCUtils.safeGetString(dbResult, 1);
    }
            case "U" -> DBSEntityConstraintType.UNIQUE_KEY;
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read Dameng procedure source")) {
    @Override

                "SYSOBJECTS TABTRIG_OBJ_INNER, " +
 * you may not use this file except in compliance with the License.
                            "PROC_OBJ.INFO1,\n" +
import org.jkiss.dbeaver.DBDatabaseException;
    }

        return "AUTO_INCREMENT";
        DBSProcedureType procedureType = sourceObject.getProcedureType();
        }

    public GenericTrigger createTableTriggerImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer genericStructContainer, @NotNull
    }
 * DBeaver - Universal Database Manager
        long columnSize,
    }
                    }
        String columnListStr = JDBCUtils.safeGetString(dbResult, "COLUMN_LIST");
            "SEQ_OBJ.NAME, " +
    public JDBCStatement prepareContainerTriggersLoadStatement(@NotNull JDBCSession session, GenericStructContainer forParent) throws SQLException {
            GenericTableColumn column = parent.getAttribute(session.getProgressMonitor(), columnName);
        if (table == null) {
        String name = JDBCUtils.safeGetStringTrimmed(resultSet, DamengConstants.NAME);


                "CONS_OBJ.CRTDATE,\n" +
        return new DamengSchema(dataSource, schemaName, true);
    public JDBCStatement prepareUniqueConstraintsLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase forParent) throws SQLException, DBException {

        return dbStat;
    }
                            "PROC_OBJ.SCHID = SCH_OBJ.ID\n" +
                "SYSOBJECTS TABTRIG_OBJ_INNER, " +
                        try {
package org.jkiss.dbeaver.ext.dameng.model;
    @Override
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                        result.add(new GenericTableTrigger(table, name, null));
 * Copyright (C) 2010-2026 DBeaver Corp and others
                    "SYSOBJECTS SCH_OBJ_INNER " +
                                case 1 -> DBSProcedureType.PROCEDURE;

        String typeName,
        return true;
        }
                    "AND TABTRIG_OBJ_INNER.NAME = ?")) {
                }
        JDBCPreparedStatement dbStat = session.prepareStatement("SELECT TABTRIG_OBJ_INNER.NAME " +
                                default -> routineType;
                "SYSOBJECTS TAB_OBJ,\n" +
    }
        };
                    "AND SCH_OBJ_INNER.NAME = ? " +
        }

 */
            dbStat.setString(1, table.getName());
        List<String> columnNameList = CommonUtils.splitString(columnListStr, ',');
        } catch (SQLException e) {
                "SYSCONS.CHECKINFO,\n" +
                "AND SCH_OBJ.NAME = ?\n" +
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
                    "TABTRIG_OBJ_INNER.SUBTYPE$ = 'TRIG' " +
    @Override
        JDBCPreparedStatement dbStat = session.prepareStatement("SELECT " +

        if (tableType != null && isView(tableType)) {
        @NotNull GenericTableBase table,
                "LISTAGG(CASE WHEN SYSINDEXES.ID IS NULL THEN NULL ELSE SYSCOLUMNS.NAME END, ',') " +
    @Override
import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.DBException;
    public GenericTrigger createContainerTriggerImpl(@NotNull GenericStructContainer container, @NotNull JDBCResultSet resultSet) throws DBException {
            case "C" -> DBSEntityConstraintType.CHECK;
    public DBSEntityConstraintType getUniqueConstraintType(@NotNull JDBCResultSet dbResult) throws DBException, SQLException {


            }
                "CONS_OBJ.CRTDATE,\n" +
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
    }
    @NotNull
            "SEQ_OBJ.INFO1 & 0xFF0000 IS_CACHE" +
    }
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
                "SYSCONS.CHECKINFO,\n" +
        return true;
    }
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaObject;
        JDBCResultSet dbResult,
        return ArrayUtils.toArray(GenericTableConstraintColumn.class, columns);
    }
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
    }
                            "PROC_OBJ.ID) = 1\n" +
                "AND SYSCOLUMNS.ID = SYSCONS.TABLEID\n" +
            return null;
    public boolean supportsCheckConstraints() {
        if (sourceObject.getContainer() instanceof DamengTable) {
import org.jkiss.dbeaver.model.DBUtils;
                "AND SCH_OBJ_INNER.NAME = ?");
            try (JDBCPreparedStatement dbStat = session.prepareStatement("SELECT " +
        boolean autoGenerated
    @Override
    @Override
    }
    public boolean isColumnNotNullByDefault() {
    @Override
                "SYSCONS.TYPE$,\n" +
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
    @NotNull
                "TABTRIG_OBJ_INNER.SUBTYPE$ = 'TRIG' " +
 * You may obtain a copy of the License at
    @Override
    public boolean supportsUniqueKeys() {
    ) throws SQLException {
                            log.warn(e);
                "TABTRIG_OBJ_INNER.SUBTYPE$ = 'TRIG' " +
                            "USER_OBJ.ID,\n" +
    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {
        int valueType,
    @Override
import java.util.ArrayList;
            }
    ) {
                "SYSOBJECTS TAB_OBJ_INNER " +
                    "SYSOBJECTS TABTRIG_OBJ_INNER, " +
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType;
        for (String columnName : columnNameList) {
        boolean notNull,
    }
    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, String tableName, String tableType, JDBCResultSet dbResult) {
                    "WHERE " +
        String remarks,
                "SYSINDEXES.XTYPE");
 * See the License for the specific language governing permissions and
            triggerName = JDBCUtils.safeGetString(resultSet, "TRIGGER_NAME");
    }
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
        int sourceType,
                            };
    }
                "SYSCONS.TYPE$,\n" +
                "SYSOBJECTS CONS_OBJ,\n" +
            case "F" -> DBSEntityConstraintType.FOREIGN_KEY;
                    "SELECT\n" +
    }
    @Override
    @Override
        return dbStat;
    }
        JDBCPreparedStatement dbStat = session.prepareStatement("SELECT\n" +
    ) {
        return new GenericTableTrigger(genericTableBase, triggerName, null);
                    dbResult);
            "AND SEQ_OBJ.SUBTYPE$ = 'SEQ' " +
        long lastValue = JDBCUtils.safeGetLong(dbResult, "LAST_VALUE");
import org.jkiss.dbeaver.ext.generic.model.*;
                            routineType = switch (type) {
        return true;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
                "SYSOBJECTS SCH_OBJ_INNER " +
import java.util.Collections;
            default -> DBSEntityConstraintType.UNIQUE_KEY;
                "FROM " +
                            int type = JDBCUtils.safeGetInt(dbResult, "INFO1");
            return Collections.emptyList();

                "AND TABTRIG_OBJ_INNER.PID = TAB_OBJ_INNER.ID " + (table != null ? "AND TAB_OBJ_INNER.NAME= ? " : ""));
    @Nullable
    }

                    "FROM " +
                        final GenericProcedure procedure = createProcedureImpl(

            "SF_SEQ_CURRVAL(SCH_OBJ.NAME,SEQ_OBJ.NAME) AS LAST_VALUE, " +
    @Override
    @Override
        if (CommonUtils.isEmpty(triggerName)) {
    @Override
import org.jkiss.dbeaver.ext.dameng.DamengConstants;
        } catch (SQLException e) {
                            "AND SCH_OBJ.NAME = ? ")) {

    @NotNull
            "SEQ_OBJ.INFO1 & 0x0000FF IS_CYCLE," +
    @Override
                        container.addProcedure(procedure);
        @NotNull JDBCSession session,
                            "PROC_OBJ.ID,\n" +
                                case 0 -> DBSProcedureType.FUNCTION;
    GenericUniqueKey object, GenericMetaObject pkObject, JDBCResultSet dbResult) throws DBException {
                "WITHIN GROUP (ORDER BY SYSCOLUMNS.ID) AS COLUMN_LIST\n" +
            case "P" -> DBSEntityConstraintType.PRIMARY_KEY;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    @NotNull
 */
                        }
    @Override
        return DamengUtils.getDDL(monitor, sourceObject, DamengConstants.ObjectType.VIEW, sourceObject.getParentObject().getName());
                    container,

    @Override
        int ordinalPos,
            throw new DBDatabaseException(e, container.getDataSource());
            "SF_SEQUENCE_GET_CACHE_NUM(SCH_OBJ.NAME,SEQ_OBJ.NAME) CACHE_SIZE," +
                "SYSCOLUMNS SYSCOLUMNS,\n" +
    public void loadProcedures(@NotNull DBRProgressMonitor monitor, @NotNull GenericObjectContainer container) throws DBException {
    @Override
                return result;

                List<GenericTrigger> result = new ArrayList<>();
                "AND TABTRIG_OBJ_INNER.PID = SCH_OBJ_INNER.ID " +
                                container,
    }
                "SYSOBJECTS SCH_OBJ,\n" +
        return new DamengSequence(container, name, null, lastValue, minValue, maxValue, incrementBy, dbResult);
 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
                            "AND PROC_OBJ.SUBTYPE$ = 'PROC'\n" +
                    while (dbResult.next()) {

    @Override
            "SYSOBJECTS SEQ_OBJ, " +
        };
    }
                "SYSCONS.ID AS KEY_SEQ,\n" +
        }
                "SYSCONS.ID,\n" +
                            "SYSOBJECTS USER_OBJ\n" +
                                null,
        String defaultValue,
                        String name = JDBCUtils.safeGetString(dbResult, 1);
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
        return true;
        return dbStat;

        return new DamengTable(container, tableName, tableType, dbResult);
            if (column == null) {
    }
    @Override
                            "WHERE\n" +
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
        }

        return true;
 * @author Shengkai Bai
        long charLength,
        }
            return new GenericView(
                "AND (SF_COL_IS_IDX_KEY(SYSINDEXES.KEYNUM, SYSINDEXES.KEYINFO, SYSCOLUMNS.COLID)= 1\n" +
    @NotNull

        return DamengUtils.getDDL(monitor, sourceObject, DamengConstants.ObjectType.TRIGGER, sourceObject.getContainer().getName());
                throw new DBException("Column '" + columnName + "' not found in table " + parent.getName());
                            "USER_OBJ.INFO1,\n" +
        dbStat.setString(2, forParent.getName());
        @NotNull GenericStructContainer container,
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
                            "PROC_OBJ.NAME,\n" +
    public DamengTableColumn createTableColumnImpl(
        return dbStat;
                            "AND SCH_OBJ.PID = USER_OBJ.ID\n" +
            columns.add(new GenericTableConstraintColumn(object, column, 0));
import org.jkiss.utils.CommonUtils;

 *     http://www.apache.org/licenses/LICENSE-2.0
        return true;
    GenericTableBase genericTableBase, String triggerName, @NotNull JDBCResultSet resultSet) throws DBException {
    public GenericUniqueKey createConstraintImpl(@NotNull GenericTableBase table, String constraintName, DBSEntityConstraintType constraintType, JDBCResultSet dbResult, boolean persisted) {
                "FROM " +
                            "CURRENT_USERTYPE(),\n" +
        }

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        String columnName,
                    }
    }
            throw new DBDatabaseException(e, dataSource);
import org.jkiss.code.Nullable;
 * limitations under the License.
    }
                                routineType,
    @Override
                "LEFT JOIN SYSINDEXES SYSINDEXES ON\n" +
        return super.createTableImpl(session, owner, tableObject, dbResult);
        dbStat.setString(1, container.getName());
 *
    public JDBCStatement prepareSequencesLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
        @NotNull GenericStructContainer container,
    }
                            "FROM\n" +
 *
                            "PROC_OBJ.CRTDATE,\n" +
        GenericTableBase table
import org.jkiss.dbeaver.Log;
    private static final Log log = Log.getLog(DamengMetaModel.class);
        return new DamengTableColumn(table, columnName, typeName, valueType, sourceType, ordinalPos, columnSize,
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType;
        dbStat.setString(1, owner.getName());
import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache;
        long incrementBy = JDBCUtils.safeGetLong(dbResult, "INCREMENT");
/**
                        } catch (IllegalArgumentException e) {
        return DamengUtils.getDDL(monitor, sourceObject, objectType, sourceObject.getContainer().getName());
        boolean autoIncrement,
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger sourceObject) throws DBException {
/*


    @Override
                            "PROC_OBJ.ID,\n" +
            return DamengUtils.getDDL(monitor, sourceObject, DamengConstants.ObjectType.TRIGGER, ((DamengTable) sourceObject.getContainer()).getContainer().getName());
    @Override
    }
        @NotNull JDBCSession session,
                "WHERE " +
    public DamengMetaModel() {
        return new DamengTableConstraint(table, constraintName, constraintType, dbResult, persisted);
            case FUNCTION -> DamengConstants.ObjectType.FUNCTION;
                    while (dbResult.nextRow()) {
        }

                "WHERE\n" +
                "SYSINDEXES.ID = SYSCONS.INDEXID\n" +
        super();
            "SF_SEQUENCE_GET_MAX(SCH_OBJ.NAME,SEQ_OBJ.NAME) AS MAX_VALUE," +
        long maxValue = JDBCUtils.safeGetLong(dbResult, "MAX_VALUE");
                "SYSCONS.VALID,\n" +
    }
            }
            "SF_SEQUENCE_GET_MIN(SCH_OBJ.NAME,SEQ_OBJ.NAME) AS MIN_VALUE," +
                "CONS_OBJ.ID = SYSCONS.ID\n" +

    public List<? extends GenericTrigger> loadTriggers(@NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container, GenericTableBase table) throws DBException {
                "SYSCONS.ID,\n" +
        int radix,
                "CONS_OBJ.NAME AS PK_NAME,\n" +
                "FROM\n" +
}
    public boolean isTableCommentEditable() {
        if (table != null) {
                "SYSINDEXES.XTYPE & 0x01,\n" +
    public JDBCStatement prepareTableTriggersLoadStatement(
    public boolean isTableColumnCommentEditable() {
                                null);
import org.jkiss.utils.ArrayUtils;
            "SEQ_OBJ.INFO4 AS INCREMENT, " +
                "CONS_OBJ.NAME,\n" +
        @NotNull DBRProgressMonitor monitor,
 * distributed under the License is distributed on an "AS IS" BASIS,
    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {

    public JDBCBasicDataTypeCache<GenericStructContainer, ? extends JDBCDataType> createDataTypeCache(@NotNull GenericStructContainer container) {
    @Override
    public String getAutoIncrementClause(GenericTableColumn column) {
 *
                "AND TAB_OBJ.NAME = ?\n" +
    public GenericSequence createSequenceImpl(
    }
        GenericDataSource dataSource = container.getDataSource();


                    tableType,

