    @NotNull
            boolean autoIncrement,
    public boolean isCubridTable() {
        }
 *     http://www.apache.org/licenses/LICENSE-2.0
    }
        return false;
 */
        if (dbResult != null) {
    @Override
    @Property(viewable = true, editable = true, updatableExpr = "!object.foreignKey && object.cubridTable", order = 70)
    }
    }

    @Property(viewable = true, editable = true, updatableExpr = "object.descriptionEditable", length = PropertyLength.MULTILINE, order = 100)
            setFullTypeName(fullTypeName);
    @Override
            setPrecision(JDBCUtils.safeGetInteger(dbResult, "prec"));
    public boolean isAutoGenerated() {
}

        return getTable().getDataSource().isServerVersionAtLeast(11, 0)
        return super.getTypeName();

        if (type == null) {
        }
public class CubridTableColumn extends GenericTableColumn

            return super.getMaxLength();
        return super.isRequired();
    @NotNull
package org.jkiss.dbeaver.ext.cubrid.model;
import org.jkiss.dbeaver.ext.cubrid.CubridConstants;
            setScale(JDBCUtils.safeGetInteger(dbResult, "scale"));
    @Nullable

        return super.getDefaultValue();
    public int getRadix() {
 * Licensed under the Apache License, Version 2.0 (the "License");
/*

    }
import java.util.Arrays;

 * You may obtain a copy of the License at
 * Copyright (C) 2010-2025 DBeaver Corp and others
    @Override
            setDescription(JDBCUtils.safeGetString(dbResult, CubridConstants.COMMENT));
 *

            setPersisted(true);
            setAutoIncrement(autoIncrement);
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
 *
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    }
import org.jkiss.dbeaver.model.meta.PropertyLength;
    public void setName(@NotNull String name) {
        return isForeignKey;
            @Nullable String columnName,
    public boolean isForeignKey;
{
    }

        super(table);
            boolean isForeignKey,
    }
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
 * See the License for the specific language governing permissions and
    @Nullable
            @Nullable String dataType,
    @Nullable
            setMaxLength(getPrecision());
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        String type =  Arrays.stream(customTypes).filter(item->fullTypeName.contains(item)).findFirst().orElse(null);
    public boolean isInUniqueKey() {
    @Override
    }
        return 0;
    public String getDefaultValue() {
 * Unless required by applicable law or agreed to in writing, software
    public boolean isRequired() {
        return getTable() instanceof CubridTable;
    }

import org.jkiss.dbeaver.model.meta.Property;
    @Override
    final static String [] customTypes = {"ENUM", "JSON"};
            setOrdinalPosition(JDBCUtils.safeGetInteger(dbResult, "ref_order"));
            setDefaultValue(JDBCUtils.safeGetString(dbResult, "default_value"));
 * limitations under the License.
    @Property(viewable = true, editable = true, updatableExpr = "!object.foreignKey && object.cubridTable", order = 20, listProvider = ColumnTypeNameListProvider.class)
import org.jkiss.dbeaver.DBException;

            setName(columnName);
    @Override
import org.jkiss.code.Nullable;

            @Nullable JDBCResultSet dbResult)
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    public long getMaxLength() {

    @Nullable
        if (getDataKind().equals(DBPDataKind.STRING)) {
            @NotNull GenericTableBase table,
    }
            setRequired(JDBCUtils.safeGetString(dbResult, "is_nullable").equals("NO"));
            this.isForeignKey = isForeignKey;

 * DBeaver - Universal Database Manager
    public String getTypeName() {
    }
 * you may not use this file except in compliance with the License.
import org.jkiss.code.NotNull;
    public void setDataType(@NotNull String fullTypeName) throws DBException {
    @Nullable
            throws DBException {
    @Override
import org.jkiss.dbeaver.model.DBPDataKind;
        } else {
        return super.getDescription();

    @NotNull
               || (isCubridTable() && !isForeignKey());
 *
    public CubridTableColumn(
    @Override
    @Property(viewable = true, editable = true, updatableExpr = "!object.foreignKey && object.cubridTable", order = 50)
    }
        return false;
        super.setName(name != null ? name.toLowerCase() : null);
    }
    @Override
    @Nullable

    @Property(viewable = true, editable = true, updatableExpr = "!object.foreignKey && object.cubridTable", order = 40)
 * distributed under the License is distributed on an "AS IS" BASIS,
            setTypeName(fullTypeName);
    public boolean isDescriptionEditable() {
        }
    public boolean isForeignKey() {
    public String getDescription() {
        return 0;
            setDataType(dataType);
    }

