    protected boolean required;
                long maxLength = newType.getMaxLength();
    @Property(viewable = true, order = 55)
            int divPos2 = fullTypeName.indexOf(')', divPos);
    @Override

import org.jkiss.code.NotNull;
        }
    public String getTypeName()

                    this.maxLength = CommonUtils.toInt(maxLength, -1);
        return typeName;
    }
            DBPDataKind newTypeDataKind = newType.getDataKind();


 * AbstractAttribute
            source.getScale(),
                if (divPos3 == -1) {
    }
import org.jkiss.utils.CommonUtils;
        String plainTypeName;
            int valueType,
    @NotNull
    {
    }
        this.precision = precision == null ? -1 : precision;
    {
            int ordinalPosition,
        return true;
        if (oldType != null && newType != null) {
    public void setValueType(int valueType)
                }
import org.jkiss.code.Nullable;
    @NotNull
    @Override
    @Override
    {
    public String getObjectToolTip() {
            validateTypeName(plainTypeName);
                this.scale = CommonUtils.toInt(newType.getScale(), -1);
            source.isRequired(),
/**
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

        this.required = required;
    @Override
import org.jkiss.dbeaver.model.DBPToolTipObject;

import org.jkiss.dbeaver.model.impl.DBObjectNameCaseTransformer;
    @Property(viewable = true, order = 20)

            plainTypeName = fullTypeName.substring(0, divPos);
    }
    public String getDescription()
    public long getMaxLength()
    }
 * Licensed under the Apache License, Version 2.0 (the "License");

    @NotNull
    public void setOrdinalPosition(int ordinalPosition)
    {
                }
    {
    }
        return valueType;
        this.typeName = typeName;
        return name + ", type=" + typeName + ", pos=" + ordinalPosition;
    @Property(viewable = true, order = 10, valueTransformer = DBObjectNameCaseTransformer.class)
    {
            boolean required,
    public void setPrecision(@Nullable Integer precision)
    }
    public boolean isPersisted()
            }

            source.getMaxLength(),
    public void setScale(@Nullable Integer scale)
    }
            source.getName(),
        this.scale = scale == null ? -1 : scale;
    }
                if ((newTypeDataKind == DBPDataKind.STRING || newTypeDataKind == DBPDataKind.CONTENT) && maxLength > this.maxLength) {
                } else {
import org.jkiss.dbeaver.DBException;
    public void setMaxLength(long maxLength)
 *
                } else {
        this.valueType = valueType;
    @Property(viewable = true, order = 50)
    @Override
    protected int valueType;
 * Copyright (C) 2010-2025 DBeaver Corp and others
    @Override

    @Nullable
            source.getTypeID(),
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt2;
    protected boolean autoGenerated;
import org.jkiss.dbeaver.model.meta.Property;
    }
    @Override
        this.ordinalPosition = ordinalPosition;
    }
        return null;
    }
    protected long maxLength;
            source.getTypeName(),
            validateTypeName(plainTypeName);

    }
    }
    {

import org.jkiss.dbeaver.model.struct.DBSTypedObject;

    {
                    scale = CommonUtils.toInt(modifiers.substring(divPos3 + 1).trim());
                this.precision = CommonUtils.toInt(newType.getPrecision(), -1);
        return getFullTypeName();
    {
        this.ordinalPosition = ordinalPosition;
{
    public int getOrdinalPosition()
    @Property(viewable = true, order = 15, valueRenderer = DBPositiveNumberTransformer.class)
 *     http://www.apache.org/licenses/LICENSE-2.0
        this.maxLength = maxLength;
        this(
    }
        this.typeName = typeName;
    }
    protected String name;

    {
    public String getName()
            source.getPrecision(),
                int divPos3 = modifiers.indexOf(',');
        return precision == -1 ? null : precision;
public abstract class AbstractAttribute implements DBSAttributeBase, DBSTypedObjectExt2, DBSTypedObjectExt3, DBPToolTipObject, DBPNamedObject2
        int divPos = fullTypeName.indexOf("(");
                String modifiers = fullTypeName.substring(divPos + 1, divPos2);


            String name,
    }
        this.maxLength = maxLength;

    protected int ordinalPosition;
 *
    public void setRequired(boolean required)

        if (divPos == -1) {
    {
    public int getTypeID()
    public Integer getPrecision()
    }
/*
import org.jkiss.dbeaver.model.DBPNamedObject2;
    }
    {
            plainTypeName = fullTypeName;
        return scale == -1 ? null : scale;
    @Override
    @Nullable
    {
import org.jkiss.dbeaver.model.DBUtils;

    }
    }
    {
    public void setName(@NotNull String columnName)

    @Override
    protected void validateTypeName(String typeName) throws DBException {
    @Override
    public void setAutoGenerated(boolean autoGenerated) {
        } else {
    @Property(viewable = true, order = 40)
                    this.maxLength = 100;
    protected void onChangeDataType(DBSTypedObject oldType, DBSTypedObject newType) {
    }
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
 * DBeaver - Universal Database Manager
                    precision= CommonUtils.toInt(modifiers.substring(0, divPos3).trim());
            long maxLength,
    }
    @Override
        setTypeName(plainTypeName);
        return required;
            Integer scale,

    {

    }
    @Override
        return autoGenerated;
    public String toString() {
    }

        return name;
    {
    @Override
    public void setTypeName(@NotNull String typeName) throws DBException
    public String getFullTypeName() {

            source.isAutoGenerated());
    protected int scale;
        }
    {
        return ordinalPosition;

    protected int precision;

        return DBUtils.getFullTypeName(this);
    public boolean isAutoGenerated() {
 * Unless required by applicable law or agreed to in writing, software
    public void setFullTypeName(@NotNull String fullTypeName) throws DBException {
        this.scale = scale == null ? -1 : scale;
        this.precision = precision == null ? - 1 : precision;
 */
 * You may obtain a copy of the License at
            }
    @Override
    @Property(viewable = false, valueRenderer = DBPositiveNumberTransformer.class, order = 41)
    }
    }
    protected String typeName;
import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
    protected AbstractAttribute(


        this.autoGenerated = autoGenerated;
 */
 *
                    maxLength = precision = CommonUtils.toInt(modifiers, -1);
 * distributed under the License is distributed on an "AS IS" BASIS,
    {
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt3;

        return maxLength;

    // Copy constructor
            boolean autoGenerated)
 * you may not use this file except in compliance with the License.
    @Override
            if (divPos2 != -1) {
        return 0;
    {
    @Property(viewable = false, valueRenderer = DBPositiveNumberTransformer.class, order = 42)
package org.jkiss.dbeaver.model.impl.struct;
        this.name = columnName;
        this.autoGenerated = autoGenerated;

    }
            String typeName,
    @Override
    public long getTypeModifiers() {
        this.required = required;
import org.jkiss.dbeaver.model.DBPDataKind;
        this.valueType = valueType;
    protected AbstractAttribute(DBSAttributeBase source)
            Integer precision,
    {
 * limitations under the License.
            if (oldType.getDataKind() != newTypeDataKind) {
    }
    public boolean isRequired()

        this.name = name;

    protected AbstractAttribute()
    }
 * See the License for the specific language governing permissions and
    public Integer getScale()
}
    @Override
    {
            source.getOrdinalPosition(),

