                owner.getName(),


            );
                forTable == null ? null : forTable.getName(),
import org.jkiss.dbeaver.model.impl.jdbc.JDBCConstants;
                typeName, valueType, ordinalPos,

import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
        this.persisted = true;
            if (valueType == Types.NUMERIC || valueType == Types.DECIMAL) {
        protected ExternalTableCache() {
    @Override
        return RedshiftExternalTable.class;

    }
 */

public class RedshiftExternalSchema extends PostgreSchema {
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
            String defaultValue = JDBCUtils.safeGetString(dbResult, JDBCConstants.COLUMN_DEF);
                precision = (int) columnSize;

            throws SQLException {
    public List<RedshiftExternalTable> getExternalTables(DBRProgressMonitor monitor) throws DBException {
    }
    @Property(viewable = true, editable = false, updatable = false, length = PropertyLength.MULTILINE, order = 50)
        this.oid = JDBCUtils.safeGetLong(dbResult, "esoid");
    }
import org.jkiss.code.Nullable;
    {
    }

    public boolean isStatisticsCollected() {
            Integer precision = null;


import org.jkiss.dbeaver.model.struct.DBSEntity;
                "SELECT * FROM pg_catalog.svv_external_tables WHERE schemaname=?" +
 *
 * DBeaver - Universal Database Manager
            return dbStat;
            }
import org.jkiss.dbeaver.DBException;
        protected RedshiftExternalTableColumn fetchChild(@NotNull JDBCSession session, @NotNull RedshiftExternalSchema owner, @NotNull RedshiftExternalTable table, @NotNull JDBCResultSet dbResult)
 * distributed under the License is distributed on an "AS IS" BASIS,
 *
 * Unless required by applicable law or agreed to in writing, software
        this.ownerId = JDBCUtils.safeGetLong(dbResult, "esowner");
    public List<RedshiftExternalTable> getChildren(@NotNull DBRProgressMonitor monitor) throws DBException {
        super(database, name, dbResult);
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    @Override
import java.sql.ResultSet;

/*
            throws SQLException, DBException
                table,
                log.warn("Error getting column scale", e);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    }
                null).getSourceStatement();
    }
    @Override
    }
    public ExternalTableCache getExternalTableCache() {
        // Not supported
        {
        @Override

 * RedshiftExternalSchema
    public class ExternalTableCache extends JDBCStructLookupCache<RedshiftExternalSchema, RedshiftExternalTable, RedshiftExternalTableColumn> {
import org.jkiss.code.NotNull;
        return esOptions;
                scale, precision, isNotNull, autoGenerated, defaultValue
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;

            int valueType = JDBCUtils.safeGetInt(dbResult, JDBCConstants.DATA_TYPE);
            super(JDBCConstants.TABLE_NAME);
 * limitations under the License.
            Integer scale = null;
            return new RedshiftExternalTable(owner, dbResult);
    public boolean isExternal() {
    }

import org.jkiss.dbeaver.model.DBUtils;
    @NotNull
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
                columnName,
        }
            } catch (Throwable e) {


        return true;
 * you may not use this file except in compliance with the License.
    }
            }
import org.jkiss.dbeaver.ext.postgresql.model.*;

        return null;

    protected void loadInfo(ResultSet dbResult)
            String columnName = JDBCUtils.safeGetStringTrimmed(dbResult, JDBCConstants.COLUMN_NAME);

                    (object == null && objectName == null ? "" : " AND tablename=?"));

}
    @Override

            if (object != null || objectName != null)
    }
 * See the License for the specific language governing permissions and
        return true;
 * You may obtain a copy of the License at
                columnSize,
            throws SQLException, DBException
    }
    private static final Log log = Log.getLog(RedshiftExternalSchema.class);
    public String getExternalOptions() {
 * Copyright (C) 2010-2025 DBeaver Corp and others
        public JDBCStatement prepareLookupStatement(@NotNull JDBCSession session, @NotNull RedshiftExternalSchema postgreSchema, @Nullable RedshiftExternalTable object, @Nullable String objectName) throws SQLException {
import org.jkiss.dbeaver.model.meta.Association;
    }
import org.jkiss.dbeaver.model.meta.Property;
                true,
    public RedshiftExternalSchema(PostgreDatabase database, String name, String esOptions, ResultSet dbResult) throws SQLException {
import org.jkiss.dbeaver.Log;

                dbStat.setString(2, object != null ? object.getName() : objectName);
        return externalTableCache.getObject(monitor, this, childName);
        return getExternalTables(monitor);
 */
        @Override
            long columnSize = JDBCUtils.safeGetLong(dbResult, JDBCConstants.COLUMN_SIZE);
    public PostgreTableBase getTable(DBRProgressMonitor monitor, long tableId) throws DBException {
    private final ExternalTableCache externalTableCache = new ExternalTableCache();
    }
        return monitor == null ? externalTableCache.getCachedObjects() : externalTableCache.getAllObjects(monitor, this);
/**
    public RedshiftExternalTable getChild(@NotNull DBRProgressMonitor monitor, @NotNull String childName) throws DBException {
            return new RedshiftExternalTableColumn(
        @Override
package org.jkiss.dbeaver.ext.postgresql.model.impls.redshift;
/*
        this.esOptions = JDBCUtils.safeGetString(dbResult, "esoptions");
        {

        return getExternalTables(monitor);
    private String esOptions;
*/
import java.util.List;
            boolean autoGenerated = "YES".equals(JDBCUtils.safeGetStringTrimmed(dbResult, JDBCConstants.IS_GENERATEDCOLUMN));
            final JDBCPreparedStatement dbStat = session.prepareStatement(
            return session.getMetaData().getColumns(
        protected RedshiftExternalTable fetchObject(@NotNull JDBCSession session, @NotNull RedshiftExternalSchema owner, @NotNull JDBCResultSet dbResult)
            int ordinalPos = JDBCUtils.safeGetInt(dbResult, JDBCConstants.ORDINAL_POSITION);
        }
            String typeName = JDBCUtils.safeGetStringTrimmed(dbResult, JDBCConstants.TYPE_NAME);

    @Override
        protected JDBCStatement prepareChildrenStatement(@NotNull JDBCSession session, @NotNull RedshiftExternalSchema owner, @Nullable RedshiftExternalTable forTable)
    @Override
        @Override
    @Override
        }
import org.jkiss.dbeaver.model.meta.PropertyLength;

        }
    @Override

    public RedshiftExternalSchema(PostgreDatabase database, String name, PostgreRole owner) {
 *
            boolean isNotNull = JDBCUtils.safeGetInt(dbResult, JDBCConstants.NULLABLE) == DatabaseMetaData.columnNoNulls;

    }
        super(database, name, owner);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    public List<? extends PostgreTable> getTables(DBRProgressMonitor monitor) throws DBException {
                null,
            setListOrderComparator(DBUtils.nameComparator());
    public void collectObjectStatistics(@NotNull DBRProgressMonitor monitor, boolean totalSizeOnly, boolean forceRefresh) throws DBException {
        this.esOptions = esOptions;
import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache;
        }
            try {
 * Licensed under the Apache License, Version 2.0 (the "License");

    @Association

 *     http://www.apache.org/licenses/LICENSE-2.0
                scale = JDBCUtils.safeGetInteger(dbResult, JDBCConstants.DECIMAL_DIGITS);
        throws SQLException
            dbStat.setString(1, postgreSchema.getName());
import java.sql.Types;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
        @NotNull
    public Class<? extends DBSEntity> getPrimaryChildType(@Nullable DBRProgressMonitor monitor) throws DBException {
    }
        return externalTableCache;
