 *
        setRequired(required);
 * limitations under the License.
        setPersisted(persisted);
    }
import org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn;
package org.jkiss.dbeaver.ext.postgresql.model.impls.redshift;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public RedshiftExternalTableColumn(RedshiftExternalTable table, boolean persisted, String name, String typeName, int valueType, int ordinalPosition, long maxLength, Integer scale, Integer precision, boolean required, boolean autoGenerated, String defaultValue) throws DBException {

        setTypeName(typeName);

public class RedshiftExternalTableColumn extends PostgreTableColumn
 * DBeaver - Universal Database Manager
import org.jkiss.code.NotNull;
    @NotNull
        setScale(scale);
        return getTable().getDataSource();
    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
 */
    public RedshiftExternalTableColumn(RedshiftExternalTable table, boolean persisted) {
    }
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource;
 *     http://www.apache.org/licenses/LICENSE-2.0
        super(table);
        setOrdinalPosition(ordinalPosition);
import org.jkiss.dbeaver.DBException;
        setAutoGenerated(autoGenerated);
 */
    public PostgreDataSource getDataSource() {

{
 * Copyright (C) 2010-2024 DBeaver Corp and others
        setDefaultValue(defaultValue);

 * You may obtain a copy of the License at
/*
        setValueType(valueType);
        setPrecision(precision);
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.


    }
 * PostgreTable base
        setMaxLength(maxLength);
        super(table);
        setPersisted(persisted);
 *
 *
 * Unless required by applicable law or agreed to in writing, software
}
/**
        setName(name);
