  dbeaver-common/modules;\
productsPaths=\
  https://download.eclipse.org/releases/${eclipse-version}/;
  org.opentest4j;\
ideaConfigurationFilesPaths=\
  dbeaver/product/community/DBeaver.product;\
testLibraries=\
featuresPaths=\
  dbeaver/test;\
  junit-jupiter-api;\
  dbeaver/plugins;\
optionalFeatureRepositories=\
workspaceName=dbeaver-ce
  dbeaver/product/repositories  dbeaver/features;
  https://repo.dbeaver.net/p2/ce/latest/;\
  dbeaver/.ide/.idea
repositories=\
  dbeaver-jdbc-libsql
  dbeaver/product/testing/DBeaverUnitTest.product;
  org.junit;\
  org.mockito.mockito-core;\
  org.hamcrest.core
bundlesPaths=\
