import org.eclipse.osgi.util.NLS;
    private final Map<String, EventProcessorComposite<?>> processors = new HashMap<>();

 *
    private Text multiRowInsertBatch;

                    } else if (!useBatchCheck.getSelection()) {
        }
        if (shell.isVisible() || getSettings().isTruncateBeforeLoad()) {
                (useBatchCheck.isDisposed() && settings.isDisableUsingBatches())))
                    int selIndex = onDuplicateKeyInsertMethods.getSelectionIndex();
                DTMessages.data_transfer_wizard_output_checkbox_new_connection,
                    if (truncateTargetTable.getSelection() && !confirmDataTruncate()) {
                GridData.VERTICAL_ALIGN_BEGINNING | GridData.HORIZONTAL_ALIGN_BEGINNING

        }
                settings.isDisableUsingBatches(),
            );
import org.jkiss.utils.CommonUtils;
                    + DTUIMessages.database_consumer_wizard_link_label_replace_method_wiki + "</a>", new SelectionAdapter() {
                @Override
 * you may not use this file except in compliance with the License.
    private String disableReferentialIntegrityCheckboxTooltip;
                .getDialect(dataSource.getSQLDialect().getDialectId());
        UIUtils.syncExec(this::loadSettings);
                DTUIMessages.database_consumer_wizard_ignore_duplicate_rows_label,

                    settings.setOpenNewConnections(newConnectionCheckbox.getSelection());
                            if (buttonIsAvailable(useBulkLoadCheck)) {
    private Button disableReferentialIntegrity;
                settings.isUseTransactions(),
                    settings.setIgnoreDuplicateRows(false);
                4);
                if (!canIgnoreDuplicateRows) {
            multiRowInsertBatch.addModifyListener(e -> settings.setMultiRowInsertBatch(CommonUtils.toInt(multiRowInsertBatch.getText())));
import org.eclipse.swt.layout.GridData;
        {
            String tableNames = getWizard().getSettings().getDataPipes().stream().map(pipe -> pipe.getConsumer() == null ? "" : pipe.getConsumer().getObjectName()).collect(Collectors.joining(","));
                    settings.setOnDuplicateKeyInsertMethodId(null);
                            settings.setIgnoreDuplicateRows(false);
                    settings.setIgnoreDuplicateRows(ignoreDuplicateRows.getSelection());
                            }
                @Override
                DTUIMessages.database_consumer_wizard_disable_import_batches_label,
        availableInsertMethodsDescriptors = insertMethodsDescriptors;
import org.jkiss.dbeaver.model.struct.DBSDataBulkLoader;
        onDuplicateKeyInsertMethods.setEnabled(!useBulkLoadCheck.getSelection());
                        );
                            if (controller.supportsChangingReferentialIntegrity(monitor)) {
                }
 * Unless required by applicable law or agreed to in writing, software
    public boolean isPageApplicable() {
 * Copyright (C) 2010-2026 DBeaver Corp and others
import org.jkiss.dbeaver.model.DBIcon;
    }
            }
                DTUIMessages.database_consumer_wizard_performance_group_label,
        onDuplicateKeyInsertMethods.removeAll();
                            }
                        statements.forEach(tooltip::add);
            ignoreDuplicateRows = UIUtils.createCheckbox(
                settings.setSkipBindValues(false);
                        if (!useMultiRowInsert.getSelection()) {

                                }
            }
import org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer;
                composite,
            return UIUtils.confirmAction(
                    }
import org.jkiss.dbeaver.ui.ShellUtils;
                GridData.VERTICAL_ALIGN_BEGINNING | GridData.HORIZONTAL_ALIGN_BEGINNING
    private Button transferAutoGeneratedColumns;
                        if (buttonIsAvailable(ignoreDuplicateRows)) {
                    DTUIMessages.database_consumer_wizard_disable_referential_integrity_label,
                }
                DTUIMessages.database_consumer_wizard_use_bulk_load_description,
        return true;


                    boolean checkSelection = useBulkLoadCheck.getSelection();
                composite,
                    }
                }
    @Override
    private boolean buttonIsAvailable(Button button) {
            Composite performanceSettings = UIUtils.createTitledComposite(
        DatabaseConsumerSettings settings = getSettings();
import org.jkiss.dbeaver.DBException;
                    settings.setDisableUsingBatches(useBatchCheck.getSelection());
            final Button showTableCheckbox = UIUtils.createCheckbox(generalSettings, DTUIMessages.database_consumer_wizard_table_checkbox_label, settings.isOpenTableOnFinish());

            logInsertQueriesCheck = UIUtils.createCheckbox(
                            disableButton(ignoreDuplicateRows);
        super(DTUIMessages.database_consumer_wizard_name);
            if (configurator.isProcessorEnabled() && configurator.isProcessorApplicable() && configurator.isProcessorComplete()) {
        for (DatabaseMappingContainer mappingContainer : getSettings().getDataMappings().values()) {
            });
            String checkbox_question = NLS.bind(DTUIMessages.database_consumer_wizard_truncate_checkbox_question, tableNames);
            gd.widthHint = UIUtils.getFontHeight(commitAfterEdit) * 6;
                insertMethodsDescriptors = dialectDescriptor.getSupportedInsertReplaceMethodsDescriptors();
            disableReferentialIntegrity = UIUtils.createCheckbox(
                @Override
        return isConsumerOfType(DatabaseTransferConsumer.class);
            gd.horizontalSpan = 3;
            for (SQLDialectInsertReplaceMethod insertMethod : insertMethodsDescriptors) {
                public void widgetSelected(SelectionEvent e) {
            final Text commitAfterEdit = UIUtils.createLabelText(performanceSettings, DTUIMessages.database_consumer_wizard_commit_spinner_label, String.valueOf(settings.getCommitAfterRows()), SWT.BORDER);
            UIUtils.createControlLabel(loadSettings, DTUIMessages.database_consumer_wizard_on_duplicate_key_insert_method_text);
import org.jkiss.dbeaver.ui.UIUtils;


                        settings.setOnDuplicateKeyInsertMethodId(onDuplicateKeyInsertMethods.getText());
            }

                if (insertMethod.getId().equals(settings.getOnDuplicateKeyInsertMethodId())) {
                skipBindValues.addSelectionListener(new SelectionAdapter() {
            newConnectionCheckbox.addSelectionListener(new SelectionAdapter() {
                try {
                        disableButton(useMultiRowInsert);
                        }
                @Override
import org.eclipse.swt.SWT;
                    settings.setDisableReferentialIntegrity(disableReferentialIntegrity.getSelection());
        for (Map.Entry<String, EventProcessorComposite<?>> processor : processors.entrySet()) {
                        if (!useMultiRowInsert.getEnabled()) {
                4
                    }

            );
            if (dialectDescriptor != null) {
        }
                            multiRowInsertBatch.setEnabled(true);
            useTransactionsCheck.addSelectionListener(new SelectionAdapter() {
                performanceSettings,
            truncateTargetTable.setSelection(false);
                });
                DTUIMessages.database_consumer_wizard_log_insert_queries_check,
        }
            });
import org.jkiss.dbeaver.tools.transfer.ui.internal.DTUIMessages;
 * Licensed under the Apache License, Version 2.0 (the "License");
            );
        }
            final Button showFinalMessageCheckbox = UIUtils.createCheckbox(generalSettings, DTUIMessages.database_consumer_wizard_final_message_checkbox_label, getWizard().getSettings().isShowFinalMessage());
            }
                }
import org.jkiss.dbeaver.model.sql.SQLDialectInsertReplaceMethod;
                DTUIMessages.database_consumer_wizard_use_bulk_load_label,
        Shell shell = getContainer().getShell();
                        }
        logInsertQueriesCheck.setSelection(settings.isEnableQmLogging());
                    if (!statements.isEmpty()) {
                public void widgetSelected(SelectionEvent e) {
                    }
            settings.setOnDuplicateKeyInsertMethodId(null);
    }
                (!useBatchCheck.isDisposed() && useBatchCheck.getSelection()) ||
            Link urlLabel = UIUtils.createLink(loadSettings, "<a href=\"" + HelpUtils.getHelpExternalReference(HELP_TOPIC_REPLACE_METHOD) + "\">"
import org.jkiss.dbeaver.runtime.DBWorkbench;
                            multiRowInsertBatch.setEnabled(false);
            });
        if (!riControllers.isEmpty()) {
            return;
    }

                @Override
    private Button skipBindValues;
                settings.isIgnoreDuplicateRows(),
    }
                        } else if (buttonIsAvailable(useBatchCheck) && useBatchCheck.getSelection()) {
            final Button useTransactionsCheck = UIUtils.createCheckbox(
            });
            final DataTransferRegistry dataTransferRegistry = DataTransferRegistry.getInstance();
                riControllers.add((DBPReferentialIntegrityController) mappingContainer.getTarget());
        DBSObjectContainer container = settings.getContainer();
                            useMultiRowInsert.setEnabled(true);
                }
 * limitations under the License.
                public void widgetSelected(SelectionEvent e) {
                4
                });
 * distributed under the License is distributed on an "AS IS" BASIS,

                @Override
import java.util.List;
                } catch (Exception e) {

            });
                    @Override
                DTUIMessages.database_consumer_wizard_name,
            final Button useMultiRowInsert = UIUtils.createCheckbox(performanceSettings, DTUIMessages.database_consumer_wizard_checkbox_multi_insert_label, DTUIMessages.database_consumer_wizard_checkbox_multi_insert_description, settings.isUseMultiRowInsert(), 1);
                                    ignoreDuplicateRows.setEnabled(true);
                    this.processors.put(descriptor.getId(), new EventProcessorComposite<>(this::updatePageCompletion, generalSettings, settings, descriptor, configurator));
        } else {

        setControl(composite);
                    if (selIndex > 0 && !CommonUtils.isEmpty(availableInsertMethodsDescriptors)) {
            }
                    2
                                if (!useBulkLoadCheck.getSelection()) {
    }
                disableButton(useBulkLoadCheck);
                }
                DTUIMessages.database_consumer_wizard_transactions_checkbox_label,
import org.jkiss.dbeaver.registry.configurator.UIPropertyConfiguratorDescriptor;

                onDuplicateKeyInsertMethods.add(insertMethod.getLabel());
            }
            if (emptyButton) {
                null,
                }
                if (!CommonUtils.isEmpty(settings.getOnDuplicateKeyInsertMethodId())) {
                    ignoreDuplicateRows.setSelection(false);
            Composite generalSettings = UIUtils.createTitledComposite(
                4,
        setTitle(DTUIMessages.database_consumer_wizard_title);
    private Button useBatchCheck;
                checkbox_question,
                getWizard().getRunnableContext().run(false, false, monitor -> {
            processor.setProcessorAvailable(processor.isProcessorApplicable());

            );
        DBPDataSource dataSource = container.getDataSource();
    private DatabaseConsumerSettings getSettings() {
        isDisablingReferentialIntegritySupported = false;
                onDuplicateKeyInsertMethods.setText(DBSDataManipulator.INSERT_NONE_METHOD);

            });

                public void widgetSelected(SelectionEvent e) {
                DTUIMessages.database_consumer_wizard_disable_import_batches_description,
        if (container == null) {
                loadSettings,
            useBulkLoadCheck = UIUtils.createCheckbox(
                            ""
                    final IDataTransferEventProcessorConfigurator<DatabaseConsumerSettings> configurator = configuratorDescriptor.createConfigurator();
                public void widgetSelected(SelectionEvent e) {
                settings.setEnableQmLogging(logInsertQueriesCheck.getSelection());
                    }

            multiRowInsertBatch.setLayoutData(gd);
        super.deactivatePage();

                        } catch (DBException e) {
                                statements.add(controller.getChangeReferentialIntegrityStatement(monitor, false));
            settings.setDisableReferentialIntegrity(isDisablingReferentialIntegritySupported && settings.isDisableReferentialIntegrity());
    }
        Composite composite = UIUtils.createComposite(parent, 2);
        final DatabaseConsumerSettings settings = getSettings();
 * See the License for the specific language governing permissions and
                    }
                log.debug("Unexpected error", e.getTargetException());

                generalSettings,
                    if (multiRowInsertBatch != null) {
                performanceSettings,
        button.setEnabled(false);
    }
                performanceSettings,
                @Override

            multiRowInsertBatch = new Text(performanceSettings, SWT.BORDER);
            if (buttonIsAvailable(useBatchCheck)) {
    private void loadSettings() {
                DTUIMessages.database_consumer_wizard_ignore_duplicate_rows_tip,
            disableReferentialIntegrity.setEnabled(isDisablingReferentialIntegritySupported);
                public void widgetSelected(SelectionEvent e) {
                    } else {
                        } else if (!multiRowInsertBatch.getEnabled()) {
            } else {
                    getWizard().getSettings().setShowFinalMessage(showFinalMessageCheckbox.getSelection());
        DatabaseConsumerSettings settings = getSettings();

                        settings.setSkipBindValues(skipBindValues.getSelection());
                    onDuplicateKeyInsertMethods.setEnabled(!checkSelection);
            );
                DTUIMessages.database_consumer_wizard_general_group_label,
            urlLabel.setLayoutData(new GridData(GridData.FILL, GridData.VERTICAL_ALIGN_BEGINNING, false, false, 2, 1));
            gd = new GridData(GridData.FILL_HORIZONTAL);
                                statements.add(controller.getChangeReferentialIntegrityStatement(monitor, true));
                @Override

                    ShellUtils.launchProgram(HelpUtils.getHelpExternalReference(HELP_TOPIC_REPLACE_METHOD));
        }
import java.util.stream.Collectors;
}
                    settings.isDisableReferentialIntegrity(),
            onDuplicateKeyInsertMethods.setEnabled(false);
        for (Map.Entry<String, EventProcessorComposite<?>> processor : processors.entrySet()) {
                settings.isTransferAutoGeneratedColumns(), 2);
        setPageComplete(false);
        updatePageCompletion();
                public void widgetSelected(SelectionEvent e) {
        List<DBPReferentialIntegrityController> riControllers = new ArrayList<>();

                public void widgetSelected(SelectionEvent e) {
            useBatchCheck.addSelectionListener(new SelectionAdapter() {
                    settings.setUseTransactions(useTransactionsCheck.getSelection());
    private boolean confirmDataTruncate() {
                public void widgetSelected(SelectionEvent e) {
            }
                null,
 * You may obtain a copy of the License at
    private Button ignoreDuplicateRows;
    @Override
            truncateTargetTable.addSelectionListener(new SelectionAdapter() {
            if (DBUtils.getAdapter(DBSDataBulkLoader.class, dataSource) == null) {
import org.jkiss.dbeaver.model.sql.SQLDialectMetadata;
        disableReferentialIntegrityCheckboxTooltip = "";
                public void widgetSelected(SelectionEvent e) {
                            settings.setIgnoreDuplicateRows(false);
        loadInsertMethods();
        if (!CommonUtils.isEmpty(insertMethodsDescriptors)) {
    }

                loadSettings,
            } catch (InvocationTargetException e) {
            logInsertQueriesCheck.addSelectionListener(SelectionListener.widgetSelectedAdapter(e -> {
                        StringJoiner tooltip = new StringJoiner(
    }
                }
        setDescription(DTUIMessages.database_consumer_wizard_description);
            });
    }
            if (useBatchCheck != null && (
                skipBindValues = UIUtils.createCheckbox(performanceSettings, DTUIMessages.database_consumer_wizard_checkbox_multi_insert_skip_bind_values_label, DTUIMessages.database_consumer_wizard_checkbox_multi_insert_skip_bind_values_description, settings.isSkipBindValues(), 4);
    private static final Log log = Log.getLog(DatabaseConsumerPageLoadSettings.class);
import org.eclipse.swt.events.SelectionEvent;
                        settings.setOnDuplicateKeyInsertMethodId(methodDescriptor.getId());
            }
            final EventProcessorComposite<?> configurator = processor.getValue();
        return true;
                            System.lineSeparator(),
                generalSettings,

                            DTUIMessages.database_consumer_wizard_disable_referential_integrity_tip_start + System.lineSeparator(),
            });
                                isDisablingReferentialIntegritySupported = true;
                return false;
                public void widgetSelected(SelectionEvent e) {
    public void activatePage() {
    }
        if (dataSource != null) {
    }
                DTUIMessages.database_consumer_wizard_transfer_checkbox_label,
            });
            boolean emptyButton = true;

    public DatabaseConsumerPageLoadSettings() {
                }
        final DatabaseConsumerSettings settings = getSettings();

    private Button logInsertQueriesCheck;
                    settings.setUseMultiRowInsert(useMultiRowInsert.getSelection());
                            // ignoreDuplicateRows can be enabled only if useBatchCheck is checked and bulk load - not
                        }
    protected boolean determinePageCompletion() {
            }
                }
        }
                    settings.setOpenTableOnFinish(showTableCheckbox.getSelection());
                boolean canIgnoreDuplicateRows = useBatchCheck.getSelection() && !settings.isUseBulkLoad();
    @Override

            loadUISettingsForDisableReferentialIntegrityCheckbox();
                public void widgetSelected(SelectionEvent e) {

            useBatchCheck = UIUtils.createCheckbox(
                settings.isUseBulkLoad(),


                    }
                2,
                        truncateTargetTable.setSelection(false);
                DTUIMessages.database_consumer_wizard_transfer_checkbox_tooltip,
            } catch (InterruptedException e) {
            commitAfterEdit.addModifyListener(e -> settings.setCommitAfterRows(CommonUtils.toInt(commitAfterEdit.getText())));
 *
            SQLDialectMetadata dialectDescriptor = DBWorkbench.getPlatform().getSQLDialectRegistry()

                    Collection<String> statements = new LinkedHashSet<>();
            });
            {
                public void widgetSelected(SelectionEvent e) {

                    settings.setTransferAutoGeneratedColumns(transferAutoGeneratedColumns .getSelection());
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        for (EventProcessorComposite<?> processor : processors.values()) {
                        }
                }
            if (!useMultiRowInsert.getSelection() || buttonIsAvailable(useBatchCheck) && useBatchCheck.getSelection()) {
            final DBPDataSource dataSource = settings.getContainer() == null ? null : settings.getContainer().getDataSource();

                @Override
                }
                            disableButton(ignoreDuplicateRows);
import org.jkiss.dbeaver.tools.transfer.database.DatabaseMappingContainer;
            );
            }
 *     http://www.apache.org/licenses/LICENSE-2.0
            return true;
                disableButton(useMultiRowInsert);
            if (settings.getContainer() != null && settings.getContainer().getDataSource().getInfo().supportsStatementBinding()) {
                            // ignoreDuplicateRows doesn't work with batches
        for (EventProcessorComposite<?> processor : processors.values()) {
import org.jkiss.dbeaver.tools.transfer.database.DatabaseConsumerSettings;
            onDuplicateKeyInsertMethods.setText(DBSDataManipulator.INSERT_NONE_METHOD);
        }
                settings.setUseBulkLoad(false);
                            ignoreDuplicateRows.setEnabled(true);
/*
                }
        }
        List<SQLDialectInsertReplaceMethod> insertMethodsDescriptors = null;
            commitAfterEdit.setLayoutData(gd);
                4
                @Override
                        }
import org.jkiss.dbeaver.Log;
                    if (buttonIsAvailable(ignoreDuplicateRows)) {

                @Override

        {
            onDuplicateKeyInsertMethods.setLayoutData(new GridData(GridData.FILL_HORIZONTAL));
package org.jkiss.dbeaver.tools.transfer.ui.pages.database;
    @Override
import org.jkiss.dbeaver.model.struct.DBSDataManipulator;
import org.eclipse.swt.events.SelectionAdapter;
                }
 */
        initializeDialogUnits(parent);
                        SQLDialectInsertReplaceMethod methodDescriptor = availableInsertMethodsDescriptors.get(selIndex - 1);


            final Button newConnectionCheckbox = UIUtils.createCheckbox(
        updateControlsEnablement();
                    final UIPropertyConfiguratorDescriptor configuratorDescriptor = configuratorRegistry.getDescriptor(descriptor.getType().getImplName());
                settings.isOpenNewConnections(),
                4);
                    if (useBatchCheck.getSelection()) {
            if (mappingContainer.getTarget() instanceof DBPReferentialIntegrityController) {
        return button != null && !button.isDisposed();
    }
        }
    @Override
            processor.getValue().setProcessorEnabled(settings.hasEventProcessor(processor.getKey()));
            onDuplicateKeyInsertMethods = new Combo(loadSettings, SWT.DROP_DOWN | SWT.READ_ONLY);
                    DTUIMessages.database_consumer_wizard_truncate_checkbox_description, settings.isTruncateBeforeLoad(), 2);
                @Override
        }
            truncateTargetTable = UIUtils.createCheckbox(loadSettings, DTUIMessages.database_consumer_wizard_truncate_checkbox_label,
                //ignore
                    }


import org.jkiss.dbeaver.tools.transfer.registry.DataTransferEventProcessorDescriptor;
import org.jkiss.dbeaver.registry.configurator.UIPropertyConfiguratorRegistry;
        onDuplicateKeyInsertMethods.add(DBSDataManipulator.INSERT_NONE_METHOD);
            processor.getValue().loadSettings(settings.getEventProcessorSettings(processor.getKey()));
                }
        }
                        disableReferentialIntegrityCheckboxTooltip = tooltip.toString();
    private final String HELP_TOPIC_REPLACE_METHOD = "Data-Import-and-Replace";
                                ignoreDuplicateRows.setEnabled(true);
                configurator.saveSettings(settings.getEventProcessorSettings(processor.getKey()));
                shell,
            if (processor.isProcessorApplicable() && processor.isProcessorEnabled() && !processor.isProcessorComplete()) {
            disableReferentialIntegrity.addSelectionListener(new SelectionAdapter() {
import java.lang.reflect.InvocationTargetException;
                    public void widgetSelected(SelectionEvent e) {
                DTUIMessages.database_consumer_wizard_log_insert_queries_check_tip,
    private List<SQLDialectInsertReplaceMethod> availableInsertMethodsDescriptors;
                    // May be this setting was used for another database

import org.jkiss.dbeaver.tools.transfer.internal.DTMessages;
 *
                    settings.setUseBulkLoad(checkSelection);
            useMultiRowInsert.addSelectionListener(new SelectionAdapter() {
import org.eclipse.swt.events.SelectionListener;
        if (buttonIsAvailable(useBulkLoadCheck)) {
            showFinalMessageCheckbox.addSelectionListener(new SelectionAdapter() {
    private void loadUISettingsForDisableReferentialIntegrityCheckbox() {

            );
            try {
        final DatabaseConsumerSettings settings = getSettings();
            final UIPropertyConfiguratorRegistry configuratorRegistry = UIPropertyConfiguratorRegistry.getInstance();
import org.jkiss.dbeaver.utils.HelpUtils;
                    emptyButton = false;
                4);
            }));
            }
import org.eclipse.swt.widgets.*;
        }
                        multiRowInsertBatch.setEnabled(false);
            }
                }
            });
    private Button useBulkLoadCheck;
        button.setSelection(false);
                        if (buttonIsAvailable(ignoreDuplicateRows) && ignoreDuplicateRows.getEnabled()) {
import java.util.*;
            multiRowInsertBatch.setToolTipText(DTUIMessages.database_consumer_wizard_spinner_multi_insert_batch_size);
    private Combo onDuplicateKeyInsertMethods;
import org.jkiss.dbeaver.tools.transfer.ui.pages.DataTransferPageNodeSettings;
                    disableReferentialIntegrityCheckboxTooltip,
            useBulkLoadCheck.addSelectionListener(new SelectionAdapter() {
                    for (DBPReferentialIntegrityController controller : riControllers) {
            transferAutoGeneratedColumns.addSelectionListener(new SelectionAdapter() {
            });
                    loadSettings,
            multiRowInsertBatch.setText(String.valueOf(settings.getMultiRowInsertBatch()));
import org.jkiss.dbeaver.model.struct.DBSObjectContainer;
        }
        }
    private void updateControlsEnablement() {
        return getWizard().getPageSettings(this, DatabaseConsumerSettings.class);
import org.jkiss.dbeaver.model.DBUtils;
                            } else {
            onDuplicateKeyInsertMethods.addSelectionListener(new SelectionAdapter() {

    private boolean isDisablingReferentialIntegritySupported;
                        settings.setUseMultiRowInsert(false);
            for (DataTransferEventProcessorDescriptor descriptor : dataTransferRegistry.getEventProcessors(DatabaseTransferConsumer.NODE_ID)) {
    }
    private void disableButton(Button button) {
                        return;
                1,
            transferAutoGeneratedColumns = UIUtils.createCheckbox(
        if (settings.isTruncateBeforeLoad() && !confirmDataTruncate()) {

import org.jkiss.dbeaver.tools.transfer.ui.IDataTransferEventProcessorConfigurator;
                ignoreDuplicateRows.setEnabled(canIgnoreDuplicateRows);


                DTUIMessages.database_consumer_wizard_truncate_checkbox_title,
                GridData.VERTICAL_ALIGN_BEGINNING | GridData.HORIZONTAL_ALIGN_BEGINNING

    private Button truncateTargetTable;
import org.jkiss.dbeaver.model.DBPDataSource;
 * DBeaver - Universal Database Manager
                composite,
                            log.debug("Unexpected error when calculating UI options for 'Disable referential integrity' checkbox", e);
import org.jkiss.dbeaver.tools.transfer.registry.DataTransferRegistry;
    public void createControl(Composite parent) {
        }
import org.jkiss.dbeaver.tools.transfer.ui.controls.EventProcessorComposite;
            );

public class DatabaseConsumerPageLoadSettings extends DataTransferPageNodeSettings {
                DBIcon.STATUS_WARNING
import org.jkiss.dbeaver.model.DBPReferentialIntegrityController;
            //This settings may break import for drivers that does not support this feature, so it is disabled for non-JDBC drivers
            });
            settings.setTruncateBeforeLoad(false);
            ignoreDuplicateRows.addSelectionListener(new SelectionAdapter() {
                settings.isEnableQmLogging(),
                @Override
            GridData gd = new GridData(GridData.HORIZONTAL_ALIGN_BEGINNING, GridData.VERTICAL_ALIGN_BEGINNING, false, false, 3, 1);
                setErrorMessage(NLS.bind(DTMessages.data_transfer_wizard_output_event_processor_error_incomplete_configuration, processor.getDescriptor().getLabel()));
                    settings.setTruncateBeforeLoad(truncateTargetTable.getSelection());
            showTableCheckbox.addSelectionListener(new SelectionAdapter() {
        if (shell == null) {
    private void loadInsertMethods() {
            Composite loadSettings = UIUtils.createTitledComposite(


                    onDuplicateKeyInsertMethods.setText(insertMethod.getLabel());
                        if (checkSelection) {
                }
                multiRowInsertBatch.setEnabled(false);

            }
                        }

        {
                    log.error("Can't create event processor", e);
    public void deactivatePage() {
                        try {
