        public ResultSet executeQuery(String sql) throws SQLException {
    }
        }
    }

    @Override
            return statement.getUpdateCount();
    }
        @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        return connection.getClientInfo();
        connection.setClientInfo(properties);

        return connection.getNetworkTimeout();



        @Override
        @Override
        return connection.createClob();
        public boolean getMoreResults(int current) throws SQLException {

        return connection.isClosed();
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        }

 */


        }
    @Override
        return connection.getAutoCommit();
        return connection.createBlob();
        connection.setAutoCommit(autoCommit);

        connection.close();

            return statement.getResultSetType();
    @Override
        return connection.prepareStatement(normalizeTableNames(sql));
    @Override
    @NotNull

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

        public void setCursorName(String name) throws SQLException {

        @Override

        }
        @Override
        @Override
        int resultSetConcurrency,

        String sql,
        public int[] executeBatch() throws SQLException {
        public void close() throws SQLException {
    public Blob createBlob() throws SQLException {
    @Override
            return statement.getFetchSize();
        }

        public void clearBatch() throws SQLException {
    }
    @Override
        @Override
    }
 *
    @Override
    public String nativeSQL(String sql) throws SQLException {
        @Override
    @Override
    private final InternalDatabaseConfig config;

    }
        return new StatementProxy(connection.createStatement(resultSetType, resultSetConcurrency));
            return statement.execute(normalizeTableNames(sql), columnNames);
        public int getMaxRows() throws SQLException {
        }
    public CallableStatement prepareCall(
    }

    @Override
    @Override
            statement.addBatch(normalizeTableNames(sql));

        }

        }

        public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        @Override

    @Override



        }
            return statement.getResultSet();
    public void setAutoCommit(boolean autoCommit) throws SQLException {
    }

        return connection.isValid(timeout);
            statement.setPoolable(poolable);
        int resultSetHoldability
    public InternalProxyConnection(@NotNull Connection connection, @NotNull InternalDatabaseConfig config) {
    }
        }
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    public int getHoldability() throws SQLException {
        @Override
        }
    public Savepoint setSavepoint() throws SQLException {
            return statement.getConnection();
            statement.closeOnCompletion();
    @Override
 * You may obtain a copy of the License at
    public NClob createNClob() throws SQLException {
    public boolean isClosed() throws SQLException {
    @Override
        }


        connection.setNetworkTimeout(executor, milliseconds);
        public ResultSet getGeneratedKeys() throws SQLException {
        public Connection getConnection() throws SQLException {
import java.util.Map;
    @Override
    }
    @Override

        return connection.prepareStatement(normalizeTableNames(sql), columnIndexes);
    private class StatementProxy implements Statement {
    }

        public int getQueryTimeout() throws SQLException {

    }
            statement.close();

            return statement.execute(normalizeTableNames(sql), autoGeneratedKeys);
        return connection.setSavepoint(name);
        }
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        public void setQueryTimeout(int seconds) throws SQLException {
        }
    }
        }
            statement.setFetchSize(rows);
        public void setMaxRows(int max) throws SQLException {
        @Override
    }
        }
    public int getTransactionIsolation() throws SQLException {
 *
        return connection.createSQLXML();

        }
    }
            statement.clearWarnings();
        @Override
    private String normalizeTableNames(@NotNull String sql) {
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return connection.prepareCall(normalizeTableNames(sql));
        public void cancel() throws SQLException {
        return connection.setSavepoint();
        }
        @Override
    @Override
        return connection.unwrap(iface);
            statement.setEscapeProcessing(enable);
    }
    @Override
        int resultSetHoldability
        @Override
        connection.clearWarnings();
        public void setFetchDirection(int direction) throws SQLException {
        @Override
    }
        return connection.getSchema();
    @Override
        int resultSetType,
        }
 * Proxy for internal connection.
        @Override
    }

    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
        public int executeUpdate(String sql, String[] columnNames) throws SQLException {





    }
        return connection.nativeSQL(normalizeTableNames(sql));

        @Override
    }
    public void setCatalog(String catalog) throws SQLException {
    }



}

    public void setClientInfo(String name, String value) throws SQLClientInfoException {
    }
    @Override
            return statement.executeUpdate(normalizeTableNames(sql));
        }
            return statement.getMoreResults();

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        public SQLWarning getWarnings() throws SQLException {
    public void setSchema(String schema) throws SQLException {
        return connection.getMetaData();
        return CommonUtils.normalizeTableNames(sql, config.getSchema());

        @Override
    @Override
    }

 * you may not use this file except in compliance with the License.
        return connection.prepareStatement(normalizeTableNames(sql), autoGeneratedKeys);
        public int executeUpdate(String sql) throws SQLException {
        return connection.isReadOnly();
    }

        return connection.getClientInfo(name);
        public int getFetchSize() throws SQLException {
    }
    public String getCatalog() throws SQLException {
            return statement.isWrapperFor(iface);
        @Override
 * DBeaver - Universal Database Manager
    @Override
            statement.setMaxRows(max);
    @Override
    public boolean isReadOnly() throws SQLException {
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {

    }
    }
        @Override
            statement.setCursorName(name);

            return statement.execute(normalizeTableNames(sql));
    public String getSchema() throws SQLException {
    }
    }

    public boolean isValid(int timeout) throws SQLException {
        return connection.isWrapperFor(iface);
import org.jkiss.code.NotNull;
            return statement.getMoreResults(current);
            return statement.executeUpdate(normalizeTableNames(sql), columnNames);

    }
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
    @Override
    public int getNetworkTimeout() throws SQLException {


        }
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    }
        @Override
    public void abort(Executor executor) throws SQLException {
        }
        }
import java.util.concurrent.Executor;
    public Map<String, Class<?>> getTypeMap() throws SQLException {



    }
            statement.setMaxFieldSize(max);
            return statement.executeUpdate(normalizeTableNames(sql), columnIndexes);

    @Override

        public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    }
        }

    }

    }
    @Override
    public boolean getAutoCommit() throws SQLException {
            statement.setFetchDirection(direction);
        return new StatementProxy(connection.createStatement());
    @Override

        return connection.getWarnings();
        public <T> T unwrap(Class<T> iface) throws SQLException {
        }
 * limitations under the License.
        connection.releaseSavepoint(savepoint);
    @Override
        @Override
        }

    @Override
        connection.setClientInfo(name, value);

    }
        @Override
    public String getClientInfo(String name) throws SQLException {
    public <T> T unwrap(Class<T> iface) throws SQLException {
    @Override
        connection.rollback(savepoint);
 *
        connection.setTransactionIsolation(level);
            statement.clearBatch();
/**
/*

    @Override
        public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    @Override
    }
            return statement.getResultSetConcurrency();
    }
        // SQL query methods with table name normalization
        }
        }
        this.config = config;
    @Override
    @Override
        public void setFetchSize(int rows) throws SQLException {
        return new StatementProxy(connection.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
        int resultSetType,
        }
        @Override
    }
    public void clearWarnings() throws SQLException {
    }

        return connection.getCatalog();
        }
import java.util.Properties;
    public Clob createClob() throws SQLException {
        public int getUpdateCount() throws SQLException {
        @NotNull



        public boolean isClosed() throws SQLException {
    }

        @Override
            statement.setQueryTimeout(seconds);

    }
    }
    @Override
        public void setMaxFieldSize(int max) throws SQLException {
        public int getMaxFieldSize() throws SQLException {

        return connection.prepareStatement(normalizeTableNames(sql), resultSetType, resultSetConcurrency);

    public PreparedStatement prepareStatement(
 *     http://www.apache.org/licenses/LICENSE-2.0
        @Override


            return statement.getGeneratedKeys();
    @Override
 * Unless required by applicable law or agreed to in writing, software
        return connection.createNClob();
            return statement.unwrap(iface);
        public void addBatch(String sql) throws SQLException {
        connection.commit();
        return connection.getTypeMap();
    @Override
    @Override
            return statement.executeQuery(normalizeTableNames(sql));
        }
    @Override
        public boolean execute(String sql) throws SQLException {
    public Savepoint setSavepoint(String name) throws SQLException {
        return connection.prepareCall(normalizeTableNames(sql), resultSetType, resultSetConcurrency);

    @NotNull
        return connection.getHoldability();

        @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
import java.sql.*;
    public Statement createStatement() throws SQLException {

        @Override
        return connection.createArrayOf(typeName, elements);

            return statement.getQueryTimeout();
        }
        public StatementProxy(@NotNull Statement statement) {
    }

        }

            return statement.getMaxRows();
    private final Connection connection;
    }
        @Override
package org.jkiss.dbeaver.model.sql.db;
        public int getFetchDirection() throws SQLException {

        @Override
        }
        return connection.prepareStatement(normalizeTableNames(sql), resultSetType, resultSetConcurrency, resultSetHoldability);
        @Override
        }
    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    @Override
            return statement.isPoolable();
        }
        public int getResultSetConcurrency() throws SQLException {
 * Normalizes part of schema name in SQL queries.
        }
        public boolean getMoreResults() throws SQLException {
        int resultSetConcurrency,
        connection.rollback();
    }
        @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
    public SQLXML createSQLXML() throws SQLException {
    @Override
    @Override
import org.jkiss.utils.CommonUtils;
 * Copyright (C) 2010-2025 DBeaver Corp and others

    @Override

    @Override
public class InternalProxyConnection implements Connection {
    }
    public void setTransactionIsolation(int level) throws SQLException {
        }
        String sql,
        return connection.createStruct(typeName, attributes);

            return statement.execute(normalizeTableNames(sql), columnIndexes);
            return statement.getResultSetHoldability();
        public int getResultSetType() throws SQLException {
        public boolean isCloseOnCompletion() throws SQLException {
    }
    ) throws SQLException {
        connection.setCatalog(catalog);
            statement.cancel();
        public boolean execute(String sql, int[] columnIndexes) throws SQLException {


        @Override
    public SQLWarning getWarnings() throws SQLException {
    @Override
        }
        }
        public boolean isWrapperFor(Class<?> iface) throws SQLException {
        connection.setReadOnly(readOnly);
    @Override
    @Override
        @Override
        }
    public Properties getClientInfo() throws SQLException {

        }
    }
    @Override
        private final Statement statement;
        public ResultSet getResultSet() throws SQLException {
        public int getResultSetHoldability() throws SQLException {

    }
    }
        public void closeOnCompletion() throws SQLException {

    }

            return statement.getWarnings();
        @Override
        }

            this.statement = statement;
    @Override
            return statement.isCloseOnCompletion();
        @Override
        return connection.prepareStatement(normalizeTableNames(sql), columnNames);


        this.connection = connection;
    }
    }
    }
    public DatabaseMetaData getMetaData() throws SQLException {
            return statement.executeUpdate(normalizeTableNames(sql), autoGeneratedKeys);
        @Override
        public boolean execute(String sql, String[] columnNames) throws SQLException {
        connection.abort(executor);
        @Override
    public void setHoldability(int holdability) throws SQLException {
        public void setPoolable(boolean poolable) throws SQLException {
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
            return statement.executeBatch();
        @Override

 * Licensed under the Apache License, Version 2.0 (the "License");
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    public void rollback(Savepoint savepoint) throws SQLException {
        connection.setHoldability(holdability);
        return connection.prepareCall(normalizeTableNames(sql), resultSetType, resultSetConcurrency, resultSetHoldability);

        @Override
    @Override
    public void rollback() throws SQLException {
        public void clearWarnings() throws SQLException {


            return statement.getFetchDirection();
        @Override
    public void setReadOnly(boolean readOnly) throws SQLException {

    @Override
        @Override
    }
import org.jkiss.dbeaver.model.connection.InternalDatabaseConfig;
        @Override
 */

            return statement.getMaxFieldSize();

    ) throws SQLException {

    }
        }
    public void commit() throws SQLException {
    public PreparedStatement prepareStatement(String sql) throws SQLException {
            return statement.isClosed();
        public boolean isPoolable() throws SQLException {

        public void setEscapeProcessing(boolean enable) throws SQLException {

        }
    @Override
        connection.setSchema(schema);
        connection.setTypeMap(map);
        return connection.getTransactionIsolation();
        @Override
    public void close() throws SQLException {
 * See the License for the specific language governing permissions and
