    public String getDescription() {
    @Override
        this.properties = JSONUtils.deserializeProperties(map, "properties");
        this.custom = custom;
            }

    }
    public DBVTransformSettings getTransformSettings() {
        return children;
    public Integer getScale() {
    }
    @Nullable
    }
        for (DBVEntityAttribute child : copy.children) {
        return CommonUtils.isEmpty(properties) ? null : properties.get(name);

        if (this.custom) {
    DBVEntityAttribute(DBVEntity entity, DBVEntityAttribute parent, DBVEntityAttribute copy) {
        return expression;
        return -1;
 *
        Map<String, Object> transformsCfg = JSONUtils.getObject(map, "transforms");
        this.precision = precision;

    private JexlExpression parsedExpression;


        return DBValueFormatting.getTypeImage(this);
        if (properties == null) {
    private Integer precision;
    public DBPDataSource getDataSource() {
        return parent;
import java.util.*;
    }
    }
    }
            }

    @Override
    }
        return this.maxLength;
    @Override
    @Override
        return false;

import org.jkiss.dbeaver.model.data.json.JSONUtils;
    public DBVEntityAttribute getChild(String name) {
    @Override
    public void setRequired(boolean required) {
        return DBUtils.findObject(children, name);


    }
        return dataKind;
            this.expression = JSONUtils.getString(map, "expression");
        this.parsedExpression = null;

            for (String incTrans : JSONUtils.deserializeStringList(transformsCfg, "include")) {

    private boolean custom;
            transformSettings = new DBVTransformSettings();
        return entity;
        return properties == null ? Collections.emptyMap() : properties;
/**
        this.transformSettings = copy.transformSettings == null ? null : new DBVTransformSettings(copy.transformSettings);

                final DBDAttributeTransformerDescriptor transformer = DBWorkbench.getPlatform().getValueHandlerRegistry().getTransformer(incTrans);
    public boolean isRequired() {
    public int getOrdinalPosition() {
    private Integer scale;
    }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public void setExpression(String expression) {
 *
 */
    public Object getProperty(String name)
        this.description = copy.description;



    }
    }
            this.properties = new LinkedHashMap<>(copy.properties);
    public DBVEntityAttribute(DBVEntity entity, DBVEntityAttribute parent, String name) {
    public String getDefaultValue() {

    public boolean isAutoGenerated() {
        this(entity, parent, name);
            for (String excTrans : JSONUtils.deserializeStringList(transformsCfg, "exclude")) {
    }
    }
    }
    public long getTypeModifiers() {
    }
            properties = new LinkedHashMap<>();
        if (!CommonUtils.isEmpty(copy.properties)) {
import org.jkiss.code.Nullable;
    }
    private DBVTransformSettings transformSettings;
 * DBeaver - Universal Database Manager
    }
    }
        return this.precision;
        return transformSettings != null && transformSettings.hasValuableData() || !CommonUtils.isEmpty(properties);
    @Override
    public void setMaxLength(long maxLength) {
    public String getExpression() {
    @Override
    }
    }
    public void setPrecision(@Nullable Integer precision) {
package org.jkiss.dbeaver.model.virtual;
            this.dataKind = CommonUtils.valueOf(DBPDataKind.class, JSONUtils.getString(map, "dataKind"), DBPDataKind.UNKNOWN);
    }

            transformSettings.setTransformOptions(JSONUtils.deserializeProperties(transformsCfg, "properties"));
    private final DBVEntityAttribute parent;

        this.dataKind = copy.dataKind;
        this.expression = expression;
    }
        return description;
                if (transformer != null) {
    @Override
 * See the License for the specific language governing permissions and
    @NotNull
    public DBVEntity getParentObject() {
    public void setDataKind(DBPDataKind dataKind) {
 * limitations under the License.
    {
    @Override
    @Nullable
    @Override
    public DBPImage getObjectImage() {


 */
    }
 * You may obtain a copy of the License at
        return typeName;
    public Map<String, Object> getProperties() {
        return true;
    @Nullable
    public int getTypeID() {
        this.typeName = typeName;
    @Property(editable = true)


import org.jkiss.dbeaver.model.meta.Property;
    public String getTypeName() {
    }
    @NotNull
    }
    @Override
    public long getMaxLength() {
    @NotNull
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
    }
import org.jkiss.dbeaver.model.data.DBDAttributeTransformerDescriptor;

        this.custom = copy.custom;
    public Integer getPrecision() {



            properties.put(name, value);

    public List<DBVEntityAttribute> getChildren() {
        this.parent = parent;
    @Override
 * Copyright (C) 2010-2025 DBeaver Corp and others
import org.jkiss.dbeaver.runtime.DBWorkbench;
    @Override
    @NotNull
    }
            }

        this.name = name;
                    return true;

        }


    private final DBVEntity entity;
            for (DBVEntityAttribute child : children) {
        this.description = description;
        if (parsedExpression == null) {
    @Property(editable = true)
    public String getName() {
                final DBDAttributeTransformerDescriptor transformer = DBWorkbench.getPlatform().getValueHandlerRegistry().getTransformer(excTrans);
        }
        this.maxLength = maxLength;
    @Property(editable = true)
    private long maxLength = -1;
    @Override
                if (transformer != null) {
        return transformSettings;
import org.jkiss.code.NotNull;
        return 0;
    DBVEntityAttribute(DBVEntity entity, DBVEntityAttribute parent, String name, Map<String, Object> map) {
    }

    public void setDefaultValue(String defaultValue) {
        this.name = copy.name;
public class DBVEntityAttribute implements DBSEntityAttribute, DBPNamedObject2, DBPImageProvider, DBSTypedObjectExt2
            properties.remove(name);
    }
    @Nullable
        this.entity = entity;

    @Nullable
    public void setCustom(boolean custom) {
            transformSettings.setCustomTransformer(JSONUtils.getString(transformsCfg, "custom"));
 * Unless required by applicable law or agreed to in writing, software
        this.entity = entity;

    public void setScale(@Nullable Integer scale) {

 * you may not use this file except in compliance with the License.
    }
        return entity.getDataSource();
    }
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt2;
    @Override
        return 0;
    }
                if (child.hasValuableData()) {
    private String expression;
        }
        }
        }
 * Virtual attribute
    }
    public void setName(@NotNull String name) {
    }
            parsedExpression = DBVUtils.parseExpression(expression);
        if (!children.isEmpty()) {
    private Map<String, Object> properties;
    public boolean isCustom() {
/*

    }
    @Nullable
        }
        return parsedExpression;
    @NotNull

    public boolean hasValuableData() {
import org.apache.commons.jexl3.JexlExpression;
        this.transformSettings = transformSettings;
    private DBPDataKind dataKind = DBPDataKind.UNKNOWN;

    }
        this.defaultValue = defaultValue;
        return entity;
 *
    @Override
    }

    private String defaultValue;

    public DBVEntity getEntity() {
        this.scale = scale;
    }

    @Property(editable = true)

        return name;

    @NotNull
            this.typeName = JSONUtils.getString(map, "typeName");

        return custom;
    @Override
    @Override
    }

    @NotNull
    private String description;
    public String toString() {
        this.children.add(child);
        return this.scale;
    public DBVEntityAttribute getParent() {
        this.name = name;
        this.parent = parent;
    @Override

    public void setTransformSettings(DBVTransformSettings transformSettings) {
 * Licensed under the Apache License, Version 2.0 (the "License");
        this.custom = JSONUtils.getBoolean(map, "custom");
        return false;
    }
    }

    public void setTypeName(@NotNull String typeName) {
            this.children.add(new DBVEntityAttribute(entity, this, child));
    private String typeName;
}

                    transformSettings.enableTransformer(transformer, true);

        if (value == null) {
    @Nullable
        return getTypeName();

        this.typeName = copy.typeName;
            return true;
import org.jkiss.dbeaver.model.*;
        return defaultValue;
    @Override
    }
                }
        this.defaultValue = copy.defaultValue;
        }
    {
    @Override
    }

                    transformSettings.enableTransformer(transformer, false);
        this.dataKind = dataKind;
        this.expression = copy.expression;
        return name;
                return null;
    public void setProperty(String name, @Nullable Object value)
{
            if (CommonUtils.isEmpty(expression)) {
                }
        }
        } else {
    }

    public void setDescription(String description) {
            }
    }
    }
                }
 *     http://www.apache.org/licenses/LICENSE-2.0
    public String getFullTypeName() {
    private String name;
    @Override
    public DBPDataKind getDataKind() {

    @Override
        if (!CommonUtils.isEmpty(defaultValue) || !CommonUtils.isEmpty(description) || !CommonUtils.isEmpty(expression)) {
    private final List<DBVEntityAttribute> children = new ArrayList<>();
    public boolean isPersisted() {
    public void addChild(DBVEntityAttribute child) {

import org.jkiss.utils.CommonUtils;
    public JexlExpression getParsedExpression() {
    @Override
    @NotNull
    }


        }
 * distributed under the License is distributed on an "AS IS" BASIS,
        if (!transformsCfg.isEmpty()) {
