import org.jkiss.dbeaver.model.DBPObjectWithLazyDescription;
import org.jkiss.dbeaver.model.meta.PropertyLength;
 * Licensed under the Apache License, Version 2.0 (the "License");
 */
    }
    }
/**
    @Property(viewable = true, editable = true, updatable = true, order = 70)

    }
    public String getDescription() {

        }
 * Copyright (C) 2010-2025 DBeaver Corp and others
        return super.isRequired();
 */

    public void setDescription(String remarks) {
            GenericTableBase table = getTable();

        this.description = remarks;
    public String getDefaultValue() {
    }
    }
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;

 * DBeaver - Universal Database Manager
import org.jkiss.dbeaver.model.meta.Property;

        return super.getTypeName();
    {
            return object.description != null;
    @Override
        return super.getMaxLength();
    @Property(viewable = true, editable = true, updatable = true, order = 40)

    @NotNull
        return super.isAutoIncrement();
import org.jkiss.code.Nullable;

}
        {
    @Override
    public long getMaxLength() {
        @Override
    }
import org.jkiss.dbeaver.DBException;
    VerticaTableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String defaultValue, boolean autoIncrement) {
 * See the License for the specific language governing permissions and
 *
 * You may obtain a copy of the License at

    public boolean isAutoGenerated() {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * VerticaTableColumn

 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.model.meta.LazyProperty;
    @Override
    @Property(viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
        return description;
    }
 *     http://www.apache.org/licenses/LICENSE-2.0
    @Override
        return description;
            if (table instanceof VerticaTable) {
    }
    @Override
 * you may not use this file except in compliance with the License.
        }
    @Nullable
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, null, defaultValue, autoIncrement, false);
 * distributed under the License is distributed on an "AS IS" BASIS,
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
    public static class CommentsValidator implements IPropertyCacheValidator<VerticaTableColumn> {
        public boolean isPropertyCached(@NotNull VerticaTableColumn object, @NotNull Object propertyId)
public class VerticaTableColumn extends GenericTableColumn implements DBPObjectWithLazyDescription {
    @Nullable
    // Not supported
/*
 * limitations under the License.
    @Override
    public boolean isAutoIncrement() {
import org.jkiss.dbeaver.model.meta.IPropertyCacheValidator;
                ((VerticaTable) table).getDescription(monitor);
 *
    @Override


        if (description == null) {
import org.jkiss.code.NotNull;
    public boolean isRequired() {
            }
    @Override

    public String getDescription(@NotNull DBRProgressMonitor monitor) throws DBException {
        return super.getDefaultValue();
 *
        return false;
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", length = PropertyLength.MULTILINE, order = 100)
package org.jkiss.dbeaver.ext.vertica.model;
    @LazyProperty(cacheValidator = CommentsValidator.class)
    private String description;

    @Override
    public String getTypeName()
    }
    }
    @Property(viewable = true, editable = true, updatable = true, order = 50)

    @Property(viewable = true, editable = true, order = 52)
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    }
