                dbStat.setString(1, owner.getName());
            " ORDER BY col.table_id, KEY_SEQ, PK_NAME");
        if (dbResult != null) {
 *
    }
            } else if (tableType.equals(VerticaConstants.TYPE_FLEX_TABLE)) {

    }
import org.jkiss.dbeaver.model.exec.DBCQueryTransformType;
            JDBCUtils.safeGetString(dbResult, "identity_table_name"),

    public boolean supportsCheckConstraints() {
        return new VerticaSchema(dataSource, catalog, schemaName);
        }
            name,
                return new VerticaFlexTable(schema, tableName, tableType, dbResult);
    @Override
import org.jkiss.utils.CommonUtils;
            columnSize,
        boolean autoGenerated
            dbStat = session.prepareStatement(sql);
        if (sourceObject.isPersisted()) {
    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject, @NotNull Map<String, Object> options) throws DBException {
        long charLength,
import java.util.Map;
    @Override
    public JDBCStatement prepareUniqueConstraintsLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase forParent) throws SQLException, DBException {

        VerticaSchema schema = (VerticaSchema) container;
import org.jkiss.code.NotNull;
            checkExpression = JDBCUtils.safeGetString(dbResult, "predicate");
            JDBCUtils.safeGetLong(dbResult, "increment_by"),

        return getTableDDL(monitor, sourceObject, options);
            dbStat.setString(1, forParent.getSchema().getName());
            } else if (tableType.equals(VerticaConstants.TYPE_SYSTEM_TABLE)) {
            String sql = "SELECT st.table_schema as table_schem, st.table_description as remarks, 'SYSTEM TABLE' as table_type, st.*\n" +
    public boolean showProcedureParamNames() {
        } else {

    }
                "FROM v_catalog.views v\n" +
        JDBCPreparedStatement dbStat;
            JDBCUtils.safeGetLong(dbResult, "current_value"),
        );
        return false;
        name = name.trim();
    @Override
        return new VerticaDataSource(monitor, container, this);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;

 * distributed under the License is distributed on an "AS IS" BASIS,
    }
                    dbStat.setString(4, table != null ? table.getName() : tableName);
    @Override
            }
        return true;
        int radix,

                (owner instanceof VerticaSchema ? "WHERE v.table_schema=?" + (table != null || CommonUtils.isNotEmpty(tableName) ? " and v.table_name = ?" : "") : "");
                return new VerticaTable(schema, tableName, tableType, dbResult);
            JDBCUtils.safeGetBoolean(dbResult, "allow_cycle")
        int ordinalPos,
        if (type == DBCQueryTransformType.RESULT_SET_LIMIT) {
        GenericDataSource dataSource = sourceObject.getDataSource();
 * limitations under the License.
    public String getAutoIncrementClause(GenericTableColumn column) {
        return dbStat;
            return new QueryTransformerLimitVertica();
                "FROM v_catalog.tables t\n" +
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
        return new VerticaConstraint(table, constraintName, null, constraintType, persisted, CommonUtils.notEmpty(checkExpression).trim(), isEnabled);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;

        String columnName,
        JDBCPreparedStatement dbStat = session.prepareStatement(ddl.toString());

    }

 * VerticaMetaModel
        return dbStat;
    public DBCQueryTransformer createQueryTransformer(@NotNull DBCQueryTransformType type) {
        } else {
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
            if ("u".equals(type)) {
        if (forParent != null) {
import org.jkiss.code.Nullable;

            JDBCUtils.safeGetLong(dbResult, "minimum"),
import org.jkiss.dbeaver.model.DBUtils;
    }
    }
    }
            dbStat.setString(1, owner.getSchema().getName());
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
            dbStat = session.prepareStatement(sql);
    @Override
    ) throws DBException {
    @Override
                    StringBuilder sql = new StringBuilder();

    }
    @Override
        int valueType,
    @Override
        if (forTable != null) {
        // From Vertica documentation: "Column constraints AUTO_INCREMENT and IDENTITY are synonyms that associate a column with a sequence"
    @Override
import org.jkiss.dbeaver.ext.vertica.VerticaConstants;
        boolean isEnabled = false;
        }
            return DBSEntityConstraintType.PRIMARY_KEY;
                if (table != null || CommonUtils.isNotEmpty(tableName)) {

        return dbStat;
            if (owner instanceof VerticaSchema) {
    }
        String typeName,
        String type = JDBCUtils.safeGetString(dbResult, "constraint_type");
    @Override
import org.jkiss.dbeaver.ext.generic.model.*;
                "from v_catalog.system_tables st where st.table_schema =?" + (table != null || CommonUtils.isNotEmpty(tableName) ? " and st.table_name=?" : "");
        JDBCResultSet dbResult,
    @Nullable
        } catch (SQLException e) {
            dbStat.setString(1, forTable.getSchema().getName());
                dbStat.setString(2, sourceObject.getName());
                return new VerticaView(schema, tableName, tableType, dbResult);
        dbStat.setString(1, container.getSchema().getName());
            }
        int sourceType,
    public JDBCStatement prepareSequencesLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
    }
    @Override

            "SELECT s.*" + (avoidCommentsReading ? "" : ", c.comment") + " FROM v_catalog.sequences s\n" +
 * you may not use this file except in compliance with the License.
                    }
        }
                        sql.append(dbResult.getString(1));
            String sql = "SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, " +
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
        if (CommonUtils.isNotEmpty(tableType)) {
            if (table != null || CommonUtils.isNotEmpty(tableName)) {
    }
    public GenericUniqueKey createConstraintImpl(@NotNull GenericTableBase table, String constraintName, DBSEntityConstraintType constraintType, JDBCResultSet dbResult, boolean persisted) {
import org.jkiss.dbeaver.DBException;
        return true;
    @Override
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
            JDBCUtils.safeGetString(dbResult, "comment"),
    }
 * Unless required by applicable law or agreed to in writing, software
    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {

 */
        return dbStat;
        String name = JDBCUtils.safeGetString(dbResult, "sequence_name");

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        } else {
                "null as partition_expression, 'VIEW' as table_type\n" +
        }
            "FROM v_catalog.constraint_columns col\n" +
/*
                "SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, " +
        return true;
        }
            "WHERE col.constraint_type IN ('u','p','c')\n" +

package org.jkiss.dbeaver.ext.vertica.model;
        } else {
        }
    public GenericTableColumn createTableColumnImpl(
            }
            charLength, scale, precision, radix, notNull,
            "c.table_id = col.table_id\n" +
    @Override
            "JOIN v_catalog.table_constraints tc ON\n" +
        StringBuilder ddl = new StringBuilder();
        String checkExpression = "";
    @NotNull
        return true;
    public JDBCStatement prepareTableColumnLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase forTable) throws SQLException {
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
            defaultValue, autoIncrement
            }
    @Override
        GenericDataSource dataSource = sourceObject.getDataSource();
    }
            JDBCUtils.safeGetLong(dbResult, "maximum"),
            JDBCUtils.safeGetLong(dbResult, "session_cache_count"),
}
        } else {
    }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, String tableName, String tableType, JDBCResultSet dbResult) {
    public boolean isTableCommentEditable() {
            "FROM v_catalog.odbc_columns col\n WHERE col.schema_name=?");
    }
        );
                }

    @Override
        JDBCPreparedStatement dbStat;
            dbStat.setString(1, owner.getName());
                    return sql.toString();
    @Override
    public boolean supportsOverloadedProcedureNames() {
            dbStat.setString(2, forTable.getName());
        ddl.append("SELECT col.*, col.sql_type_id AS SOURCE_DATA_TYPE, col.data_type_name AS TYPE_NAME, col.column_default AS COLUMN_DEF " +
            "AND col.column_name = c.column_name \n" +
                dbStat.setString(2, table != null ? table.getName() : tableName);

        return true;
                } else {
public class VerticaMetaModel extends GenericMetaModel implements DBCQueryTransformProvider {
    @Override

            isEnabled = JDBCUtils.safeGetBoolean(dbResult, "is_enabled");
            return VerticaUtils.getObjectDDL(monitor, dataSource, sourceObject);
        super();
        boolean autoIncrement,
    }
        String remarks,
                (owner instanceof VerticaSchema ? "WHERE t.table_schema=?" + (table != null || CommonUtils.isNotEmpty(tableName) ? " and t.table_name = ?" : "") : "")+
        if (forTable != null) {
            if ("c".equals(type)) {
                "\nUNION ALL\n" +

            if (isView(tableType)) {
                "t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type\n" +
 * DBeaver - Universal Database Manager

        if (owner instanceof VerticaSchema && ((VerticaSchema) owner).isSystem()) {

 *
            dbStat.setString(2, forParent.getName());
            return new VerticaTable(schema, tableName, tableType, dbResult);
    public VerticaMetaModel() {
            }
        Integer precision,
                return DBSEntityConstraintType.UNIQUE_KEY;
        @NotNull GenericTableBase table,
                dbStat.setString(1, sourceObject.getSchema().getName());
                return DBSEntityConstraintType.CHECK;
    }
                (avoidCommentsReading ? "" : "LEFT JOIN v_catalog.comments c\n" +
        dbStat = session.prepareStatement("SELECT col.constraint_name as PK_NAME, col.table_name as TABLE_NAME, col.column_name as COLUMN_NAME, " +
                    while (dbResult.nextRow()) {
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
        JDBCPreparedStatement dbStat = session.prepareStatement(

        if (CommonUtils.isEmpty(name)) {
        return null;
        }

            autoIncrement = JDBCUtils.safeGetBoolean(dbResult, "is_identity");
                return new VerticaSystemTable(schema, tableName, tableType, dbResult);
            } else {
                    dbStat.setString(2, table != null ? table.getName() : tableName);
            typeName, valueType, sourceType, ordinalPos,
            throw new DBDatabaseException(e, dataSource);

        if (dbResult != null) {
    public JDBCStatement prepareTableLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, GenericTableBase table, String tableName) throws SQLException {
        @NotNull DBRProgressMonitor monitor,
        }
 */
    @Override
                "WHERE sequence_schema=? ORDER BY sequence_name");
            "c.ordinal_position as KEY_SEQ, col.constraint_type, tc.predicate, col.is_enabled\n" +

    @Override
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            ddl.append("AND col.table_name=? ");
            }
                }
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
        return super.getUniqueConstraintType(dbResult);
            "tc.constraint_id = col.constraint_id \n" +
            dbStat.setString(1, owner.getName());
        return true;
        long columnSize,
        Integer scale,
    public GenericSchema createSchemaImpl(@NotNull GenericDataSource dataSource, GenericCatalog catalog, @NotNull String schemaName) throws DBException {
 *     http://www.apache.org/licenses/LICENSE-2.0
    public boolean supportsTableDDLSplit(@NotNull GenericTableBase sourceObject) {
    }
                "ON s.sequence_id = c.object_id\n") +
            container,
import org.jkiss.dbeaver.model.exec.DBCQueryTransformProvider;
 * Copyright (C) 2010-2026 DBeaver Corp and others
    @Override
        boolean avoidCommentsReading = ((VerticaDataSource) container.getDataSource()).avoidCommentsReading();
            "AND col.table_schema = ?" + (forParent != null ? " AND col.table_name = ?" : "") +
        }
    @Override
    }
        if (type != null) {
    @NotNull
        }
    @Override
        return "IDENTITY";
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read Vertica procedure source")) {
        return new VerticaSequence(
    public DBSEntityConstraintType getUniqueConstraintType(@NotNull JDBCResultSet dbResult) throws DBException, SQLException {
        boolean notNull,
 *
        return new VerticaTableColumn(table,
import java.sql.SQLException;
            return super.getTableDDL(monitor, sourceObject, options);
/**
 * You may obtain a copy of the License at
            try (JDBCPreparedStatement dbStat = session.prepareStatement("SELECT function_definition FROM v_catalog.user_functions WHERE schema_name=? AND function_name=?")) {
import org.jkiss.dbeaver.ext.vertica.VerticaUtils;
 * Licensed under the Apache License, Version 2.0 (the "License");
    public GenericSequence createSequenceImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
                    dbStat.setString(2, owner.getName());

    }
    }
                    dbStat.setString(3, owner.getName());
        String defaultValue,
        }
    }
            return null;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.DBDatabaseException;
    public boolean supportsUniqueKeys() {
import org.jkiss.dbeaver.model.exec.DBCQueryTransformer;
    }
        }
            columnName,
            "LEFT JOIN v_catalog.columns c ON\n" +
 * See the License for the specific language governing permissions and
    @NotNull
