
                        }
        return getTable().getDataSource();
 * You may obtain a copy of the License at
public class VerticaProjectionColumn extends JDBCTableColumn<VerticaProjection>
                    String length = typeName.substring(divPos + 1, divPos2);

/**
            setMaxLength(0);
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
                            setScale(Integer.parseInt(scale));
    public DBPDataSource getDataSource() {
import org.jkiss.dbeaver.model.meta.Property;
 *
                        setMaxLength(Integer.parseInt(length));
    @Property(viewable = true, editable = true, updatable = true, length = PropertyLength.MULTILINE, order = 100)
    }
                            scale = numbers[1];
                    try {
        super(table, true);
        this.description = description;

                    if (length.contains(",")) { // floats, numbers etc.

import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    public String getDescription() {
    @Override
                    boolean numericType = false;
    }
    }
import org.jkiss.dbeaver.ext.vertica.VerticaUtils;
    @Override
    @Override
import org.jkiss.dbeaver.model.DBPDataKind;
    @Override
        return super.isRequired();
    @Nullable
        setRequired(false);
        return super.isAutoGenerated();
package org.jkiss.dbeaver.ext.vertica.model;
    @Override
                            length = numbers[0];
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
    protected VerticaProjectionColumn(VerticaProjection table, JDBCResultSet dbResult) {
}
import org.jkiss.dbeaver.Log;

 * you may not use this file except in compliance with the License.

                    String scale = null;
            }
                    }
        return super.getDataKind();
import org.jkiss.dbeaver.model.meta.PropertyLength;
                if (divPos2 != -1) {


import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.code.Nullable;
    @Override
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        this.description = JDBCUtils.safeGetString(dbResult, "comment");
 * DBeaver - Universal Database Manager
 */
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
        this.valueType = VerticaUtils.resolveValueType(this.typeName);
                        if (numericType) {
 * distributed under the License is distributed on an "AS IS" BASIS,

 *
    }
    }
                            numericType = true;
{
        {
                        String[] numbers = length.split(",");
 * VerticaProjectionColumn
 * limitations under the License.
                typeName = typeName.substring(0, divPos);
    public boolean isAutoGenerated() {
                        }
 * Licensed under the Apache License, Version 2.0 (the "License");
                        log.warn(e);
    private static final Log log = Log.getLog(VerticaProjectionColumn.class);
                        if (numbers.length == 2) {
            int divPos = typeName.indexOf('(');
            if (divPos != -1) {
                }
                int divPos2 = typeName.indexOf(')', divPos);
    public void setDescription(String description) {
    public Integer getPrecision() {
    @NotNull
        setName(JDBCUtils.safeGetString(dbResult, "projection_column_name"));

        this.typeName = JDBCUtils.safeGetString(dbResult, "data_type");
    }
    }
        }
/*
 */
    }

    private String description;
        setOrdinalPosition(JDBCUtils.safeGetInt(dbResult, "column_position"));

 * See the License for the specific language governing permissions and
    public DBPDataKind getDataKind() {

import org.jkiss.code.NotNull;

    public boolean isRequired() {
import org.jkiss.dbeaver.model.DBPDataSource;
                    } catch (NumberFormatException e) {
        return super.getDefaultValue();
    @Override
 * Unless required by applicable law or agreed to in writing, software
        return super.getPrecision();
                    }
    public String getDefaultValue() {
        return description;
