productBrandText=Universal Database Manager
productLicense=ASL 2.0
packageName=dbeaver
productType=community
productWebSite=https://dbeaver.io/
productDescription=Universal Database Manager and SQL Client
appName=DBeaver
productEmail=support@dbeaver.com
productModifier=ce
productEclipseId=org.jkiss.dbeaver.core.product
appTitle=DBeaver
productRepository=dbeaver/dbeaver
productCopyright=DBeaver Corp
productName=DBeaver Community
productTrademark=DBeaver is a trademark of DBeaver Corp
productBundleId=org.jkiss.dbeaver.core.product
productCompany=DBeaver Corp
