                    case "f" -> hasFunctionSupport() ? DBSProcedureType.FUNCTION : DBSProcedureType.UNKNOWN;
                    }
    public GenericProcedure createProcedureImpl(
                %s
import org.jkiss.dbeaver.model.DBUtils;
     * Table Trigger
                charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
                    schema_charlen(c.coltype, c.extended_id, c.collength)::INTEGER AS CHAR_OCTET_LENGTH,
    }
        triggerName = triggerName.trim();
    @Override
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
                            DBSProcedureType.FUNCTION.equals(procedureType) ? GenericFunctionResultType.TABLE : null);
                    schema_isnullable(c.coltype)::INTEGER AS NULLABLE,
                    final GenericProcedure procedure = createProcedureImpl(container, procedureName, specificName, null,
        @NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container,
    // TABLE_TYPE: String {@code =>} table type. ('TABLE', 'VIEW', 'SYSTEM TABLE')
                    schema_precision(c.coltype, c.extended_id, c.collength)::INTEGER AS COLUMN_SIZE,
            String query = "SELECT T1.trigname FROM systriggers AS T1, systables AS T2 WHERE T2.tabid = T1.tabid AND T2.tabname = ?";
            boolean autoGenerated) throws DBException {
            @NotNull Map<String, Object> options) throws DBException {
        return new GBase8sDataTypeCache(container);
                        log.debug("Broken driver [" + session.getDataSource().getContainer().getDriver().getName()
                    AND (
                WHERE T2.tabid = T1.tabid
                : JDBCUtils.escapeWildCards(session, owner.getSchema().getName());
        return true;
                SELECT t.tabid, t.tabname AS TABLE_NAME, t.owner AS
            tableNamePattern = JDBCUtils.escapeWildCards(session, (object != null ? object.getName() : objectName));
                ) c
                    t.tabname::VARCHAR(128) AS TABLE_NAME,

                    END AS TABLE_TYPE,

                        WHEN 'S' THEN 'dbservername'::VARCHAR(254)
        String schema = owner.getSchema() == null || DBUtils.isVirtualObject(owner.getSchema()) ? null
    @Override
                // Read procedures/functions

/*
}        }
                    OUTER %ssyscolcomms cc
            }
        return dbStat;
 * distributed under the License is distributed on an "AS IS" BASIS,
        @Nullable String tableType, @Nullable JDBCResultSet dbResult) {
                    case "t" -> DBSProcedureType.PROCEDURE;
                        WHEN t.tabtype = 'V' AND t.tabid <= (SELECT tabid FROM systables WHERE trim(tabname) = 'VERSION') THEN 'SYSTEM VIEW'
    /**
    private static final String[] VALID_SYNONYM_TYPES = { "S" };
    @NotNull
    @Override
import org.jkiss.code.Nullable;
    // Constraints
     */
                            i.part1, i.part2, i.part3, i.part4, i.part5, i.part6, 
import org.jkiss.dbeaver.ext.generic.GenericConstants;
                : JDBCUtils.escapeWildCards(session, owner.getSchema().getName());
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Load procedures")) {
    @Override
import org.jkiss.dbeaver.ext.gbase8s.GBase8sUtils;
                    %ssyscolumns c,
            @NotNull GenericStructContainer container) {
                        OR (c.constrtype = 'C' AND col.colno = cd.colno)
     */
        GenericFunctionResultType functionResultType
                """
            @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws SQLException {
import org.jkiss.dbeaver.ext.generic.model.*;
        return GBase8sUtils.getViewDDL(monitor, sourceObject);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    public GenericTableTrigger createTableTriggerImpl(@NotNull JDBCSession session,
                FROM (
            if (tableFilters != null && tableFilters.hasSingleMask()) {
    private static final String[] VALID_TABLE_TYPES = { "T", "V" };

import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
        } catch (SQLException e) {
                LEFT JOIN %ssysindexes i ON c.idxname = i.idxname
    public GenericTableBase createTableOrViewImpl(
    }
    }

        String tableDDL = super.getTableDDL(monitor, sourceObject, options);
                    %ssystables t,

                    CASE d.type
            @NotNull GenericStructContainer container, @NotNull GenericTableBase genericTableBase, String triggerName,
    /**
        @NotNull GenericTableBase table,
 * limitations under the License.
                LEFT JOIN (
                ) ck ON c.constrid = ck.constrid
            throw new DBDatabaseException(e, dataSource);
                    // 3:Stored Procedure, 4:Stored Function )
    }
    @Override
        }
                    CASE
                    String specificName = GenericUtils.safeGetStringTrimmed(procObject, dbResult, "specificname");
    }
        return dbStat;
        String sql = """
    public JDBCBasicDataTypeCache<GenericStructContainer, ? extends JDBCDataType> createDataTypeCache(
                tableNamePattern = tableFilters.getSingleMask();
    @Override
                while (dbResult.next()) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     */
        String ownerPattern = "%s%s".formatted(isOracleMode ? schema : catalog, isOracleMode ? "." : ":");
                """.formatted(table != null ? "AND T2.tabname = ?" : "");
        }
        return dbStat;
            }
                            procedureType,
                    }
                        if (name == null) {
                WHERE
                    AND t.tabid = cc.tabid
                tableNamePattern = owner.getDataSource().getAllObjectsPattern();
            @NotNull JDBCSession session,

        switch (constraintType) {
        }
    @Override
        if (table != null) {


    }
    }
        return new GBase8sTableColumn(table, columnName, typeName, valueType, sourceType, ordinalPos, columnSize,
        boolean persisted) {
    @Override
    public JDBCStatement prepareTableColumnLoadStatement(
                        result.add(new GBase8sTableTrigger(table, name.trim(), dbResult));
    @NotNull
        dbStat.setString(1, tableName);
    public GBase8sMetaModel() {
 * you may not use this file except in compliance with the License.
                                + "] - returns the same list for getProcedures and getFunctons");
import org.jkiss.dbeaver.DBDatabaseException;
    public boolean supportsSynonyms(@NotNull GenericDataSource dataSource) {
    }
                        WHEN t.tabtype = 'V' THEN 'VIEW'
                        SELECT procid, procname, isproc, specificname, type, procflags, paramtypes::LVARCHAR AS columntypenames, mode
        String constraintType = JDBCUtils.safeGetString(dbResult, GBase8sConstants.CONSTRAINT_TYPE);
                        WHEN 'L' THEN get_default_value(c.coltype, c.extended_id, c.collength, d.default::lvarchar(256))::VARCHAR(254)
                            i.part7, i.part8, i.part9, i.part10, i.part11, i.part12, 
        Map<String, GenericProcedure> funcMap = new LinkedHashMap<>();
        return new GBase8sCatalog(dataSource, catalogName);
     * Procedure

            @NotNull JDBCSession session,
    }

import org.jkiss.dbeaver.model.struct.DBSObjectFilter;
    }
        return true;
    }
                List<GBase8sTableTrigger> result = new ArrayList<>();
            }
            final DBSObjectFilter tableFilters = session.getDataSource().getContainer()

        String schema = owner.getSchema() == null || DBUtils.isVirtualObject(owner.getSchema()) ? null
        String tableNamePattern;
 * See the License for the specific language governing permissions and
        return false;
                LEFT JOIN %ssyscolumns col ON c.tabid = col.tabid
    }
                    GenericProcedure function = funcMap.get(procedureName);
                            i.part13, i.part14, i.part15, i.part16
    }
                    : null;
                        break;
import org.jkiss.dbeaver.ext.gbase8s.model.*;
    @Override
                        continue;
 */
    @NotNull
                    c.idxname AS INDEX_NAME,
    public boolean supportNestedForeignKeys() {
    }
    public boolean hasFunctionSupport() {

                        ) 
                    if (container.hasProcedure(procedureName)) {
        String tableName = forTable == null ? owner.getDataSource().getAllObjectsPattern()
                    null::VARCHAR(254) AS IS_GENERATEDCOLUMN,
            return DBSEntityConstraintType.CHECK;
    }
        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
    }
                    schema_nullable(c.coltype)::VARCHAR(3) AS ISNULLABLE,
        if (tableType != null && isView(tableType)) {
                    %s,
        // Triggers, Serials
        @Nullable GenericTableBase table) throws DBException {
            return new GBase8sCheckConstraint(table, constraintName, null, constraintType, checkText, persisted);

import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaObject;
            if (hasProcedureSupport()) {
        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
    }

                    SELECT constrid, constrname, tabid, constrtype, idxname
        }
                return result;

                    c.coltype
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
 *
                    c.constrtype AS CONSTRAINT_TYPE,
        }

    ) {
        String sql = """
        String tableName = forParent == null ? owner.getDataSource().getAllObjectsPattern()
                .formatted(ownerPattern, ownerPattern, ownerPattern, ownerPattern);
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject,
    @NotNull
                SELECT T1.trigname as TRIGGER_NAME, T1.*, T2.tabname AS OWNER
    }
    @Override
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
        JDBCResultSet dbResult,
        return true;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

                        specificName = procedureName;
    /**
                    c.constrname AS PK_NAME,
                    c.colname::VARCHAR(128) AS COLUMN_NAME,
                    case "u" -> DBSProcedureType.PROCEDURE;
import java.sql.SQLException;
                    if (function != null && !supportsEqualFunctionsAndProceduresNames()) {
 */
                            continue;
                    }
        } else {
    }
import java.util.*;
                    c.constrname AS CONSTRAINT_NAME,

                SELECT
        return new GBase8sTableTrigger(genericTableBase, triggerName, resultSet);
import org.jkiss.code.NotNull;
     * Table/View
                : JDBCUtils.escapeWildCards(session, forParent.getName());

                    FROM %ssysconstraints 
                """
        String specificName,
                WHERE t.tabname LIKE ?
        JDBCResultSet dbResult = null;
    public GenericSchema createSchemaImpl(@NotNull GenericDataSource dataSource, @Nullable GenericCatalog catalog,
                LEFT JOIN %ssyscomms c ON t.tabid = c.tabid
                    String procedureName = GenericUtils.safeGetStringTrimmed(procObject, dbResult, "procname");
                    FROM %ssyschecks 
        @NotNull DBSProcedureType procedureType,
                        col.colno IN (
            @Nullable GenericTableBase object, @Nullable String objectName) throws SQLException {
        if (triggerName == null) {
                    WHERE constrtype IN ('U', 'P', 'C')
 * Copyright (C) 2010-2026 DBeaver Corp and others
                %s%s""".formatted(isOracleMode ? schema : catalog, isOracleMode ? "." : ":");
                    DBSProcedureType procedureType = switch (isProc) {
    public JDBCStatement prepareUniqueConstraintsLoadStatement(
                    schema_isautoincr(c.coltype)::VARCHAR(3) AS IS_AUTOINCREMENT,

        JDBCPreparedStatement dbState = null;
                %s
                                : ""));

                    c.coltype::INTEGER AS SQL_DATA_TYPE,
            try (JDBCPreparedStatement dbStat = session.prepareStatement(query)) {
        return tableDDL + GBase8sUtils.getTriggerDDL(monitor, sourceObject);
     * Schema
                        WHEN 'C' THEN 'current' || replace(get_colname(c.coltype, c.collength, c.extended_id, 1), schema_coltypename(c.coltype, c.extended_id), '')::VARCHAR(254)
                    AND d.tabid = t.tabid
        if (object == null && objectName == null) {
        return GBase8sUtils.getProcedureSource(monitor, sourceObject);
        String query = """
    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject,
        if (types != null) {
                        """;
        String schema = owner.getSchema() == null || DBUtils.isVirtualObject(owner.getSchema()) ? null
    @Override
                    String procType = GenericUtils.safeGetString(procObject, dbResult, "type");
        String constraintName,
            Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement,
            @NotNull GenericStructContainer container) throws SQLException {


    }
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
                    WHERE type IN ('T') AND seqno = 0
        if (constraintType == null) {
                    OUTER %ssysdefaults d,

                }
    }
                                        + ")"
    }
                    }
            return DBSEntityConstraintType.PRIMARY_KEY;
                    }
        GenericDataSource dataSource = container.getDataSource();
    public void loadProcedures(@NotNull DBRProgressMonitor monitor, @NotNull GenericObjectContainer container)
                    END AS COLUMN_DEF,
                        }
                LEFT JOIN %ssyscoldepend cd ON c.constrid = cd.constrid
                }
    @Override
        String remarks,
        return new GBase8sProcedure(container, procedureName, specificName, remarks, procedureType, functionResultType);
            @NotNull String schemaName) throws DBException {
        }
     */
public class GBase8sMetaModel extends GenericMetaModel {
/**
    @Override
        String name = JDBCUtils.safeGetString(dbResult, "TABLE_NAME");
    public boolean supportsUniqueKeys() {
    public JDBCStatement prepareTableLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner,
            @Nullable GenericTableBase forParent) throws SQLException, DBException {
        if (CommonUtils.isEmpty(triggerName)) {
            int valueType, int sourceType, int ordinalPos, long columnSize, long charLength, Integer scale,
            return DBSEntityConstraintType.PRIMARY_KEY;
    @Override
                    .getObjectFilter(GenericTable.class, owner, false);

 * DBeaver - Universal Database Manager
    @NotNull
        @NotNull GenericStructContainer container,
            return new GenericView(container, tableName, tableType, dbResult);
            triggerName = JDBCUtils.safeGetString(resultSet, "TRIGGER_NAME");
        return true;
    public JDBCStatement prepareTableTriggersLoadStatement(@NotNull JDBCSession session,
        }
                    t.tabname = ?
        return new GBase8sSynonym(container, name, description, dbResult);
                    String isProc = GenericUtils.safeGetString(procObject, dbResult, "isproc");
        DBSEntityConstraintType constraintType,
        assert table != null;
    public GenericCatalog createCatalogImpl(@NotNull GenericDataSource dataSource, @NotNull String catalogName) {
    @Override


    private static final Log log = Log.getLog(GBase8sMetaModel.class);
            @NotNull JDBCResultSet dbResult) throws DBException {
                    schema_numscale(c.coltype, c.collength)::INTEGER AS DECIMAL_DIGITS,
    @Override
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                        WHEN 'E' THEN read_defaultstr(c.tabid, c.colno, c.coltype, c.collength, c.extended_id)::VARCHAR(32731)
    JDBCStatement prepareTSObjectLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner,
        }
                FROM
    }
                FROM systriggers AS T1, systables AS T2
                    SELECT constrid, checktext
    @Override
                """.formatted(ownerPattern, ownerPattern, ownerPattern, ownerPattern, ownerPattern, ownerPattern);
                String sql = """
    public List<GBase8sTableTrigger> loadTriggers(
    }
                        // Broken driver
            @NotNull JDBCResultSet resultSet) {
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType;
    public GenericSynonym createSynonymImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container,
import org.jkiss.dbeaver.ext.gbase8s.GBase8sConstants;
            dbStat.setString(1, table.getName());

                        ELSE null::VARCHAR(254)
 * @author Chao Tian
                        ELSE 'SYNONYM'
package org.jkiss.dbeaver.ext.gbase8s.model.meta;
                        WHEN t.tabtype = 'T' THEN 'TABLE'
     * Synonym
import org.jkiss.dbeaver.Log;
    // TABLE_TYPE: String {@code =>} table type. ('SYNONYM')
                    container.addProcedure(procedure);
                    trim(ck.checktext) AS CHECK_TEXT,
                LEFT JOIN %ssystables t ON c.tabid = t.tabid
        return new GBase8sUniqueKey(table, constraintName, null, constraintType, persisted);
                dbStat.setString(1, table.getName());
                .formatted(isOracleMode ? "TABLE_SCHEM" : "TABLE_CATALOG", ownerPattern, ownerPattern,
            @Nullable GenericTableBase forTable) throws SQLException {
                        WHEN 'N' THEN 'null'::VARCHAR(10)
    /**
                    )
            throw new DBDatabaseException(e, container.getDataSource());
            return DBSEntityConstraintType.UNIQUE_KEY;

                    c.comments AS REMARKS
                    };
                    // procedureType ( 0:Procedure/Function 1:Package Specification, 2:Package Body,
            @Nullable JDBCResultSet dbResult, @NotNull GenericTableBase table, String columnName, String typeName,
                }

    /**
    @Override
                    col.colname AS COLUMN_NAME,
                        WHEN 'U' THEN 'user'::VARCHAR(254)
    public JDBCStatement prepareSynonymsLoadStatement(@NotNull JDBCSession session,
                    t.tabid = c.tabid
    @Override
        String catalog = owner.getCatalog() == null ? null : owner.getCatalog().getName();
     */
    public GBase8sUniqueKey createConstraintImpl(
        return prepareTSObjectLoadStatement(session, container, null, "%", VALID_SYNONYM_TYPES);
        return GBase8sUtils.getTriggerDDL(monitor, trigger);
            String checkText = dbResult != null ? JDBCUtils.safeGetString(dbResult, GBase8sConstants.CHECK_CLAUSE)

        String catalog = owner.getCatalog() == null ? null : owner.getCatalog().getName();
    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {
        }
                    c.colattr::INTEGER AS COLATTR,
        @NotNull GenericStructContainer container, @Nullable String tableName,
                    c.extended_id::INTEGER AS EXTENDED_ID,
 *     http://www.apache.org/licenses/LICENSE-2.0
        dbStat.setString(paramIndex++, tableNamePattern);
    @Override
                    0::SMALLINT AS SOURCE_DATA_TYPE,
        return true;
        boolean isOracleMode = GBase8sUtils.isOracleSqlMode(owner.getDataSource().getContainer());
                dbResult = dbState.executeQuery();
import org.jkiss.dbeaver.DBException;
 * Licensed under the Apache License, Version 2.0 (the "License");
                        break;
                        FROM sysprocedures
        dbStat.setString(1, tableName);
    }
        return prepareTSObjectLoadStatement(session, owner, object, objectName, VALID_TABLE_TYPES);
        }
        return true;

                    t.tabname AS TABLE_NAME,
 * Unless required by applicable law or agreed to in writing, software
                    get_data_type(c.coltype, c.extended_id, 0)::SMALLINT AS DATA_TYPE,
            @NotNull GenericStructContainer owner,

                SELECT
                    c.colno::integer AS ORDINAL_POSITION,
                FROM %ssystables t
            for (String type : types) {
        } catch (SQLException e) {
                        WHEN t.tabtype = 'T' AND t.tabid <= (SELECT tabid FROM systables WHERE trim(tabname) = 'VERSION') THEN 'SYSTEM TABLE'
            @NotNull GenericStructContainer owner,

import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;

        String description = JDBCUtils.safeGetString(dbResult, "REMARKS");
    public boolean isTableColumnCommentEditable() {
        return new GBase8sTable(container, tableName, tableType, dbResult);

    public boolean isTrimObjectNames() {
                    AND c.colno = cc.colno
        int paramIndex = 1;
        boolean isOracleMode = GBase8sUtils.isOracleSqlMode(owner.getDataSource().getContainer());
import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache;
    public boolean isTableCommentEditable() {
                        continue;
        String ownerPattern = "%s%s".formatted(isOracleMode ? schema : catalog, isOracleMode ? "." : ":");
                        WHEN 'T' THEN 'today'::VARCHAR(254)
        return false;
                    }
                WHERE
                dbState = session.prepareStatement(sql);
        default:
                        // Seems to be a duplicate
                : JDBCUtils.escapeWildCards(session, owner.getSchema().getName());
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
 *
        GenericMetaObject procObject = dataSource.getMetaObject(GenericConstants.OBJECT_PROCEDURE);
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType;
                    while (dbResult.next()) {

                    CASE WHEN c.constrtype != 'C' THEN ROW_NUMBER() OVER (PARTITION BY c.tabid, c.constrname ORDER BY col.colno) ELSE NULL END AS KEY_SEQ
        boolean isOracleMode = GBase8sUtils.isOracleSqlMode(owner.getDataSource().getContainer());
        String sql = """
                    AND c.colno = d.colno


     * Catalog
import org.jkiss.dbeaver.model.sql.SQLUtils;
    }
                                ? " AND t.tabtype IN (" + String.join(", ", Collections.nCopies(types.length, "?"))
            return null;
    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {
                : JDBCUtils.escapeWildCards(session, forTable.getName());
    //////////////////////////////////////////////////////
import org.jkiss.utils.CommonUtils;
    }
            }
                    cc.comments AS REMARKS,
                dbStat.setString(paramIndex++, type);
    }
        return new GBase8sSchema(dataSource, catalog, schemaName);
    }
        case GBase8sConstants.CONSTRAINT_TYPE_CHECK:
            } else {

        String catalog = owner.getCatalog() == null ? null : owner.getCatalog().getName();
                ORDER BY col.tabid, c.constrid, KEY_SEQ;
            @NotNull Map<String, Object> options) throws DBException {
                    if (!"0".equalsIgnoreCase(procType)) {
                    schema_coltypename(c.coltype, c.extended_id)::VARCHAR(128) AS TYPE_NAME,
     */
    @Override
            log.warn("Can't get column '" + GBase8sConstants.CONSTRAINT_TYPE + "': No such column name");
    @Override

    public GenericTableColumn createTableColumnImpl(@NotNull DBRProgressMonitor monitor,
            @Nullable GenericTableBase object, @Nullable String objectName, @Nullable String[] types)
            throws SQLException {
    /**
    @Override
 *
        if (dbResult == null || !constraintType.isUnique()) {
                    if (CommonUtils.isEmpty(specificName)) {


        super();
        return dbStat;
        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
                        String name = JDBCUtils.safeGetString(dbResult, 1);
                if (!CommonUtils.isEmpty(tableNamePattern)) {
        return true;
                    schema_datetype(c.coltype, c.collength)::INTEGER AS DB_DATA_TYPE,
    public DBSEntityConstraintType getUniqueConstraintType(@NotNull JDBCResultSet dbResult) throws DBException, SQLException {
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger trigger)

                    if (monitor.isCanceled()) {

    @Override
                    AND t.tabname = ?
        JDBCPreparedStatement dbStat = session.prepareStatement(query);
        String ownerPattern = """
                        (types != null

    public boolean supportsCheckConstraints() {
    }
    }
        case GBase8sConstants.CONSTRAINT_TYPE_UNIQUE_KEY:
                    schema_numprecradix(c.coltype)::INTEGER AS NUM_PREC_RADIX,
 * You may obtain a copy of the License at
                    tableNamePattern = SQLUtils.makeSQLLike(tableNamePattern);

            throws DBException {
                    default -> DBSProcedureType.UNKNOWN;
    }
        @NotNull String procedureName,
            throws DBException {
