            "NewConstraint",
        @NotNull Map<String, Object> options
            if (tcc != null && tcc.size() == 1) {
        return super.getAddConstraintTypeClause(constraint);
        @NotNull DBRProgressMonitor monitor,
    private static boolean checkPersistedState(DBPPersistedObject persistedObject, boolean checkPersisted) {
        }
public class MySQLConstraintManager extends SQLConstraintManager<MySQLTableConstraint, MySQLTable> {
 *
}
        }
            return "ALTER TABLE " + constraint.getParentObject().getFullyQualifiedName(DBPEvaluationContext.DDL) +
import org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLConstraintManager;
                    " DROP CONSTRAINT " + DBUtils.getQuotedIdentifier(constraint);
import org.jkiss.dbeaver.ext.mysql.MySQLConstants;
import org.jkiss.dbeaver.model.edit.DBEPersistAction;
 *     http://www.apache.org/licenses/LICENSE-2.0
        @NotNull Map<String, Object> options
        @NotNull SQLObjectEditor<MySQLTableConstraint, MySQLTable>.ObjectCreateCommand command,

        @NotNull DBCExecutionContext executionContext,
            }
    @Override
        @NotNull DBECommandContext context,
        if (tryGetColumnOfPrimaryKeyConstraintForAutoincrementColumn(monitor, command.getObject(), true) == null) {
package org.jkiss.dbeaver.ext.mysql.edit;

        @NotNull List<DBEPersistAction> actions,
 * Unless required by applicable law or agreed to in writing, software
 */
import org.jkiss.code.NotNull;
    }
 * MySQL constraint manager

    @Override
    }
        }

 * See the License for the specific language governing permissions and

/*
import java.util.List;
    @Override
            false);
        @NotNull Map<String, Object> options
import org.jkiss.dbeaver.model.impl.edit.DBECommandAbstract;
        if (constraint.getConstraintType() == DBSEntityConstraintType.PRIMARY_KEY) {
    }

        @NotNull List<DBEPersistAction> actions,
        } else {
                    return column;
            super.addObjectDeleteActions(monitor, executionContext, actions, command, options);
    }
    protected void addObjectCreateActions(
        if (tryGetColumnOfPrimaryKeyConstraintForAutoincrementColumn(monitor, command.getObject(), false) == null) {
    @Nullable
            return "ALTER TABLE " + PATTERN_ITEM_TABLE + " DROP KEY " + PATTERN_ITEM_CONSTRAINT; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
            null,
            return MySQLConstants.CONSTRAINT_UNIQUE; //$NON-NLS-1$
 * DBeaver - Universal Database Manager
    }
        return checkPersisted == persistedObject.isPersisted();
    }

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

        boolean checkPersisted
        @NotNull DBCExecutionContext executionContext,
        }
    @NotNull
            return MySQLConstants.CONSTRAINT_CHECK; //$NON-NLS-1$
import org.jkiss.dbeaver.model.DBPEvaluationContext;
                if (checkPersistedState(tc, checkPersisted) && column.isAutoGenerated()
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
        } else if (constraint.getConstraintType() == DBSEntityConstraintType.CHECK) {

        if (command.getObject().getConstraintType() == DBSEntityConstraintType.CHECK) {
import org.jkiss.dbeaver.ext.mysql.model.*;
/**
 * Licensed under the Apache License, Version 2.0 (the "License");
import org.jkiss.code.Nullable;
        @NotNull DBRProgressMonitor monitor,
            DBSEntityConstraintType.PRIMARY_KEY,
        }
        @Nullable Object from,
                MySQLTableColumn column = tcc.get(0).getAttribute();
    @Override
        @NotNull SQLObjectEditor<MySQLTableConstraint, MySQLTable>.ObjectDeleteCommand command,
                }
            return object.getTable().getContainer().getUniqueKeyCache();
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
    }
    ) {
 * distributed under the License is distributed on an "AS IS" BASIS,
        if (object.getConstraintType() == DBSEntityConstraintType.CHECK) {
        return new MySQLTableConstraint(
    @Override
        } else {
        @NotNull DBRProgressMonitor monitor,
    ) {
    @Override
    @Override
        @NotNull MySQLTableConstraint tc,

        @NotNull Object container,
    protected MySQLTableConstraint createDatabaseObject(
    @Nullable

    public static MySQLTableColumn tryGetColumnOfPrimaryKeyConstraintForAutoincrementColumn(
import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;
    ) {
 * Copyright (C) 2010-2025 DBeaver Corp and others
                    && column.getExtraInfo().toLowerCase().contains(MySQLConstants.EXTRA_AUTO_INCREMENT)
import org.jkiss.dbeaver.model.DBPPersistedObject;
 * You may obtain a copy of the License at
    protected String getAddConstraintTypeClause(MySQLTableConstraint constraint) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    protected void appendConstraintDefinition(StringBuilder decl, DBECommandAbstract<MySQLTableConstraint> command) {
 *
        }

import org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor;
 *
            return "ALTER TABLE " + PATTERN_ITEM_TABLE + " DROP PRIMARY KEY"; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
    public DBSObjectCache<MySQLCatalog, MySQLTableConstraint> getObjectsCache(MySQLTableConstraint object) {
import org.jkiss.dbeaver.model.edit.DBECommandContext;
        if (constraint.getConstraintType() == DBSEntityConstraintType.UNIQUE_KEY) {
    protected void addObjectDeleteActions(
    ) {
            return object.getTable().getContainer().getCheckConstraintCache();
    }
        return null;
    protected String getDropConstraintPattern(MySQLTableConstraint constraint) {
 */
            super.appendConstraintDefinition(decl, command);
            super.addObjectCreateActions(monitor, executionContext, actions, command, options);
        } else {
import org.jkiss.dbeaver.model.DBUtils;
        if (tc.getConstraintType() == DBSEntityConstraintType.PRIMARY_KEY && checkPersistedState(tc, checkPersisted)) {
 * limitations under the License.
                ) {
            decl.append(" (").append((command.getObject()).getCheckClause()).append(")");
        }
        } else if (constraint.getConstraintType() == DBSEntityConstraintType.CHECK) {
    }
            (MySQLTable) container,
import java.util.Map;
        @NotNull DBRProgressMonitor monitor,
 * you may not use this file except in compliance with the License.
            List<MySQLTableConstraintColumn> tcc = tc.getAttributeReferences(monitor);
