                constraints != null && constraints.stream().anyMatch(c -> c instanceof  MySQLTableConstraint tc &&
            sql.append(" COLLATE ").append(column.getCollation().getName()); //$NON-NLS-1$
    @Override
        {
    }
import org.jkiss.utils.CommonUtils;
        MySQLTableColumn column;
        return column;
    protected void addObjectModifyActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actionList, @NotNull ObjectChangeCommand command, @NotNull Map<String, Object> options)
    @Override
    protected void addObjectRenameActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions, @NotNull ObjectRenameCommand command, @NotNull Map<String, Object> options)
        if (!fullTypeName.contains("(") && (typeName.equalsIgnoreCase(MySQLConstants.TYPE_VARCHAR) || typeName.equalsIgnoreCase(MySQLConstants.TYPE_VARBINARY))) {
    public void renameObject(@NotNull DBECommandContext commandContext, @NotNull MySQLTableColumn object, @NotNull Map<String, Object> options, @NotNull String newName) throws DBException {
        String extraInfo = column.getExtraInfo();
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " CHANGE " +
        if (!CommonUtils.isEmpty(extraInfo)) {
    }
import org.jkiss.dbeaver.model.edit.*;
            }
    private final ColumnModifier<MySQLTableColumn> CollationModifier = (monitor, column, sql, command) -> {
import org.jkiss.dbeaver.ext.mysql.model.*;
    {

            final String typeName = columnType == null ? "integer" : columnType.getName().toLowerCase();
            }
import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;
        String fullTypeName = column.getFullTypeName();
        StringBuilder decl = super.getNestedDeclaration(monitor, owner, command, options);
    {
        processObjectRename(commandContext, object, options, newName);
                // remove "DEFAULT_GENERATED" See #13577
    {

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
                sql.append(modifiers);
        if (column.isAutoGenerated() &&
        }
        final MySQLTableColumn column = command.getObject();
            column.setTypeName(typeName); //$NON-NLS-1$
                extraInfo = extraInfo.replaceAll(MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED,"");
            sql.append(fullTypeName);
package org.jkiss.dbeaver.ext.mysql.edit;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " MODIFY COLUMN " + getNestedDeclaration(monitor, column.getTable(), command, options))); //$NON-NLS-1$ //$NON-NLS-2$
    }
    // Reorder
import org.jkiss.dbeaver.model.impl.edit.SQLDatabasePersistAction;
        actions.add(
    }

        }
            else {
 * Unless required by applicable law or agreed to in writing, software
            if (!CommonUtils.isEmpty(extraInfo) && MySQLConstants.EXTRA_INFO_VIRTUAL_GENERATED.equalsIgnoreCase(extraInfo)) {
            if (extraInfo.contains(MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED)) {
//                // Do not add "DEFAULT_GENERATED" to the statement. It caused MySQLSyntaxErrorException. See #10797
	private final ColumnModifier<MySQLTableColumn> ExtraInfoModifier = (monitor, column, sql, command) -> {
    @Override
            if (options.get(DBPScriptObject.OPTION_COMPOSITE_OBJECT) == null &&
            sql.append(" CHARACTER SET ").append(column.getCharset().getName()); //$NON-NLS-1$
                    log.debug("No virtual column generate expression found for " + column.getName());
{
    @Override
        }
    };
import org.jkiss.code.NotNull;
            }
import java.sql.Types;
                    order = "AFTER " + DBUtils.getQuotedIdentifier(col);
import java.util.*;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        }
    protected void addObjectReorderActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions, @NotNull ObjectReorderCommand command, @NotNull Map<String, Object> options) {
        return new ColumnModifier[] {MySQLDataTypeModifier, CharsetModifier, CollationModifier, DefaultModifier, ExtraInfoModifier, NullNotNullModifier};
        if (!CommonUtils.isEmpty(column.getComment())) {
    @Override
        if (copyFrom instanceof DBSEntityAttribute) {
    public DBSObjectCache<? extends DBSObject, MySQLTableColumn> getObjectsCache(MySQLTableColumn object)

    public int getMaximumOrdinalPosition(MySQLTableColumn object) {


                    break;
                column.setFullTypeName(typeName);
        return decl;
                MySQLConstraintManager.tryGetColumnOfPrimaryKeyConstraintForAutoincrementColumn(monitor, tc, false) == column)
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
        final MySQLTableColumn column = command.getObject();
                sql.append(" ").append(extraInfo); //$NON-NLS-1$
    }
                    DBUtils.getQuotedIdentifier(command.getObject()) + " " +
    }
            if (columnType != null && columnType.getDataKind() == DBPDataKind.STRING) {
 * limitations under the License.

 * See the License for the specific language governing permissions and
        }
        String order = "FIRST";
            decl.append(" AUTO_INCREMENT"); //$NON-NLS-1$
            }
        } else {
            if (modifiers != null) {
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " CHANGE " +
        try {
    };
public class MySQLTableColumnManager extends SQLTableColumnManager<MySQLTableColumn, MySQLTableBase>
    }
        return object.getTable().getCachedAttributes().size();
                    sql.append(" GENERATED ALWAYS AS (").append(column.getGenExpression()).append(") VIRTUAL"); //$NON-NLS-1$ //$NON-NLS-2$

    {
 */
                "Reorder column",
            column.setOrdinalPosition(table.getCachedAttributes().size() + 1);
 *
    }
                }
        sql.append(' ');
                "Rename column",


                decl.append(" PRIMARY KEY");

import org.jkiss.dbeaver.model.DBUtils;

    protected MySQLTableColumn createDatabaseObject(@NotNull final DBRProgressMonitor monitor, @NotNull final DBECommandContext context, final Object container, Object copyFrom, @NotNull Map<String, Object> options) throws DBException {
 * Licensed under the Apache License, Version 2.0 (the "License");

 * Copyright (C) 2010-2025 DBeaver Corp and others
 * You may obtain a copy of the License at
    public StringBuilder getNestedDeclaration(@NotNull DBRProgressMonitor monitor, @NotNull MySQLTableBase owner, @NotNull DBECommandAbstract<MySQLTableColumn> command, @NotNull Map<String, Object> options)

        if (column.getOrdinalPosition() > 0) {
        if (column.getDataKind() == DBPDataKind.STRING && column.getCharset() != null) {

import org.jkiss.dbeaver.model.struct.DBSObject;
                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getOldName()) + " " +
 *
            sql.append(typeName);
            String modifiers = SQLUtils.getColumnTypeModifiers(column.getDataSource(), column, typeName, column.getDataKind());
            column.setMaxLength(columnType != null && columnType.getDataKind() == DBPDataKind.STRING ? 100 : 0);
    private final ColumnModifier<MySQLTableColumn> CharsetModifier = (monitor, column, sql, command) -> {
import org.jkiss.dbeaver.model.struct.DBSDataType;
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
            }
            column = new MySQLTableColumn(table);

            } 
        final MySQLTableColumn column = command.getObject();
import org.jkiss.dbeaver.model.sql.SQLUtils;
            DBSDataType columnType = findBestDataType(table, "varchar"); //$NON-NLS-1$

    @Nullable
        } catch (DBException ex) {
        MySQLTable table = (MySQLTable) container;
import org.jkiss.code.Nullable;

/**
            (CommonUtils.isEmpty(column.getExtraInfo()) || !column.getExtraInfo().toLowerCase(Locale.ENGLISH).contains(MySQLConstants.EXTRA_AUTO_INCREMENT)))
 * MySQL table column manager
            decl.append(" COMMENT ").append(SQLUtils.quoteString(column, column.getComment())); //$NON-NLS-1$
            Collection<? extends DBSTableConstraint> constraints = command.getObject().getParentObject().getConstraints(monitor);
    @Override

            column.setName(getNewColumnName(monitor, context, table));
import org.jkiss.dbeaver.ext.mysql.MySQLConstants;
            } else {
        }
        }
            }
}
    public void setObjectOrdinalPosition(DBECommandContext commandContext, MySQLTableColumn object, List<MySQLTableColumn> siblingObjects, int newPosition) throws DBException {
        if (column.getDataKind() == DBPDataKind.STRING && column.getCollation() != null) {

                column.setFullTypeName(typeName + "(" + column.getMaxLength() + ")");
    protected ColumnModifier[] getSupportedModifiers(MySQLTableColumn column, Map<String, Object> options)
 */
    @Override
 *
            column = new MySQLTableColumn(monitor, table, (DBSEntityAttribute)copyFrom);
import org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableColumnManager;
        actions.add(
    ///////////////////////////////////////////////
            new SQLDatabasePersistAction(
    public int getMinimumOrdinalPosition(MySQLTableColumn object) {
import org.jkiss.dbeaver.model.DBPDataKind;
                if (!CommonUtils.isEmpty(column.getGenExpression())) {
        String typeName = column.getTypeName();
            column.setValueType(columnType == null ? Types.INTEGER : columnType.getTypeID());
            for (MySQLTableColumn col : command.getObject().getTable().getCachedAttributes()) {
        } else {
    @Override
    @Override
        actionList.add(

 * distributed under the License is distributed on an "AS IS" BASIS,
    }
    }

        processObjectReorder(commandContext, object, siblingObjects, newPosition);
import org.jkiss.dbeaver.model.impl.edit.DBECommandAbstract;
        }
import org.jkiss.dbeaver.model.DBPScriptObject;
    private final ColumnModifier<MySQLTableColumn> MySQLDataTypeModifier = (monitor, column, sql, command) -> {
            log.error(ex);

//             else if (MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED.equals(extraInfo)) {
        return 1;
//            }
                if (col.getOrdinalPosition() == column.getOrdinalPosition() - 1) {
    };
                    getNestedDeclaration(monitor, column.getTable(), command, options) + " " + order));
            new SQLDatabasePersistAction(
            new SQLDatabasePersistAction(
                "Modify column",
                    getNestedDeclaration(monitor, column.getTable(), command, options)));
/*
 * DBeaver - Universal Database Manager
        }
        return object.getParentObject().getContainer().getTableCache().getChildrenCache(object.getParentObject());
    implements DBEObjectRenamer<MySQLTableColumn>, DBEObjectReorderer<MySQLTableColumn>
            ) {
    };
    @Override
                } else {
import org.jkiss.dbeaver.model.struct.rdb.DBSTableConstraint;
                }
    }
 *     http://www.apache.org/licenses/LICENSE-2.0
        final MySQLTableColumn column = command.getObject();
import org.jkiss.dbeaver.DBException;
    {
 * you may not use this file except in compliance with the License.
