    public long getCharLength()
    }
    private String remarks;
    @Nullable
    }
    private long charLength;
import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
    }
    public GenericTableColumn(GenericTableBase table)
    }
 * Copyright (C) 2010-2025 DBeaver Corp and others
    }
        GenericTableBase table,
                if (key.hasColumn(this)) {


    }
            defaultValue);
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    public boolean isAutoGenerated()
 * you may not use this file except in compliance with the License.
    @Override
        boolean autoIncrement,
    {
    public GenericDataSource getDataSource()

    {
        long charLength,
    @Override
    {
        this.autoIncrement = autoIncrement;
        String typeName,
        this.charLength = charLength;
 * distributed under the License is distributed on an "AS IS" BASIS,
        return autoIncrement;
        return getTable().getFullyQualifiedName(DBPEvaluationContext.UI) + "." + getName();
    public String getDescription()
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
    }
 *


        return autoGenerated;
        int radix,
        return false;
            precision,
        return remarks;
    @Override
            columnSize,
    }
            ordinalPosition,

        return getTable().getDataSource();
    {
import org.jkiss.dbeaver.model.struct.rdb.DBSTableColumn;
    @Property(viewable = true, editable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 41)

    private boolean autoIncrement;
        return radix;

            scale,
    @Override
    {
    }
/*
 * Unless required by applicable law or agreed to in writing, software
    public int getSourceType()
    }
    @Override
            columnName,
    public int getRadix()
    {
 * Licensed under the Apache License, Version 2.0 (the "License");
    }
        String defaultValue,
        }

    @Nullable
 */
    public void setDescription(String remarks) {
 * See the License for the specific language governing permissions and
        final Collection<GenericUniqueKey> uniqueKeysCache = getTable().getContainer().getConstraintKeysCache().getCachedObjects(getTable());
    }
import org.jkiss.dbeaver.model.DBPEvaluationContext;
    public void setRadix(int radix)
    {
    @NotNull
        super(table,
    {
        this.autoIncrement = autoIncrement;
    private int sourceType;
        return sourceType;

    @Override
    public JDBCColumnKeyType getKeyType()
        int valueType,
    {
import java.util.Collection;
    {
        if (!CommonUtils.isEmpty(uniqueKeysCache)) {
            }
        return charLength;
            true,
public class GenericTableColumn extends JDBCTableColumn<GenericTableBase> implements DBSTableColumn, DBPNamedObject2, JDBCColumnKeyType, DBPOrderedObject {
    @Override
package org.jkiss.dbeaver.ext.generic.model;
    public boolean isInUniqueKey()
/**
    @Property(viewable = true, order = 51)

                    return true;
    @Property(viewable = true, editableExpr = "object.dataSource.metaModel.tableColumnCommentEditable", updatableExpr = "object.dataSource.metaModel.tableColumnCommentEditable", length = PropertyLength.MULTILINE, order = 100)
    public Integer getScale()
 * Generic table column
            autoGenerated || autoIncrement,
 * You may obtain a copy of the License at
    }
    public boolean isAutoIncrement()
    {
        String remarks,
import org.jkiss.dbeaver.model.meta.PropertyLength;
            notNull,

        int sourceType,
        Integer scale,

 */
 * limitations under the License.
        super(table, false);
        this.radix = radix;
        boolean autoGenerated)
    @Property(viewable = true, editable = true, order = 52)
    {
    private int radix;

        boolean notNull,
    {

    }
    public boolean isInReferenceKey()
        long columnSize,
        this.remarks = remarks;
import org.jkiss.utils.CommonUtils;
    public String toString()
    }
            valueType,
import org.jkiss.dbeaver.model.meta.Property;
        this.radix = radix;
import org.jkiss.dbeaver.model.DBPOrderedObject;
 *
    }
            typeName,


import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCColumnKeyType;
 * DBeaver - Universal Database Manager
        return false;
}
    @Property(viewable = false, valueRenderer = DBPositiveNumberTransformer.class, order = 62)
            for (GenericUniqueKey key : uniqueKeysCache) {
        Integer precision,
        this.sourceType = sourceType;
    }
 *     http://www.apache.org/licenses/LICENSE-2.0
        this.remarks = remarks;

import org.jkiss.dbeaver.model.DBPNamedObject2;
        String columnName,
 *

    public GenericTableColumn(
    @Property(viewable = false, order = 80)
    {

                }
        int ordinalPosition,
    {
        return super.getScale();
    public void setAutoIncrement(boolean autoIncrement) {
        return this;
    @Override
