        try {
    private long rsOffset = -1;

    @Override

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    @Override
    }
        } finally {
    @Override
    @Override
        } catch (Throwable e) {
    }
        try {
            try {
            this.afterExecute();

    public int getMaxFieldSize() throws SQLException {
        }
    }

        // So let's start the block
        getConnection().getExecutionContext().unlockStatementExecution(this);

    }
            // Cache update count (for QM logging)
/*
    /// /////////////////////////////////
                return getUpdateCount();
    }
        this.beforeExecute();
    public SQLWarning getWarnings() throws SQLException {
    private Throwable executeError;
    public void clearWarnings() throws SQLException {
    ////////////////////////////////////////////////////////////////////
        JDBCResultSet dbResult = createResultSetImpl(resultSet);
import org.jkiss.dbeaver.model.impl.AbstractStatement;
    public JDBCResultSet getResultSet() throws SQLException {
        setQueryString(sql);
                }
import java.util.List;
            }
        try {
    public long[] executeStatementBatch() throws DBCException {
        if (rsOffset > 0) {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
        this.executeError = null;
            throw this.handleExecuteError(e);

            QMUtils.getDefaultHandler().handleStatementExecuteEnd(this, this.updateCount, this.executeError);

        return makeResultSet(getOriginal().getResultSet());
        try {

        setQueryString(sql);

            throw new DBCException(e, connection.getExecutionContext());
        this.beforeExecute();

    }
            return handleExecuteResult(getOriginal().executeUpdate(sql, autoGeneratedKeys));
        }

            } catch (SQLFeatureNotSupportedException | UnsupportedOperationException | IncompatibleClassChangeError e) {
            JDBCUtils.reportWarnings(getOriginal().getWarnings());
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    public void closeOnCompletion() throws SQLException {
import org.jkiss.dbeaver.model.qm.QMUtils;
    protected final STATEMENT original;
    }
        } catch (Throwable e) {
        }
    @Override
        updateCount = result;
        }
        this.beforeExecute();
                if (!connection.isClosed() && !connection.getAutoCommit()) {

    @Override
                    // Cycle

    public void setPoolable(boolean poolable) throws SQLException {
 *     http://www.apache.org/licenses/LICENSE-2.0
            } catch (Throwable e) {
    public int getFetchSize() throws SQLException {
    @Override
import org.jkiss.code.NotNull;
            dbResult.setMaxRows(rsMaxRows);

        } finally {
            try {
    @Override


    }
        setQueryString(sql);
    /// /////////////////////////////////
            this, null/*this.query == null ? "?" : JDBCUtils.limitQueryLength(query, 200)*/);
        if (closed) {
            return getOriginal().getMoreResults();
    public void setCursorName(String name) throws SQLException {
    }
    }
        getOriginal().setPoolable(poolable);
            // Remember limit values - we'll use them in resultset fetch routine
        }
    }
        @NotNull JDBCObjectSupplier<STATEMENT> original,
    public void setEscapeProcessing(boolean enable) throws SQLException {
            throw new DBRuntimeException(e);
    @Override
        getOriginal().clearWarnings();
        if (uc >= 0) {
    }
        getOriginal().setMaxFieldSize(max);
        }
        }
        // Sometimes warnings are cached in connection and as a result we got a lot of spam in log
    }
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
 * Manageable statement.
            } catch (SQLException e) {
    @Override
            throw this.handleExecuteError(e);
        }
    public int getQueryTimeout() throws SQLException {
        getOriginal().setFetchDirection(direction);
        }
            this.afterExecute();
                if (warnings.contains(warning)) {
    protected int handleExecuteResult(int result) {
            return handleExecuteResult(getOriginal().execute(sql));
    @Override

    @Override
        return query;
    private long rsMaxRows = -1;
        executeError = ex;
        }
    }
    @NotNull
        return getOriginal().getFetchSize();

 *
        return getOriginal().getWarnings();
    protected void afterExecute() {
            throw this.handleExecuteError(e);
    }
        this.beforeExecute();

        if (offset <= 0) {
            return handleExecuteResult(getOriginal().executeUpdate(sql, columnIndexes));
    public void clearBatch() throws SQLException {

        }
                    warnings = new ArrayList<>();

    @Override
        if (ex instanceof SQLException) {


        this.query = queryString;
        return !disableLogging;

    }

        @Nullable Thread blockThread
            getOriginal().clearWarnings();
            this.afterExecute();
            try {
            closeError = e;
            }
    }


    public void setMaxRows(int max) throws SQLException {
        }
        } catch (SQLException e) {
        this.connection.getExecutionContext().lockStatementExecution(this);

    public long getLargeUpdateCount() throws SQLException {
    }
        // Close statement
            throw this.handleExecuteError(e);
        } catch (Throwable e) {
 *
        if (uc >= 0) {
                }
    @Override
    }

        }
            throw this.handleExecuteError(e);
            throw new DBCException(e, connection.getExecutionContext());

    }
    public void setStatementTimeout(int timeout) throws DBCException {
    public int getUpdateCount() throws SQLException {
        return getOriginal().getResultSetType();
        try {
    }
        this.connection.setBlockThread(Thread.currentThread());
        } catch (Throwable e) {
        this.connection.setBlockThread(null);
    public int executeUpdate(String sql) throws SQLException {

            throw new DBCException(e, connection.getExecutionContext());
import java.sql.*;
    protected SQLException handleExecuteError(Throwable ex) {
        try {
            this.afterExecute();
    }
                int[] result = this.executeBatch();
        @Nullable String queryString,
        this.beforeExecute();
/**
 * Stores information about execution in query manager and operated progress monitor.
        this.beforeExecute();
        if (isQMLoggingEnabled()) {

        try {
    protected boolean isQMLoggingEnabled() {
        } catch (Throwable e) {
        }

    public void addBatch(String sql) throws SQLException {
        super(connection);
    public boolean getMoreResults() throws SQLException {
    public void setFetchDirection(int direction) throws SQLException {
        try {
        } catch (Throwable e) {
        try {
    @Override
    @Override
    public String toString() {
        }
        this.query = query;
import java.util.ArrayList;
    }
    public String getQueryString() {
 * See the License for the specific language governing permissions and
            }
/*
    }
            throw new DBCException(e, connection.getExecutionContext());
            QMUtils.getDefaultHandler().handleStatementOpen(this);
        }
    public ResultSet getGeneratedKeys() throws SQLException {
    @Override
    }
        if (resultSet == null) {
    public int[] executeBatch() throws SQLException {

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        // because opening a statement may take a time and we have to measure it
    @Override

        } catch (Throwable e) {
            throw new DBCException(e, connection.getExecutionContext());

    public STATEMENT getOriginal() {

        }
        }
            this.afterExecute();



            return handleExecuteResult(getOriginal().execute(sql, columnIndexes));
            return makeResultSet(getOriginal().executeQuery(sql));
            throw this.handleExecuteError(e);
            return execute(query);
        }

        } catch (SQLException e) {
        if (totalRows > 0 && connection.getDataSource().getInfo().supportsResultSetLimit()) {
import org.jkiss.dbeaver.model.impl.jdbc.JDBCTrace;
                return getLargeUpdateCount();
    @Override
    @Override

        getOriginal().addBatch(sql);
    @Override
        }
        if (rsMaxRows > 0 && connection.getDataSource().getInfo().supportsResultSetLimit()) {
    public <T> T unwrap(Class<T> iface) throws SQLException {
        } catch (Throwable e) {
            return getResultSet();

                // We'll use rsOffset and rsMaxRows anyway
        }
        return "JDBC Statement [" + query + "]";

    @Override
    protected void endBlock() {
    }
        }
        } catch (SQLException e) {

        this.beforeExecute();

        if (connection.getDataSource().getContainer().getPreferenceStore().getBoolean(ModelPreferences.QUERY_ROLLBACK_ON_ERROR)) {
        return connection;
        return getOriginal().isWrapperFor(iface);
                if (warnings == null) {
    @Override
    @Nullable
    }
    // Close
 * Unless required by applicable law or agreed to in writing, software
    public void cancelBlock(
    }
                }

    @Override
    // Executions
        return getOriginal().isPoolable();
import org.jkiss.utils.CommonUtils;
        }
    @Override
        }
    @Override
    }
            this.afterExecute();


        } else {
            try {
    }

        }
        } finally {
        this.closed = true;
    }
        setQueryString(sql);
                long[] longResult = new long[result.length];
            return isClosed();

                    connection.rollback();
        if (isQMLoggingEnabled()) {
    @Override
        getOriginal().setMaxRows(max);
        }
    @Override
        return result;
    protected void beforeExecute() {
        }

import org.jkiss.dbeaver.ModelPreferences;
    public void cancel() throws SQLException {
            return makeResultSet(getOriginal().getGeneratedKeys());
                log.error("Can't rollback connection after error (" + ex.getMessage() + ")", e); //$NON-NLS-1$ //$NON-NLS-2$
    }


        } catch (Throwable e) {
    }
                // [JDBC:ODBC] Probably setMaxRows is not supported. Just log this error
            throw this.handleExecuteError(e);
    @Nullable
    @Override
        this.beforeExecute();
        }
    @Override
        // Some driver perform real RS fetch at this moment.
            QMUtils.getDefaultHandler().handleStatementExecuteBegin(this);
    @Override
        return getOriginal().getResultSetHoldability();
package org.jkiss.dbeaver.model.impl.jdbc.exec;
    @Override
        } catch (Throwable e) {
        } finally {
            totalRows = limit > 0 ? (int) (offset + limit) : -1;
                try {
 */
        if (isQMLoggingEnabled()) {
        } finally {

        getOriginal().setEscapeProcessing(enable);
        boolean disableLogging
        return connection.getDataSource().getJdbcFactory().createResultSet(connection, this, resultSet, disableLogging);
            if (closeError != null) {
        }
    public JDBCResultSet executeQuery(@NotNull String sql) throws SQLException {
    @Override
        return getOriginal().isClosed();
        }
        } catch (SQLException e) {
    @Override
        try {
                return this.executeLargeBatch();
        return getOriginal().getMoreResults();
    public void close() {
            this.afterExecute();
        return uc;
            totalRows = (int) limit;
 * distributed under the License is distributed on an "AS IS" BASIS,
        connection.getProgressMonitor().endBlock();
        return getOriginal().unwrap(iface);
    }
    @Override
                log.error("Error closing statement (suppressed", e);
                    log.debug("Internal error during clearWarnings", e);
    public boolean isPoolable() throws SQLException {
    }
        this.startBlock();
        }
    @Nullable
    public JDBCStatementImpl(
            this.rsMaxRows = limit;
            return handleExecuteResult(getOriginal().execute(sql, columnNames));
        } finally {
        setQueryString(sql);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;

    public int getMaxRows() throws SQLException {
    @Override
        }
    /// /////////////////////////////////////////////////////////////////
    @Override

    }

        return getOriginal().isCloseOnCompletion();
        getOriginal().setCursorName(name);

    }
        // We signal statement pen BEFORE we get actual one
    }

    public void addToBatch() throws DBCException {
    }
        return uc;
                } catch (Throwable e) {

        }
    @Override
            this.updateCount = uc;
        setQueryString(sql);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCObjectSupplier;
    }

    @Override
        } finally {
    public void setMaxFieldSize(int max) throws SQLException {
    protected boolean handleExecuteResult(boolean result) {


    private boolean closed;

        getOriginal().setFetchSize(rows);

            try {

    public boolean isCloseOnCompletion() throws SQLException {
    }
                log.debug("Error reading JDBC warnings: " + e.getMessage());
        this.disableLogging = disableLogging;
        getOriginal().closeOnCompletion();
        try {
import org.jkiss.dbeaver.DBException;
            this.endBlock();


        } catch (SQLException e) {
    // DBC Statement overrides
    public int getFetchDirection() throws SQLException {
        getOriginal().clearBatch();
        }
                }
        } catch (Throwable e) {
            throw this.handleExecuteError(e);
            throw new DBCException("Unable to determine if statement is closed", e);
        } catch (Throwable e) {
            return (SQLException) ex;
    @Override

            throw new DBCException(e, connection.getExecutionContext());
    @Override
        } catch (SQLException e) {



            throw this.handleExecuteError(e);
        try {
        getOriginal().cancel();
 */
    }
    public int getResultSetType() throws SQLException {
        this.original = original.get();
    public boolean isStatementClosed() throws DBCException {
    public JDBCSession getConnection() {

        try {
            //            return SecurityManagerUtils.wrapDriverActions(connection.getDataSource().getContainer(), () -> execute(query));
    @Override
        getConnection().getDataSource().cancelStatementExecute(monitor, this);
import org.jkiss.dbeaver.model.exec.DBCException;
        final long uc = getOriginal().getLargeUpdateCount();
            List<Throwable> warnings = null;
    }
    }
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    }
            }

        } finally {
        this.beforeExecute();

    @Override
    public void setLimit(long offset, long limit) throws DBCException {
    }
        return result;

                    break;
        } catch (SQLException e) {
        return getOriginal().getResultSetConcurrency();
    }
        if (JDBCUtils.LOG_JDBC_WARNINGS) {
        }
        return getOriginal().getMaxRows();
    @Override
        }
    public int getResultSetHoldability() throws SQLException {
            this.rsMaxRows = limit;
*/
import org.jkiss.dbeaver.Log;
    @Nullable
    }
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    public boolean isClosed() throws SQLException {
        }
    @Override
    }
        try {

    }
    @Override
    }
 * Licensed under the Apache License, Version 2.0 (the "License");
    @Override
        Throwable closeError = null;
        this.updateCount = -1;
    public void setQueryTimeout(int seconds) throws SQLException {
        return getOriginal().getQueryTimeout();
    public void setResultsFetchSize(int fetchSize) throws DBCException {
 * Copyright (C) 2010-2025 DBeaver Corp and others
    @Override
    public void setFetchSize(int rows) throws SQLException {
            }
        setQueryString(sql);
            throw this.handleExecuteError(e);
import org.jkiss.dbeaver.DBRuntimeException;
    ////////////////////////////////////////////////////////////////////
            return warnings == null ? null : warnings.toArray(new Throwable[0]);
    /// /////////////////////////////////
            this.afterExecute();
                    longResult[i] = result[i];

        return original;
        }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        getOriginal().setQueryTimeout(seconds);

    protected String query;
    protected void startBlock() {
            return updateCount;
                setMaxRows(totalRows);
public class JDBCStatementImpl<STATEMENT extends Statement> extends AbstractStatement<JDBCSession> implements JDBCStatement {
                if (warning.getMessage() == null && warning.getErrorCode() == 0) {
    @Override
    public int getResultSetConcurrency() throws SQLException {
        return getOriginal().getMoreResults(current);
            getOriginal().setFetchSize(fetchSize);
    @Override
        } catch (Throwable e) {
    }
            addBatch(query);
        this.endBlock();
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

    private long updateCount;
        if (closeError != null) {
                }
        try {
        if (closed) {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
    public Throwable[] getStatementWarnings() throws DBCException {
            throw new DBRuntimeException(closeError);

        @NotNull JDBCSession connection,
            }
    @Override
 *
        }
    }
    public boolean execute(@NotNull String sql) throws SQLException {
                for (int i = 0; i < result.length; i++) {
        } catch (SQLException e) {

    private static final Log log = Log.getLog(JDBCStatementImpl.class);
            this.rsOffset = offset;
                JDBCUtils.reportWarnings(getSession(), this.getWarnings());
        } finally {
    }
        }
        return getOriginal().getFetchDirection();
        try {
        return makeResultSet(getOriginal().getGeneratedKeys());
            return getOriginal().executeBatch();
    @Nullable
    }
        this.beforeExecute();

        } finally {
    @Override

    }
        // for each closed statement on this connection (MySQL)
            // Cache update count (for QM logging)

        this.startBlock();
 * You may obtain a copy of the License at
            return handleExecuteResult(getOriginal().executeUpdate(sql, columnNames));
                }
                    continue;
    @Override
    public boolean getMoreResults(int current) throws SQLException {
        }
            return handleExecuteResult(getOriginal().executeUpdate(sql));
    public boolean execute(String sql, String[] columnNames) throws SQLException {
    @Override
        } catch (SQLException e) {
            throw new DBCException(e, connection.getExecutionContext());
        } catch (Throwable e) {
    }
            } catch (SQLException e) {
        setQueryString(sql);
    @Override

    @Override
        int totalRows;
            getOriginal().setQueryTimeout(timeout);
        try {
}
            throw new DBSQLException(query, e, connection.getExecutionContext());
        @NotNull DBRProgressMonitor monitor,
        // Do not check for warnings here
        if (closed) {
 * you may not use this file except in compliance with the License.
    }
            log.debug("Can't check for statement warnings", e);
        int uc = getOriginal().getUpdateCount();
    @Nullable
            for (SQLWarning warning = getWarnings(); warning != null; warning = warning.getNextWarning()) {
    @Override

                warnings.add(warning);
    public boolean nextResults() throws DBCException {
        try {
    }
            // Just set max row num
                    clearWarnings();
    }
        this.connection.getProgressMonitor().startBlock(
 * limitations under the License.
            return handleExecuteResult(getOriginal().execute(sql, autoGeneratedKeys));
    }
    protected boolean disableLogging;
            return updateCount;
                    // Skip trash [Excel driver]
            JDBCUtils.scrollResultSet(resultSet, rsOffset, !getConnection().getDataSource().getInfo().supportsResultSetScroll());
            getOriginal().close();

            if (!CommonUtils.isEmpty(warnings)) {
    @Override
    public JDBCResultSet openGeneratedKeysResultSet() throws DBCException {
 * DBeaver - Universal Database Manager
        if (JDBCTrace.isApiTraceEnabled()) {
        try {

    @Override
    public void setQueryString(@Nullable String query) {
                log.debug(getOriginal().getClass().getName() + ".setMaxRows not supported?", e);
            this.afterExecute();
    }
        } catch (Throwable e) {
    public boolean executeStatement() throws DBCException {
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        try {
    protected JDBCResultSet makeResultSet(@Nullable ResultSet resultSet) throws SQLException {
    }
    ) throws DBException {
    /// /////////////////////////////////////////////////////////////////
    }
    @Override
    }
            }
    }
                return longResult;

    }
            return (int) updateCount;
    public JDBCResultSet openResultSet() throws DBCException {

import org.jkiss.code.Nullable;
    }
    }
    }
import org.jkiss.dbeaver.model.messages.ModelMessages;
        setQueryString(sql);
        try {
import org.jkiss.dbeaver.model.sql.DBSQLException;
            super.close();
    @Nullable
        } else {

    }
        // Scroll original result set if needed
    public long getUpdateRowCount() throws DBCException {
    // Statement overrides
            return new SQLException(ModelMessages.model_jdbc_exception_internal_jdbc_driver_error, ex);
        try {
        return getOriginal().getMaxFieldSize();
        }
            this.updateCount = uc;
        try {
    }
    ) throws SQLException {
        try {
            throw new DBCException(e, connection.getExecutionContext());
        } finally {
        return dbResult;
            JDBCTrace.traceQueryBegin(getQueryString());
    }
            throw new DBSQLException(query, e, connection.getExecutionContext());
    protected JDBCResultSet createResultSetImpl(ResultSet resultSet) throws SQLException {
    @Nullable
            return null;
            } catch (Throwable ignored) {
            this.afterExecute();
            }
    // Other
