        throws SQLException
    public void setAsciiStream(int parameterIndex, InputStream x)
        throws SQLException
        return 0;
        throws SQLException
    public ResultSetMetaData getMetaData()
    @Override
    }

    }
    @Override
    }
    {
import java.sql.*;
    }
    public boolean getMoreResults()
        return 0;
 *     http://www.apache.org/licenses/LICENSE-2.0
    public ResultSet executeQuery(String sql)
      
    @Override
    }
        return 0;
      
    public void closeOnCompletion() throws SQLException {
        throws SQLException
    }
        throws SQLException
    @Override
    {
    @Override
        throws SQLException
    {
    public ResultSet getResultSet()
    @Override
    public void setTime(int parameterIndex, Time x)
    public Connection getConnection()
    {
    {
    }
    {
    }
      
    @Override
    {
    }
        throws SQLException
    public void setDate(int parameterIndex, Date x)

    {


    public int executeUpdate(String sql, int autoGeneratedKeys)

        return false;
      
    }
        throws SQLException
        throws SQLException
    }
        throws SQLException
import java.io.Reader;
      
    public void setClob(int parameterIndex, Reader reader, long length)
    @Override
        throws SQLException

        return 0;
 * limitations under the License.
    {
      

    {
        throws SQLException
    public int executeUpdate()
    public void setUnicodeStream(int parameterIndex, InputStream x, int length)
        throws SQLException
    }
    }
    }
      
    @Override
    public void cancel()
    public void setQueryTimeout(int seconds)

    }
    public boolean execute(String sql, String[] columnNames)
    {
      
    @Override
import java.math.BigDecimal;
    {
    public void setSQLXML(int parameterIndex, SQLXML xmlObject)
    {
        return null;
        return false;
        return false;
        throws SQLException
        throws SQLException
    }
    @Override
        throws SQLException

    {
    }
    @Override
        throws SQLException
    @Nullable
    @Override
    @Override
    @Override
    @Nullable
        throws SQLException
    }

    }
    {
    {


        throws SQLException



    @Override
    {
    public boolean execute(String sql, int autoGeneratedKeys)
    {

    }
      
    @Override
    }
    public int getMaxRows()

    @Nullable
        throws SQLException
    }

    public void addBatch()
    {
    @Override

      
        throws SQLException
        throws SQLException
package org.jkiss.dbeaver.model.impl.jdbc.exec;
    @Override

        throws SQLException
    {
    @Override
      
    }
        throws SQLException
    @Override
    public boolean execute(String sql)
    }
    {
      

        throws SQLException

    }


        throws SQLException
        throws SQLException
    }
    }
    @Nullable
    }
    public void setNCharacterStream(int parameterIndex, Reader value)
    }
        throws SQLException
    {
      
}
    @Override
    {
    }
        throws SQLException
    }


        return null;
        throws SQLException
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
    public void clearBatch()
    {
    @Override
    @Override
    }
    public void setPoolable(boolean poolable)
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        return null;
import org.jkiss.code.Nullable;
    @Override

    }
    {
        throws SQLException
    }

    @Override
    }
        throws SQLException
    }
        throws SQLException
    public void setNClob(int parameterIndex, Reader reader, long length)
    public void setString(int parameterIndex, String x)
      
    @Override
    }
    }
    {
        return 0;
    }
        throws SQLException
    }
    public ResultSet getGeneratedKeys()

      
    }
      
        throws SQLException
    {
    public void setBlob(int parameterIndex, Blob x)
    @Override
      

      
    {
    public void setURL(int parameterIndex, URL x)
        return null;
      
        return 0;
    {
    {
        throws SQLException
 * you may not use this file except in compliance with the License.
    public void setTimestamp(int parameterIndex, Timestamp x)
    {
    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length)
    @Deprecated
    {
        throws SQLException
    }
      
        throws SQLException
    }
      
    public void setFetchDirection(int direction)
    }

    {
        throws SQLException
      

        throws SQLException
    }

    @Override
    {
    @Override
    @Override
    {
    {
    {

    {
    }
    }
    @Override

    }
    {
    @Override

        throws SQLException
        return 0;

        throws SQLException
    @Override
    public void setFetchSize(int rows)
        throws SQLException
    {
    {

        return false;
    }
    @Override
    public ParameterMetaData getParameterMetaData()

    public int getResultSetConcurrency()
    {
    {
        return 0;
    {
        return 0;
    @Override
    }
        throws SQLException
        throws SQLException

        throws SQLException
    @Override
    {
    {
        throws SQLException
    public void setCharacterStream(int parameterIndex, Reader reader)
        return false;
import java.io.InputStream;
    @Override

/**
    }
    @Override

    }
    }
      
    public ResultSet executeQuery()
        return null;

    {
 *
    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length)
 * Copyright (C) 2010-2024 DBeaver Corp and others
    @Override
        throws SQLException
        return null;
    }
    @Override
    }

        return new int[0];
    @Override
    }
        throws SQLException
    {
    {
        return 0;
    @Override
    {

        throws SQLException
    @Override
    {
        throws SQLException
      
        return 0;
    }
      
    @Override
    public void setClob(int parameterIndex, Reader reader)

    @Override
      
    public void setObject(int parameterIndex, Object x)

    @Override
      
    {
    @Override
    @Override

 */
    }
        throws SQLException
    @Override
    @Override
    }

    }
      

    public boolean isClosed()
    @Override
    @Override
    public void setRowId(int parameterIndex, RowId x)
    {
    {

        throws SQLException
      
    }
      
    {
    public void setArray(int parameterIndex, Array x)


    public int getFetchSize()
    public int getQueryTimeout()
        throws SQLException

        throws SQLException
    public void setClob(int parameterIndex, Clob x)
    }
        throws SQLException
    public void setRef(int parameterIndex, Ref x)
    public boolean isWrapperFor(Class<?> iface)
        throws SQLException
        throws SQLException
    public void setBinaryStream(int parameterIndex, InputStream x, int length)

        return false;
    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal)
    @Override
    {
    }
    }
    @Override
        throws SQLException
    }
    {

      
    {
    }
        throws SQLException
    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal)
        return 0;
    }
      
    public void setDouble(int parameterIndex, double x)


      
/*

    @Override
        throws SQLException
      
      
        return false;

    public boolean getMoreResults(int current)
        throws SQLException
      
    public boolean isPoolable()

    @Override
    {
    public SQLWarning getWarnings()
    @Override
    }
      
    @Override
        throws SQLException

      
        throws SQLException
    {
    @Override
        throws SQLException
    {
        throws SQLException
 * distributed under the License is distributed on an "AS IS" BASIS,
    @Override
    @Override
      
    @Override
    }
      

    }
      
    public <T> T unwrap(Class<T> iface)

      
 * You may obtain a copy of the License at
        return false;
        throws SQLException
    {
    @Override
        throws SQLException

    @Override
        throws SQLException
    {
        throws SQLException
    public static final JDBCVoidStatementImpl INSTANCE = new JDBCVoidStatementImpl();
    {
    @Override
      

    public void setBigDecimal(int parameterIndex, BigDecimal x)
    }
      
        throws SQLException
import java.util.Calendar;
    @Override

        return null;
    public void setAsciiStream(int parameterIndex, InputStream x, int length)

      
    }

    {
    public void setNCharacterStream(int parameterIndex, Reader value, long length)
        throws SQLException
    }
        throws SQLException
    {

    public void clearParameters()
 *
    @Override
      
        throws SQLException

    public void setBinaryStream(int parameterIndex, InputStream x, long length)

        throws SQLException
    public boolean execute(String sql, int[] columnIndexes)
    {
    public int getResultSetType()
        throws SQLException
    public boolean isCloseOnCompletion() throws SQLException {


    public void clearWarnings()

    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength)
    {
        return false;
        throws SQLException
    }
    }
    }
    }
        throws SQLException
 */

    }
    }
        return false;
    @Override
    public void setMaxFieldSize(int max)
 * See the License for the specific language governing permissions and
        return 0;

    @Override


    @Override
    {
      
    {
    @Override
      

    @Override
    @Override
        throws SQLException
    public void setByte(int parameterIndex, byte x)
      
    @Override
    @Nullable
    @Override
public class JDBCVoidStatementImpl implements PreparedStatement {

    @Nullable
    @Override
    public void setMaxRows(int max)
    @Override
    public void setNClob(int parameterIndex, NClob value)

    {
    public void setNString(int parameterIndex, String value)
    {
    @Override
    public int executeUpdate(String sql, String[] columnNames)
 * Licensed under the Apache License, Version 2.0 (the "License");

    @Override
      
    }
    public int executeUpdate(String sql, int[] columnIndexes)
    @Override
    @Override

 *
    public int[] executeBatch()

    }
 * DBeaver - Universal Database Manager
    public void setNull(int parameterIndex, int sqlType, String typeName)
        throws SQLException
      
    public int getUpdateCount()
    @Override
    }
    }
        throws SQLException
      
      
    public void setAsciiStream(int parameterIndex, InputStream x, long length)
    {
    public void setObject(int parameterIndex, Object x, int targetSqlType)
    public int getMaxFieldSize()
    {
    {
    public void setNClob(int parameterIndex, Reader reader)
    public void setInt(int parameterIndex, int x)


    @Override
      
    @Override

    {
    }
    }
      
        return false;
    public void setFloat(int parameterIndex, float x)
        throws SQLException
        throws SQLException
    {
    {

    @Override
    {
    {

    public int getResultSetHoldability()
    {
      

        throws SQLException
        throws SQLException
    public void setEscapeProcessing(boolean enable)
    }
    {
    {
    {
    public void setLong(int parameterIndex, long x)
    @Override
        throws SQLException
    public void setBoolean(int parameterIndex, boolean x)

        throws SQLException
        throws SQLException
    {
    }
    }
        throws SQLException
    public void addBatch(String sql)
        throws SQLException
    public int getFetchDirection()
    public void setBlob(int parameterIndex, InputStream inputStream)
    public void close()
    public void setCursorName(String name)
    public void setBlob(int parameterIndex, InputStream inputStream, long length)
    @Override

import java.net.URL;
      
    {
        throws SQLException
    {
    {
    {
 * Void PreparedStatement
      
    @Nullable
    {
        throws SQLException
      
        throws SQLException

    {

      
    }
 * Unless required by applicable law or agreed to in writing, software


    @Override

    {
    }
    @Override

      
    }
    {
    }

    @Override
    {
    public void setNull(int parameterIndex, int sqlType)
    @Override
    @Nullable
    public void setBinaryStream(int parameterIndex, InputStream x)
      
    @Override
    }
        throws SQLException
      
    @Override
        return null;
    public int executeUpdate(String sql)
    }

    public boolean execute()
        throws SQLException
        return null;
    {
    }
    @Override
        throws SQLException

        return 0;
    public void setShort(int parameterIndex, short x)

    {
    }
    }
    public void setBytes(int parameterIndex, byte[] x)
    @Nullable
        throws SQLException

    }
    }
    {
