        return attribute.isRequired();
    public boolean isReadOnly() {
    public Integer getScale() {
    }
    public long getTypeModifiers() {
    }
        return false;


    @Override
    public DBCEntityMetaData getEntityMetaData() {
    @Override
        }
    {
        if (attribute instanceof DBSObject) {
import org.jkiss.dbeaver.model.exec.DBCAttributeMetaData;


    }
    @Override

    {
    /**
    }
        return attribute.getTypeModifiers();
    }
        DBSAttributeBase proxyAttribute = getProxyAttribute();
    public int hashCode() {
 * you may not use this file except in compliance with the License.
     */
    @NotNull
    @NotNull
 *     http://www.apache.org/licenses/LICENSE-2.0
        DBSObject source = getSource();
    @NotNull
    @NotNull
    @Nullable
        return null;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
    {
import org.jkiss.dbeaver.model.struct.DBSObject;
        }
    public boolean isAutoGenerated() {

    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
    }

    }

    }
    public DBPImage getObjectImage() {

 * Licensed under the Apache License, Version 2.0 (the "License");
    public String getFullTypeName() {
    @Nullable
    }
    @Override
            return ((DBSObject)attribute).getParentObject();
    /**
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    @Override
    @NotNull
    @Override
        return null;

 *
    }
        return obj instanceof AttributeMetaDataProxy &&
    public long getMaxLength() {
 * You may obtain a copy of the License at
            return attributeMetaData.getLabel();
package org.jkiss.dbeaver.model.impl.data;
}
 * Unless required by applicable law or agreed to in writing, software
    }

        return attribute.isAutoGenerated();
import org.jkiss.dbeaver.model.exec.DBCEntityMetaData;
 * Copyright (C) 2010-2024 DBeaver Corp and others

 * DBeaver - Universal Database Manager

        return attribute.getFullTypeName();
import org.jkiss.code.NotNull;
    {

/**
import org.jkiss.dbeaver.model.DBPImage;
    @Nullable
        if (source instanceof DBSEntity) {

 * Type attribute value binding info
    @NotNull
    public String getEntityName() {
    public String getName()
    public String getTypeName() {
            return source.getName();
    public int getTypeID() {
    @Override
 */
    public DBSAttributeBase getProxyAttribute() {
        DBSAttributeBase proxyAttribute = getProxyAttribute();
     */
        return null;
    @Override
    public String getLabel()
    }
    @Nullable
    }
     * Attribute index in result set
    public AttributeMetaDataProxy(
        if (proxyAttribute instanceof DBCAttributeMetaData attributeMetaData) {
        return attribute.getPrecision();

    }
/*
    public DBSObject getSource() {
    @Nullable
    }
 * limitations under the License.

    public int getOrdinalPosition()
    public boolean equals(Object obj) {
    @Nullable

        return attribute.getMaxLength();
        return attribute.getTypeID();
    @Override
    }
     * @return attribute index (zero based)
    }
    }
    @Override
    }
    @Override
    @Override
        return attribute.hashCode();
            attribute.equals(((AttributeMetaDataProxy) obj).attribute);
        }
    @NotNull
        return attribute.getScale();

    }
    public String toString() {
    @Override
    public boolean isRequired() {
    @Override
 * See the License for the specific language governing permissions and

        return DBValueFormatting.getObjectImage(attribute);
        @NotNull DBSAttributeBase attribute)
        return attribute.getOrdinalPosition();
        return attribute.getDataKind();

import org.jkiss.dbeaver.model.DBPDataKind;

     */

     * Attribute name
    @Override
import org.jkiss.dbeaver.model.DBPImageProvider;
    /**
        return attribute.getTypeName();
    @Override
 *
 */
public class AttributeMetaDataProxy implements DBCAttributeMetaData, DBPImageProvider {
        }
        return attribute.getName();
    }

     * Attribute label
        if (proxyAttribute instanceof DBCAttributeMetaData attributeMetaData) {
    @Override
import org.jkiss.dbeaver.model.DBValueFormatting;
    }
            return attributeMetaData.getEntityMetaData();

        return attribute.toString();
        return attribute.getName();
    public Integer getPrecision() {
    }
    public DBPDataKind getDataKind() {
    protected final DBSAttributeBase attribute;

import org.jkiss.dbeaver.model.struct.DBSEntity;
        this.attribute = attribute;
    @Override
        return attribute;
 *
