/**
    }
            column.setValueType(oracleTableColumn.getTypeID());
        @NotNull DBECommandContext commandContext,
    }
 */
            column.setTypeName(oracleTableColumn.getTypeName());
 * you may not use this file except in compliance with the License.
    }
 */
                        sql.append(patchedName);
        } else {
            if (oracleTableColumn.getDataType() != null) {
                        String patchedName = " INTERVAL YEAR(" + precision + ") TO MONTH";
        final OracleTableColumn column = new OracleTableColumn(table);
import org.jkiss.dbeaver.model.DBUtils;
                        String patchedName = " INTERVAL DAY(" + precision + ") TO SECOND(" + scale + ")";

            column.setAutoGenerated(oracleTableColumn.isAutoGenerated());
import org.jkiss.dbeaver.ext.oracle.model.OracleTableColumn;
            column.setName(getNewColumnName(monitor, context, table));

        }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
import org.jkiss.code.Nullable;
        @NotNull Map<String, Object> options


    }
        if (dataType != null) {
        @NotNull Map<String, Object> options
        }
    @Override
            addColumnCommentAction(actions, command.getObject(), command.getObject().getParentObject());
import org.jkiss.dbeaver.model.impl.edit.SQLDatabasePersistAction;
import org.jkiss.dbeaver.model.struct.DBSDataType;
    }
            }
        final OracleTableColumn column = command.getObject();
    }
import org.jkiss.dbeaver.DBException;
        super.addObjectCreateActions(monitor, executionContext, actions, command, options);
import org.jkiss.dbeaver.ext.oracle.model.OracleTableBase;
    }
    implements DBEObjectRenamer<OracleTableColumn> {
 * distributed under the License is distributed on an "AS IS" BASIS,
 * DBeaver - Universal Database Manager

import org.jkiss.dbeaver.model.edit.DBECommandContext;
                column.setDataType((OracleDataType) columnType);
import org.jkiss.dbeaver.model.edit.DBEPersistAction;
 * See the License for the specific language governing permissions and
                if (OracleConstants.TYPE_INTERVAL_YEAR_MONTH.equals(typeName) && precision != null) {
import org.jkiss.utils.CommonUtils;
                    if (scale != null) {
        @NotNull OracleTableColumn object,
            String typeName = dataType.getTypeName();
    protected void addObjectRenameActions(
        @NotNull ObjectCreateCommand command,
        return true;
    };
                Integer precision = column.getPrecision();
        @NotNull ObjectRenameCommand command,
                        sql.append(patchedName);
        @NotNull DBRProgressMonitor monitor,

    @Override
    protected final ColumnModifier<OracleTableColumn> OracleDataTypeModifier = (monitor, column, sql, command) -> {
        @NotNull DBRProgressMonitor monitor,
        processObjectRename(commandContext, object, options, newName);
        @NotNull Map<String, Object> options
        column.setOrdinalPosition(-1);
    @Override
                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getNewName())

import org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableColumnManager;
            column.setMaxLength(oracleTableColumn.getMaxLength());
                        return;
            column.setName(oracleTableColumn.getName());
    ) {
                // These types have precision inside type name
 * Copyright (C) 2010-2025 DBeaver Corp and others
import org.jkiss.dbeaver.model.DBPEvaluationContext;
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + //$NON-NLS-1$
    ) {
        final OracleTableColumn column = command.getObject();
            }
                "Rename column",
 * You may obtain a copy of the License at
import org.jkiss.dbeaver.ext.oracle.model.OracleDataType;
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " RENAME COLUMN " +
            addColumnCommentAction(actionList, column, column.getTable());
            column.setRequired(oracleTableColumn.isRequired());

                    if (precision != OracleConstants.INTERVAL_DEFAULT_YEAR_DAY_PRECISION) {
                    " MODIFY " + getNestedDeclaration(monitor, column.getTable(), command, options)
            )
        OracleTableBase table = (OracleTableBase) container;
        if (!hasComment || command.getProperties().size() > 1) {
    protected void addObjectModifyActions(
            actionList.add(new SQLDatabasePersistAction(
        actions.add(
        DataTypeModifier.appendModifier(monitor, column, sql, command);
import org.jkiss.dbeaver.ext.oracle.model.OracleConstants;
    @Nullable
        @NotNull DBRProgressMonitor monitor,
        @NotNull String newName
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.edit.DBEObjectRenamer;
                    }
                column.setValueType(columnType.getTypeID());
                        return;
            column.setDefaultValue(oracleTableColumn.getDefaultValue());
    @Override
}
 *
 *
                "Modify column",
        @NotNull DBCExecutionContext executionContext,
    ) throws DBException {

    public void renameObject(
                column.setDataType(oracleTableColumn.getDataType());

package org.jkiss.dbeaver.ext.oracle.edit;
import java.util.Map;
        @NotNull ObjectChangeCommand command,

        @NotNull DBCExecutionContext executionContext,

        if (copyFrom instanceof OracleTableColumn oracleTableColumn) {

        @NotNull DBCExecutionContext executionContext,
        @NotNull DBRProgressMonitor monitor,
        OracleDataType dataType = column.getDataType();
    public DBSObjectCache<? extends DBSObject, OracleTableColumn> getObjectsCache(OracleTableColumn object) {

        @NotNull Map<String, Object> options
                    }
 * limitations under the License.
    protected ColumnModifier[] getSupportedModifiers(OracleTableColumn column, Map<String, Object> options) {
    public boolean canEditObject(@NotNull OracleTableColumn object) {
        if (hasComment) {
            column.setScale(oracleTableColumn.getScale());
                    Integer scale = column.getScale(); // fractional seconds precision

        if (CommonUtils.isNotEmpty(command.getObject().getDescription())) {
        Object container,

import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;
            DBSDataType columnType = findBestDataType(table, "varchar2");
/*
        }
    ) throws DBException {
 * Oracle table column manager
        }
        @NotNull List<DBEPersistAction> actions,
            column.setPrecision(oracleTableColumn.getPrecision());
        @NotNull DBECommandContext context,

                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getOldName()) + " TO " +
import org.jkiss.code.NotNull;
            )); //$NON-NLS-1$
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
        );
        }
        return object.getParentObject().getContainer().tableCache.getChildrenCache(object.getParentObject());

    @Override
import org.jkiss.dbeaver.model.DBPDataKind;
    protected OracleTableColumn createDatabaseObject(
            if (dataType.getDataKind() == DBPDataKind.STRING && column.isPersisted() &&
        return column;
        @NotNull Map<String, Object> options,
        Object copyFrom,
    @Override
public class OracleTableColumnManager extends SQLTableColumnManager<OracleTableColumn, OracleTableBase>
        boolean hasComment = command.getProperty("comment") != null;
            if (columnType != null) {
 *     http://www.apache.org/licenses/LICENSE-2.0
            new SQLDatabasePersistAction(
        return new ColumnModifier[] {OracleDataTypeModifier, DefaultModifier, NullNotNullModifierConditional};
                (OracleConstants.TYPE_INTERVAL_DAY_SECOND.equals(typeName) || OracleConstants.TYPE_INTERVAL_YEAR_MONTH.equals(typeName))) {
    ) throws DBException {
                }
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;

    }

import java.util.List;
            }
    protected void addObjectCreateActions(
                } else {
        @NotNull List<DBEPersistAction> actionList,
import org.jkiss.dbeaver.model.struct.DBSObject;
 * Unless required by applicable law or agreed to in writing, software
                column.setTypeName(columnType.getName());
    @Override
        @NotNull List<DBEPersistAction> actions,
                column.setMaxLength(columnType.getDataKind() == DBPDataKind.STRING ? 100 : 0);
