    			);
        return column;
    protected void addObjectRenameActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions, @NotNull ObjectRenameCommand command, @NotNull Map<String, Object> options) {
import org.jkiss.code.NotNull;
    }
    // -------
    	return new SQLDatabasePersistAction(
    }
        
/**
    // -----
import org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableColumnManager;
        	
import org.jkiss.dbeaver.model.DBUtils;
        }
                );
    	for(ExasolTableColumn c: distKey)
    // Create
        }
    
    {
                    "Add column",
                                                     Object copyFrom, @NotNull Map<String, Object> options) throws DBException {
        }
    			String.format(CREATE_DIST_KEY, table.getFullyQualifiedName(DBPEvaluationContext.DDL), CommonUtils.joinStrings(",", names))
    	}
    			ret = ret + identityValue.toString() + " ";
        	try {
        actions.add(
import org.jkiss.dbeaver.ext.exasol.model.ExasolTableBase;
        		props.containsKey("identityValue") ||
    }
 *
import org.jkiss.dbeaver.model.edit.DBEPersistAction;
    	ExasolTable table = (ExasolTable) exasolColumn.getParentObject();
        DBEPersistAction commentAction = buildCommentAction(exasolColumn);
            new SQLDatabasePersistAction(
        return object.getParentObject().getContainer().getTableCache().getChildrenCache((ExasolTable) object.getParentObject());
                    "ALTER TABLE " + exasolColumn.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " ADD COLUMN " + addSQL + " "
        	String nullability = "";
                                          @NotNull Map<String, Object> options) {
        		props.containsKey("required")
    			"Create Distribution Key",
    }
public class ExasolTableColumnManager extends SQLTableColumnManager<ExasolTableColumn, ExasolTableBase> implements DBEObjectRenamer<ExasolTableColumn> {
        
import org.jkiss.dbeaver.model.edit.DBECommandContext;
    private String formatIdentiy(Boolean isAutoGenerated,BigDecimal identityValue)
import org.jkiss.code.Nullable;
 * @author Karl Griesser
    	// build nullability string
        if (exasolColumn.isDistKey())
    		
    	return commands;
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
            return null;
    	{
    protected void addObjectCreateActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions,
            + " " + nullability;
        if ((exasolTableBase != null) && (exasolTableBase.getClass().equals(ExasolTable.class))) {
        if (command.getProperties().containsKey("distKey"))
			try {
    }
    			"Drop Distribution Key",
 * Copyright (C) 2010-2025 DBeaver Corp and others

    
        } else {
import org.jkiss.dbeaver.model.DBPEvaluationContext;
    	{

    }
    	return ret;
    		
        }

    private static final String DROP_DIST_KEY = "ALTER TABLE %s DROP DISTRIBUTION KEYS";
 * Unless required by applicable law or agreed to in writing, software
 * DBeaver - Universal Database Manager

    private SQLDatabasePersistAction generateDropDist(ExasolTableColumn exasolColumn)
            return new SQLDatabasePersistAction(CMD_COMMENT, commentSQL);

    	ExasolTable table = null;
    {
                + " " + nullability;
        		nullability = exasolColumn.isRequired() ? "NOT NULL" : "NULL";
    
    	
    @Override
        		
import org.jkiss.dbeaver.Log;
    	if (!distKey.isEmpty())
        ExasolTableBase exasolTableBase = object.getParentObject();
        processObjectRename(commandContext, object, options, newName);

import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;
    	
    }
 * Licensed under the Apache License, Version 2.0 (the "License");
        column.setName(getNewColumnName(monitor, context, (ExasolTableBase) container));
    	);
    public DBSObjectCache<? extends DBSObject, ExasolTableColumn> getObjectsCache(ExasolTableColumn object) {
import java.util.List;

        Map<Object,Object> props = command.getProperties();
        }
        	if (exasolColumn.isOriRequired() != null &&  exasolColumn.isOriRequired() != exasolColumn.isRequired())
				modifyDistKey(monitor, exasolColumn);
                "ALTER TABLE " + column.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL) + " RENAME COLUMN " +
    }

 * Exasol Table Column Manager
    {
 *
        if ( props.containsKey("defaultValue") ||
                + " " + formatIdentiy(exasolColumn.isAutoGenerated(), exasolColumn.getIdentityValue())
                + " " + (exasolColumn.getDefaultValue() == null ? "" : " DEFAULT " + exasolColumn.getDefaultValue())
    protected void addObjectModifyActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actionList, @NotNull ObjectChangeCommand command, @NotNull Map<String, Object> options) {
        actions.add(
    			String.format(
    	final ExasolTableColumn exasolColumn = command.getObject();
    	return new SQLDatabasePersistAction(

           ) {
    	Collection<SQLDatabasePersistAction> commands = new ArrayList<SQLDatabasePersistAction>();
            String comment = exasolColumn.getDescription();
    private static final String SQL_ALTER = "ALTER TABLE %s MODIFY COLUMN %s ";
    
    // ------
				log.error("Failed to modify distkey settings",e);
    					DROP_DIST_KEY, 
                String sqlAlterColumn = String.format(SQL_ALTER, exasolColumn.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL), deltaSQL);
    		if (table == null)
    
                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getOldName()) + " TO " +
        	// build nullability string
    		ret = "IDENTITY ";
import org.jkiss.dbeaver.ext.exasol.model.ExasolTable;
                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getNewName()))
import java.util.Collection;
            if (!deltaSQL.isEmpty()) {
        		props.containsKey("scale") ||
        ExasolTableColumn column = new ExasolTableColumn((ExasolTableBase) container);
    	
 *     http://www.apache.org/licenses/LICENSE-2.0
    
 * You may obtain a copy of the License at
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

package org.jkiss.dbeaver.ext.exasol.manager;

            String columnName = DBUtils.getObjectFullName(exasolColumn, DBPEvaluationContext.DDL);
    private SQLDatabasePersistAction generateCreateDist(Collection<ExasolTableColumn> distKey)
    // Business Contract

    	
import java.util.ArrayList;
            actionList.add(commentAction);
        if (commentAction != null) {
    		{
    // ------
    @Override
            return true;
    	Collection<ExasolTableColumn> distKey = table.getDistributionKey(monitor);
    	Collection<String> names = new ArrayList<>();
 */
 *
    }

            final String deltaSQL = DBUtils.getQuotedIdentifier(exasolColumn) + " " + exasolColumn.getFormatType()
        {
 * you may not use this file except in compliance with the License.
    		}
    @Override
    }

    		commands.add(generateCreateDist(distKey));
 * See the License for the specific language governing permissions and
        final ExasolTableColumn column = command.getObject();
			} catch (DBException e) {

import org.jkiss.dbeaver.model.edit.DBEObjectRenamer;
    		commands.add(generateDropDist(exasolColumn));
    public boolean canEditObject(@NotNull ExasolTableColumn object) {
			} catch (DBException e) {

import org.jkiss.dbeaver.DBException;
    	
            return false;
        if (CommonUtils.isNotEmpty(exasolColumn.getDescription())) {
import org.jkiss.dbeaver.ext.exasol.model.ExasolTableColumn;
        final String addSQL = DBUtils.getQuotedIdentifier(exasolColumn) + " " + exasolColumn.getFormatType()
    protected ExasolTableColumn createDatabaseObject(@NotNull DBRProgressMonitor monitor, @NotNull DBECommandContext context, Object container,
    private static final Log log = Log.getLog(ExasolTableColumnManager.class);
                new SQLDatabasePersistAction(
    @Override
    
    	
    private DBEPersistAction buildCommentAction(ExasolTableColumn exasolColumn) {
            + " " + formatIdentiy(exasolColumn.isAutoGenerated(), exasolColumn.getIdentityValue())
    // -----------------
        ExasolTableColumn exasolColumn = command.getObject();
    private static final String CMD_COMMENT = "Comment on Column";
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    	
    	
    					)
                actionList.add(new SQLDatabasePersistAction(CMD_ALTER, sqlAlterColumn));
    // -----

        		props.containsKey("dataType") ||
    @Nullable
        
    // Helpers
    // -------
    	String nullability = exasolColumn.isRequired() ? "NOT NULL" : "NULL";
    	
 * limitations under the License.
    public void renameObject(@NotNull DBECommandContext commandContext, @NotNull ExasolTableColumn object, @NotNull Map<String, Object> options, @NotNull String newName) throws DBException {
    @Override
/*
    @Override
    private Collection<SQLDatabasePersistAction> modifyDistKey(DBRProgressMonitor monitor, ExasolTableColumn exasolColumn) throws DBException
            String commentSQL = String.format(SQL_COMMENT, tableName, columnName, ExasolUtils.quoteString(comment));
    }
                                          @NotNull ObjectCreateCommand command,
                "Rename column",
import org.jkiss.utils.CommonUtils;
    private static final String CMD_ALTER = "Alter Column";
    	if (isAutoGenerated)
            }
        // Comment
			}
				log.error("Failed to generate distribution key",e);
    					exasolColumn.getParentObject().getFullyQualifiedName(DBPEvaluationContext.DDL)
    	String ret = "";
            + " " + (exasolColumn.getDefaultValue() == null ? "" : " DEFAULT " + exasolColumn.getDefaultValue())
    	}
        		props.containsKey("maxLength") ||
        // Edit is only available for ExasolTable and not for other kinds of tables (View, MQTs, Nicknames..)
 * distributed under the License is distributed on an "AS IS" BASIS,
import java.util.Map;
			}
            String tableName = exasolColumn.getTable().getFullyQualifiedName(DBPEvaluationContext.DDL);
 */
    // -----------------
    	
				actionList.addAll(modifyDistKey(monitor, exasolColumn));
    			table = (ExasolTable) c.getParentObject();
    
                		)
 *
import org.jkiss.dbeaver.model.struct.DBSObject;
import org.jkiss.dbeaver.ext.exasol.tools.ExasolUtils;
        );
}
    	{
        	
    		if (identityValue != null)

    {
    private static final String CREATE_DIST_KEY = "ALTER TABLE %s DISTRIBUTE BY %s";
    // Alter
    	}
import java.math.BigDecimal;
        } else {
    private static final String SQL_COMMENT = "COMMENT ON COLUMN %s.%s IS '%s'";
    		names.add(c.getName());
    	if (table.getAdditionalInfo(monitor).getHasDistKey(monitor))

import org.jkiss.dbeaver.model.impl.edit.SQLDatabasePersistAction;
    @Override
        		props.containsKey("autoGenerated") ||

    }
