    }
    @Override
 * Copyright (C) 2010-2024 DBeaver Corp and others
 */
    @Override
public class GBase8sTableColumn extends GenericTableColumn {
    }
/*
    @Override
    }
        return super.isAutoIncrement();

 *
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 70)
    @NotNull
    @Override

import org.jkiss.dbeaver.model.meta.Property;
            int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix,
    @Override

 * Licensed under the Apache License, Version 2.0 (the "License");
    }
 * limitations under the License.
import org.jkiss.code.NotNull;
    }
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 40, valueRenderer = DBDummyNumberTransformer.class)
package org.jkiss.dbeaver.ext.gbase8s.model;
/**
    }
    public String getDefaultValue() {
 * Unless required by applicable law or agreed to in writing, software

    @Property(hidden = true)
}

 * distributed under the License is distributed on an "AS IS" BASIS,
import org.jkiss.dbeaver.model.impl.DBDummyNumberTransformer;
        return super.getMaxLength();
 *
        return super.getTypeName();
    public boolean isRequired() {
 */

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public String getTypeName() {
    public long getMaxLength() {
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 50)

    @Property(hidden = true)
    @Override
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * DBeaver - Universal Database Manager
        return required;
        return autoGenerated;
            boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) {
        return super.getDefaultValue();
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 20, listProvider = ColumnTypeNameListProvider.class)
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
    public boolean isAutoGenerated() {
                precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);

import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
    public GBase8sTableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType,
    public boolean isAutoIncrement() {
 *     http://www.apache.org/licenses/LICENSE-2.0
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale,
 *
 * @author Chao Tian


    }

