 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
    }
    public SQLServerGenericTableColumn(GenericTableBase table) {

    public SQLServerGenericTableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) {
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
 * DBeaver - Universal Database Manager

 *     http://www.apache.org/licenses/LICENSE-2.0
        super(table);
public class SQLServerGenericTableColumn extends GenericTableColumn {
 * You may obtain a copy of the License at
 *

 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
 * limitations under the License.

/*
 * you may not use this file except in compliance with the License.
 */
 *
package org.jkiss.dbeaver.ext.mssql.model.generic;
 *
}
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * Licensed under the Apache License, Version 2.0 (the "License");
