            return new SQLServerGenericView(container, tableName, tableType, dbResult);
            dataSource,
    private final Map<String, Boolean> sysViewsCache = new HashMap<>();
        @Nullable GenericCatalog catalog,
    public GenericTrigger createTableTriggerImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer genericStructContainer, @NotNull GenericTableBase genericTableBase, String name, @NotNull JDBCResultSet resultSet) throws DBException {
    ) {
        }
                if (isSapIQ(dataSource)) {
        return new SQLServerGenericDataSource(monitor, container, this);
    ) throws SQLException {
            }
        return extractSource(monitor, table.getDataSource(), table, table.getCatalog(), table.getSchema().getName(), trigger.getName());
        @NotNull GenericStructContainer container,


                                JDBCUtils.safeGetString(dbResult, "proc_name"),
import org.jkiss.dbeaver.model.exec.DBCQueryTransformType;
                            continue;
        int valueType,
                        result.add(trigger);
            charLength, scale, precision, radix, notNull,
                        dataSource, catalog, name, schemaId);
        return sqlServer ? SQLServerConstants.SQL_SERVER_SYSTEM_SCHEMA : SQLServerConstants.SYBASE_SYSTEM_SCHEMA;
                try (JDBCPreparedStatement dbStat = session.prepareStatement(
        }
                dbStat.setString(1, tableSchema.getName());
                            "ON s.creator = su.uid\n" +
        boolean autoGenerated
        return true;
            }
        ServerType serverType = getServerType();
    private static final Log log = Log.getLog(SQLServerMetaModel.class);
        return isSqlServer();

            name = JDBCUtils.safeGetString(resultSet, 1);
        }
    }
import java.util.Map;
        }
        return extractSource(monitor, sourceObject.getDataSource(), sourceObject, sourceObject.getCatalog(), sourceObject.getSchema().getName(), sourceObject.getName());
            return new SQLServerGenericTable(container, tableName, tableType, dbResult);
/*

        @NotNull DBRProgressMonitor monitor,
                    "FROM " + sysSchema + ".sysusers u, " + sysSchema + ".sysobjects o\n" +
 *
            remarks, defaultValue, autoIncrement, autoGenerated
                    "WHERE u.uid=o.uid\n" +
                sysViewsCache.put(viewName, check);
    @Override
        if (table != null) {
    public JDBCStatement prepareTableTriggersLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws SQLException {
        @NotNull JDBCSession session,
                        "ORDER BY sc.colid";

    @Override
                        name = name.trim();
    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {
                    if (object instanceof SQLServerView) {
                    while (dbResult.nextRow()) {
                            }
    @NotNull
        return true;
            columnSize,
import org.jkiss.dbeaver.model.struct.DBSObject;
    }
    private String extractSource(

                    }
    public SQLServerMetaModel(boolean sqlServer) {
 * Unless required by applicable law or agreed to in writing, software



 * Licensed under the Apache License, Version 2.0 (the "License");
import org.jkiss.utils.CommonUtils;
                dbStat.setLong(1, schemaId);
        return dbStat;
        List<GenericSchema> result = new ArrayList<>();
        long charLength,

            CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "current_value")),
            }
    }
                if (dataSource instanceof SQLServerGenericDataSource sqlDataSource &&
        @NotNull GenericStructContainer container
                }
                    getSystemSchema()) +
            return new QueryTransformerTop();
        assert table != null;
                }
    @Override
        return new SQLServerGenericProcedure(container, procedureName, specificName, remarks, procedureType, functionResultType);
        return new SQLServerGenericSchema(dataSource, catalog, schemaName, 0);
                            "LEFT JOIN " +
                }
        return new SQLServerGenericTableColumn(table,
                        "JOIN sys.sysuser AS u ON u.user_id = so.uid\n" +

            }
        Boolean check;
    }
    }
        this(true);
 *     http://www.apache.org/licenses/LICENSE-2.0
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
            "SELECT * FROM " + SQLServerUtils.getSystemSchemaFQN(container.getDataSource(), container.getCatalog().getName(), getSystemSchema()) + ".synonyms WHERE schema_name(schema_id)=?");
        @NotNull GenericStructContainer container,
        String columnName,
                    dbStat.setString(1, container.getName());
    public SQLServerGenericIndex createIndexImpl(@NotNull GenericTableBase table, boolean nonUnique, String qualifier, long cardinality, String indexName, DBSIndexType indexType, boolean persisted) {
import org.jkiss.dbeaver.ext.mssql.model.SQLServerView;
    @Override
        }
    private String getSystemSchema() {
    public SQLServerGenericSchema createSchemaImpl(@NotNull GenericDataSource dataSource, GenericCatalog catalog, @NotNull String schemaName) throws DBException {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, dataSource, "Read source code")) {
                            "WHERE s.proc_name=? AND su.name=?")) {
        if (getServerType() == ServerType.SYBASE) {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
                    }
    public boolean isSqlServer() {
    }
                    try (JDBCPreparedStatement dbStat = session.prepareStatement(

        String name = JDBCUtils.safeGetString(dbResult, "name");
            return null;
                    objectName);
                            DBSProcedureType procedureType = DBSProcedureType.PROCEDURE;
import org.jkiss.dbeaver.model.DBPErrorAssistant;
                // P – Transact-SQL or SQLJ procedure
                result.add(new GenericSchema(dataSource, catalog, SQLServerConstants.DEFAULT_SCHEMA_NAME));
    @Override
    public boolean isSchemasOptional() {
    @Override
                    if (isSqlServer()) {
                    "ORDER BY 1";
    }
 * Copyright (C) 2010-2026 DBeaver Corp and others
            } else {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            typeName, valueType, sourceType, ordinalPos,
package org.jkiss.dbeaver.ext.mssql.model.generic;
        String schema = SQLServerUtils.getSystemSchemaFQN(container.getDataSource(), container.getCatalog().getName(), getSystemSchema());

    public JDBCStatement prepareSynonymsLoadStatement(

                    }
                            "ON so.id = s.object_id\n" +
                        while (dbResult.nextRow()) {
            "SELECT * FROM " +

                    StringBuilder sql = new StringBuilder();
        this.sqlServer = sqlServer;
                    sourceObject.getCatalog(),
                        sql.append(dbResult.getString(1));
        return false;
            try (JDBCPreparedStatement dbStat = (JDBCPreparedStatement) prepareTableTriggersLoadStatement(session, container, table)) {
            if (!schemaReadFailed && !showAllSchemas) {
import org.jkiss.dbeaver.ext.mssql.SQLServerConstants;

    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {
                SQLServerUtils.getSystemSchemaFQN(
        boolean schemaReadFailed = false;
                    String ddl = sql.toString();
                        continue;
                }
 * DBeaver - Universal Database Manager

import org.jkiss.dbeaver.ext.mssql.model.SQLServerObject;
                    }
        }
    ) {
        String sysSchema = SQLServerUtils.getSystemSchemaFQN(
        return new SQLServerGenericDatabase(dataSource, catalogName);
                    "ORDER BY 1";
            dbStat.setString(2, table.getName());
        if (tableType != null && isView(tableType)) {
    }
        String productName = dataSource.getInfo().getDatabaseProductName();

                    if (name == null) {
 * limitations under the License.
    @Override
        name = name.trim();
        synchronized (sysViewsCache) {
            }
        Integer precision,
        return result;
        return "IDENTITY(1,1)";
    public String getAutoIncrementClause(GenericTableColumn column) {
            }
            try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read routine definition")) {
        } else {

import java.util.HashMap;
    ) throws DBException {
            } catch (SQLException e) {
        }
    }
            name,
    @Override
    @Override
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            JDBCUtils.safeGetString(dbResult, "base_object_name"));
                {
    }
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.DBException;
                }
        }
        @NotNull DBRProgressMonitor monitor,
                    String name = JDBCUtils.safeGetString(dbResult, "name");
    @NotNull
                        SQLServerGenericTrigger trigger = new SQLServerGenericTrigger(table, name, null);
                                    return source;
                List<GenericTrigger> result = new ArrayList<>();
                        "and su.name=?"))
                    SQLServerGenericSchema schema = new SQLServerGenericSchema(
            if (dataSource.discoverErrorType(e) == DBPErrorAssistant.ErrorType.CONNECTION_LOST) {
    private boolean hasSybaseSystemView(JDBCSession session, String systemSchema, String viewName) throws SQLException {
import org.jkiss.dbeaver.Log;
    @Override
        }
        if (CommonUtils.isEmpty(name)) {
        if (name == null) {
    public GenericTableColumn createTableColumnImpl(
        GenericSchema tableSchema = table == null ? null : table.getSchema();
                query.append("AND user_name(tables.uid) = ?");
            name,
                                procedureType,
    }
                                container,

        } else {

                            DBUtils.getQuotedIdentifier(sourceObject.getCatalog()) + ".dbo.sysobjects so " +
        @Nullable JDBCResultSet dbResult,
    public GenericTableBase createTableOrViewImpl(
                                if (!CommonUtils.isEmpty(source)) {
        JDBCPreparedStatement dbStat = session.prepareStatement(
    @Override
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
            container,
                    "select distinct so.name as proc_name,su.name as schema_name, so.[type] as type_name\n" +
        );
    @Override
                    dbStat.setString(2, name);
            } else {
    }
                            "LEFT JOIN " +
    }
import org.jkiss.dbeaver.ext.mssql.model.ServerType;
 * You may obtain a copy of the License at
import java.util.ArrayList;
        if (type == DBCQueryTransformType.RESULT_SET_LIMIT) {
        return productName != null && (productName.contains("IQ SAP") || productName.contains("SAP IQ") || productName.contains("Sybase IQ"));
                            final GenericProcedure procedure = createProcedureImpl(
            getSystemSchema());
                return extractSource(monitor,
                    container.getDataSource(),
        Integer scale,
            }
    public GenericSequence createSequenceImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
                        }
        String defaultValue,
        } catch (SQLException e) {
    public boolean isColumnNotNullByDefault() {

                    result.add(schema);
        @Nullable GenericCatalog catalog
                            return "-- Routine '" + objectName + "' definition not found";

    }
    }
            if (schemaId == 0) {
        GenericDataSource dataSource = sourceObject.getDataSource();
{
                    container.getCatalog() == null ? null : container.getCatalog().getName(),
    ) throws DBException {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
                // Maybe something went wrong. LEt's try to use native function
            } catch (SQLException e) {
        if (CommonUtils.isEmpty(name)) {
            && dataSource.isServerVersionAtLeast(SQLServerConstants.SQL_SERVER_2005_VERSION_MAJOR, 0)

            && sourceObject instanceof SQLServerObject sqlServerObject) {
        @NotNull JDBCSession session,
    private boolean hasMetaDataProcedureView;



    }
 */
    }
    @Override
            }
        boolean notNull,
                            DBUtils.getQuotedIdentifier(sourceObject.getCatalog()) + ".dbo.sysusers su " +
        @NotNull String procedureName,
                sql = "SELECT DISTINCT s.*\n" +

        String typeName,
        }
    }
        @NotNull GenericDataSource dataSource,
            container,
    public List<GenericTrigger> loadTriggers(@NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws DBException {
        return new SQLServerGenericIndex(table, nonUnique, qualifier, cardinality, indexName, indexType, persisted);
    @NotNull
                    sqlDataSource.hasMetaDataProcedureView()) {
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
                mdQuery = SQLServerUtils.selectObjectDefinitionDescriptionSQL(monitor, sqlServerObject, true);
        }
    }
    ) {
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
import org.jkiss.dbeaver.DBDatabaseException;
        return null;
            CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "minimum_value")),
    @NotNull
    }
import java.sql.SQLException;
            CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "maximum_value")),
    public boolean isSystemTable(@NotNull GenericTableBase table) {
    @Override
        JDBCPreparedStatement dbStat = session.prepareStatement(
                        "SELECT source, proc_defn " +
    }
                    "FROM " + sysSchema + ".schemas s, " + sysSchema + ".sysobjects o\n" +
        String remarks,
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
                }
            throw new DBDatabaseException(e, dataSource);
        GenericFunctionResultType functionResultType
    @NotNull
            String mdQuery;
        return extractSource(monitor, dataSource, sourceObject, sourceObject.getCatalog(), sourceObject.getSchema().getName(), objectName);
        @NotNull JDBCResultSet dbResult
        return dbStat;
    @Override
                while (dbResult.next()) {

        return new GenericSequence(
                        "FROM " + systemSchema + ".sysobjects AS so\n" +
 * you may not use this file except in compliance with the License.
        int radix,
                        schemaId = JDBCUtils.safeGetLong(dbResult, "schema_id");
        }
        name = name.trim();
        dbStat.setString(1, container.getSchema().getName());
            null,
        if (table != null) {
        long columnSize,
                        if (name == null) {
        @NotNull String schema,
    }
                        continue;
        if (!isSqlServer()) {
                                String source = dbResult.getString(1);
        return table.getSchema() != null && getSystemSchema().equals(table.getSchema().getName()) && table.getName().startsWith("sys");
                            procedure.setSource(JDBCUtils.safeGetString(dbResult, "definition"));
    @Nullable
        @Nullable String tableName,
                    return ddl;

        }
    @Override
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
                        "FROM " + systemSchema + ".sysobjects so, " + systemSchema + ".syscomments sc\n" +
                        "where so.type IN ('P', 'SF')\n" +

            if (getServerType() == ServerType.SQL_SERVER) {
        return new SQLServerGenericSynonym(
import org.jkiss.dbeaver.model.exec.DBCQueryTransformProvider;
    }
    public List<GenericSchema> loadSchemas(
        name = name.trim();
            GenericDataSource dataSource = container.getDataSource();
        String name = JDBCUtils.safeGetString(dbResult, "name");
                        }
    }
            try (JDBCResultSet dbResult = dbStat.executeQuery()) {
    }
        GenericTableBase table = ((GenericTableTrigger) trigger).getTable();
        try (JDBCPreparedStatement dbStat = session.prepareStatement(sql)) {
            synchronized (sysViewsCache) {
import org.jkiss.dbeaver.model.struct.DBSObjectFilter;
 * See the License for the specific language governing permissions and

    public JDBCStatement prepareSequencesLoadStatement(
            } else {
        return  new SQLServerGenericTrigger(genericTableBase, name, null);
            String dbName = DBUtils.getQuotedIdentifier(container.getParentObject());
        @NotNull DBSObject object,
    @Override
                throw new DBDatabaseException(e, dataSource);
    }
        } else {
        query.append(",").append(schema).append(".sysobjects tables").append("\nWHERE triggers.type = 'TR' AND triggers.deltrig = tables.id\n");
    @Override
                    "WHERE s.schema_id=o.uid\n" +
        String remarks,
                    sourceObject.getSchema().getName(),
    }
    }
    }

        return check;
    private boolean isSapIQ(GenericDataSource dataSource) {
            query.append(" AND tables.name = ?");
                    name = name.trim();
    public SQLServerGenericDatabase createCatalogImpl(@NotNull GenericDataSource dataSource, @NotNull String catalogName) {
        StringBuilder query = new StringBuilder("SELECT triggers.name as TRIGGER_NAME, triggers.*, tables.name as OWNER FROM " + schema + ".sysobjects triggers");
    public boolean useCatalogInObjectNames() {
                    sourceObject,
    @Nullable
            super.loadProcedures(monitor, container);
        }
    public SQLServerMetaModel() {
        return getServerType() == ServerType.SQL_SERVER;

        );
import org.jkiss.dbeaver.model.struct.rdb.DBSIndexType;
                        schemaId = JDBCUtils.safeGetLong(dbResult, "uid");
                            if ("SF".equals(typeName)) {
    }
public class SQLServerMetaModel extends GenericMetaModel implements DBCQueryTransformProvider
                sql = "SELECT * FROM " + sysSchema + ".sysusers";
                                procedureType = DBSProcedureType.FUNCTION;
            null,
        } catch (SQLException e) {

                        // Doesn't match filter
            }
    @Override
                }
        }
                // Perhaps all schemas were filtered out
}
                        "and su.uid = so.uid\n" +
        }
        JDBCPreparedStatement dbStat = session.prepareStatement(query.toString());
                throw new DBDatabaseException(e, dataSource);
 */
                        dbStat.setString(2, sourceObject.getSchema().getName());
        @NotNull GenericStructContainer container
        if (showAllSchemas) {
                    dbStat.setString(1, schema);
        final DBSObjectFilter schemaFilters = dataSource.getContainer().getObjectFilter(GenericSchema.class, catalog, false);
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger trigger) throws DBException {
        @NotNull JDBCSession session,
/**
            }
            if (schemaId == 0) {
    @Override
    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
                        try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                        String name = JDBCUtils.safeGetString(dbResult, 1);
        super();
            check = JDBCUtils.queryString(session, "SELECT name from " + systemSchema + ".sysobjects where name=?", viewName) != null;
 * SQLServerMetaModel
                        dbStat.setString(1, objectName);
        @NotNull String name
            try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Sybase procedure list")) {
                return result;
                    }
import org.jkiss.code.NotNull;
                    dataSource,
            return null;
import org.jkiss.code.Nullable;
                            "FROM SYS.SYSPROCEDURE s\n" +
            }
            } else {
    public boolean supportsSynonyms(@NotNull GenericDataSource dataSource) {
            CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "increment"))
    @NotNull
                } else {

    public SQLServerGenericProcedure createProcedureImpl(
    }
        int sourceType,
                query.append("AND tables.uid = ?");

            if (getServerType() == ServerType.SQL_SERVER && dataSource.isServerVersionAtLeast(SQLServerConstants.SQL_SERVER_2005_VERSION_MAJOR ,0)) {
                    while (dbResult.next()) {
                    if (schemaFilters != null && !schemaFilters.matches(name)) {
                schemaReadFailed = true;
                        "JOIN sys.syssource AS s ON s.object_id = so.id\n" +
        boolean showAllSchemas = SQLServerUtils.isShowAllSchemas(dataSource);
                                null,
import org.jkiss.dbeaver.model.exec.DBCQueryTransformer;
        if (check == null) {
        JDBCResultSet dbResult
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
                                null);
        String specificName,
        @Nullable String tableType,
            } else {
        DBSProcedureType procedureType,

        int ordinalPos,
        long schemaId = tableSchema instanceof SQLServerGenericSchema ? ((SQLServerGenericSchema) tableSchema).getSchemaId() : 0;
                                return dbResult.getString(2);
            } else {
            if (serverType == ServerType.SQL_SERVER && object instanceof SQLServerObject sqlServerObject) {

                        }
            return SQLServerUtils.extractSource(monitor, sqlServerObject);
                    long schemaId;
        }
    public SQLServerGenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
        return sqlServer;
            throw new DBDatabaseException(e, container.getDataSource());
        if (result.isEmpty()) {
    }
import org.jkiss.dbeaver.model.impl.sql.QueryTransformerTop;
            columnName,
import org.jkiss.dbeaver.model.DBUtils;
    ) throws DBException {
        String objectName = sourceObject.getName();
            }
            }
    }
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                log.warn("Schema read failed: empty list returned. Try generic method.", e);
            } else {
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
        }
        return sqlServer ? ServerType.SQL_SERVER : ServerType.SYBASE;
                    mdQuery = "SELECT sc.text\n" +
                sql = "SELECT DISTINCT u.name,u.uid\n" +
            catalog == null ? null : catalog.getName(),
        boolean autoIncrement,
                    }

        String sql;
                    mdQuery = "SELECT s.source\n" +
        dbStat.setString(1, container.getSchema().getName());
        if (CommonUtils.isEmpty(name)) {
        @NotNull GenericStructContainer container,
    public GenericSynonym createSynonymImpl(
                    } else {
                                }
                        "WHERE user_name(so.uid)=? AND so.name=? and sc.id = so.id\n" +
        @NotNull
    public DBCQueryTransformer createQueryTransformer(@NotNull DBCQueryTransformType type) {

                                null,
        } catch (SQLException e) {
    @Override
                if (serverType == ServerType.SYBASE) {
                // SF – scalar or user-defined functions - from SAP Adaptive Server version 16
                            if (dbResult.nextRow()) {
import java.util.List;
    @Override
                        "from " + dbName + ".dbo.sysobjects so, "+ dbName + ".dbo.sysusers su\n" +
                    }
    }
            check = sysViewsCache.get(viewName);
 *
            try (JDBCPreparedStatement dbStat = session.prepareStatement(mdQuery)) {

    @Override
                sql = "SELECT * FROM " + sysSchema + ".schemas";
    @Override
    @Override
 *

    @Override
        @NotNull GenericTableBase table,
    ) throws SQLException {
    private final boolean sqlServer;

        @NotNull GenericDataSource dataSource,
                        "WHERE user_name(so.uid)=? AND so.name=?";
                throw new DBDatabaseException(e, dataSource);
        return dbStat;
    @NotNull

    }
        String systemSchema = SQLServerUtils.getSystemSchemaFQN(dataSource, catalog != null ? catalog.getName() : null, getSystemSchema());
                        ddl = ddl.replaceAll("(?i)CREATE VIEW", "CREATE OR REPLACE VIEW");
    public ServerType getServerType() {
                ".sequences WHERE schema_name(schema_id)=?");
                            String typeName = JDBCUtils.safeGetString(dbResult, "type_name");
        return true;
                            }
        @NotNull JDBCSession session,
import org.jkiss.dbeaver.ext.generic.model.*;
                            container.addProcedure(procedure);
import org.jkiss.dbeaver.ext.mssql.SQLServerUtils;
    }

                    try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            return null;
        if (isSqlServer()
                    }
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType;
                return super.loadSchemas(session, dataSource, catalog);
    public void loadProcedures(@NotNull DBRProgressMonitor monitor, @NotNull GenericObjectContainer container) throws DBException {
