#include <jni.h>
  (JNIEnv *, jobject);
/*
#endif
#endif
 * Class:     org_jkiss_wmi_service_WMIObject
 */
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIObject_readMethods
 * Class:     org_jkiss_wmi_service_WMIObject
 * Method:    readAttributes
 * Signature: (JLjava/util/List;)V

JNIEXPORT jobject JNICALL Java_org_jkiss_wmi_service_WMIObject_readAttributeValue
 * Signature: (JLjava/util/List;)V
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIObject_releaseObject
 */
  (JNIEnv *, jobject, jlong, jobject);
  (JNIEnv *, jobject, jlong, jobject);
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
 * Class:     org_jkiss_wmi_service_WMIObject
 * Method:    readMethods
/* Header for class org_jkiss_wmi_service_WMIObject */
 * Class:     org_jkiss_wmi_service_WMIObject
 * Method:    readAttributeValue
 */

JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIObject_readAttributes
 * Class:     org_jkiss_wmi_service_WMIObject
  (JNIEnv *, jobject, jstring, jobject);
#ifdef __cplusplus
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
/*

 */
JNIEXPORT jstring JNICALL Java_org_jkiss_wmi_service_WMIObject_readObjectText
 * Method:    readQualifiers
/*
#ifdef __cplusplus
  (JNIEnv *, jobject, jstring);
}
 */
 * Method:    releaseObject

 * Signature: (ZLjava/lang/String;Ljava/util/List;)V
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIObject_readQualifiers
/*
#ifndef _Included_org_jkiss_wmi_service_WMIObject
 * Class:     org_jkiss_wmi_service_WMIObject
/*
 * Signature: ()Ljava/lang/String;
 * Method:    writeAttributeValue
 * Signature: ()V
 */
/*
#define _Included_org_jkiss_wmi_service_WMIObject
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIObject_writeAttributeValue
  (JNIEnv *, jobject, jboolean, jstring, jobject);


/*
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
extern "C" {
  (JNIEnv *, jobject);

 * Class:     org_jkiss_wmi_service_WMIObject
 */

 * Method:    readObjectText
