/*
 */

JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIService_close
 * Class:     org_jkiss_wmi_service_WMIService

#define _Included_org_jkiss_wmi_service_WMIService
 * Signature: (Ljava/lang/String;Lorg/jkiss/wmi/service/WMIObjectSink;J)V
#include <jni.h>
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring);
 * Method:    cancelSink
 * Class:     org_jkiss_wmi_service_WMIService
  (JNIEnv *, jobject, jstring);
 * Class:     org_jkiss_wmi_service_WMIService
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIService_enumInstances
  (JNIEnv *, jobject, jstring, jobject, jlong);
 * Signature: (Ljava/lang/String;)Lorg/jkiss/wmi/service/WMIService;
 */
 * Method:    enumInstances
 * Signature: ()V

#endif
#endif
/*
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIService_executeQuery
  (JNIEnv *, jobject, jstring, jobject, jlong);

#endif
 * Signature: (Lorg/jkiss/wmi/service/WMIObjectSink;)V
/*
/* DO NOT EDIT THIS FILE - it is machine generated */

 * Class:     org_jkiss_wmi_service_WMIService
  (JNIEnv *, jobject, jobject);
 * Signature: (Ljava/lang/String;Lorg/jkiss/wmi/service/WMIObjectSink;J)V
/*
 */
/*
 */
#ifdef __cplusplus
JNIEXPORT jobject JNICALL Java_org_jkiss_wmi_service_WMIService_openNamespace
 * Method:    executeQuery
 */
/* Header for class org_jkiss_wmi_service_WMIService */
/*

}
 */
 * Method:    close

 * Method:    enumClasses
 * Method:    openNamespace
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIService_enumClasses
 * Method:    connect

#ifdef __cplusplus
 * Class:     org_jkiss_wmi_service_WMIService
  (JNIEnv *, jobject, jstring, jobject, jlong);
 * Class:     org_jkiss_wmi_service_WMIService
extern "C" {
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/jkiss/wmi/service/WMIService;
  (JNIEnv *, jobject);
 * Class:     org_jkiss_wmi_service_WMIService
JNIEXPORT void JNICALL Java_org_jkiss_wmi_service_WMIService_cancelSink
JNIEXPORT jobject JNICALL Java_org_jkiss_wmi_service_WMIService_connect
 * Signature: (Ljava/lang/String;Lorg/jkiss/wmi/service/WMIObjectSink;J)V
/*
#ifndef _Included_org_jkiss_wmi_service_WMIService
 */
