}
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.data.DBDAttributeBinding;
 * limitations under the License.
    }
 *
/*
        DBDAttributeBinding attribute,
        super(
    {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * Licensed under the Apache License, Version 2.0 (the "License");

    @Override
 * you may not use this file except in compliance with the License.
        return dataKind;
 * TransformerPresentationAttribute
package org.jkiss.dbeaver.model.impl.data.transformers;
        int typeId,
    public TransformerPresentationAttribute(
 * You may obtain a copy of the License at
public class TransformerPresentationAttribute extends AbstractAttribute {
            attribute.getPrecision(),
 *

            attribute.getOrdinalPosition(),
 *

 * Unless required by applicable law or agreed to in writing, software
            attribute.getName(),
 * See the License for the specific language governing permissions and
 * DBeaver - Universal Database Manager
            attribute.getMaxLength(),
    public DBPDataKind getDataKind() {
 * Copyright (C) 2010-2024 DBeaver Corp and others
 */
            attribute.isAutoGenerated());
import org.jkiss.code.NotNull;
        DBPDataKind dataKind)
        String typeName,
 */
            attribute.getScale(),
    @NotNull

            attribute.isRequired(),
            typeName,
            typeId,
 *     http://www.apache.org/licenses/LICENSE-2.0
    }
/**
import org.jkiss.dbeaver.model.impl.struct.AbstractAttribute;
        this.dataKind = dataKind;

    private final DBPDataKind dataKind;
 * distributed under the License is distributed on an "AS IS" BASIS,
