    
 */
    String OPTION_SKIP_UNIQUE_KEYS = "ddl.skipUniqueKeys"; //$NON-NLS-1$
    String OPTION_SCRIPT_INCLUDE_VIEWS = "script.include.views";
    // Use fully qualified names. True by default
    String OPTION_EMBEDDED_SOURCE = "embedded.source";
    // Means that result script will be used for object save

public interface DBPScriptObject extends DBPObject {
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    String OPTION_SKIP_INDEXES = "ddl.skipIndexes"; //$NON-NLS-1$
    // Can be used by DDL generators to generate object ALTER but CREATE.
    String OPTION_SCRIPT_USE_CUSTOM_DATA_FORMAT = "script.use.custom.data.format";
 *     http://www.apache.org/licenses/LICENSE-2.0
    String OPTION_SCRIPT_FORMAT_COMPACT = "script.format.compact";

 * You may obtain a copy of the License at

    String OPTION_OBJECT_ALTER = "object.alter";

    String OPTION_OBJECT_SAVE = "object.save";

    String OPTION_REFRESH = "refresh";
    // Extracts object source for debugger

    // If object definition was cached - refresh it
 * Licensed under the Apache License, Version 2.0 (the "License");


    String OPTION_DDL_SKIP_FOREIGN_KEYS = "ddl.skipForeignKeys"; //$NON-NLS-1$

 *
package org.jkiss.dbeaver.model;

 * Unless required by applicable law or agreed to in writing, software

 *
 * Object with DDL
    String OPTION_DEBUGGER_SOURCE = "debugger.source";
 */

/**
 * Copyright (C) 2010-2025 DBeaver Corp and others
import java.util.Map;
    String OPTION_SCRIPT_FORMAT = "script.format";

    Map<String, Object> EMPTY_OPTIONS = Map.of();
    // nested objects (columns, constraints, etc) which can be embedded in parent object declaration (tables)
    @NotNull
    String getObjectDefinitionText(@NotNull DBRProgressMonitor monitor, @NotNull Map<String, Object> options)
    String OPTION_INCLUDE_NESTED_OBJECTS = "ddl.includeNestedObjects"; //$NON-NLS-1$
        throws DBException;
import org.jkiss.code.NotNull;
 * limitations under the License.
    String OPTION_SCRIPT_EXCLUDE_AUTO_GENERATED_COLUMN = "script.exclude.autogenerated.column";
 * distributed under the License is distributed on an "AS IS" BASIS,

    String OPTION_INCLUDE_COMMENTS = "ddl.includeComments"; //$NON-NLS-1$
import org.jkiss.dbeaver.DBException;
 * you may not use this file except in compliance with the License.
 * See the License for the specific language governing permissions and
    String OPTION_CAST_PARAMS = "sql.castParameter"; //$NON-NLS-1$
 * DBeaver - Universal Database Manager
    // Embedded source is used for obtaining source of
    String OPTION_DDL_ONLY_FOREIGN_KEYS = "ddl.onlyForeignKeys"; //$NON-NLS-1$
    String OPTION_COMPOSITE_OBJECT = "composite.object"; //$NON-NLS-1$
    String OPTION_INCLUDE_PARTITIONS = "ddl.includePartitions"; //$NON-NLS-1$
    String OPTION_DDL_SOURCE = "ddl.source";
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    String OPTION_DDL_SEPARATE_FOREIGN_KEYS_STATEMENTS = "ddl.separateForeignKeys"; //$NON-NLS-1$
    String OPTION_FULLY_QUALIFIED_NAMES = "useFQN";

    String OPTION_INCLUDE_PERMISSIONS = "ddl.includePermissions"; //$NON-NLS-1$
    String OPTION_SKIP_DROPS = "ddl.skipDrops"; //$NON-NLS-1$
}
/*

    // By default the same as regular source but in some cases source should be transformed (e.g. for PG)
    String OPTION_USE_SPECIAL_NAME = "ddl.useSpecialName"; //$NON-NLS-1$
    String OPTION_INCLUDE_OBJECT_DROP = "script.includeDrop";
 *
