    @SerializedName("finish_reason")
/*
    }
     */
    private ChatMessage delta;
        this.index = index;
public class ChatCompletionChoice {
    @SerializedName("delta")
        return delta != null ? delta : message;
    }
package org.jkiss.dbeaver.model.ai.engine.openai.dto.legacy;
 *
    /**
 * See the License for the specific language governing permissions and


    }
     * This index of this completion in the returned list.
        return index;
    public void setFinishReason(String finishReason) {
    public void setMessage(ChatMessage message) {

     * The reason why GPT stopped generating, for example "length".
 * distributed under the License is distributed on an "AS IS" BASIS,
 */
        this.finishReason = finishReason;
import com.google.gson.annotations.SerializedName;

    private Integer index;
    private ChatMessage message;
    public Integer getIndex() {


 */
     */
    public String getFinishReason() {
    public ChatMessage getMessage() {
 * Licensed under the Apache License, Version 2.0 (the "License");
    /**
 * DBeaver - Universal Database Manager
    }
 * limitations under the License.
 * you may not use this file except in compliance with the License.

 * Copyright (C) 2010-2025 DBeaver Corp and others
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    }
 * You may obtain a copy of the License at

/**
 * A chat completion generated by OpenAI

 * Unless required by applicable law or agreed to in writing, software
    private String finishReason;
}
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
    }
        return finishReason;

 *
    public void setIndex(Integer index) {

        this.message = message;
