    public ChatCompletionRequestFunctionCall getFunctionCall() {
    }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        return stream;
        this.topP = topP;
    }
}
        }

    /**

    private List<ChatMessage> messages;
    public Double getPresencePenalty() {
        return user;
        return messages;
 * Unless required by applicable law or agreed to in writing, software
    }
    }
    }
     * href="https://platform.openai.com/docs/guides/chat/introduction">chat format</a>.<br>
     * ID of the model to use.
        return model;

    }
    }
     * The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return will
     * see {@link ChatMessage}
    private String user;
    public void setStream(Boolean stream) {
    }
     */
    public String getModel() {
    }
     * values like 0.2 will make it more focused and deterministic.<br>



     * href="https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format">server-sent

    public Boolean getStream() {
    public void setMessages(List<ChatMessage> messages) {
    private List<String> stop;
        this.user = user;
     * increasing the model's likelihood to talk about new topics.
    }
     */
    /**
    @SerializedName("function_call")

    public void setFunctions(List<?> functions) {
import java.util.Map;
        return functionCall;
 * distributed under the License is distributed on an "AS IS" BASIS,
import java.util.List;
 * See the License for the specific language governing permissions and
    }
    /**
        return temperature;
    }
        this.model = model;
    }

    public void setStop(List<String> stop) {
        this.functionCall = functionCall;
     * We generally recommend altering this or top_p but not both.

     */
     * decreasing the model's likelihood to repeat the same line verbatim.
        return stop;
    /**
    public void setTopP(Double topP) {
    public void setModel(String model) {
 *     http://www.apache.org/licenses/LICENSE-2.0
    public void setLogitBias(Map<String, Integer> logitBias) {
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

     * How many chat completion chatCompletionChoices to generate for each input message.
 *
        return frequencyPenalty;


    public Double getTopP() {


    }
        this.n = n;
 *
    }
    }
 *
    public String getUser() {
    /**
        return n;
     * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower
    private List<?> functions;
     */
        return maxTokens;
    /**
    }
    @SerializedName("frequency_penalty")
    private Map<String, Integer> logitBias;
    /**

        public static ChatCompletionRequestFunctionCall of(String name) {

    /**
     * to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will
     */


     * A list of the available functions.

    /**
     * The messages to generate chat completions for, in the <a

    public List<ChatMessage> getMessages() {
 * You may obtain a copy of the License at
        this.stop = stop;


    public void setMaxTokens(Integer maxTokens) {
 * Copyright (C) 2010-2025 DBeaver Corp and others
 * DBeaver - Universal Database Manager
    private Integer maxTokens;
    public Integer getMaxTokens() {

        this.frequencyPenalty = frequencyPenalty;
        return presencePenalty;
    public List<String> getStop() {
    public Integer getN() {

    }
        return logitBias;
 * limitations under the License.
    }
    }

    }
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far,
    /**
    @SerializedName("max_completion_tokens")
    public Double getFrequencyPenalty() {
    public Double getTemperature() {
     */
    public void setFunctionCall(ChatCompletionRequestFunctionCall functionCall) {
    /**
    }
        this.messages = messages;
     */

        return topP;
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far,


    private Double topP;
     */
     * with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.<br>
    @SerializedName("top_p")

    /**
    /**
     * If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only <a
     * We generally recommend altering this or temperature but not both.
    public List<?> getFunctions() {
 * you may not use this file except in compliance with the License.

     * events</a> as they become available, with the stream terminated by a data: [DONE] message.
    public void setPresencePenalty(Double presencePenalty) {
        this.functions = functions;
     */
    private Double frequencyPenalty;
    }
    public void setTemperature(Double temperature) {
    }
    @SerializedName("logit_bias")

import com.google.gson.annotations.SerializedName;
    private Integer n;
        this.temperature = temperature;
    @SerializedName("presence_penalty")

    public Map<String, Integer> getLogitBias() {
     * be (4096 - prompt tokens).

     */
        return functions;
    public void setN(Integer n) {
    private ChatCompletionRequestFunctionCall functionCall;
    }
    }
package org.jkiss.dbeaver.model.ai.engine.openai.dto.legacy;
    public void setUser(String user) {
    /**
     * Controls how the model responds to function calls, as specified in the <a href="https://platform.openai.com/docs/api-reference/chat/create#chat/create-function_call">OpenAI documentation</a>.


     * Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100
            return new ChatCompletionRequestFunctionCall(name);
        this.maxTokens = maxTokens;
        this.stream = stream;
     */
     */





     * A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse.

    }
    }
     * vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100
     */
    public static record ChatCompletionRequestFunctionCall(String name) {

     * should result in a ban or exclusive selection of the relevant token.


    private Double temperature;
public class ChatCompletionRequest {
     * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens
     */
    private Boolean stream;

     * Up to 4 sequences where the API will stop generating further tokens.
    private String model;

    private Double presencePenalty;
    public void setFrequencyPenalty(Double frequencyPenalty) {
/*

        this.logitBias = logitBias;
        this.presencePenalty = presencePenalty;
    }
