    @Override
        this.colcard = JDBCUtils.safeGetLong(dbResult, "COLCARD");
        return nbMostFreq;
        return collationSchema;
    @Property(viewable = false, order = 120)

    {
        return getTable().getDataSource();
        return hiddenState;
    {
    {
        return nbNulls;
        super(tableBase, false);

    public void setDataType(@NotNull DB2DataType dataType) {
    @Nullable
    {

    {
    public Integer getNbMostFreq()
            log.debug("Data type '" + typeName + "' wasn't resolved");
    private Long colcard;

    public DB2TableColumn(DBRProgressMonitor monitor, DB2TableBase tableBase, ResultSet dbResult) throws DBException

            this.pctInlined = JDBCUtils.safeGetInteger(dbResult, "PCTINLINED");
    public String getLow2key()
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
        this.avgLength = JDBCUtils.safeGetInteger(dbResult, "AVGCOLLEN");
    }
import org.jkiss.dbeaver.model.DBPHiddenObject;

        this.codePage = JDBCUtils.safeGetInt(dbResult, "CODEPAGE");
        // Search for DataType
    private String remarks;
        return identity;
        if (this.dataType == null) {
    {
        this.identity = JDBCUtils.safeGetBoolean(dbResult, "IDENTITY", DB2YesNo.Y.name());
            } else {
            setValueType(dataType.getTypeID());
    }

    private String collationSchema;
    }
    {
    // -----------------
    public String getTypeName()
    }
    }
        return rowEnd;
        this.dataType = dataType;

import org.jkiss.dbeaver.model.DBConstants;
    @Property(viewable = true, order = 45)
/*

    public Boolean getIdentity()
import org.jkiss.dbeaver.DBException;
    }
    private Integer nbQuantiles;

    // {
    public String getCollationSchema()
        if (this.dataType == null) {
    @Override
    @Property(viewable = false, order = 134)
    {
        // GENERATED ALWAYS columns must not be included in such scenario
    @Override
    }
        } else {
    private DB2ColumnHiddenState hidden;
        }
    }
    @Property(viewable = true, editable = true, updatable = true, order = 38)
    }
        setName(JDBCUtils.safeGetString(dbResult, "COLNAME"));
    public DB2TableBase getOwner()
    @Property(viewable = false, order = 181, category = DB2Constants.CAT_COLLATION)
        setScale(JDBCUtils.safeGetInteger(dbResult, "SCALE"));
        // DF: This method is used when the user uses the "insert row" function
import org.jkiss.dbeaver.model.meta.PropertyLength;
    private Integer partKeySeq;
    // @Property(viewable = true, order = 41)
        String typeName = JDBCUtils.safeGetString(dbResult, "TYPENAME");
    {
            this.stringUnitsLength = JDBCUtils.safeGetInteger(dbResult, "STRINGUNITSLENGTH");
 * @author Denis Forveille
            this.dataTypeSchema = dataType.getSchema();
    }
    @Override
    }
            this.rowEnd = JDBCUtils.safeGetString(dbResult, "ROWEND");
    @Property(viewable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 39)


import org.jkiss.dbeaver.ext.db2.DB2Constants;
    private String typeStringUnits;
        return nbQuantiles;

    @Property(viewable = true, order = 40)
    // -----------------
        return dataType;
import org.jkiss.dbeaver.model.struct.DBSTypedObjectEx;
import org.jkiss.dbeaver.ext.db2.model.dict.DB2TableColumnCompression;
    @Property(viewable = true, editable = false, order = 19, category = DB2Constants.CAT_OWNER)
import org.jkiss.dbeaver.model.struct.DBSDataType;
        return stringLength;
        return pctInlined;
import org.jkiss.dbeaver.model.DBPDataKind;
 *
    // Temporal
    {
        // Look first in Standards type
    }
 */
            this.typeStringUnits = JDBCUtils.safeGetStringTrimmed(dbResult, "TYPESTRINGUNITS");
    private Integer nbMostFreq;
        return compress;
        setMaxLength(50L);
    private Boolean identity;
            return DBPDataKind.CONTENT; // FOR BIT DATA
        // in the data table editor or for generating INSERT INTO statements (not yet 2013-12-17)
        setRequired(false);
    private int codePage;
    public DB2ColumnHiddenState getHidden()

    @Property(viewable = false, order = 138, category = DB2Constants.CAT_TEMPORAL)
    private Long nbNulls;
    @Property(viewable = false, order = 152, category = DBConstants.CAT_STATISTICS)
    // public String getTypeStringUnits()
    @Property(viewable = false, order = 47)
    {
 * You may obtain a copy of the License at
import org.jkiss.dbeaver.model.DBPEvaluationContext;
    public boolean isAutoGenerated()
        setOrdinalPosition(JDBCUtils.safeGetInt(dbResult, "COLNO"));
 * Licensed under the Apache License, Version 2.0 (the "License");
 * DBeaver - Universal Database Manager
        DBPDataKind dataKind = dataType.getDataKind();

    @Property(viewable = true, order = 999, editable = true, updatable = true, length = PropertyLength.MULTILINE)
 */
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
    }
    @Nullable
    // -----------------

    private Integer avgLength;
    // return stringUnitsLength;
    }
    private Boolean lobCompact;
    public String getDescription()
        return super.getDefaultValue();

            }
    @Property(viewable = true, editable = false, order = 20, category = DB2Constants.CAT_OWNER)
    @NotNull
        setDefaultValue(JDBCUtils.safeGetString(dbResult, "DEFAULT"));
    @Property(viewable = true, order = 44, editable = true)
    }
    @Nullable
        hiddenState = this.hidden == null ? false : hidden.isHidden();

import org.jkiss.dbeaver.ext.db2.model.dict.DB2ColumnHiddenState;
    public DB2DataSource getDataSource()
        this.remarks = remarks;
        return collationName;
    @Property(viewable = false, order = 159, category = DBConstants.CAT_STATISTICS)
        }

    // Properties

        }

/**
            setTypeName(dataType.getFullyQualifiedName(DBPEvaluationContext.DML));
 *

    }
    private String collationName;
        }

        }

            String typeSchemaName = JDBCUtils.safeGetStringTrimmed(dbResult, "TYPESCHEMA");
    public boolean isRequired()
        if (generated != null) {
    private String rowEnd;
            this.rowBegin = JDBCUtils.safeGetString(dbResult, "ROWBEGIN");
        this.dataType = tableBase.getDataSource().getDataTypeCache().getCachedObject("VARCHAR");

    public String getRowBegin()
            }
package org.jkiss.dbeaver.ext.db2.model;
        return getTable();
        if (db2DataSource.isAtLeastV10_1()) {

        return super.getScale();
    @Override
        DB2DataSource db2DataSource = tableBase.getDataSource();
    {
 * DB2 Table Column
    public Integer getPctInlined()
    @Override
    {
    @Property(viewable = false, order = 137)
    @Override
            this.nbMostFreq = JDBCUtils.safeGetInteger(dbResult, "NMOSTFREQ");
    {
    private Integer pctInlined;

import org.jkiss.dbeaver.ext.db2.model.dict.DB2YesNo;
            this.dataTypeSchema = dataType.getSchema();
    // -----------------
    }
    {

        this.low2key = JDBCUtils.safeGetString(dbResult, "LOW2KEY");
    {
    public DB2TableColumnGenerated getGenerated()
        super(tableBase, true);

    }
        setOrdinalPosition(-1);
        this.dataType = tableBase.getDataSource().getDataTypeCache().getObject(monitor, getTable().getDataSource(), typeName);
            this.nbQuantiles = JDBCUtils.safeGetInteger(dbResult, "NQUANTILES");
    {
        this.hidden = CommonUtils.valueOf(DB2ColumnHiddenState.class, JDBCUtils.safeGetString(dbResult, "HIDDEN"));
    }
        return keySeq;
        return super.getTypeName();
        this.lobCompact = JDBCUtils.safeGetBoolean(dbResult, "COMPACT", DB2YesNo.Y.name());
    }
    private String generatedText;
        return high2key;
import org.jkiss.dbeaver.Log;
    {

    }
        this.generated = CommonUtils.valueOf(DB2TableColumnGenerated.class, JDBCUtils.safeGetString(dbResult, "GENERATED"));


        return dataTypeSchema;
 * you may not use this file except in compliance with the License.
    @Property(viewable = false, order = 46)
        return transactionStartId;
    public DB2Schema getTypeSchema()
    {
    @Property(viewable = false, valueRenderer = DBPositiveNumberTransformer.class, order = 42)
            this.collationName = JDBCUtils.safeGetString(dbResult, "COLLATIONNAME");
    }
        this.compress = CommonUtils.valueOf(DB2TableColumnCompression.class, JDBCUtils.safeGetString(dbResult, "COMPRESS"));
    private static final Log log = Log.getLog(DB2TableColumn.class);
    }
        } else {
    private Integer stringUnitsLength;
    @Property(viewable = false, order = 121)
    {
    @Property(viewable = false, order = 136)
    //
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt4;

    {
 * 
    {
    }
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
    @Nullable
    public DBSDataType getDataType()
import org.jkiss.dbeaver.ext.db2.model.dict.DB2TableColumnGenerated;

    @Override
        this.keySeq = JDBCUtils.safeGetInteger(dbResult, "KEYSEQ");
    public String getDefaultValue()
 * limitations under the License.
    {
        return super.isRequired();
    @Override

    {
    public String getcollationName()
public class DB2TableColumn extends JDBCTableColumn<DB2TableBase>
        return avgLength;
        }
        this.remarks = JDBCUtils.safeGetString(dbResult, DB2Constants.SYSCOLUMN_REMARKS);
    @NotNull

    }
        this.partKeySeq = JDBCUtils.safeGetInteger(dbResult, "PARTKEYSEQ");
                stringLength = stringUnitsLength + " " + typeStringUnits;
        return colcard;

    {

    // return typeStringUnits;
    @Property(viewable = false, order = 180, category = DB2Constants.CAT_COLLATION)
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    {
            if (generated.equals(DB2TableColumnGenerated.A)) {
        if (dataType != null) {
        }
    @Property(viewable = false, order = 156, category = DBConstants.CAT_STATISTICS)
    private String transactionStartId;
        if (db2DataSource.isAtLeastV10_5()) {
        this.generatedText = JDBCUtils.safeGetString(dbResult, "TEXT");

import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.code.Nullable;
    public long getMaxLength()
    public String getRowEnd()
    private DB2DataType dataType;
import org.jkiss.utils.CommonUtils;
        }
    @Property(viewable = true, editable = true, updatable = true, order = 21, listProvider = DB2ColumnDataTypeListProvider.class)
        // Set DataTypes data
 * Unless required by applicable law or agreed to in writing, software
    private DB2TableColumnCompression compress;

        return dataKind;
        this.typeName = dataType.getTypeName();
            setTypeName(typeName);
        setRequired(JDBCUtils.safeGetBoolean(dbResult, "NULLS", DB2YesNo.N.name()));

            setValueType(Types.OTHER);
    {
    }

    {

    public Long getColcard()
import org.jkiss.dbeaver.model.struct.rdb.DBSTableColumn;
    {
    @Override

    private DB2Schema dataTypeSchema;
        return partKeySeq;
    public Integer getPctEncoded()
    {
    @NotNull
    {
    // @Property(viewable = true, order = 40)
            this.collationSchema = JDBCUtils.safeGetStringTrimmed(dbResult, "COLLATIONSCHEMA");
    {
        if (dataKind == DBPDataKind.STRING && this.codePage == 0) {

    }
    implements DBSTableColumn, DBSTypedObjectEx, DBPHiddenObject, DBSTypedObjectExt4<DB2DataType> {
 *
import org.jkiss.code.NotNull;
import java.sql.Types;
    @Property(viewable = false, order = 153, category = DBConstants.CAT_STATISTICS)
    public Boolean getLobCompact()
        return super.getMaxLength();
    @Property(viewable = true, order = 43, editable = true, updatable = true)
    }
    public Integer getPrecision()
            this.dataTypeSchema = getDataSource().getSchema(monitor, typeSchemaName);

    private String high2key;
    private String stringLength;
    private DB2TableColumnGenerated generated;
    public String getStringLength()
 *     http://www.apache.org/licenses/LICENSE-2.0
    {
    // -----------------
    public DB2TableColumn(DB2TableBase tableBase) throws DBException
        return generated;
    // }
    {
    public Long getNbNulls()

    {
        return lobCompact;
    {

    }

    private String low2key;
    private boolean hiddenState;


        this.nbNulls = JDBCUtils.safeGetLong(dbResult, "NUMNULLS");
            setTypeName(dataType.getFullyQualifiedName(DBPEvaluationContext.DML));
    public String getGeneratedText()
    public Integer getKeySeq()
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
        return pctEncoded;
    @Property(viewable = false, order = 150, category = DBConstants.CAT_STATISTICS)
    // -----------------


        setMaxLength(JDBCUtils.safeGetInt(dbResult, "LENGTH"));
        return rowBegin;
    @Property(viewable = false, order = 140, category = DB2Constants.CAT_TEMPORAL)
        this.high2key = JDBCUtils.safeGetString(dbResult, "HIGH2KEY");
    }
    }


        }
    // Constructors
    }
    public Integer getPartKeySeq()

    public DB2TableColumnCompression getCompress()
    {
import java.sql.ResultSet;
        return hidden;
    // }
    {
    public Integer getAvgLength()
        return generatedText;
    public boolean isHidden()
    }

    private Integer pctEncoded;


        if (db2DataSource.isAtLeastV9_7()) {
    }
                stringLength = "";
    // Business Contract
    @Property(viewable = false, order = 158, category = DBConstants.CAT_STATISTICS)
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        return remarks;

 * distributed under the License is distributed on an "AS IS" BASIS,
        return super.getPrecision();
        if (db2DataSource.isAtLeastV9_5()) {
    }
    }
        onChangeDataType(this.dataType, dataType);
            this.pctEncoded = JDBCUtils.safeGetInteger(dbResult, "PCTENCODED");
    public Integer getNbQuantiles()
    public String getTransactionStartId()
 * Copyright (C) 2013-2016 Denis Forveille (titou10.titou10@gmail.com)
                return true;
    // {
            this.dataType = this.dataTypeSchema.getUDT(monitor, typeName);
    @Property(viewable = false, order = 155, category = DBConstants.CAT_STATISTICS)
    public void setDescription(String remarks)

    {
    public String getHigh2key()

    @Property(viewable = false, order = 139, category = DB2Constants.CAT_TEMPORAL)
    @Override
            this.transactionStartId = JDBCUtils.safeGetStringTrimmed(dbResult, "TRANSACTIONSTARTID");
    // public Integer getStringUnitsLength()

import org.jkiss.dbeaver.ext.db2.editors.DB2ColumnDataTypeListProvider;
    private Integer keySeq;
            setValueType(dataType.getTypeID());
    }

    @Property(viewable = false, order = 157, category = DBConstants.CAT_STATISTICS)
}
    }
        return false;
    public DBPDataKind getDataKind()
    public Integer getScale()
    }
    {
        return low2key;
            if (typeStringUnits == null) {
    @Override
    private String rowBegin;
    }
    @Property(viewable = false, order = 154, category = DBConstants.CAT_STATISTICS)
