 * See the License for the specific language governing permissions and
                param.getParameterKind());
            Integer scale,
     * Hide: Altibase doesn't support comment for procedure and parameter
            DBSProcedureParameterKind parameterKind) {
    @Property(viewable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 41)
 * limitations under the License.
            int ordinalPosition,
                param.getPrecision(),

import org.jkiss.code.Nullable;
    @Override
    /*
                param.getScale(),
 * Licensed under the Apache License, Version 2.0 (the "License");
}
        return precision == -1 ? null : precision;
        super(procedure, columnName, typeName, valueType, ordinalPosition, columnSize, scale, precision, 
            String columnName,
        return scale == -1 ? null : scale;
    public static final int PARAM_OUT   = 1;
    public Integer getPrecision() {
            int valueType,
    @Override

                param.getTypeName(),
    public static final int PARAM_IN    = 0;

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    }
                param.isRequired(),
    @Property(viewable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 42)
    @Override
     */
    }
 * distributed under the License is distributed on an "AS IS" BASIS,
    public boolean isAutoGenerated() {
            boolean notNull,
import org.jkiss.dbeaver.ext.generic.model.GenericProcedureParameter;

 * you may not use this file except in compliance with the License.

package org.jkiss.dbeaver.ext.altibase.model;
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameterKind;
 *
 *
import org.jkiss.dbeaver.ext.generic.model.GenericProcedure;
            Integer precision,
    // Constructor with GenericProcedureParameter
        return autoGenerated;
            String typeName,
 * You may obtain a copy of the License at
 * DBeaver - Universal Database Manager

    public Integer getScale() {
                param.getDescription(),

    }
            GenericProcedure procedure,
                (int) param.getMaxLength(),
                notNull, remarks, parameterKind);
public class AltibaseProcedureParameter extends GenericProcedureParameter {
    @Property(viewable = true, order = 43)
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
    public boolean isRequired() {

    @Override
    public AltibaseProcedureParameter(GenericProcedureParameter param) {
import org.jkiss.dbeaver.model.meta.Property;
                param.getName(),
    @Property(viewable = false, hidden = true, order = 55)
 * Unless required by applicable law or agreed to in writing, software
        return required;
    }
 *
        super(param.getParentObject(),
    }
            String remarks,
    public AltibaseProcedureParameter(
    @Nullable
 */

 *     http://www.apache.org/licenses/LICENSE-2.0
/*
    }
            int columnSize,
                param.getTypeID(),
                param.getOrdinalPosition(),
 * Copyright (C) 2010-2024 DBeaver Corp and others
    public static final int PARAM_INOUT = 2;
