import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
        super(table);
            long charLength,

            String remarks,
    }
    @Property(viewable = false, order = 51)
    public boolean hasComment() {
                typeName,
                notNull,
            int ordinalPosition,
    public AltibaseTableColumn(GenericTableBase table) {
 * DBeaver - Universal Database Manager
    }
    /**
     * Whether the column has its own comment or not. 

    @Override
            String typeName,
 * Copyright (C) 2010-2024 DBeaver Corp and others

            long columnSize,
/*
    public AltibaseTableColumn(
            boolean autoGenerated) {
                ordinalPosition,

 * limitations under the License.
            GenericTableBase table,
 *

        return autoGenerated;
 * Licensed under the Apache License, Version 2.0 (the "License");
 *
        return (this.getDescription() != null && this.getDescription().length() > 0);
                charLength,
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
            String defaultValue,
 * you may not use this file except in compliance with the License.
                columnName,
     */
import org.jkiss.dbeaver.model.DBPNamedObject2;
            boolean autoIncrement,
import org.jkiss.dbeaver.model.meta.Property;
}
public class AltibaseTableColumn extends GenericTableColumn implements DBPNamedObject2 {
    public boolean isAutoGenerated() {
        return super.isAutoIncrement();
                autoGenerated);
 *
                radix,
                sourceType,
                precision,
    @Override
            int valueType,
            boolean notNull,

                columnSize,
                remarks,
                autoIncrement,
 * You may obtain a copy of the License at
 * See the License for the specific language governing permissions and
    @Property(viewable = false, hidden = true, order = 52)
 * Unless required by applicable law or agreed to in writing, software
    
    }
     */
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                valueType,
            int radix,
    /*
        super(table,
    }
    public boolean isAutoIncrement() {
                scale,
            String columnName,
            Integer precision,
            Integer scale,
            int sourceType,
 *     http://www.apache.org/licenses/LICENSE-2.0
 * distributed under the License is distributed on an "AS IS" BASIS,
package org.jkiss.dbeaver.ext.altibase.model;
 */
     * No auto-generated or auto-increment table columns in Altibase
                defaultValue,
    }
