productBrandText=Universal Database Manager
productEclipseId=org.jkiss.dbeaver.core.appstore
productBundleId=org.jkiss.dbeaver.core.appstore
productEmail=support@dbeaver.com
packageName=dbeaver
productModifier=ce
productTrademark=DBeaver is a trademark of DBeaver Corp
productWebSite=https://dbeaver.io/
productDescription=Universal Database Manager and SQL Client
productCopyright=DBeaver Corp
appTitle=DBeaver
appName=DBeaver
productType=community
productName=DBeaver CE
productCompany=DBeaver Corp
