    public String getLabel() {
 */
import org.jkiss.dbeaver.model.exec.DBCAttributeMetaData;
    /**
        return "Virtual attribute";


        if (obj instanceof DBDAttributeBindingCustom) {
    @NotNull
    @Nullable
import org.jkiss.utils.CommonUtils;
    }
    public boolean isRequired() {
/*
        return false;
    public boolean isCustom() {
    @Override
    @Override
        return true;
    }
    private List<DBSEntityReferrer> referrers;
    @Override
    @NotNull
        this.dataContainer = dataContainer;
    public int getOrdinalPosition() {
        return CommonUtils.notEmpty(vAttribute.getName()).hashCode();
 * You may obtain a copy of the License at


            DBVEntityAttribute cmpMeta = ((DBDAttributeBindingCustom) obj).vAttribute;
        this.parent = parent;
    }
    public String getFullTypeName() {

    public int getTypeID() {

import org.jkiss.dbeaver.model.virtual.DBVEntityAttribute;
    @Override

    public Object extractNestedValue(@NotNull Object ownerValue, int itemIndex) throws DBCException {
    private DBSDataContainer dataContainer;
    public Integer getScale() {
    public long getMaxLength() {

    @Nullable
 *
        return parent;
     * Row identifier (may be null)
    public boolean equals(Object obj) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    private int ordinalPosition;
 * limitations under the License.
    @Override
    public String toString() {
    }
    @Override
     * Attribute index in result set

    @Override
        return false;
    public long getTypeModifiers() {
     */
import org.jkiss.dbeaver.model.DBUtils;
import java.util.List;
        return vAttribute.getDataKind();
     *
    }
    }
 * DBeaver - Universal Database Manager
    @Nullable
    @Override
    @Override
        return true;
    @Nullable
    @Override
import org.jkiss.dbeaver.model.struct.DBSEntityReferrer;
    public DBCAttributeMetaData getMetaAttribute() {
import org.jkiss.dbeaver.model.exec.DBCSession;
    public List<DBSEntityReferrer> getReferrers() {
        return vAttribute.getScale();
    }
    @Nullable
        }
     */
     */
    }
    @NotNull
    @NotNull
    /**
        return vAttribute.getName();

    }

        return ordinalPosition;
        @Nullable DBDAttributeBindingCustom parent,
        return vAttribute.getTypeID();

    }
    }

    public DBDAttributeBindingCustom(
 */
package org.jkiss.dbeaver.model.data;
        this.vAttribute = vAttribute;
    public DBSDataContainer getDataContainer() {
    }

        return vAttribute.getName();
     * Meta attribute (obtained from result set)
    }
/**

     * Attribute label

 * Copyright (C) 2010-2024 DBeaver Corp and others
    /**
 * See the License for the specific language governing permissions and
    }
     * Attribute name
    /**
    private final DBVEntityAttribute vAttribute;
    @Override
    @Override
        return dataContainer;
        return vAttribute;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.model.DBPDataKind;
 *     http://www.apache.org/licenses/LICENSE-2.0
     * @return attribute index (zero based)
    }
    public String getName() {
        return referrers;
    }
    }
    }
    }
    @Override
import org.jkiss.dbeaver.model.exec.DBCException;
import org.jkiss.code.Nullable;

    public void lateBinding(@NotNull DBCSession session, List<Object[]> rows) throws DBException {
     * Entity attribute (may be null)
        return vAttribute.getFullTypeName();
 *
 * Unless required by applicable law or agreed to in writing, software
    }
    public DBDAttributeBindingCustom getParentObject() {
        @NotNull DBPDataSource dataSource,
     */
 *
    }
    public DBPDataSource getDataSource() {
        return null;
        return vAttribute.toString();
    @Override

 * you may not use this file except in compliance with the License.


        @NotNull DBSDataContainer dataContainer,
import org.jkiss.code.NotNull;
    }
 * Virtual attribute value binding info
    }

        return vAttribute.getTypeName();
import org.jkiss.dbeaver.model.struct.DBSDataContainer;
    private final DBDAttributeBindingCustom parent;
    }
        super.lateBinding(session, rows);
}

        return vAttribute.getTypeModifiers();
    @Nullable

        this.ordinalPosition = ordinalPosition;
    public boolean isAutoGenerated() {



        @NotNull DBVEntityAttribute vAttribute,
    @NotNull
    @Override

    @Override
    @Nullable
    public DBVEntityAttribute getEntityAttribute() {
            return CommonUtils.equalObjects(vAttribute.getName(), cmpMeta.getName());
        int ordinalPosition) {
public class DBDAttributeBindingCustom extends DBDAttributeBinding {
import org.jkiss.dbeaver.model.DBPDataSource;
    @Override
    public int hashCode() {
 * Licensed under the Apache License, Version 2.0 (the "License");
    @NotNull
    @NotNull
        throw new DBCException("Meta binding doesn't support nested values");


    }
    }
        this.ordinalPosition = ordinalPosition;
 * distributed under the License is distributed on an "AS IS" BASIS,
    public String getRowIdentifierStatus() {
        referrers = findVirtualReferrers();

    @Override

    /**
    public DBPDataKind getDataKind() {
        return vAttribute.getMaxLength();
    public String getTypeName() {
     */
    @Override
    @NotNull
    public Integer getPrecision() {
    public void setOrdinalPosition(int ordinalPosition) {
    @Override
    @Override
        return vAttribute.getPrecision();
        super(DBUtils.findValueHandler(dataSource, vAttribute));
    }
    @NotNull
    @NotNull
     */

    /**
        return dataContainer.getDataSource();
    }
    @Override
    }
        return null;
    public DBDRowIdentifier getRowIdentifier() {

