
        return collection;
    }

    @NotNull
    }
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
    @NotNull
}
    private final DBDCollection collection;
        return collection.getComponentType().getTypeID();

    public int getOrdinalPosition()
public class DBDAttributeBindingElement extends DBDAttributeBindingNested implements DBPImageProvider {
    @Override

    private final int index;
    }

        if (collection.isNull()) {
        int index)
    public Integer getPrecision() {
        @NotNull DBDAttributeBinding parent,
import org.jkiss.code.NotNull;
    public int hashCode() {
    }
    }
    }
 * You may obtain a copy of the License at
        return DBUtils.getFullTypeName(collection.getComponentType());
/*
    @Override
    /**
    @Nullable
    {
            CommonUtils.equalObjects(collection, ((DBDAttributeBindingElement) obj).collection) &&

    public Integer getScale() {
    public DBDCollection getSource() {
    }
        super(parent, collection.getComponentValueHandler());
    @Override


    public String getEntityName() {
    public long getTypeModifiers() {
     */
    {
    }
    {
    }

package org.jkiss.dbeaver.model.data;
    @Override

            // Can happen if values was released

    @Nullable
    public long getMaxLength() {
    @Override
/**
        return getName();
        return null;
    /**
     * Entity attribute
        }
    @NotNull
        return 0;
    }
    @Override
import org.jkiss.dbeaver.model.*;
        return collection.getComponentType().getTypeName();
    @Override
    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
import org.jkiss.utils.CommonUtils;
    }
 * limitations under the License.
        return collection.toString() + "@" + index;
     * Attribute name
        return super.equals(obj) && obj instanceof DBDAttributeBindingElement &&
        this.index = index;
    @Nullable
    @NotNull
     */
        return String.valueOf(index + 1);


        return false;
    }
 * DBeaver - Universal Database Manager
 *
    public boolean isAutoGenerated() {
    public String getLabel()

        @NotNull DBDCollection collection,
    public String getTypeName() {
    @Override
 * See the License for the specific language governing permissions and

    }

 * you may not use this file except in compliance with the License.
    public DBPImage getObjectImage() {
            index == ((DBDAttributeBindingElement) obj).index;
    @Override
        return false;
    @Override
    public DBDAttributeBindingElement(
     * Attribute label
    @NotNull
 *

     * @return attribute index (zero based)


    @Override
    }
 * Licensed under the Apache License, Version 2.0 (the "License");
    {
    /**
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        return collection.getComponentType().getMaxLength();
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
        return null;
    @Override
    @Override
    }

        return false;
    @Nullable
     */
 */
    @Nullable

    @Override

        this.collection = collection;
        }
    public Object extractNestedValue(@NotNull Object ownerValue, int itemIndex) throws DBCException {
        return collection.getComponentType().getPrecision();
 * Unless required by applicable law or agreed to in writing, software
    {
 *     http://www.apache.org/licenses/LICENSE-2.0
        return DBValueFormatting.getObjectImage(collection.getComponentType());
    }
    }
 *
    public boolean isPseudoAttribute() {
import org.jkiss.code.Nullable;
        return collection.getComponentType().getScale();
    }
    }
    public String getFullTypeName() {
    public int getTypeID() {
     * Attribute index in result set
            return ((DBDCollection) ownerValue).get(index);
    }

import org.jkiss.dbeaver.model.exec.DBCException;
    public boolean equals(Object obj) {

        return collection.hashCode() + index;
    /**
    @Override
    }
     */
    public DBPDataKind getDataKind() {

    @Nullable
    @Nullable
    public String toString() {
 * Collection element binding info

        return collection.getItem(index);

 */
    public DBSEntityAttribute getEntityAttribute()
    @NotNull
        return collection.getComponentType().getDataKind();
        if (ownerValue instanceof DBDCollection) {
    @Override
    public String getName()
    @Override
    @Override
        return collection.getComponentType().getTypeModifiers();
    public boolean isRequired() {
    }
            return null;
