    public DBSDataType getDataType() {
    @NotNull
    @Nullable
 */
        return attribute.getMaxLength();
    @Override

    public int getTypeID() {
    {
        return attribute.getScale();
 * See the License for the specific language governing permissions and

    @NotNull
    /**
    @Override
    @Override
    @Nullable
        return attribute.toString();
import org.jkiss.dbeaver.model.exec.DBCSession;
    public void lateBinding(@NotNull DBCSession session, List<Object[]> rows) throws DBException {
public class DBDAttributeBindingType extends DBDAttributeBindingNested implements DBPImageProvider {
    public Integer getPrecision() {
    public DBSAttributeBase getAttribute() {
    }
import org.jkiss.dbeaver.model.exec.DBCException;
        }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    }
    /**
    }
    public String getName()
}
    public long getTypeModifiers() {
        @NotNull DBSAttributeBase attribute,
    }
    }
    }
 *
import org.jkiss.utils.CommonUtils;

            return ((DBSTypedObjectEx) attribute).getDataType();
        int ordinalPosition)
        this.ordinalPosition = ordinalPosition;
        return attribute.isAutoGenerated();
 *
    }
    }
    @Override
    public void setOrdinalPosition(int ordinalPosition) {
    public DBPDataKind getDataKind() {
        return ordinalPosition < 0 ? attribute.getOrdinalPosition() : ordinalPosition;

            return ownerValue;
    @Nullable
    public String getEntityName() {
     * Entity attribute
    @NotNull
            return ((DBSObject)attribute).getParentObject();

     */

        return attribute.getTypeName();
    @Override
        return false;
    public long getMaxLength() {
        return attribute;
/**
import java.util.List;
    @Override
    }
        if (attribute instanceof DBSTypedObjectEx) {
    @NotNull
        return null;
    }
        return attribute.getName();
        } else if (ownerValue instanceof Map<?, ?> map) {



        } else {
     */
    @Override
        }
        @NotNull DBDAttributeBinding parent,
    {
    public String getLabel()
    }
     * @return attribute index (zero based)
    public List<DBSEntityReferrer> getReferrers() {
    @Override
    public DBSEntityAttribute getEntityAttribute()
    @Override

    @Override
/*
        return attribute.getTypeID();
     */
        return attribute.getPrecision();

        if (ownerValue instanceof DBDCollection collection) {
        super.lateBinding(session, rows);
    {
    @Override
        return attribute.getTypeModifiers();
        this.attribute = attribute;

    @NotNull

    }
        return super.getDataType();
            return collection.get(itemIndex);
    }
        }
        return DBUtils.getFullTypeName(attribute);
            return source.getName();
    @Nullable
 *     http://www.apache.org/licenses/LICENSE-2.0


import org.jkiss.dbeaver.model.*;
        } else if (ownerValue instanceof DBDComposite composite) {
 * distributed under the License is distributed on an "AS IS" BASIS,
    }
 * DBeaver - Universal Database Manager
     * Attribute label
    }

    @Nullable
    @Nullable
        if (attribute instanceof DBSObject) {

        return attribute.isRequired();
    private List<DBSEntityReferrer> referrers;
    }
 * limitations under the License.

import org.jkiss.code.NotNull;
    }
    @Override
import java.util.Map;
    @Override
    public int getOrdinalPosition() {
    @Override

        return DBValueFormatting.getObjectImage(attribute);
    public boolean isRequired() {
    @Override
        return super.equals(obj) && obj instanceof DBDAttributeBindingType &&
        DBSObject source = getSource();
 * Copyright (C) 2010-2024 DBeaver Corp and others
    @Override
    @NotNull
    public String toString() {
    }
    }

        if (source instanceof DBSEntity) {
    private static final Log log = Log.getLog(DBDAttributeBindingType.class);
    /**

            return composite.getAttributeValue(attribute);
        }
     * Attribute index in result set
    }
    public Object extractNestedValue(@NotNull Object ownerValue, int itemIndex) throws DBCException {


    }
package org.jkiss.dbeaver.model.data;
import org.jkiss.dbeaver.model.struct.*;
    @Nullable
    public boolean isAutoGenerated() {
    }


 * you may not use this file except in compliance with the License.
        return referrers;
 */
        return attribute.hashCode();
 * Licensed under the Apache License, Version 2.0 (the "License");
    public DBSObject getSource() {

    /**

    @Override
    }
        super(parent, DBUtils.findValueHandler(parent.getDataSource(), attribute));
    @Override
            CommonUtils.equalObjects(attribute, ((DBDAttributeBindingType) obj).attribute);
    @Override
        this.ordinalPosition = ordinalPosition;
    @Override
    public Integer getScale() {
        referrers = findVirtualReferrers();
     */

 * Type attribute value binding info
    @Override
    public DBDAttributeBindingType(
        return null;

    public String getFullTypeName() {
    }
     * Attribute name

    @Override
    }
        return null;
import org.jkiss.dbeaver.DBException;

    public boolean equals(Object obj) {


 *
        if (attribute instanceof DBSEntityAttribute) {
    public DBPImage getObjectImage() {
        return attribute.getDataKind();

        }
        return attribute.getName();
    public int hashCode() {
    private int ordinalPosition;
import org.jkiss.code.Nullable;
    @Override
            return map.get(getName());
    }
    private final DBSAttributeBase attribute;
 * Unless required by applicable law or agreed to in writing, software
    public boolean isPseudoAttribute() {
    @NotNull
    {

    }
            return (DBSEntityAttribute) attribute;
    @Nullable
    public String getTypeName() {
 * You may obtain a copy of the License at
    }
import org.jkiss.dbeaver.Log;

