    protected void addObjectModifyActions(
/**
        @NotNull List<DBEPersistAction> actions,
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }
import org.jkiss.dbeaver.model.edit.DBEObjectReorderer;
        @NotNull DBCExecutionContext executionContext,
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
 *     http://www.apache.org/licenses/LICENSE-2.0
            // DefaultModifier and ComputedModifier not supported in this case, IncrementModifier must be before NotNullModifier
        }
        final GenericTableColumn column = command.getObject();
{

                "Reorder column",
            return new ColumnModifier[] {DataTypeModifier, IncrementModifier, NotNullModifier};
import org.jkiss.dbeaver.model.edit.DBEObjectRenamer;
            ));
import org.jkiss.dbeaver.model.impl.edit.DBECommandAbstract;
            if (CommonUtils.isEmpty(column.getDefaultValue())) {
        final String definition = ((FireBirdTableColumn) column).getComputedDefinition();
            }
            actionList.add(new SQLDatabasePersistAction("Set column comment", "COMMENT ON COLUMN " +

            // Only GENERATED ALWAYS AS is supported when field is computed
    implements DBEObjectRenamer<GenericTableColumn>, DBEObjectReorderer<GenericTableColumn>
            addColumnCommentAction(actions, command.getObject(), command.getObject().getTable());
            return object.getTable().getAttributes(new VoidProgressMonitor()).size();
 *
                "ALTER TABLE " + DBUtils.getQuotedIdentifier(column.getTable()) + " ALTER COLUMN " +
    @Override
import org.jkiss.utils.CommonUtils;
            sql.append(" GENERATED ALWAYS AS ").append(definition);
            new SQLDatabasePersistAction(
    @Override
        if (CommonUtils.isNotEmpty(command.getObject().getDescription())) {
            sql.append(" GENERATED BY DEFAULT AS IDENTITY"); //$NON-NLS-1$
    public int getMaximumOrdinalPosition(GenericTableColumn object) {
        final FireBirdTableColumn column = (FireBirdTableColumn) command.getObject();
    }
                ddl.append(" GENERATED ALWAYS AS ").append(computedDefinition);
        String prefix = "ALTER TABLE " + DBUtils.getObjectFullName(column.getTable(), DBPEvaluationContext.DDL) + " ALTER COLUMN " + DBUtils.getQuotedIdentifier(column) + " ";
                .append(prefix).append("TYPE ").append(typeClause);
    }


    @Override
 * See the License for the specific language governing permissions and
import java.util.Map;
    ) throws DBException {
    protected void addObjectRenameActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions, @NotNull ObjectRenameCommand command, @NotNull Map<String, Object> options)
            new SQLDatabasePersistAction(
    }
        @NotNull List<DBEPersistAction> actionList,
        String typeClause = column.getFullTypeName();
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
        processObjectReorder(commandContext, object, siblingObjects, newPosition);
                // Can't change type for computed columns without this clause.
        @NotNull Map<String, Object> options

        if (command.getProperty(DBConstants.PROP_ID_DESCRIPTION) != null) {
        actions.add(

        }
        if (column.isAutoIncrement()) {


                DBUtils.getObjectFullName(column.getTable(), DBPEvaluationContext.DDL) + "." + DBUtils.getQuotedIdentifier(column) +
import org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn;
    {
    // Reorder
    }
 * limitations under the License.
        if (CommonUtils.isNotEmpty(((FireBirdTableColumn) column).getComputedDefinition())) {
import java.util.List;
        }

    };

        super.addObjectCreateActions(monitor, executionContext, actions, command, options);
        } catch (DBException e) {
        final GenericTableColumn column = command.getObject();
                prefix + "TYPE " + typeClause + " GENERATED ALWAYS AS (" + computedDefinition + ")"
        if (command.getProperty(DBConstants.PROP_ID_DEFAULT_VALUE) != null) {
        try {
                " IS " + SQLUtils.quoteString(column, CommonUtils.notEmpty(column.getDescription()))));
        return new ColumnModifier[] {DataTypeModifier, DefaultModifier, NotNullModifier};
    @Override
            log.error("Error reading columns for maximum order position", e);

}
 * Licensed under the Apache License, Version 2.0 (the "License");
import org.jkiss.dbeaver.DBException;
    ) throws DBException {
     */
 * distributed under the License is distributed on an "AS IS" BASIS,
    private final ColumnModifier<GenericTableColumn> ComputedModifier = (monitor, column, sql, command) -> {
import org.jkiss.dbeaver.model.impl.edit.SQLDatabasePersistAction;
        String computedDefinition = column.getComputedDefinition(monitor);
    protected void addObjectReorderActions(@NotNull DBRProgressMonitor monitor, @NotNull DBCExecutionContext executionContext, @NotNull List<DBEPersistAction> actions, @NotNull ObjectReorderCommand command, @NotNull Map<String, Object> options) {
/*
    public void setObjectOrdinalPosition(DBECommandContext commandContext, GenericTableColumn object, List<GenericTableColumn> siblingObjects, int newPosition) throws DBException {
    }
    private final ColumnModifier<GenericTableColumn> IncrementModifier = (monitor, column, sql, command) -> {
            }
    }
    protected ColumnModifier[] getSupportedModifiers(GenericTableColumn column, Map<String, Object> options) {
        @NotNull Map<String, Object> options
    public int getMinimumOrdinalPosition(GenericTableColumn object) {
                "Rename column",
     * Is is pretty standard
                    DBUtils.getQuotedIdentifier(column.getDataSource(), command.getOldName()) +
    public void addIncrementClauseToNestedDeclaration(DBECommandAbstract<GenericTableColumn> command, StringBuilder decl) {
    @Override
        }
    @Override
 * FireBirdTableColumnManager
    @Override
            actionList.add(new SQLDatabasePersistAction("Set column type", ddl.toString()));
    };
        // According to SQL92 DEFAULT comes before constraints
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    /**
        @NotNull ObjectCreateCommand command,
        @NotNull DBRProgressMonitor monitor,
    protected void addObjectCreateActions(
 *
        if (column.isAutoIncrement()) {
                    " TO " + DBUtils.getQuotedIdentifier(column.getDataSource(), command.getNewName())));
import org.jkiss.dbeaver.model.edit.DBECommandContext;
            return new ColumnModifier[] {DataTypeModifier, ComputedModifier};
                "Set column computed definition",
            final StringBuilder ddl = new StringBuilder()
        @NotNull DBCExecutionContext executionContext,
public class FireBirdTableColumnManager extends GenericTableColumnManager
                "ALTER TABLE " + DBUtils.getQuotedIdentifier(command.getObject().getTable()) + " ALTER COLUMN " +
        processObjectRename(commandContext, object, options, newName);
    public void renameObject(@NotNull DBECommandContext commandContext, @NotNull GenericTableColumn object, @NotNull Map<String, Object> options, @NotNull String newName) throws DBException {
import org.jkiss.dbeaver.model.DBConstants;
                actionList.add(new SQLDatabasePersistAction("Set column default", prefix + "SET DEFAULT " + column.getDefaultValue()));
    @Override
    ///////////////////////////////////////////////
import org.jkiss.code.NotNull;
            actionList.add(new SQLDatabasePersistAction(
    @Override

    }
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
    }
        // Increment clause already append with the IncrementModifier

        actions.add(
import org.jkiss.dbeaver.model.sql.SQLUtils;
        @NotNull DBRProgressMonitor monitor,
        if (command.getProperty("computedDefinition") != null) {
        }
        return 1;
            } else {
 * you may not use this file except in compliance with the License.

        @NotNull ObjectChangeCommand command,
        if (command.getProperty(DBConstants.PROP_ID_TYPE_NAME) != null || command.getProperty("maxLength") != null || command.getProperty("precision") != null || command.getProperty("scale") != null) {
import org.jkiss.dbeaver.model.edit.DBEPersistAction;

    }
 */
package org.jkiss.dbeaver.ext.firebird.edit;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
    @Override
                    DBUtils.getQuotedIdentifier(command.getObject()) + " POSITION " + column.getOrdinalPosition()));
 * You may obtain a copy of the License at
            return 0;

import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
        }

        }

 * DBeaver - Universal Database Manager
                actionList.add(new SQLDatabasePersistAction("Drop column default", prefix + "DROP DEFAULT"));
        }
 *
        if (CommonUtils.isNotEmpty(definition)) {
 */
import org.jkiss.dbeaver.ext.generic.edit.GenericTableColumnManager;
 * Unless required by applicable law or agreed to in writing, software
        }
        }

import org.jkiss.dbeaver.model.DBUtils;
            if (CommonUtils.isNotEmpty(computedDefinition)) {
