     * Restores the auto-range calculation on both axes.
            int width,
    /** The default limit below which chart scaling kicks in. */

        this.selectionColor = color;
     * Returns {@code true} if file extensions should be enforced, and

            }

import org.jfree.chart.event.ChartChangeEvent;
        }
        else if (listener instanceof DisposeListener) {
    /** The chart that is displayed in the panel. */

            }
    /** The zoom rectangle (selected by the user with the mouse). */

            }
        if (save) {
    /** The width of the chart buffer. */
    }
    public ChartComposite(
 */
                new MenuItem(result, SWT.SEPARATOR);
        int y = (int) Math.round(rect.getY() * this.getScaleY()) + insets.y;

     * Returns the flag that determines whether or not zooming is enabled for
        if (this.zoomRectangle != null) {
     * Zooms in on a selected region.
                    result = entity.getToolTipText();
        this.chart.draw(
    public void zoomInBoth(double x, double y) {

     *
     * @param e  the paint event.
            if (this.zoomInBothMenuItem != null) {
import java.awt.geom.Point2D;
        MouseListener, MouseMoveListener, Printable {
            }
        this.verticalAxisTrace = flag;
            boolean isDomainZoomable = false;
     *
                }
     * Handles action events generated by the popup menu.
    }
    }
        if (listeners.length == 0) {
        else {
     */
                    / (double) scaledDataArea.height;
            this.rangeZoomable = false;
     */
                DEFAULT_MINIMUM_DRAW_WIDTH,
                        (int) ((e.y - insets.y) / this.scaleY));
    public void setEnforceFileExtensions(boolean enforce) {
     * Decreases the length of the domain axis, centered about the given

                doSaveAs();
            z.zoomDomainAxes(this.zoomOutFactor, this.info.getPlotInfo(),
        if (this.info != null) {
     */
        }
        else if (command.equals(SAVE_COMMAND)) {
            org.eclipse.swt.graphics.Point movingPoint
     * @return The zoom in factor.
             true,  // zoom
            }
            e.gc.drawLine(this.verticalTraceLineX, area.y,
        if (this.horizontalAxisTrace && area.x < this.verticalTraceLineX
    /** A flag that controls whether or not the off-screen buffer is used. */
        if (properties || save || print || zoom)
    }
    }
        Rectangle available = getBounds();


    }
        int h = (int) (dataArea.getHeight() * this.scaleY);
            this.zoomInDomainMenuItem.addSelectionListener(this);
        else if (command.equals(ZOOM_RESET_DOMAIN_COMMAND)) {
     * @param height  the preferred height of the panel.
    /**
     * @param event  the mouse event.
        super.dispose();
     *              be added to the popup menu.
            this.canvas.addPaintListener((PaintListener) listener);
        // are we using the chart buffer?
    }
     * @param properties  a flag indicating whether or not the chart property
        this.horizontalTraceLineY = 0;
     *                   buffer to improve performance (at the expense of
    /** The default limit below which chart scaling kicks in. */

     * @param java2DPoint  the Java2D point.
     *
                DEFAULT_BUFFER_USED,
    public void chartProgress(ChartProgressEvent event) {
    private int maximumDrawWidth;
                // anti-aliasing
        }
     *              available via the popup menu.
    public String getToolTipText(org.eclipse.swt.events.MouseEvent e) {
        // add the new chart

     *
    private org.eclipse.swt.graphics.Color selectionColor = getDisplay().getSystemColor(SWT.COLOR_BLUE);

     */
        ev.x = 0;
     * @see #setZoomOutFactor(double)
            Menu zoomInMenu = new Menu(result);
     *
        // handle zoom box

        this.enforceFileExtensions = enforce;

            boolean tooltips) {
                true,  // properties
     * @param chart  the chart.
    public void zoomOutRange(double x, double y) {
                this.canvas.setData("double-buffer-image", this.chartBuffer);
                true,  // zoom

     * @param print  a flag indicating whether or not the print option
    public void setRangeZoomable(boolean flag) {
     * Returns the zoom in factor.
        boolean scale = false;
     * the value of {@link #getZoomInFactor()}.
                null,
        for (int i = listeners.length - 1; i >= 0; i -= 1) {
    private int zoomTriggerDistance;
            }
                SWTGraphics2D sg2d = new SWTGraphics2D(gci);
     * @return The screen location.
                tooltips
            restoreAutoBounds();
        // handle axis trace
     * Creates a popup menu for the canvas.
                    || this.chartBufferHeight != available.height) {
        int x = (int) Math.round(rect.getX() * getScaleX()) + insets.x;
        }
            MenuItem saveItem = new MenuItem(result, SWT.NONE);

     * @param y  the y-coordinate.
     */
        Plot p = this.chart.getPlot();
    /**
import org.jfree.swt.SWTUtils;
        }
    public void mouseDown(MouseEvent event) {
            this.chart.removeChangeListener(this);
    /** The height of the chart buffer. */
                    z.zoomRangeAxes(hLower, hUpper, plotInfo, selectOrigin);
            if (this.chartBuffer == null
     * Constructs a panel that displays the specified chart.
    public static final String SAVE_COMMAND = "SAVE";

     *
     */
    /**
    /**
            }
     * @param event  the mouse event.
        else if (command.equals(ZOOM_OUT_RANGE_COMMAND)) {
    }
            drawHeight = this.maximumDrawHeight;
        if (drawWidth < this.minimumDrawWidth) {
    /**
    /**
    /** The resourceBundle for the localization. */
        PlotRenderingInfo plotInfo = this.info.getPlotInfo();
                else {
     *
    public double getScaleY() {
     * heights).
            separator = true;
        }
    private boolean enforceFileExtensions;
    /**
                    sg2d.scale(this.scaleX, this.scaleY);

        // pass mouse down event if some ChartMouseListener are listening
     * @param properties  include a menu item for the chart property editor.
     *
        }
    public void paintControl(PaintEvent e) {
     * @param y  the y-coordinate (for subplot selection).
                return null;


     * @param useBuffer  a flag controlling whether or not an off-screen buffer

     * @param event  the event.
    }

    /**
     * @param x  the x coordinate (in screen coordinates).
     *
     * coordinate on the screen.  The length of the domain axis is increased
    /** Menu item for zooming out on a chart. */
     *
        return result;

            if (this.popup != null && event.button == 3) {
                this.zoomRectangle = new Rectangle(
     * The maximum width for drawing a chart (uses scaling for bigger
     * @return The scaled data area.
            this.canvas.addFocusListener((FocusListener) listener);
                    : new org.eclipse.swt.graphics.Point(0, 0));
        if (drawHeight < this.minimumDrawHeight) {
     * @param enforce  the new flag value.
     *
            }
     */
    }
                this.refreshBuffer = false;
        }
    /** The default limit below which chart scaling kicks in. */
     *      pointer on the horizontal axis.
        }
     * Returns the data area for the chart (the area inside the axes) with the
                DEFAULT_HEIGHT,
    public void doSaveAs() throws IOException {
        if (this.horizontalAxisTrace || this.verticalAxisTrace) {
     *
     */
                    "Domain_Axis"));
        if (this.zoomPoint != null) {
        if (this.popup != null) {
    /**
                    "Range_Axis"));
    /**
        Event ev = new Event();
        }
    /**
     * @return ?.

            saveItem.setText(localizationResources.getString("Save_as..."));

        // get the origin of the zoom selection in the Java2D space used for
    public void mouseMove(MouseEvent event) {

            this.scaleY = (double) drawHeight / this.maximumDrawHeight;
     *
    /**
                DEFAULT_MAXIMUM_DRAW_HEIGHT,
     */
     * in PNG format.
            EntityCollection entities = this.info.getEntityCollection();
        this.chart = chart;
     */
    }
    /**
                    translateScreenToJava2D(new Point((int) x, (int) y)));
        zoomInDomain(x, y);
     * Disposes the control.
 * Copyright (C) 2010-2025 DBeaver Corp and others
     * @param style The style of the composite.

    public double getZoomOutFactor() {
                DEFAULT_HEIGHT,
    }
                }
                this.zoomPoint = getPointInRectangle(event.x, event.y,
        else if (command.equals(ZOOM_OUT_BOTH_COMMAND)) {
            this.zoomInRangeMenuItem = new MenuItem(zoomInMenu, SWT.PUSH);


    public void widgetDefaultSelected(SelectionEvent e) {
        {

     * heights).
    private MenuItem zoomResetDomainMenuItem;
                gci.dispose();
     * Returns the X scale factor for the chart.  This will be 1.0 if no
    private MenuItem zoomOutDomainMenuItem;
            double hUpper = (selection.x + selection.width - scaledDataArea.x)
     */
            Rectangle screenDataArea = getScreenDataArea(event.x, event.y);
     * @param event  details of the chart change event.
                GC gci = new GC(this.chartBuffer);
        this.forceRedraw();
    /** The factor used to zoom in on an axis range. */
        java.awt.event.MouseEvent mouseEvent = SWTUtils.toAwtMouseEvent(event);
     */
            this.zoomInDomainMenuItem = new MenuItem(zoomInMenu, SWT.PUSH);
     * @return A boolean.
    }
        if (p instanceof Zoomable)
        this.canvas.redraw();
    public static final int DEFAULT_MAXIMUM_DRAW_HEIGHT = 600;
             DEFAULT_MINIMUM_DRAW_HEIGHT,
    /** Menu item for zooming out on a chart (range axis). */
        if (plot instanceof Zoomable) {
    /**
    public double getZoomInFactor() {
                true,  // print
    }
            if (separator) {
    /**
     *               should be available via the popup menu.
        }
            this.canvas.addMouseMoveListener((MouseMoveListener) listener);
     *              pointer on the vertical axis.
     * @param style The style of the composite.
package org.jfree.chart.swt;
    public void addChartMouseListener(ChartMouseListener listener) {
            return;
                this.chartBuffer = new org.eclipse.swt.graphics.Image(
        double x = pageFormat.getImageableX();
            }
        if (p instanceof ValueAxisPlot) {
                    "org.jfree.chart.LocalizationBundle");
     *
        }
     * @return A tool tip or {@code null} if no tooltip is available.
     *
        this.minimumDrawWidth = minimumDrawW;
                entity = entities.getEntity(x, y);
     * Decreases the length of the range axis, centered about the given

        Plot p = this.chart.getPlot();
import org.eclipse.swt.SWT;
     *
            boolean save,
                    z.zoomRangeAxes(vLower, vUpper, plotInfo, selectOrigin);
     */
        int y = (int) ((screenPoint.y - insets.y) / this.scaleY);
        this.canvas.redraw();
            MenuItem printItem = new MenuItem(result, SWT.NONE);
import org.eclipse.swt.widgets.FileDialog;
     * @param save  include a menu item for saving the chart.
                }


            Menu zoomOutMenu = new Menu(result);
            boolean usingBuffer,
                    gci.setAntialias(SWT.ON);
                new MenuItem(result, SWT.SEPARATOR);
     */

        this.useBuffer = usingBuffer;
     *
            boolean properties,
     *
                zoom,
        if (this.info != null) {
                properties,
     */
     *
                Zoomable z = (Zoomable) plot;
            }
    /**
            separator = true;
        int drawWidth = available.width;
            zoomInMenuItem.setText(localizationResources.getString("Zoom_In"));
import org.eclipse.swt.widgets.Composite;
     *
    /**

        }
            }
                    && Math.abs(this.zoomRectangle.height)
            this.canvas.addKeyListener((KeyListener) listener);
     *
    public boolean getFillZoomRectangle() {

         * those values are unused AFAIK. */
     * been scaled up or down to fit the panel).
                this.zoomOutBothMenuItem.setEnabled(isDomainZoomable
    /** Menu item for resetting the zoom (range axis only). */
        if (this.useBuffer) {
        return new Point(x, y);

        }
            zoomOutBoth(e.x, e.y);
            this.horizontalTraceLineY = event.y;
    public static final String ZOOM_RESET_DOMAIN_COMMAND = "ZOOM_RESET_DOMAIN";
    }
    public void setChart(JFreeChart chart) {
        this.verticalTraceLineX = 0;
     *
        return this.rangeZoomable;

    public void zoomInRange(double x, double y) {
    public JFreeChart getChart() {
    }
    private MenuItem zoomOutRangeMenuItem;
            this.zoomInBothMenuItem = new MenuItem(zoomInMenu, SWT.PUSH);
            this.canvas.addMouseTrackListener((MouseTrackListener) listener);
            boolean zoomTrigger2 = vZoom
     * @throws PrinterException if there is a problem.

                    || s != null && !s.equals(this.canvas.getToolTipText()))
    }
                hZoom = this.rangeZoomable;
    /**
     *
                this.zoomResetDomainMenuItem.setEnabled(isDomainZoomable);
     * Translates a Java2D point on the chart to a screen location.
        if (this.displayToolTips) {
     * @param flag  {@code true} enables trace lines for the mouse
        else if (listener instanceof MouseMoveListener) {
                true,  // print
        this.refreshBuffer = false;
        int x = (int) ((screenPoint.x - insets.x) / this.scaleX);
     * Adds a listener to the list of objects listening for chart mouse events.
        }
        if (chart != null) {
                DEFAULT_MINIMUM_DRAW_HEIGHT,
                true,  // save

    }
            printItem.setText(localizationResources.getString("Print..."));
     * Returns the anchor point.
     */
        String command = (String) ((MenuItem) e.getSource()).getData();
                }
        boolean hZoom, vZoom;
        }
        else {
            if (plot instanceof Zoomable) {
                Zoomable z = (Zoomable) plot;


        SWTGraphics2D sg2 = new SWTGraphics2D(e.gc);
/**
            this.zoomResetRangeMenuItem.setText(
        int h = (int) Math.round(rect.getHeight() * this.getScaleY());
    }
    /**
    /** The canvas to display the chart. */
        }
        /*
        }
                this.canvas.redraw();
import org.jfree.chart.event.ChartChangeListener;
            if (plot instanceof Zoomable) {
     * Returns the color used to draw the zoom rectangle


                    "All_Axes"));
     * @param x  the x value (in screen coordinates).
     * @param listener  the listener ({@code null} not permitted).
            }
        }
        }
        for (int i = listeners.length - 1; i >= 0; i -= 1) {
    /** The drawing info collected the last time the chart was drawn. */
        this.fillZoomRectangle = flag;
    }
                e.gc.setAntialias(SWT.ON);
    /**
     */
     * filled when drawn.
        }
            }
                true   // tooltips
    public Rectangle scale(Rectangle2D rect) {
    /**
     * @return The Java2D coordinates.
        setLayout(new FillLayout());
                entity = entities.getEntity(x, y);
        return PAGE_EXISTS;
        this.info = new ChartRenderingInfo();
        }
                hZoom = this.rangeZoomable;
    /**
                        & isRangeZoomable);
        Rectangle insets = this.getClientArea();
                    "All_Axes"));

        if ((selection.height > 0) && (selection.width > 0)) {
            }
     * Handles a mouse down event.
 * You may obtain a copy of the License at
    public void forceRedraw() {
     * @param zoom  a flag indicating whether or not zoom options should be
    }
     *
            this.refreshBuffer = true;
            result = getScreenDataArea();
        this.enforceFileExtensions = true;
            this.scaleX = (double) drawWidth / this.maximumDrawWidth;
        int x = (int) (dataArea.getX() * this.scaleX + clientArea.x);
        }

            }
            zoomOutRange(e.x, e.y);

    }
        this.zoomPoint = null;
                            drawWidth, drawHeight), getAnchor(), this.info);
            this.chart.addChangeListener(this);
        sg2.dispose();
    }

        }
        }

    private JFreeChart chart;
    private transient Rectangle zoomRectangle = null;
    /** A flag that indicates that the tooltips should be displayed. */

            if (p instanceof Zoomable) {
     * @param factor  the factor.

     * @return A boolean.
     * domain axis.  A check is made to ensure that the current plot supports
            this.chartBuffer = (org.eclipse.swt.graphics.Image)
            this.zoomResetBothMenuItem.addSelectionListener(this);
        else {
            }
     *
     * Sets a flag that controls whether or not file extensions are enforced.


     * Displays a dialog that allows the user to edit the properties for the
     */
/*
     * coordinate on the screen.  The length of the domain axis is reduced
        }
     *
            int minimumDrawW,
     * @return A new scaled rectangle.
    }

    /** A vertical trace line. */
        Rectangle insets = this.getClientArea();
        return new Rectangle(x, y, w, h);
             DEFAULT_MAXIMUM_DRAW_HEIGHT,
     * A flag that controls trace lines on the vertical axis.
     * @param width  the preferred width of the panel.
//          this.canvas.addMouseWheelListener((MouseWheelListener) listener);
                    this.canvas.getSize().x, this.canvas.getSize().y);
        return new org.eclipse.swt.graphics.Point(x, y);
    public void setZoomInFactor(double factor) {
        }
 *
     * A flag that controls trace lines on the horizontal axis.
        // de-register the composite as a listener for the chart.

     * @param x  horizontal position of the popup.
        this.scaleY = 1.0;



    public void setFillZoomRectangle(boolean flag) {
     * @param screenPoint  the screen location.
            this.zoomResetRangeMenuItem.setData(ZOOM_RESET_RANGE_COMMAND);
 * A SWT GUI composite for displaying a {@link JFreeChart} object.
    /** Menu item for zooming out on a chart (domain axis). */
             true,  // save
        int y = (int) (dataArea.getY() * this.scaleY + clientArea.y);
     *              available via the popup menu.

import javax.swing.event.EventListenerList;
     */
    }
    private double zoomOutFactor = 2.0;


    private EventListenerList chartMouseListeners;

        // drawing the chart (that is, before any scaling to fit the panel)
     * @param y  the y-coordinate (in screen coordinates).
 * Licensed under the Apache License, Version 2.0 (the "License");
        boolean hZoom, vZoom;
             true,  // properties
        FileDialog fileDialog = new FileDialog(this.canvas.getShell(),
     * @param minimumDrawW  the minimum drawing width.
        Plot plot = this.chart.getPlot();
import java.util.EventListener;
            = ResourceBundleWrapper.getBundle(
         * this helps to handle the mouse events and besides,
     * Restores the auto-range calculation on the domain axis.
     *                   is used.
    /** The scale factor used to draw the chart. */
        }
     * @param flag  {@code true} instructs to fill the rectangle on
     * coordinate on the screen.  The length of the range axis is reduced by
            if (this.zoomResetBothMenuItem != null) {
     *
     *
    public static final int DEFAULT_HEIGHT = 420;
     */

                }
            autoRangeMenuItem.setMenu(autoRangeMenu);
                e.gc.setBackground(this.selectionColor);
        if (scaledDataArea == null) return;
        this.anchor = new Point2D.Double(x, y);

        Rectangle scaledDataArea = getScreenDataArea(event.x, event.y);
            }
    private transient int verticalTraceLineX;
            Zoomable z = (Zoomable) p;
                DEFAULT_WIDTH,
    private PlotOrientation orientation = PlotOrientation.VERTICAL;
import java.awt.print.Printable;
            this.zoomResetDomainMenuItem.setText(
    }
 * distributed under the License is distributed on an "AS IS" BASIS,
     * @see #getZoomOutFactor()
     * given rectangle.
        }
     * Forces a redraw of the canvas by invoking a new PaintEvent.
    /**
        String[] extensions = {"*.png"};
            boolean zoom,
     */
     * Receives notification of a chart progress event.
     *
    /**
     */
        }
    /** Color for the selection rectangle */
    private MenuItem zoomInBothMenuItem;
    /**
    /**
                    (this.zoomPoint != null ? this.zoomPoint
        return this.enforceFileExtensions;
            this.zoomOutDomainMenuItem.addSelectionListener(this);
        if (pageIndex != 0) {
    /** The minimum distance required to drag the mouse to trigger a zoom. */
        if (filename != null) {
//      else if (listener instanceof MenuDetectListener) {
import java.awt.print.PageFormat;
        }

                true   // tooltips
     * The maximum height for drawing a chart (uses scaling for bigger
    public boolean isEnforceFileExtensions() {
        Rectangle2D dataArea = this.info.getPlotInfo().getDataArea();
        if (this.chart == null) {
    }
            zoomInMenuItem.setMenu(zoomInMenu);
        Menu result = new Menu(this);
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                save,
import java.io.File;
    protected static ResourceBundle localizationResources
            this.zoomOutBothMenuItem.setText(localizationResources.getString(
                        (int) ((e.x - insets.x) / this.scaleX),
    /** Menu item for zooming in on a chart (both axes). */
            scale = true;
                (selection.y + selection.height / 2));
     * with the current scaling applied.
    public void mouseUp(MouseEvent event) {

                hZoom = this.domainZoomable;
     */
import org.eclipse.swt.layout.FillLayout;
        if (p instanceof Zoomable) {
                this.zoomInRangeMenuItem.setEnabled(isRangeZoomable);

            this.canvas.addTraverseListener((TraverseListener) listener);
                DEFAULT_MAXIMUM_DRAW_WIDTH,
     * @param y  the y coordinate (in screen coordinates).
            this.zoomOutRangeMenuItem = new MenuItem(zoomOutMenu, SWT.PUSH);

            // get the origin of the zoom selection in the Java2D space used for

            else if (hZoom) {
     */
    /** Properties action command. */

            z.zoomDomainAxes(0.0, this.info.getPlotInfo(),
     */
    /**
                useBuffer,
    /** The plot orientation. */
 * <p>
     */

            this.rangeZoomable = false;
     */
                DEFAULT_WIDTH,
                    translateScreenToJava2D(new Point((int) x, (int) y)));
     */
            this.popup.setVisible(true);
    public void setZoomOutFactor(double factor) {
    }
            if (isEnforceFileExtensions()) {
                e.gc.setAlpha(63);
    private MenuItem zoomInDomainMenuItem;
        else if (drawWidth > this.maximumDrawWidth) {
    private double scaleY;
                    : new org.eclipse.swt.graphics.Point(0, 0));
            z.zoomRangeAxes(this.zoomOutFactor, this.info.getPlotInfo(),

     * @param x  the x coordinate (in screen coordinates).
     * @return A boolean.
                this.zoomInDomainMenuItem.setEnabled(isDomainZoomable);
     *                  enabled for the chart.
     */
     * by the value of {@link #getZoomInFactor()}.
     * @param y  the y value (in screen coordinates).

                this.chartBufferWidth = available.width;
            Composite comp,
    }
    /**
        // does nothing - override if necessary
        if (p instanceof Zoomable) {
        return result;

            this.zoomInRangeMenuItem.addSelectionListener(this);
     * @param x  the x value (in screen coordinates).
        */
                    >= this.zoomTriggerDistance;
                    "Zoom_Out"));
            this.canvas.drawBackground(e.gc, available.x, available.y,
                this.zoomResetRangeMenuItem.setEnabled(isRangeZoomable);
     * A flag that controls mouse-based zooming on the vertical axis.
                    "All_Axes"));
            if(this.fillZoomRectangle) {
                        getDisplay(), this.chartBufferWidth,
    public static final String ZOOM_IN_BOTH_COMMAND = "ZOOM_IN_BOTH";
     * Handles action events generated by the popup menu.
            double vUpper = (scaledDataArea.y + scaledDataArea.height
     * Sets the zoom in factor.
                int ymax = Math.max(movingPoint.y, scaledDataArea.y);
     * @return Current selection color
    /** A flag that controls whether or not domain zooming is enabled. */

     */
            boolean print,
                        & isRangeZoomable);
    /**

     * @param zoom  include menu items for zooming.
        this.canvas.addMouseMoveListener(this);
    /**
            // zap the buffer onto the canvas...
    public void restoreAutoRangeBounds() {

    private boolean displayToolTips;
        return new Point(x, y);
     */
        new ChartPrintJob("PlotPrint").print(this);
        }
     */
     * Returns the data area (the area inside the axes) for the plot or subplot,
        Object[] listeners = this.chartMouseListeners.getListeners(
        this.zoomOutFactor = factor;
     * @param properties  a flag indicating whether or not the chart property
                ChartEntity entity = entities.getEntity(
                && area.y + area.height > this.horizontalTraceLineY) {
            if (plot instanceof Zoomable) {
 *
    /** Controls if the zoom rectangle is drawn as an outline or filled. */
                            drawWidth, drawHeight), getAnchor(), this.info);
     *
     */
    /**
    }
        }
    }

                    area.x + area.width, this.horizontalTraceLineY);
            }
        zoomOutRange(x, y);
     * @throws IOException if there is an I/O error.
    public void zoomInDomain(double x, double y) {
            propertiesItem.setData(PROPERTIES_COMMAND);
     * @param chart  the chart.

        }
            return;
        }
            }
                this.orientation = z.getOrientation();
            Menu autoRangeMenu = new Menu(result);
            this.zoomResetDomainMenuItem = new MenuItem(autoRangeMenu,
                this.rangeZoomable = z.isRangeZoomable();
                e.gc.setTextAntialias(SWT.ON);
        Plot p = this.chart.getPlot();
    public ChartComposite(Composite comp,
    /** Zoom out (both axes) action command. */
        // TODO workout insets for SWT
        // work out if scaling is required...
                    = getPointInRectangle(event.x, event.y, scaledDataArea);
    public ChartComposite(Composite comp, int style) {
     *                    editor should be available via the popup menu.
 * notification is received.
                true,  // save
                this.rangeZoomable = flag && (z.isRangeZoomable());
     * @param print  a flag indicating whether or not the print option
        if (flag) {
     * @return A point within the rectangle.
    public static final boolean DEFAULT_BUFFER_USED = false;
     * line is drawn over the plot area at the current mouse location.
            Zoomable plot = (Zoomable) p;
            z.zoomRangeAxes(0.0, this.info.getPlotInfo(),
     */
     * @param comp The parent.

    /**
             DEFAULT_BUFFER_USED,
        }
     *
        if (print) {
     */
            this.zoomResetRangeMenuItem.addSelectionListener(this);
     * Increases the length the range axis, centered about the given
     * @param x  the x-coordinate.
    }
    private org.eclipse.swt.graphics.Point getPointInRectangle(int x, int y,
            }
     * @param screenPoint  the screen location.

     * subclasses, not end users.
     */
        return this.zoomOutFactor;
     * @return The chart (possibly {@code null}).
                        screenDataArea);
    public ChartComposite(Composite comp, int style, JFreeChart chart,
    /** Zoom in (range axis only) action command. */
        }
        }
        }
                mouseEvent, entity);

     *
        Rectangle area = getScreenDataArea();
     * Returns the chart contained in the panel.
        return this.anchor;
        }
     *
     * @param comp The parent.
     * the range axis.
    /** A flag that controls whether or not horizontal tracing is enabled. */

     * scaling has been used.
                if ((hZoom && (this.zoomRectangle.x + this.zoomRectangle.width
    }
    public void createChartPrintJob() {
                    filename = filename + ".png";
    public static final int DEFAULT_MAXIMUM_DRAW_WIDTH = 800;
                this.domainZoomable = flag && (z.isDomainZoomable());
            }
     *
        ev.width = this.canvas.getBounds().width;
        return this.domainZoomable;

     * The idea is to modify the zooming options depending on the type of chart
     * Applies any scaling that is in effect for the chart drawing to the
     * Removes a listener from the list of objects listening for chart mouse
                this.chart);
            if (separator) {
     * The minimum height for drawing a chart (uses scaling for smaller
        this.popup = null;
    }
                DEFAULT_MINIMUM_DRAW_HEIGHT,
        int w = (int) (dataArea.getWidth() * this.scaleX);
    /**
    private boolean horizontalAxisTrace = false;
        this(comp, style, chart,
            saveItem.setData(SAVE_COMMAND);

            if (this.zoomResetDomainMenuItem != null) {
            e.gc.drawRectangle(this.zoomRectangle);
            }
                this.chartBufferHeight = available.height;

            // we need to guard against this.zoomPoint being null
                isDomainZoomable = z.isDomainZoomable();
            this.zoomResetDomainMenuItem.addSelectionListener(this);


    }

     * @param area  the rectangle ({@code null} not permitted).
     */
        Rectangle insets = this.getClientArea();
    public void dispose() {
        }
    public static final String ZOOM_RESET_BOTH_COMMAND = "ZOOM_RESET_BOTH";
     * @param event  the event.
            boolean properties,
        // create the canvas and add the required listeners

            Zoomable z = (Zoomable) plot;
     */
    /** A flag that controls whether or not file extensions are enforced. */
            }
            Zoomable z = (Zoomable) p;

            //SwtGraphics2D sg2 = new SwtGraphics2D(e.gc);
     * @return The popup menu.
                separator = false;
            boolean print, boolean zoom) {
            }
            new MenuItem(zoomInMenu, SWT.SEPARATOR);
    public ChartComposite(Composite comp, int style, JFreeChart chart) {
                DEFAULT_BUFFER_USED,
                    == RenderingHints.KEY_TEXT_ANTIALIASING) {

                separator = false;
import org.eclipse.swt.graphics.Rectangle;
        else if (listener instanceof MouseTrackListener) {
        else if (command.equals(ZOOM_IN_DOMAIN_COMMAND)) {
        else {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public Rectangle getScreenDataArea(int x, int y) {
     *
import org.eclipse.swt.widgets.MenuItem;
     * Sets the flag that controls whether or not zooming is enable for the
        if (listener instanceof ControlListener) {
     * @param comp The parent.
    /** Menu item for resetting the zoom (both axes). */
     */
 * The composite listens to the chart to receive notification of changes to any
     * Paints the control.

            autoRangeMenuItem.setText(localizationResources.getString(
     * @param tooltips  a flag indicating whether or not tooltips should be
                    zoom(this.zoomRectangle);

        this.displayToolTips = displayToolTips;
     *
            this.canvas.addDisposeListener((DisposeListener) listener);
    public void restoreAutoBounds() {
    /**

     * @param y  the y-coordinate (in screen coordinates).
        if (flag) {

     * @return The flag.
     * @param displayToolTips the displayToolTips to set

     * org.eclipse.swt.events.SelectionEvent)
                vZoom = this.domainZoomable;
            }
        this.maximumDrawHeight = maximumDrawH;
        // new entity code
     *
            MenuItem zoomOutMenuItem = new MenuItem(result, SWT.CASCADE);
     * @param rect  the rectangle.
     * @param style The style of the composite.
        else if (command.equals(PRINT_COMMAND)) {

                SWT.SAVE);
    public void widgetSelected(SelectionEvent e) {
     * @param zoom  a flag indicating whether or not zoom options should
            propertiesItem.addSelectionListener(this);
                if (this.chart.getTextAntiAlias()
        );
    /** A buffer for the rendered chart. */
        // first determine the size of the chart rendering area...
             true,  // print
                if (entity != null) {
            this.domainZoomable = false;
     * A flag that controls how the zoom rectangle is drawn.
            Plot plot = this.chart.getPlot();
                Zoomable z = (Zoomable) p;
     *
            if (this.refreshBuffer) {
            drawWidth = this.minimumDrawWidth;
    private MenuItem zoomResetRangeMenuItem;
            this.rangeZoomable = false;
    }
                vZoom = this.rangeZoomable;
        }
    /** A flag that controls whether or not range zooming is enabled. */
        return this.scaleY;
    public static final String ZOOM_OUT_BOTH_COMMAND = "ZOOM_OUT_BOTH";
     * Returns the Y scale factory for the chart.  This will be 1.0 if no
            this.canvas.redraw();
            zoomInBoth(e.x, e.y);
     * Hook an SWT listener on the canvas where the chart is drawn.

    }
        ev.gc.dispose();


    private org.eclipse.swt.graphics.Image chartBuffer;
     * @param flag  {@code true} enables trace lines for the mouse
                // if the box has been drawn backwards, restore the auto bounds
     *
                        + this.zoomRectangle.height < this.zoomPoint.y)))
                    gci.setTextAntialias(SWT.ON);
            Point2D selectOrigin = translateScreenToJava2D(new Point(x, y));
            if (this.zoomOutBothMenuItem != null) {
     *
     * by the value of {@link #getZoomOutFactor()}.
 * Unless required by applicable law or agreed to in writing, software
        return new Rectangle(x, y, w, h);

            separator = true;
                if (img != null) {
    /**
    }
    }
        Plot p = this.chart.getPlot();
        widgetSelected(e);
                        == RenderingHints.KEY_TEXT_ANTIALIASING) {
            this.zoomOutRangeMenuItem.addSelectionListener(this);
            this.verticalTraceLineX = event.x;
                    >= this.zoomTriggerDistance;
//      } else if (listener instanceof MouseWheelListener) {
        // axis traces
     * Returns the chart rendering info from the most recent chart redraw.
    /** Menu item for resetting the zoom (domain axis only). */
            try {
                    SWTUtils.toAwtPoint(zp));
     * @param comp The parent.
    }
import org.jfree.chart.event.ChartProgressEvent;
     * Creates a print job for the chart.
                    "Domain_Axis"));
    public static final String ZOOM_IN_DOMAIN_COMMAND = "ZOOM_IN_DOMAIN";
     */
    }
            }

     *
        }
     * @param selection  the selected region.
    /**
    public void setVerticalAxisTrace(boolean flag) {
        Rectangle clientArea = this.getClientArea();
            if (this.zoomResetRangeMenuItem != null) {
                else {
        else if (command.equals(ZOOM_RESET_BOTH_COMMAND)) {
            this.zoomResetDomainMenuItem.setData(ZOOM_RESET_DOMAIN_COMMAND);
    public boolean getHorizontalAxisTrace() {
     * @param x  the x coordinate (in screen coordinates).

        else {
    public static final int DEFAULT_WIDTH = 680;
     */
                }
        else if (listener instanceof FocusListener) {
    public boolean getVerticalAxisTrace() {
    /**
        Point2D selectOrigin = translateScreenToJava2D(
            Zoomable z = (Zoomable) p;
            this.zoomOutRangeMenuItem.setData(ZOOM_OUT_RANGE_COMMAND);
    /** Zoom reset (domain axis only) action command. */
            this.zoomInBothMenuItem.setText(localizationResources.getString(
     * Opens a file chooser and gives the user an opportunity to save the chart

                        scaledDataArea.x, this.zoomPoint.y,
    protected Menu createPopupMenu(boolean properties, boolean save,
                isRangeZoomable = z.isRangeZoomable();
     *               should be available via the popup menu.

                DEFAULT_MINIMUM_DRAW_WIDTH,
     * @param flag  {@code true} enables zooming.
                this.zoomOutRangeMenuItem.setEnabled(isRangeZoomable);
     * Constructs a panel containing a chart.
                        this.chartBufferHeight);
     * coordinate on the screen.  The length of the range axis is increased
            int style,
    /** Default setting for buffer usage. */
     *
            this.zoomInDomainMenuItem.setText(localizationResources.getString(
        return this.scaleX;
    /** Zoom reset (range axis only) action command. */
                        scaledDataArea.y, movingPoint.x - this.zoomPoint.x,
                vZoom = this.domainZoomable;
     *
     */
     */
    }
 * DBeaver - Universal Database Manager
                this.zoomResetBothMenuItem.setEnabled(isDomainZoomable
            public void widgetDisposed(DisposeEvent e) {
        }
        /* in the next zoomPoint.x and y replace by e.x and y for now.
                img = (org.eclipse.swt.graphics.Image) canvas.getData("double-buffer-image");
            String s = getToolTipText(event);
    }
                    this.verticalTraceLineX, area.y + area.height);
                    z.zoomDomainAxes(hLower, hUpper, plotInfo, selectOrigin);

     */
    /**
                / (double) scaledDataArea.width;
     * @param print  include a menu item for printing the chart.
                print,

            }
                    SWTUtils.toAwtPoint(zp));
            this.zoomOutDomainMenuItem.setData(ZOOM_OUT_DOMAIN_COMMAND);
                (selection.x + selection.width / 2),
            boolean print,
     * @param chart  the chart.
    }
            // we need to guard against this.zoomPoint being null
        if (this.chart != null) {
    /**
            plot.zoomDomainAxes(this.zoomInFactor, this.info.getPlotInfo(),
     */
     * Zooms in on an anchor point (specified in screen coordinate space).
     * @see org.eclipse.swt.events.SelectionListener#widgetDefaultSelected(
    /** Zoom out (domain axis only) action command. */
    /**
            Rectangle area) {

            double hLower = (selection.x - scaledDataArea.x)
    public void setDomainZoomable(boolean flag) {
public class ChartComposite extends Composite implements ChartChangeListener,
    public void setDisplayToolTips(boolean displayToolTips) {
        if (drawWidth == 0.0 || drawHeight == 0.0) return;

    /** The default panel height. */
     * Returns the zoom out factor.
        if (this.info != null) {

            createChartPrintJob();
                true,  // zoom
     *
    /**
        double h = pageFormat.getImageableHeight();
        if (listeners.length == 0) {
            this.zoomOutBothMenuItem.addSelectionListener(this);

            }
        if (p instanceof Zoomable) {
            this.zoomOutDomainMenuItem = new MenuItem(zoomOutMenu, SWT.PUSH);
     */

     * @param maximumDrawH  the maximum drawing height.
     * Does nothing - override if necessary.
                    this.chart.draw(sg2d, new Rectangle2D.Double(0, 0,
        if (this.popup != null) {
     *                   memory).
                if (!filename.endsWith(".png")) {
import org.jfree.chart.entity.EntityCollection;
        boolean separator = false;
    private Menu popup;
     * @return The scale factor.

        throws PrinterException {
            if (entities != null) {
            this.zoomInRangeMenuItem.setData(ZOOM_IN_RANGE_COMMAND);
                separator = false;
        ev.y = 0;
    /**
    protected void setAnchor(Point2D anchor) {
     * scaling has been used.
                Zoomable z = (Zoomable) plot;
        }
             style,
        return this.chart;
            restoreAutoDomainBounds();
                && area.x + area.width > this.verticalTraceLineX) {
     * of the given rectangle.  This method could be moved to JCommon.
     */
     */

            new MenuItem(zoomOutMenu, SWT.SEPARATOR);
    public void zoomOutBoth(double x, double y) {
        editor.open();
             DEFAULT_WIDTH,
    /**
        return this.zoomInFactor;
     * @param save  a flag indicating whether or not save options should be
        Plot p = this.chart.getPlot();
    }
    private MenuItem zoomResetBothMenuItem;
     * Constructs a JFreeChart panel.
     * The purpose of this method is to allow some degree of customization.
            if (zoomTrigger1 || zoomTrigger2) {
            g2, new Rectangle2D.Double(x, y, w, h), this.anchor, null
        ev.height = this.canvas.getBounds().height;
                // Performs the actual drawing here ...
     */
     * @param jfreechart  the chart.

     */
            if (entities != null) {
        if (this.chartBuffer != null) {
    /** Zoom out (range axis only) action command. */
        this(
                    img.dispose();
        }
     *                  enabled for the chart.
                    localizationResources.getString("Range_Axis"));
    }
        this.maximumDrawWidth = maximumDrawW;

            this.orientation = z.getOrientation();
            JFreeChart jfreechart,
        }
        this.chart.setNotify(true);  // force a redraw
        this(comp,
     * Increases the length of the domain axis, centered about the given
                DEFAULT_MAXIMUM_DRAW_WIDTH,
            }
    }
                style,
     * The minimum width for drawing a chart (uses scaling for smaller widths).
    /**
        zoomOutDomain(x, y);
            this.zoomResetBothMenuItem = new MenuItem(autoRangeMenu, SWT.PUSH);
    /**
     * line is drawn over the plot area at the current mouse location.
     * @param style The style of the composite.
                this.zoomRectangle = new Rectangle(this.zoomPoint.x,
    /**
            this.chart.removeProgressListener(this);
                this.getBounds().width, this.getBounds().height);
    }
     *
                DEFAULT_MAXIMUM_DRAW_WIDTH,
                DEFAULT_MAXIMUM_DRAW_HEIGHT,
            this.canvas.addMouseListener((MouseListener) listener);
        this(comp,
        setChart(jfreechart);

     * @return The chart rendering info (possibly {@code null}).
            boolean isRangeZoomable = false;
            this.popup.dispose();
        else {
                }
     */
}
     * Returns the flag that controls whether or not a vertical axis trace
    private int chartBufferWidth;
        else if (command.equals(ZOOM_RESET_RANGE_COMMAND)) {
            this.chart.removeProgressListener(this);
     * @return A boolean.

                if (this.chartBuffer != null) {
        });
            EntityCollection entities = this.info.getEntityCollection();
        this.chartMouseListeners = new EventListenerList();
     * org.eclipse.swt.events.SelectionEvent)
    /** Zoom reset (both axes) action command. */
     *
     * @param x  the x-coordinate (in screen coordinates).
    private int chartBufferHeight;
    /**
     */
            restoreAutoRangeBounds();
        int drawHeight = available.height;
                    this.chart.draw(sg2d, new Rectangle2D.Double(0, 0,
     * Translates a screen location to a Java2D point.
 * See the License for the specific language governing permissions and
     *
            new MenuItem(autoRangeMenu, SWT.SEPARATOR);
            org.eclipse.swt.graphics.Point zp =
            return NO_SUCH_PAGE;
        Rectangle result;

            if (this.zoomInRangeMenuItem != null) {
        return this.selectionColor;
    /**
        }
     */
    private boolean refreshBuffer;
        String filename = fileDialog.open();
                new MenuItem(result, SWT.SEPARATOR);
 * you may not use this file except in compliance with the License.
            Plot plot = chart.getPlot();
     */
    public static final int DEFAULT_MINIMUM_DRAW_WIDTH = 300;
        if (this.zoomRectangle == null) {
        else if (command.equals(ZOOM_IN_RANGE_COMMAND)) {
     * @return The Java2D coordinates.
        fileDialog.setFilterExtensions(extensions);

 */
    private transient int horizontalTraceLineY;
     */
    /**
        CairoImage image = new CairoImage(
            Rectangle scaledDataArea = getScreenDataArea(this.zoomPoint.x,
            int maximumDrawW,
     *                    editor should be available via the popup menu.

        y = Math.max(area.y, Math.min(y, area.y + area.height));
    /**
                mouseEvent, entity);
            if (separator) {
    }
        else if (listener instanceof KeyListener) {
                    || this.chartBufferWidth != available.width
    public void setSelectionColor(org.eclipse.swt.graphics.Color color) {
    /**
        ev.count = 0;
    private double zoomInFactor = 0.5;
    /**
    private MenuItem zoomOutBothMenuItem;
            int style,
     * the domain axis.
    /** The chart anchor point. */
            }
    public Point translateScreenToJavaSWT(Point screenPoint) {
            printItem.addSelectionListener(this);
        }
            int subplotIndex = plotInfo.getSubplotIndex(selectOrigin);
     *
            this.chart.removeChangeListener(this);
     *
            this.chart.addProgressListener(this);
            catch (IOException ex) {
                / (double) scaledDataArea.width;

        else if (listener instanceof TraverseListener) {
    /**
    public void setHorizontalAxisTrace(boolean flag) {
        ChartEntity entity = null;
     */
    }
                DEFAULT_WIDTH,
    }
            JFreeChart chart,
     * @param anchor  the anchor point ({@code null} permitted).
        else if (listener instanceof MouseListener) {
                    translateScreenToJava2D(new Point((int) x, (int) y)));
    public boolean isRangeZoomable() {
        int w = (int) Math.round(rect.getWidth() * this.getScaleX());
    public org.eclipse.swt.graphics.Color getSelectionColor () {
     * widths).
        }
        this.zoomInFactor = factor;
                this.zoomRectangle = new Rectangle(this.zoomPoint.x,
        }
            boolean tooltips) {
     * Returns a string for the tooltip.
            if (this.chart.getAntiAlias()) {
     *
        this.zoomPoint = getPointInRectangle(event.x, event.y, scaledDataArea);
    private int maximumDrawHeight;

        this.chartMouseListeners.add(ChartMouseListener.class, listener);
            this.zoomOutBothMenuItem = new MenuItem(zoomOutMenu, SWT.PUSH);
    /** The default limit below which chart scaling kicks in. */
                    localizationResources.getString("Range_Axis"));
            this.canvas.redraw();
     * @param minimumDrawH  the minimum drawing height.
    }
     *
            }
                else {
        restoreAutoRangeBounds();
    private boolean fillZoomRectangle = true;
            vZoom = false;

    }

    }
                    z.zoomDomainAxes(vLower, vUpper, plotInfo, selectOrigin);
    private int minimumDrawWidth;
     */

    /**
            else {
            // enable it...
    }

     *
        );
     */
    public static final String PRINT_COMMAND = "PRINT";
    /**
     * @param tooltips  a flag indicating whether or not tooltips should be

     * @param color New selection color
             DEFAULT_MINIMUM_DRAW_WIDTH,

            }
     * Changes the color used to draw the zoom rectangle
        Object[] listeners = this.chartMouseListeners.getListeners(
            int minimumDrawH,
import java.awt.*;
    /**
     */
     * Returns the flag that controls whether or not a horizontal axis trace
    public void chartChanged(ChartChangeEvent event) {
     *
     *
        }
    /**

    }

             DEFAULT_HEIGHT,
                this.refreshBuffer = true;

            attemptEditChartProperties();
     * @param pageIndex  the page index.
     * @see #getZoomInFactor()
    /**
     * @param flag  {@code true} enables zooming if possible.
     * events.
        }
     */
     *
    /**

            this.zoomInBothMenuItem.addSelectionListener(this);
    public static final String ZOOM_IN_RANGE_COMMAND = "ZOOM_IN_RANGE";
    /**
     *
                new Point(selection.x, selection.y));
                this.domainZoomable = z.isDomainZoomable();
     *
            org.eclipse.swt.graphics.Point zp =
//      }
    /** Zoom in (domain axis only) action command. */
    }
            MenuItem autoRangeMenuItem = new MenuItem(result, SWT.CASCADE);

            this.zoomOutDomainMenuItem.setText(localizationResources.getString(
        }
            if (subplotIndex == -1) {
     * Returns the flag that determines whether or not zooming is enabled for
     */
import org.eclipse.swt.widgets.Event;
            else {
        }
     * @param pageFormat  the page format.
            this.chart.draw(sg2, new Rectangle2D.Double(0, 0,
     */
            int height,
    private boolean domainZoomable = false;
            ((ChartMouseListener) listeners[i]).chartMouseClicked(chartEvent);
     */
    private void attemptEditChartProperties() {
                    this.canvas.getData("double-buffer-image");
     */
     *
 *
        return this.fillZoomRectangle;
    public void zoomOutDomain(double x, double y) {
                this.canvas.setToolTipText(s);
            // do we need to redraw the buffer?
        setDisplayToolTips(tooltips);
            this.zoomResetBothMenuItem.setData(ZOOM_RESET_BOTH_COMMAND);
     * Sets the anchor point.  This method is provided for the use of

            this.zoomResetRangeMenuItem = new MenuItem(autoRangeMenu, SWT.PUSH);
    public static final int DEFAULT_MINIMUM_DRAW_HEIGHT = 200;
        }
    public void addSWTListener(EventListener listener) {
        ChartEntity entity = null;
            saveItem.addSelectionListener(this);
            int maximumDrawH,
            if (this.orientation == PlotOrientation.HORIZONTAL) {
            boolean useBuffer) {

     * @param y  the y-coordinate (in screen coordinates).
            scale = true;
     * @see #setZoomInFactor(double)
     */
                    "Auto_Range"));

    public void restoreAutoDomainBounds() {
     */
     * Not implemented.



        int x = (int) ((event.x - getClientArea().x) / this.scaleX);
                    this.zoomPoint.y);
        Graphics2D g2 = image.createGraphics2D();
        int x = (int) (java2DPoint.getX() * this.scaleX + insets.x);
    private MenuItem zoomInRangeMenuItem;
     */
    }
    /** Menu item for zooming in on a chart (domain axis). */
                );
            Plot p = this.chart.getPlot();
        else if (command.equals(ZOOM_IN_BOTH_COMMAND)) {
     * being displayed by the panel.
    /** Save action command. */
                this.zoomOutDomainMenuItem.setEnabled(isDomainZoomable);
    private org.eclipse.swt.graphics.Point zoomPoint = null;
                    SWT.PUSH);
//          this.canvas.addDragDetectListener((DragDetectListener) listener);
    }

            this.popup.setLocation(x, y);


    /** A flag that indicates that the buffer should be refreshed. */
     * Receives notification of changes to the chart, and redraws the chart.
     *
                    available.width, available.height);
        if (p instanceof Zoomable) {
            EntityCollection entities = this.info.getEntityCollection();
        double w = pageFormat.getImageableWidth();
            if (this.zoomInDomainMenuItem != null) {
            this.chartBuffer.dispose();
            MenuItem propertiesItem = new MenuItem(result, SWT.PUSH);
     * @param listener  the listener.
     *
        zoomInRange(x, y);
            this.zoomOutBothMenuItem.setData(ZOOM_OUT_BOTH_COMMAND);
                    translateScreenToJava2D(new Point((int) x, (int) y)));
            zoomInDomain(e.x, e.y);
            sg2.drawImage(this.chartBuffer, 0, 0);
        }

            }

    public void removeChartMouseListener(ChartMouseListener listener) {
     * by the value of {@link #getZoomOutFactor()}.
import org.jfree.chart.util.ResourceBundleWrapper;
import org.eclipse.swt.events.*;
        if (plotInfo.getSubplotCount() == 0)
             DEFAULT_MAXIMUM_DRAW_WIDTH,
                }
        String result = null;
            if (plot instanceof Zoomable) {
     *
     * @param maximumDrawW  the maximum drawing width.

        this.canvas.notifyListeners(SWT.Paint, ev);
     * This way, when drawn, the chart will fill all the space.
    /**

        }
    /**
                    - selection.y) / (double) scaledDataArea.height;
            double vLower = (scaledDataArea.y + scaledDataArea.height
            if (this.zoomOutDomainMenuItem != null) {
        // new entity code
import org.jfree.swt.SWTGraphics2D;
     * @param usingBuffer  a flag that indicates whether to use the off-screen
     * @param y  vertical position of the popup.
import org.jfree.chart.event.ChartProgressListener;
        ChartMouseEvent chartEvent = new ChartMouseEvent(getChart(),
            if (this.orientation == PlotOrientation.HORIZONTAL) {
        return this.info;

                    "Properties..."));
            if (screenDataArea != null) {

                DEFAULT_MINIMUM_DRAW_WIDTH,
            }
            }
    public ChartRenderingInfo getChartRenderingInfo() {
    public boolean isDomainZoomable() {
            this.zoomResetBothMenuItem.setText(localizationResources.getString(
            propertiesItem.setText(localizationResources.getString(
            zoomInRange(e.x, e.y);
    }
            this.zoomOutRangeMenuItem.setText(
                    getBounds().width, getBounds().height), getAnchor(),
        this.canvas.addDisposeListener(new DisposeListener() {
        else if (listener instanceof PaintListener) {
        if (command.equals(PROPERTIES_COMMAND)) {
        if (this.verticalAxisTrace && area.y < this.horizontalTraceLineY
    public static final String PROPERTIES_COMMAND = "PROPERTIES";
    }

    }
import org.jfree.chart.swt.editor.SWTChartEditor;
        return this.verticalAxisTrace;
            Plot plot = this.chart.getPlot();

            scale = true;
import org.eclipse.swt.widgets.Menu;
    /**
            printItem.setData(PRINT_COMMAND);
        this.zoomTriggerDistance = DEFAULT_ZOOM_TRIGGER_DISTANCE;
                true,  // properties
            e.gc.drawLine(area.x, this.horizontalTraceLineY,
import org.eclipse.swt.graphics.GC;

            boolean zoom,

                org.eclipse.swt.graphics.Point pt = this.canvas.toDisplay(
     * @param e  the mouse event.
    /**
     * current chart.
                vZoom = this.rangeZoomable;
    private boolean verticalAxisTrace = false;
        super(comp, style);
        else if (listener instanceof HelpListener) {
     * Handles a mouse up event.
                        event.x, event.y);
        Rectangle scaledDataArea = getScreenDataArea(
     * Translates a screen location to a Java SWT point.
        Rectangle insets = this.getClientArea();
    }
        this.refreshBuffer = true;
            boolean zoomTrigger1 = hZoom && Math.abs(this.zoomRectangle.width)

        ChartMouseEvent chartEvent = new ChartMouseEvent(getChart(),
        }
            // go through each zoom menu item and decide whether or not to
import org.eclipse.swt.widgets.Canvas;
             chart,
            this.domainZoomable = false;
            zoomOutDomain(e.x, e.y);
        java.awt.event.MouseEvent mouseEvent = SWTUtils.toAwtMouseEvent(event);
                    localizationResources.getString("Domain_Axis"));

     * Restores the auto-range calculation on the range axis.
        int x = (int) ((event.x - getClientArea().x) / this.scaleX);
import org.jfree.chart.*;
import java.awt.print.PrinterException;
        }
            }

            Zoomable z = (Zoomable) p;
        }
    public static final int DEFAULT_ZOOM_TRIGGER_DISTANCE = 10;
     * Handles a mouse move event.
     */

            z.zoomRangeAxes(this.zoomInFactor, this.info.getPlotInfo(),
    public Point2D translateScreenToJava2D(Point screenPoint) {
            if (this.zoomOutRangeMenuItem != null) {

                comp,
    private boolean rangeZoomable = false;
            }
        restoreAutoDomainBounds();
    /** The scale factor used to draw the chart. */

                // selected rectangle shouldn't extend outside the data area...
        // pass mouse move event if some ChartMouseListener are listening
            drawHeight = this.minimumDrawHeight;
        x = Math.max(area.x, Math.min(x, area.x + area.width));
        return new Point2D.Double(x, y);
     * Create a new chart composite with a default FillLayout.
//          this.canvas.addMenuDetectListener((MenuDetectListener) listener);
                    restoreAutoBounds();
                        scaledDataArea.height);
     * @return The scaled data area.
    /**
//      else if (listener instanceof DragDetectListener) {
     *              zoom, otherwise it will be outlined.
            else if (vZoom) {
        }
     */
        int y = (int) (java2DPoint.getY() * this.scaleY + insets.y);
                ChartMouseListener.class);
     * @param event  the event.
                Rectangle insets = getClientArea();
        // skip if chart is null
                DEFAULT_HEIGHT,
     * Zooms out on an anchor point (specified in screen coordinate space).
                hZoom = this.domainZoomable;
                e.gc.fillRectangle(this.zoomRectangle);
    private boolean useBuffer;
     */
                ex.printStackTrace();
     *
    /**
            boolean save,
            return;
     * @param x  the x-coordinate (for subplot selection).
    }
     * @param listener The SWT listener to attach to the canvas.
     * @param style The style of the composite.
    private double scaleX;
     * @param chart  the chart ({@code null} permitted).

import java.awt.geom.Rectangle2D;

    /** The minimum size required to perform a zoom on a rectangle */
    /**
            this.popup = createPopupMenu(properties, save, print, zoom);
     *
    public static final String ZOOM_OUT_RANGE_COMMAND = "ZOOM_RANGE_BOTH";
     *
        }

        else if (drawHeight > this.maximumDrawHeight) {
import java.io.IOException;

     *              added to the popup menu.
    /** Storage for registered (chart) mouse listeners. */
    /** The factor used to zoom out on an axis range. */
        int y = (int) ((screenPoint.y - insets.y) / this.scaleY);
        PlotRenderingInfo plotInfo = this.info.getPlotInfo();
            ((ChartMouseListener) listeners[i]).chartMouseMoved(chartEvent);
     * @return The anchor point (possibly {@code null}).
        return result;
            zoomOutMenuItem.setMenu(zoomOutMenu);
     * @param save  a flag indicating whether or not save options should be
    /**
    }
            // drawing the chart (that is, before any scaling to fit the panel)
     * @param y  the y value (in screen coordinates).
import org.jfree.chart.entity.ChartEntity;
    /** The popup menu for the frame. */
                    this.info);
        // set up popup menu...
            if (entities != null) {
        // stop listening for changes to the existing chart
import org.jfree.chart.plot.*;
                        this.zoomPoint.y, movingPoint.x - this.zoomPoint.x,
    /** Zoom in (both axes) action command. */
     * The zoom rectangle starting point (selected by the user with a mouse
 *     http://www.apache.org/licenses/LICENSE-2.0
        this.horizontalAxisTrace = flag;
     * {@code false} otherwise.
    /**
                ChartMouseListener.class);
     */
import java.util.ResourceBundle;
                sg2d.dispose();
                if (this.chart.getAntiAlias()) {
    }
     * zooming for the domain values.
     * Sets the zoom out factor.
                chart,
            this.domainZoomable = false;
        this.zoomRectangle = null;
     * Returns the flag that controls whether or not the zoom rectangle is
        }
    public Point translateJava2DToScreen(Point2D java2DPoint) {
        // do nothing, override if necessary
     *
             true   // tooltips
    public static final String ZOOM_RESET_RANGE_COMMAND = "ZOOM_RESET_RANGE";
                this.zoomInBothMenuItem.setEnabled(isDomainZoomable
            ChartUtils.saveChartAsPNG(new File(filename), this.chart,
     *

        this.chartMouseListeners.remove(ChartMouseListener.class, listener);
     *
        }
        SWTChartEditor editor = new SWTChartEditor(this.canvas.getDisplay(),
            zoomOutMenuItem.setText(localizationResources.getString(
        this.canvas.addMouseListener(this);
            this.scaleX = (double) drawWidth / this.minimumDrawWidth;
    public void zoom(Rectangle selection) {
     *
                if (scale) {
    private Point2D anchor;

        Plot p = this.chart.getPlot();
    /**
            }
    private ChartRenderingInfo info;
        int y = (int) ((event.y - getClientArea().y) / this.scaleY);
            if (hZoom && vZoom) {
     */

     * @param graphics  the graphics.
            result = scale(plotInfo.getSubplotInfo(subplotIndex).getDataArea());
    public void mouseDoubleClick(MouseEvent event) {
    public static final String ZOOM_OUT_DOMAIN_COMMAND = "ZOOM_DOMAIN_BOTH";
                    - selection.y - selection.height)
        if (this.chart != null) {

        ev.gc = new GC(this.canvas);
    /** Print action command. */

        this.anchor = anchor;
        }
 * component of the chart.  The chart is redrawn automatically whenever this
    public Rectangle getScreenDataArea() {
        ChartProgressListener, PaintListener, SelectionListener,
        }
    /**
        );
            if (this.chart.getTextAntiAlias()
        }

                }
            Plot plot = this.chart.getPlot();
        //ChartEditorManager.getChartEditor(canvas.getDisplay(), this.chart);
     * @see org.eclipse.swt.events.SelectionListener#widgetSelected(



            // do we need to fill the buffer?
        this.scaleX = 1.0;
        double y = pageFormat.getImageableY();
            //TODO replace getSize by getBounds ?
        this.canvas = new Canvas(this, SWT.DOUBLE_BUFFERED | SWT.NO_BACKGROUND);
        if (this.useBuffer) {
        }
                        < this.zoomPoint.x)) || (vZoom && (this.zoomRectangle.y
            this.zoomInRangeMenuItem.setText(localizationResources.getString(
                if (z.getOrientation() == PlotOrientation.HORIZONTAL) {
    }
     * @return The zoom out factor.


            this.canvas.addHelpListener((HelpListener) listener);
                        movingPoint.y - this.zoomPoint.y);
        // or redrawing the chart every time...


                DEFAULT_MAXIMUM_DRAW_HEIGHT,
     *
            e.gc.setForeground(this.selectionColor);
    }
        this.canvas.addPaintListener(this);
    /**

     * @return The scale factor.
            this.canvas.addControlListener((ControlListener) listener);
            this.zoomInDomainMenuItem.setData(ZOOM_IN_DOMAIN_COMMAND);
 * limitations under the License.
     *
        if (zoom) {
     * current scaling applied (that is, the area as it appears on screen).
    public double getScaleX() {
     * Sets the chart that is displayed in the panel.
        }
                org.eclipse.swt.graphics.Image img;

     * @param comp The parent.
     *
     */
        }
            scale = true;
            Zoomable z = (Zoomable) p;
     * click).  This is a point on the screen, not the chart (which may have

     */
    private Canvas canvas;
        if (properties) {
                displayPopupMenu(pt.x, pt.y);
                DEFAULT_MINIMUM_DRAW_HEIGHT,
            if (s == null && this.canvas.getToolTipText() != null
     *
        // TODO see if we need to apply some line color and style to the


    public Point2D getAnchor() {
                style,
     *
     * Constructs a JFreeChart panel.
        int x = (int) ((screenPoint.x - insets.x) / this.scaleX);
            hZoom = false;
                );
     * @return A boolean.
    private int minimumDrawHeight;
                        & isRangeZoomable);
//      }
     * Returns a point based on (x, y) but constrained to be within the bounds
    /** A flag that controls whether or not vertical tracing is enabled. */
    /** The default panel width. */
            drawWidth = this.maximumDrawWidth;
            }
                Zoomable z = (Zoomable) plot;

                    (this.zoomPoint != null ? this.zoomPoint
    /** A horizontal trace line. */
    /** Menu item for zooming in on a chart (range axis). */
    /**
        this.minimumDrawHeight = minimumDrawH;
                }
     * @param factor  the factor.
            this.scaleY = (double) drawHeight / this.minimumDrawHeight;

        else if (command.equals(ZOOM_OUT_DOMAIN_COMMAND)) {
                    this.chartBuffer.dispose();

        return this.horizontalAxisTrace;
            }

        // handle tool tips in a simple way
            this.zoomInBothMenuItem.setData(ZOOM_IN_BOTH_COMMAND);
            MenuItem zoomInMenuItem = new MenuItem(result, SWT.CASCADE);
    /**
     *
    }
    protected void displayPopupMenu(int x, int y) {
                }
        int y = (int) ((event.y - getClientArea().y) / this.scaleY);
                        scaledDataArea.width, ymax - this.zoomPoint.y);
