 * Copyright (C) 2010-2024 DBeaver Corp and others
 *     http://www.apache.org/licenses/LICENSE-2.0

 */

 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.model.struct.DBSObject;
 *
    @Override
public class HANAInplaceTableTypeColumn extends JDBCAttribute {
    @Override
    @Override

 *
 * DBeaver - Universal Database Manager
 * you may not use this file except in compliance with the License.
    @Property(hidden = true)
    @Override
 * You may obtain a copy of the License at
    @Property(hidden = true)

 * Unless required by applicable law or agreed to in writing, software


 * Licensed under the Apache License, Version 2.0 (the "License");

    
    DBSObject parent;
    @Override
import org.jkiss.dbeaver.model.DBPDataSource;
    public boolean isRequired() { return false; }
    }
 *
    HANAInplaceTableTypeColumn(DBSObject parent, String name, String typeName, int position, int length, int scale) {
    public String getDescription() { return null; }
        super(name, typeName, 0 /*valueType*/, position, length, scale, 0 /*precision*/, false /*required*/, false /*sequence*/);
import org.jkiss.dbeaver.model.meta.Property;

 * distributed under the License is distributed on an "AS IS" BASIS,
        this.parent = parent;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public DBPDataSource getDataSource() { return parent.getDataSource(); }
 * limitations under the License.
/*
    @Override
    public boolean isAutoGenerated() { return false; }
    public DBSObject getParentObject() { return parent; }
package org.jkiss.dbeaver.ext.hana.model;
}
    public boolean isPersisted() { return true; }
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCAttribute;

