
                break;
        GenericFunctionResultType functionResultType
        String targetObjectSchema = JDBCUtils.safeGetString(dbResult, 3);
                dbStat.setString(2, sourceObject.getName());
        } catch (SQLException e) {
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
    public boolean supportsTableDDLSplit(@NotNull GenericTableBase sourceObject) {
    private static final Log log = Log.getLog(HANAMetaModel.class);
    @Override
    }
    }
 */
                        result.add(new GenericTableTrigger(table, name, null));
        }
    public GenericTableBase createTableImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @NotNull GenericMetaObject tableObject, @NotNull JDBCResultSet dbResult) {
    @Nullable
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger sourceObject) throws DBException {
                    remarks, defaultValue, autoIncrement, autoGenerated);
        return new HANAProcedure(container, procedureName, specificName, remarks, procedureType, functionResultType);
        String typeName,
 */
        if (tableType != null && tableType.equals("SYNONYM"))
            @NotNull GenericStructContainer owner, @Nullable GenericTableBase forParent) throws SQLException {
    @Override
import org.jkiss.dbeaver.model.DBPEvaluationContext;
        if (sourceObject instanceof HANATrigger) {
    }

    @Override
        dbStat.setString(1, container.getName());
        int ordinalPos,

        long columnSize,
        } else {
        return new HANASchema(dataSource, catalog, schemaName);


        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read HANA trigger source")) {
        }
        int valueType,
public class HANAMetaModel extends GenericMetaModel
        return JDBCUtils.safeGetBoolean(dbResult, "IS_PRIMARY_KEY", HANAConstants.SYS_BOOLEAN_TRUE)
                "SELECT DEFINITION\n" +
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
    }
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaObject;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
        JDBCPreparedStatement dbStat = session.prepareStatement(

    public JDBCStatement prepareSequencesLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
            }
        super();
            return new HANASysViewColumn(table, columnName,
        } catch (SQLException e) {
        }
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
        if (table != null) {
        if(forParent!=null) { 
    }
    public GenericSequence createSequenceImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
        Number minValue = JDBCUtils.safeGetBigDecimal(dbResult, 2);
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
        boolean autoGenerated
                    while (dbResult.nextRow()) {
 *
        }

        Integer scale,
                }
        return new HANATrigger(genericTableBase, triggerName, resultSet);
            return ((HANATrigger) sourceObject).getDefinition();
            {
        return dbStat;
    ) throws DBException {
        if (tableType != null && isView(tableType)) {
    @Override
            if (matcher.find()) {
        dbStat.setString(1, container.getName());
    public JDBCStatement prepareSynonymsLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
                    "WHERE SCHEMA_NAME=? and VIEW_NAME=?"))
import org.jkiss.dbeaver.model.DBPErrorAssistant;
/*
    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {
    }
            return null;
    }
    public JDBCStatement prepareTableTriggersLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws SQLException {
    public DBSEntityConstraintType getUniqueConstraintType(@NotNull JDBCResultSet dbResult) throws DBException, SQLException {
        JDBCPreparedStatement dbStat = session.prepareStatement(
        if (!CommonUtils.isEmpty(message)) {
    ) {

        schemas.add(i, publicSchema);
            "SELECT SYNONYM_NAME, OBJECT_TYPE, OBJECT_SCHEMA, OBJECT_NAME FROM SYS.SYNONYMS WHERE SCHEMA_NAME = ? ORDER BY SYNONYM_NAME");
 * HANAMetaModel
                    charLength, scale, precision, radix, notNull,
    public JDBCStatement prepareUniqueConstraintsLoadStatement(@NotNull JDBCSession session,
                    if (dbResult.nextRow()) {
        return dbStat;
            ((HANADataSource)table.getDataSource()).initializeSysViewColumnUnits(monitor);
    public GenericTableTrigger createTableTriggerImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull GenericTableBase genericTableBase, String triggerName, @NotNull JDBCResultSet resultSet) {
    }
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
                dbStat.setString(1, table.getSchema().getName());
        int sourceType,
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            schemaName.startsWith("_SAP_") ||
                        ddl.append(dbResult.getString("OBJECT_CREATION_STATEMENT"));
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read HANA procedure source")) {
        String defaultValue,
            {
    @Override
                    }
    @Override
        } else {
    
            }
    }
        } catch (Exception e) {
            log.debug("Error reading DDL from HANA server", e);
    }
    @Override
                    return "-- HANA trigger source not found";
    @Override
{
        GenericDataSource dataSource = sourceObject.getDataSource();
                "CALL get_object_definition(?,?)"))
                    + " TABLE_NAME, COLUMN_NAME, POSITION AS KEY_SEQ, CONSTRAINT_NAME AS PK_NAME, IS_PRIMARY_KEY" 
        return new HANADataSource(monitor, container, this);
 * distributed under the License is distributed on an "AS IS" BASIS,
        GenericDataSource dataSource = sourceObject.getDataSource();

                    + " TABLE_NAME, COLUMN_NAME, POSITION AS KEY_SEQ, CONSTRAINT_NAME AS PK_NAME, IS_PRIMARY_KEY" 
    }
    }
                    + " FROM SYS.CONSTRAINTS"
                pos.line = -1;

        		? DBSEntityConstraintType.PRIMARY_KEY : DBSEntityConstraintType.UNIQUE_KEY;
            return Collections.emptyList();
    @Override
        boolean notNull,
        return false;

    public HANASchema createSchemaImpl(@NotNull GenericDataSource dataSource, @Nullable GenericCatalog catalog, @NotNull String schemaName) {

        HANASchema publicSchema = new HANASchema(dataSource, catalog, HANAConstants.SCHEMA_PUBLIC);
import org.jkiss.dbeaver.model.impl.jdbc.JDBCConstants;
        }
                    if (ddl.length() > 0) {
                typeName, valueType, sourceType, ordinalPos, columnSize,
    
    @Override
        if (CommonUtils.isEmpty(name)) {
    }
    @NotNull
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read HANA view source")) {
                return result;
        // empty schemas are still shown, so hiding everything in system schemas looks strange
    public boolean isSystemSchema(GenericSchema schema) {
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType;
    @Override

import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
            {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
    public boolean isSchemasOptional() {
        return true;
            throw new DBDatabaseException(e, container.getDataSource());
                        // Format DDL
    
    @Override
        return false;
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
        int i;
            dbStat = session.prepareStatement("SELECT"
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
        String columnName,
    }
            dbStat = session.prepareStatement("SELECT"
    }
        }
        String name = JDBCUtils.safeGetString(dbResult, 1);

    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject, @NotNull Map<String, Object> options) throws DBException {
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
        if (CommonUtils.isEmpty(triggerName)) {
            if (schemas.get(i).getName().compareTo(HANAConstants.SCHEMA_PUBLIC) > 0)

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        }


                    }
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {
        for (i = 0; i < schemas.size(); i++)
                    if (dbResult.nextRow()) {
    
        String schemaName = schema.getName();
    @Override
    }
    public GenericProcedure createProcedureImpl(
            throw new DBDatabaseException(e, dataSource);
            String procedureType = sourceObject.getProcedureType().name();
                    if (dbResult.nextRow()) {
                    + " FROM SYS.CONSTRAINTS"
                    StringBuilder ddl = new StringBuilder();
        return dbStat;
                DBPErrorAssistant.ErrorPosition pos = new DBPErrorAssistant.ErrorPosition();
        long charLength,
                    return "-- HANA procedure source not found";
    public boolean supportsSynonyms(@NotNull GenericDataSource dataSource) {
        }
        return "GENERATED ALWAYS AS IDENTITY";
    @Override
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        if(table.getSchema().getName().equals("SYS") && table.isView()) {
 *
            schemaName.startsWith("HANA_") ||
        return true;
    @Override
        JDBCResultSet dbResult,
                "SELECT T.SUBJECT_TABLE_NAME AS OWNER, T.* FROM SYS.TRIGGERS T WHERE SUBJECT_TABLE_SCHEMA=?" + (table != null ? " AND SUBJECT_TABLE_NAME=?" : ""));
                    }
        String remarks,
                remarks, defaultValue, autoIncrement, autoGenerated);
                charLength, scale, precision, radix, notNull,
import java.util.regex.Pattern;
 * Copyright (C) 2010-2026 DBeaver Corp and others
        String targetObjectType = JDBCUtils.safeGetString(dbResult, 2);
    }
        return null;

        return schemaName.startsWith("_SYS_") ||
        } catch (SQLException e) {
                        return dbResult.getString(3);
    }
    @Override
    @Override
import org.jkiss.code.NotNull;
    @Override
            {
                dbStat.setString(1, sourceObject.getContainer().getName());
        return super.createTableImpl(session, owner, tableObject, dbResult);
    @Override
                    "WHERE SCHEMA_NAME = ? AND TRIGGER_NAME = ?"))
        return dbStat;
        @NotNull String procedureName,
                pos.position = Integer.parseInt(matcher.group(1)) - 1;
import java.util.List;
                }
    @Override
                    }
                        return dbResult.getString(3);
        //if (table.getSchema().getName().startsWith("_SYS_"))
 * DBeaver - Universal Database Manager
    ) throws DBException {
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
            }
        return new HANASynonym(container, name, targetObjectType, targetObjectSchema, targetObjectName);
import java.util.regex.Matcher;
                    }
                dbStat.setString(1, DBUtils.getQuotedIdentifier(sourceObject.getContainer()));
            schemaName.equals("SYS_DATABASES");
            dbStat.setString(1, owner.getName());
    
    @NotNull
}
            schemaName.equals("SYS") ||
    }
    }
                        String name = JDBCUtils.safeGetString(dbResult, 1);
        List<GenericSchema> schemas = super.loadSchemas(session, dataSource, catalog);
    @Nullable
        // throws exception if password or license expired

    @Override
    @NotNull
            return new HANATableColumn(table, columnName,
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read HANA table DDL")) {
    public List<GenericSchema> loadSchemas(
            try (JDBCPreparedStatement dbStat = session.prepareStatement("SELECT TRIGGER_NAME FROM SYS.TRIGGERS WHERE SUBJECT_TABLE_SCHEMA=? AND SUBJECT_TABLE_NAME=?")) {
        @NotNull JDBCSession session,
            }
 * You may obtain a copy of the License at
            return new HANAView(container, tableName, tableType, dbResult);
        return table.getName().startsWith("_SYS_");
                dbStat.setString(2, DBUtils.getQuotedIdentifier(sourceObject));
    public boolean isSystemTable(@NotNull GenericTableBase table) {
    @Override
        GenericDataSource dataSource = sourceObject.getDataSource();
            dbStat.setString(2, table.getName());
    }
                    + " WHERE SCHEMA_NAME=? "
                    + " ORDER BY PK_NAME");
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
    }
                    "FROM SYS.VIEWS\n" +
import java.util.Collections;
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
    }
                        return
                    "WHERE SCHEMA_NAME = ? AND " + procedureType + "_NAME = ?"))
 *     http://www.apache.org/licenses/LICENSE-2.0
import org.jkiss.dbeaver.ext.generic.model.*;
                    typeName, valueType, sourceType, ordinalPos, columnSize,
    @Override

        String name = JDBCUtils.safeGetString(dbResult, 1);
                            dbResult.getString(1);
    public GenericTableColumn createTableColumnImpl(
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
                dbStat.setString(2, table.getName());
import java.sql.SQLException;
                            "CREATE VIEW " + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL) + " AS\n" +
            schemaName.startsWith("SAP_") ||
        if (table == null) {

                "SELECT SCHEMA_NAME,"+ procedureType + "_NAME,DEFINITION FROM SYS."+ procedureType + "S\n" +
                dbStat.setString(2, sourceObject.getName());
        }
 * Unless required by applicable law or agreed to in writing, software
        @NotNull GenericStructContainer container,
            triggerName = JDBCUtils.safeGetString(resultSet, "TRIGGER_NAME");
        @NotNull GenericStructContainer container,
                "SELECT SCHEMA_NAME,TRIGGER_NAME,DEFINITION FROM SYS.TRIGGERS\n" +
        //    return true;
    @Override
import org.jkiss.code.Nullable;
                    + " ORDER BY TABLE_NAME,PK_NAME");
    public List<? extends GenericTrigger> loadTriggers(@NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws DBException {
    public DBPErrorAssistant.ErrorPosition getErrorPosition(@NotNull Throwable error) {
                        return SQLFormatUtils.formatSQL(sourceObject.getDataSource(), ddl.toString());
        boolean autoIncrement,
    }
    @Override
        @Nullable String tableName, @Nullable String tableType, @Nullable JDBCResultSet dbResult) {
                    + " WHERE SCHEMA_NAME=? AND TABLE_NAME=?"
    public GenericTableBase createTableOrViewImpl(
 * you may not use this file except in compliance with the License.
        return new GenericSequence(container, name, "", null, minValue, maxValue, incrementBy);
    public GenericSynonym createSynonymImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
            }
import org.jkiss.dbeaver.Log;
        Integer precision,
    }

import java.util.ArrayList;
        @Nullable GenericCatalog catalog
        Number maxValue = JDBCUtils.safeGetBigDecimal(dbResult, 3);
    private static Pattern ERROR_POSITION_PATTERN = Pattern.compile(" \\(at pos ([0-9]+)\\)");
        return true;
        @NotNull DBRProgressMonitor monitor,
    @NotNull
import org.jkiss.utils.CommonUtils;
    @Override
import org.jkiss.dbeaver.DBException;
package org.jkiss.dbeaver.ext.hana.model;
    @Override
    public HANAMetaModel() {
            "SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY FROM SYS.SEQUENCES WHERE SCHEMA_NAME = ? ORDER BY SEQUENCE_NAME");
                }
                    return "-- HANA view definition not found";

        Number incrementBy = JDBCUtils.safeGetBigDecimal(dbResult, 4);
        String remarks,
    }
    @Override
            throw new DBDatabaseException(e, dataSource);
    }
            return null;
        @NotNull GenericTableBase table,
        }
        JDBCPreparedStatement dbStat = session.prepareStatement(
/**
        }
    @Override

import org.jkiss.dbeaver.model.DBUtils;
 * limitations under the License.

    public String getAutoIncrementClause(GenericTableColumn column) {
    }
            try (JDBCPreparedStatement dbStat = session.prepareCall(
        }
            throw new DBDatabaseException(e, dataSource);
        return true;
            dbStat.setString(2, forParent.getName());
    public boolean supportsUniqueKeys() {

import org.jkiss.dbeaver.DBDatabaseException;
        }
                dbStat.setString(1, sourceObject.getContainer().getName());
            Matcher matcher = ERROR_POSITION_PATTERN.matcher(message);
        @NotNull DBSProcedureType procedureType,
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
                }

        String targetObjectName = JDBCUtils.safeGetString(dbResult, 4);
 *
        @NotNull GenericDataSource dataSource,
        String specificName,
            }
import org.jkiss.dbeaver.model.sql.format.SQLFormatUtils;
        return schemas;
    }
        String message = error.getMessage();
        return new HANATable(container, tableName, tableType, dbResult);

        dbStat.setString(1, container.getName());
        if (CommonUtils.isEmpty(name)) {

        }
 * Licensed under the Apache License, Version 2.0 (the "License");
                    }
        String tableType = GenericUtils.safeGetStringTrimmed(tableObject, dbResult, JDBCConstants.TABLE_TYPE);
import java.util.Map;

        JDBCPreparedStatement dbStat;
                }
                    while (dbResult.next()) {
    }
            return null;
    }
            dbStat.setString(1, forParent.getSchema().getName());
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    @NotNull
 * See the License for the specific language governing permissions and
                dbStat.setString(1, sourceObject.getContainer().getName());
        return super.getTableDDL(monitor, sourceObject, options);
        int radix,
        }
    @Override
                List<GenericTrigger> result = new ArrayList<>();
        } catch (SQLException e) {

                return pos;
                dbStat.setString(2, sourceObject.getName());
