    public HANASysViewColumn(GenericTable table) {
    public HANASysViewColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) throws DBException {
 * DBeaver - Universal Database Manager
 *     http://www.apache.org/licenses/LICENSE-2.0
    @Property(viewable = true, editable = true, order = 70)
 */
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
/*
    public String getUnit() 
    }
import org.jkiss.dbeaver.DBException;

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
}
    
 * Copyright (C) 2010-2024 DBeaver Corp and others
    }

package org.jkiss.dbeaver.ext.hana.model;
        super(table);
 * you may not use this file except in compliance with the License.
    {
 *
        return dataSource.getSysViewColumnUnit(getTable().getName(), getName());
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.ext.generic.model.GenericTable;
 * limitations under the License.
 *
public class HANASysViewColumn extends HANATableColumn {

    }
        HANADataSource dataSource = (HANADataSource) getTable().getDataSource();
 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.model.meta.Property;

 * You may obtain a copy of the License at
 * distributed under the License is distributed on an "AS IS" BASIS,
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
    
 * Licensed under the Apache License, Version 2.0 (the "License");
