        if (geometryInfo != null) {

        super(table);
        }
 * Licensed under the Apache License, Version 2.0 (the "License");
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
                    .prepareStatement("SELECT SRS_ID, DATA_TYPE_NAME FROM SYS.ST_GEOMETRY_COLUMNS "
                            gi.srid -= FLAT_EARTH_SRID_START;
    public HANATableColumn(GenericTable table) {
    }
        }
    }
    }
package org.jkiss.dbeaver.ext.hana.model;
    @Nullable
import org.jkiss.dbeaver.model.gis.GisAttribute;
                        // a flat earth. If the SRID is in such a range, we have to substract the SRID to find the
        } else {

 * You may obtain a copy of the License at
            return;

import org.jkiss.dbeaver.model.DBUtils;
 *
    private void readGeometryInfo(DBRProgressMonitor monitor) throws DBCException {
        geometryInfo = gi;
                    }
        }
                dbStat.setString(3, getName());
 * DBeaver - Universal Database Manager
	private static final int FLAT_EARTH_SRID_START = 1000000000;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    public String getAttributeGeometryType(DBRProgressMonitor monitor) throws DBCException {
        GeometryInfo gi = new GeometryInfo();
 * Copyright (C) 2010-2024 DBeaver Corp and others
import org.jkiss.dbeaver.model.DBPNamedObject2;
 *
            throw new DBCException("Error reading geometry info", e);
import org.jkiss.code.Nullable;
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    if (dbResult.next()) {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, this, "Load table inheritance info")) {
    public HANATableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) throws DBException {
            return null;


import org.jkiss.dbeaver.DBException;
 *     http://www.apache.org/licenses/LICENSE-2.0
                dbStat.setString(1, getTable().getSchema().getName());
        if (geometryInfo == null) {

                        }
    @Override
        }
import org.jkiss.dbeaver.model.exec.DBCException;
            readGeometryInfo(monitor);
            return geometryInfo.srid;
    public int getAttributeGeometrySRID(DBRProgressMonitor monitor) throws DBCException {

                        if ((FLAT_EARTH_SRID_START <= gi.srid) && (gi.srid < FLAT_EARTH_SRID_END)) {
    }

                        // HANA does not distinguish between geometry and geography type. Instead, HANA has additional
                }
                dbStat.setString(2, getTable().getName());
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * you may not use this file except in compliance with the License.
            readGeometryInfo(monitor);
    private static class GeometryInfo {
	private static final int FLAT_EARTH_SRID_END = 2000000000;
}
    }
 * See the License for the specific language governing permissions and
 * Unless required by applicable law or agreed to in writing, software
            try (JDBCPreparedStatement dbStat = session


                        gi.type = dbResult.getString(2);

import org.jkiss.dbeaver.ext.generic.model.GenericTable;
            return -1;
        } catch (SQLException e) {
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    @Override
import java.sql.SQLException;
        if (geometryInfo == null) {
        if (geometryInfo != null) {
        private int srid = -1;
 */
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
    private GeometryInfo geometryInfo;

        if (geometryInfo != null) {
                        gi.srid = dbResult.getInt(1);
                            + "WHERE SCHEMA_NAME=? AND TABLE_NAME=? AND COLUMN_NAME=?")) {
 * distributed under the License is distributed on an "AS IS" BASIS,

        }

public class HANATableColumn extends GenericTableColumn implements DBPNamedObject2, GisAttribute {
                        // actual SRID that works with leaflet.
                        // SRS's for round-earth spatial reference systems with an offset of 1,000,000,000 that emulate
        } else {
            }
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
        private String type;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
 *
        }
/*
    }
 * limitations under the License.
            return geometryInfo.type;
