    
    public List<HANAInplaceTableTypeColumn> getInplaceTableType(DBRProgressMonitor monitor) throws DBException {
    
    }
            int ordinalPosition, int columnSize, Integer scale, DBSProcedureParameterKind parameterKind,
        		0 /*precision*/, false /*notNull*/, null /*remarks*/, parameterKind);
    
 * Copyright (C) 2010-2024 DBeaver Corp and others
    @Association
 * Licensed under the Apache License, Version 2.0 (the "License");

    @Property(hidden = true)
 *
    public long getMaxLength() {
        return super.getScale();
    @Override
    }
 * limitations under the License.
    }
            return DBIcon.TREE_TABLE;
import java.util.List;
    @Override
import org.jkiss.dbeaver.model.DBPImage;

    public DBPImage getObjectImage() {
    // optional column in summary view and optional table in detail view with plugin.xml/visibleIf=...
import org.jkiss.dbeaver.model.struct.DBSObject;

 *
    }
import org.jkiss.dbeaver.model.meta.Property;
    public HANAProcedureParameter(GenericProcedure procedure, String columnName, String typeName, int typeId,
package org.jkiss.dbeaver.ext.hana.model;
 * See the License for the specific language governing permissions and
 * DBeaver - Universal Database Manager
    }
    private DBSObject tableType;
}
    
import org.jkiss.dbeaver.model.DBIcon;
    }
            DBSObject tableType, List<HANAInplaceTableTypeColumn> inplaceTableType, boolean hasDefaultValue) {
        		HANAProcedure.DATA_TYPE_NAME_ANY_TABLE_TYPE.equals(typeName))
    }
        return tableType;
        return super.getMaxLength();
    public Boolean hasInplaceTableType() {
        if (HANAProcedure.DATA_TYPE_NAME_TABLE_TYPE.equals(typeName) || 
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
            return true;
 * Unless required by applicable law or agreed to in writing, software
        return super.isRequired();
    @Property(viewable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 41)
import org.jkiss.dbeaver.DBException;
    @Property(viewable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 40)
/*
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
        super(procedure, columnName, typeName, typeId, ordinalPosition, columnSize, scale,
        return inplaceTableType;

    public Integer getScale() {
 *     http://www.apache.org/licenses/LICENSE-2.0
 * distributed under the License is distributed on an "AS IS" BASIS,
    @Override
    public DBSObject getTableType() {
    private List<HANAInplaceTableTypeColumn> inplaceTableType;
 * You may obtain a copy of the License at
    }
        this.inplaceTableType = inplaceTableType;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    @Property(viewable = true, order = 26, optional = true)
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameterKind;

 * you may not use this file except in compliance with the License.
    
        return null;
        if(inplaceTableType != null)
    @Override
    public boolean isRequired() {
        this.tableType = tableType;
import org.jkiss.dbeaver.model.meta.Association;

        this.autoGenerated = hasDefaultValue;
import org.jkiss.dbeaver.ext.generic.model.GenericProcedureParameter;
        return super.getObjectImage();
 *
    @Property(viewable = true, order = 25, optional = true)
import org.jkiss.dbeaver.ext.generic.model.GenericProcedure;


public class HANAProcedureParameter extends GenericProcedureParameter {
 */
