            useSeparateFkStatements.addSelectionListener(new SelectionAdapter() {
 *
 * distributed under the License is distributed on an "AS IS" BASIS,
            }
                    public void widgetSelected(SelectionEvent e) {
                useShowComments.addSelectionListener(new SelectionAdapter() {
        }
            }
                @Override

        if (button != null) {
}
    protected Composite createDialogArea(Composite parent) {
                    getDialogBoundsSettings().put(DBPScriptObject.OPTION_INCLUDE_COMMENTS, useShowFullDdl.getSelection());
                }
    private static final String PROP_USE_COMPACT_SQL = "GenerateSQL.compactSQL";
                    return Status.OK_STATUS;

            @Override
        for (Object object : sqlGenerator.getObjects()) {
                }
    protected void createButtonsForButtonBar(Composite parent) {
                    }
import org.jkiss.dbeaver.model.runtime.AbstractJob;
                public void widgetSelected(SelectionEvent e) {
 * you may not use this file except in compliance with the License.
        }
        sqlGenerator.setCompactSQL(getDialogBoundsSettings().get(PROP_USE_COMPACT_SQL) != null &&
    protected void buttonPressed(int buttonId) {
import org.eclipse.core.runtime.IStatus;
                        if (event.getResult() == Status.OK_STATUS) {
            final AbstractJob job = new AbstractJob("Refresh metadata for SQL Generator") { //$NON-NLS-1$
                    public void widgetSelected(SelectionEvent e) {
                        if (SQLGeneratorDialog.this.getShell() != null && !SQLGeneratorDialog.this.getShell().isDisposed()) {
            });
            @Override
                @Override
                public void widgetSelected(SelectionEvent e) {
                    getDialogBoundsSettings().put(PROP_EXCLUDE_AUTO_GENERATED_COLUMNS, excludeAutoGeneratedColumn.getSelection());


                getDialogBoundsSettings().getBoolean(DBPScriptObject.OPTION_INCLUDE_PERMISSIONS));
        }
                }

 * limitations under the License.
 *
                        }
        if (supportsPartitionsDDL) {
                sqlGenerator.isShowPartitionsDDL());
    }
                getDialogBoundsSettings().getBoolean(PROP_USE_SEPARATE_FK_STATEMENTS));
import org.jkiss.dbeaver.model.DBPScriptObject;
        createRefreshButton(parent);
                sqlGenerator.setFullyQualifiedNames(useFQNames.getSelection());

import org.eclipse.swt.layout.RowLayout;
                                    break;
                    startGenerateJob();
            }
        updateSQL();
                } catch (DBException e) {
import org.jkiss.utils.CommonUtils;
                        sqlGenerator.run(monitor);
import org.eclipse.swt.widgets.Button;
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
                public void done(IJobChangeEvent event) {
            }
                    SQLEditorMessages.sql_generator_dialog_button_show_cast_params,
            });
        return super.close();
package org.jkiss.dbeaver.ui.editors.sql.generator;
            };

 * You may obtain a copy of the License at
    
        }
                getDialogBoundsSettings().put(PROP_USE_FQ_NAMES, useFQNames.getSelection());
                protected IStatus run(@NotNull DBRProgressMonitor monitor) {
import org.eclipse.swt.events.SelectionAdapter;
        Button useCompactSQL = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_compact_sql, sqlGenerator.isCompactSQL());
import org.eclipse.swt.SWT;
            Button useCustomDateFormat = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_use_custom_data_format, sqlGenerator.isUseCustomDataFormat());
import org.jkiss.dbeaver.DBException;
                                monitor.worked(1);
                });
        if (sqlGenerator.isDMLOption()) {
                public void widgetSelected(SelectionEvent e) {
        sqlGenerator.setFullyQualifiedNames(getDialogBoundsSettings().get(PROP_USE_FQ_NAMES) == null ||
                    supportSeparateFKStatements = true;
                            }
    private static final String PROP_USE_CUSTOM_DATA_FORMAT = "GenerateSQL.useCustomDataFormat";
                if (supportPermissions && supportComments && supportFullDDL) {
        sqlGenerator.setShowFullDdl(getDialogBoundsSettings().get(DBPScriptObject.OPTION_INCLUDE_NESTED_OBJECTS) != null &&
                if (sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_DDL_ONLY_FOREIGN_KEYS) && 
                        startGenerateJob();
        super.createButtonsForButtonBar(parent);

                        }
 *
                        if (object instanceof DBSObject dbsObject) {
        Composite composite = super.createDialogArea(parent);
        }
import org.eclipse.ui.IWorkbenchPartSite;
                            if (button != null) {
            supportsCastParamsButton.addSelectionListener(new SelectionAdapter() {
import org.jkiss.code.NotNull;
        generateDDLJob.cancel();
                sqlGenerator.setCompactSQL(useCompactSQL.getSelection());
    }
                                log.error("Error refreshing object '" + dbsObject.getName() + "'", e); //$NON-NLS-1$ //$NON-NLS-2$
                    sqlGenerator.setShowFullDdl(useShowFullDdl.getSelection());
                    });
                        startGenerateJob();
                    }
                        sqlGenerator.setShowComments(useShowComments.getSelection());
        generateDDLJob.cancel();
        settings.setLayout(new RowLayout());
import org.jkiss.dbeaver.model.struct.DBSObject;
                    }
                    Object sql = sqlGenerator.getResult();
    @Override
    private void startGenerateJob() {
                            }
import org.jkiss.dbeaver.model.navigator.DBNUtils;
                }
    public boolean close() {
import org.jkiss.dbeaver.ui.UIUtils;
 * See the License for the specific language governing permissions and
    @Override
                }
            useCustomDateFormat.addSelectionListener(new SelectionAdapter() {

        boolean supportPermissions = false;

import org.jkiss.dbeaver.ui.editors.sql.dialogs.ViewSQLDialog;
import org.eclipse.jface.dialogs.IDialogConstants;
                            try {
                                updateSQL();
        sqlGenerator.setShowComments(getDialogBoundsSettings().get(DBPScriptObject.OPTION_INCLUDE_COMMENTS) != null &&
        sqlGenerator.setUseSeparateForeignKeys(getDialogBoundsSettings().get(PROP_USE_SEPARATE_FK_STATEMENTS) == null ||
                    return Status.error("Error running DDL generation", e);
    private static final Log log = Log.getLog(SQLGeneratorDialog.class);
                    getDialogBoundsSettings().put(DBPScriptObject.OPTION_INCLUDE_PARTITIONS, supportsPartitionsDDLButton.getSelection());
            NLS.bind(SQLEditorMessages.sql_generator_dialog_title, context.getDataSource().getContainer().getName()),
                        sqlGenerator.setShowPermissions(useShowPermissions.getSelection());
                    sqlGenerator.setShowCastParams(supportsCastParamsButton.getSelection());
                    sqlGenerator.setExcludeAutoGeneratedColumn(excludeAutoGeneratedColumn.getSelection());
        }
        boolean supportSeparateFKStatements = false;
            supportsPartitionsDDLButton.addSelectionListener(new SelectionAdapter() {
    }
                    }
        Composite settings = UIUtils.createTitledComposite(composite, "Settings", 5, GridData.FILL_HORIZONTAL, SWT.DEFAULT);
                        return Status.CANCEL_STATUS;
                @Override
                            } catch (Exception e) {
import org.eclipse.swt.events.SelectionEvent;
        Button useFQNames = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_use_fully_names, sqlGenerator.isFullyQualifiedNames());
                    startGenerateJob();
            job.schedule();
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            return composite;
 */
                getDialogBoundsSettings().getBoolean(DBPScriptObject.OPTION_INCLUDE_COMMENTS));
                getDialogBoundsSettings().getBoolean(PROP_USE_COMPACT_SQL));
            job.addJobChangeListener(new JobChangeAdapter() {
    private static final String PROP_EXCLUDE_AUTO_GENERATED_COLUMNS = "GenerateSQL.excludeAutoGeneratedColumn";
                    supportPermissions = true;
                    sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_DDL_SKIP_FOREIGN_KEYS)) { 
import org.jkiss.dbeaver.Log;
        sqlGenerator.setShowPermissions(getDialogBoundsSettings().get(DBPScriptObject.OPTION_INCLUDE_PERMISSIONS) != null &&
        useCompactSQL.addSelectionListener(new SelectionAdapter() {
import org.jkiss.dbeaver.model.navigator.DBNDatabaseNode;
    @Override
 *     http://www.apache.org/licenses/LICENSE-2.0
                            Button button = getButton(IDialogConstants.DETAILS_ID);
                if (sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_INCLUDE_NESTED_OBJECTS)) {
                    });
                        }
                @NotNull
class SQLGeneratorDialog extends ViewSQLDialog {
            if (supportComments) {
        Button button = getButton(IDialogConstants.DETAILS_ID);
                        }
import org.eclipse.core.runtime.Status;
                    getDialogBoundsSettings().put(PROP_USE_CUSTOM_DATA_FORMAT, useCustomDateFormat.getSelection());
    SQLGeneratorDialog(IWorkbenchPartSite parentSite, DBCExecutionContext context, SQLGenerator<?> sqlGenerator) {
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
                @Override
        useFQNames.addSelectionListener(new SelectionAdapter() {
                Button useShowComments = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_show_comments, sqlGenerator.isShowComments());
                }
            if (supportPermissions) {
                    supportFullDDL = true;
                startGenerateJob();
        });
                public void widgetSelected(SelectionEvent e) {
                    getDialogBoundsSettings().put(DBPScriptObject.OPTION_CAST_PARAMS, supportsCastParamsButton.getSelection());
                }
                    @Override
    }
        if (buttonId == IDialogConstants.RETRY_ID) {
                useShowPermissions.addSelectionListener(new SelectionAdapter() {
                        getDialogBoundsSettings().put(DBPScriptObject.OPTION_INCLUDE_PERMISSIONS, useShowPermissions.getSelection());
        
        boolean supportComments = false;
    private Job generateDDLJob;
                            if (sql != null) {
import org.eclipse.swt.layout.GridData;
                startGenerateJob();
                });
                settings,
                            }
        }
                }
                    for (Object object : sqlGenerator.getObjects()) {
import org.eclipse.core.runtime.jobs.IJobChangeEvent;
        if (supportFullDDL) {
            Button supportsCastParamsButton = UIUtils.createCheckbox(
                    supportsPartitionsDDL = true;
import org.eclipse.swt.widgets.Composite;
            @NotNull
                    sqlGenerator.isShowCastParams());
 * Copyright (C) 2010-2026 DBeaver Corp and others
                Button useShowPermissions = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_show_permissions, sqlGenerator.isIncludePermissions());
                }
            null, "");
            });
            }
        };
                getDialogBoundsSettings().getBoolean(PROP_EXCLUDE_AUTO_GENERATED_COLUMNS));
            useShowFullDdl.addSelectionListener(new SelectionAdapter() {
                SQLEditorMessages.sql_generator_dialog_button_show_partitions_DDL,

        boolean supportFullDDL = false;
import org.jkiss.dbeaver.model.sql.generator.SQLGenerator;
                    UIUtils.syncExec(() -> {

                public void widgetSelected(SelectionEvent e) {
        if (supportSeparateFKStatements) {
        boolean supportsPartitionsDDL = false;
                    startGenerateJob();
            });
    }
                }
                                if (monitor.isCanceled()) {
        super.buttonPressed(buttonId);
            button.setEnabled(false);
        if (!sqlGenerator.hasOptions()) {
                    getDialogBoundsSettings().put(DBPScriptObject.OPTION_DDL_SEPARATE_FOREIGN_KEYS_STATEMENTS, useSeparateFkStatements.getSelection());
                if (sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_INCLUDE_COMMENTS)) {
            Button excludeAutoGeneratedColumn = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_exclude_columns, sqlGenerator.isExcludeAutoGeneratedColumn());
import org.jkiss.dbeaver.ui.editors.sql.internal.SQLEditorMessages;
            protected IStatus run(@NotNull DBRProgressMonitor monitor) {
                    startGenerateJob();
                }
 * Licensed under the Apache License, Version 2.0 (the "License");
 * DBeaver - Universal Database Manager
                getDialogBoundsSettings().getBoolean(DBPScriptObject.OPTION_INCLUDE_NESTED_OBJECTS));
import org.eclipse.osgi.util.NLS;
                    break; //it supports everything
                getDialogBoundsSettings().getBoolean(PROP_USE_FQ_NAMES));
        return composite;
        sqlGenerator.setExcludeAutoGeneratedColumn(getDialogBoundsSettings().get(PROP_EXCLUDE_AUTO_GENERATED_COLUMNS) != null &&
                    DBExecUtils.tryExecuteRecover(monitor, getExecutionContext().getDataSource(), param -> {
    private static final String PROP_USE_SEPARATE_FK_STATEMENTS = "GenerateSQL.useSeparateFKStatements";
        }
                                }
                getDialogBoundsSettings().put(PROP_USE_COMPACT_SQL, useCompactSQL.getSelection());
                    startGenerateJob();
            if (object instanceof DBPScriptObjectExt2 sourceObject) {
            }
        super(parentSite, () -> context,
    private static final String PROP_USE_FQ_NAMES = "GenerateSQL.useFQNames";
            });

                    });
                    });
                    return Status.OK_STATUS;
                    UIUtils.syncExec(() -> {
import org.eclipse.core.runtime.jobs.Job;
            excludeAutoGeneratedColumn.addSelectionListener(new SelectionAdapter() {
                            startGenerateJob();
                                button.setEnabled(true);
                if (sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_INCLUDE_PARTITIONS)) {
        setSQLText("Loading DDL...");
        if (sqlGenerator.isInsertOption()) {
            @Override
    @Override
                    supportComments = true;
        if (sqlGenerator.isDDLOption()) {
import org.jkiss.dbeaver.model.DBPScriptObjectExt2;
        startGenerateJob();
                                setSQLText(CommonUtils.toString(sql));
                public void widgetSelected(SelectionEvent e) {
                @Override
                        if (SQLGeneratorDialog.this.getShell() != null && !SQLGeneratorDialog.this.getShell()
            Button useSeparateFkStatements = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_separate_fk_constraints_definition, sqlGenerator.isUseSeparateForeignKeys());
            public void widgetSelected(SelectionEvent e) {
        generateDDLJob = new AbstractJob("Generating DDL") {
                                DBNDatabaseNode dbnNode = DBNUtils.getNodeByObject(dbsObject);
                    settings,
                try {
                    sqlGenerator.setShowPartitionsDDL(supportsPartitionsDDLButton.getSelection());
            public void widgetSelected(SelectionEvent e) {
    private final SQLGenerator<?> sqlGenerator;
            Button useShowFullDdl = UIUtils.createCheckbox(settings, SQLEditorMessages.sql_generator_dialog_button_show_full_DDL, sqlGenerator.isShowFullDdl());
        });
                    UIUtils.syncExec(() -> {
                if (sourceObject.supportsObjectDefinitionOption(DBPScriptObject.OPTION_INCLUDE_PERMISSIONS)) {

                                dbnNode.refreshNode(monitor, object);
                            .isDisposed()) {
                    sqlGenerator.setUseCustomDataFormat(useCustomDateFormat.getSelection());
        this.sqlGenerator = sqlGenerator;
            });
                        getDialogBoundsSettings().put(DBPScriptObject.OPTION_INCLUDE_COMMENTS, useShowComments.getSelection());
                }
            Button supportsPartitionsDDLButton = UIUtils.createCheckbox(
                }
    @NotNull
        generateDDLJob.schedule();
                    if (monitor.isCanceled()) {
                }
/*
                    sqlGenerator.setUseSeparateForeignKeys(useSeparateFkStatements.getSelection());
            supportsCastParamsButton.setToolTipText(SQLEditorMessages.sql_generator_dialog_button_show_cast_params_tip);
                    monitor.done();
                    startGenerateJob();
import org.eclipse.core.runtime.jobs.JobChangeAdapter;
                            setSQLText("Error running DDL generation");
 * Unless required by applicable law or agreed to in writing, software
        }
                @Override
    }
        }
        if (sqlGenerator.supportCastParams()) {
                @Override
import org.jkiss.dbeaver.model.exec.DBExecUtils;

            });
        }
                }
                    @Override
