    @Override
        throws SQLException;
    JDBCDatabaseMetaData getMetaData()

    @NotNull

    @NotNull


    @NotNull

    JDBCCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
    JDBCStatement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
    @NotNull
    @Override
    @NotNull
    @NotNull

 *     http://www.apache.org/licenses/LICENSE-2.0
    JDBCPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
    @Override

    @Nullable
        throws SQLException;
    @NotNull

        throws SQLException;
 * Unless required by applicable law or agreed to in writing, software
    @Override
 * Copyright (C) 2010-2024 DBeaver Corp and others
 * limitations under the License.
public interface JDBCSession extends DBCSession, Connection {
    @NotNull
    JDBCExecutionContext getExecutionContext();
 * distributed under the License is distributed on an "AS IS" BASIS,
        throws SQLException;
    void setSchema(String schema) throws SQLException;

    @Override
    @NotNull
    @Override
    @Override
import java.sql.Connection;
        throws SQLException;
    @Override

    @Override
import org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext;
    @NotNull

    @NotNull

        throws SQLException;
 */
        boolean scrollable,
    JDBCPreparedStatement prepareStatement(String sql, String[] columnNames)
    ////////////////////////////////////////////////////////////////////////////


import java.sql.SQLException;


 *
 * DBeaver - Universal Database Manager
    @Override
        @NotNull String query,
    @Override
        @NotNull DBCStatementType type,
 *
 * you may not use this file except in compliance with the License.
    JDBCStatement prepareStatement(

import org.jkiss.dbeaver.model.exec.DBCException;
    JDBCPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
import org.jkiss.dbeaver.model.exec.DBCSession;
 */
        boolean returnGeneratedKeys) throws DBCException;
    @Override
    JDBCCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
    @NotNull
 * JDBC session
    JDBCCallableStatement prepareCall(String sql)
    JDBCPreparedStatement prepareStatement(String sql, int autoGeneratedKeys)

    void setBlockThread(Thread blockThread);
    Connection getOriginal()
import org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource;
    void abort(Executor executor) throws SQLException;
    JDBCPreparedStatement prepareStatement(String sql, int[] columnIndexes)
        throws SQLException;
    void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException;
    @NotNull
    @Override

        throws SQLException;
        throws SQLException;
import java.util.concurrent.Executor;

    JDBCPreparedStatement prepareStatement(String sql)

}
    @Override
 *
 * You may obtain a copy of the License at
 * See the License for the specific language governing permissions and
        throws SQLException;
        throws SQLException;
        throws SQLException;

/**
        throws SQLException;
package org.jkiss.dbeaver.model.exec.jdbc;
/*
    JDBCDataSource getDataSource();
    @Override
    @Override

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    // JDBC 1.7
    @Override

import org.jkiss.dbeaver.model.exec.DBCStatementType;
        boolean updatable,
    int getNetworkTimeout() throws SQLException;
    @NotNull
import org.jkiss.code.NotNull;

    JDBCStatement createStatement()

    @Override
    @NotNull
    String getSchema() throws SQLException;

import org.jkiss.code.Nullable;
 * Licensed under the Apache License, Version 2.0 (the "License");
    void close();
    @Override
