        return null;
    }
    public boolean isDisableUsingBatches() {
                        throw new InvocationTargetException(e);
public class DatabaseConsumerSettings implements IDataTransferConsumerSettings {

        if (mappingContainer.getTarget() == null && dialogSettings != null) {
    }
        containerNodePath = CommonUtils.toString(settings.get("container"), containerNodePath);
                return DBUtils.findDataSourceByObjectId(dataTransferSettings.getProject(), entityId);
        this.openNewConnections = openNewConnections;
        onDuplicateKeyInsertMethodId = CommonUtils.toString(settings.get("onDuplicateKeyMethod"), onDuplicateKeyInsertMethodId);

    }
        settings.put("openNewConnections", openNewConnections);
    public DatabaseConsumerSettings() {
    public void setUseBulkLoad(boolean useBulkLoad) {
    private boolean skipBindValues;
        loadObjectContainer(runnableContext, dataTransferSettings, null);
    }
                            DBNNode node = DBWorkbench.getPlatform().getNavigatorModel().getNodeByPath(monitor, containerNodePath);

    public boolean isUseTransactions() {
                        Map<String, Object> dmcSettings = (Map<String, Object>) mappings.get(DBUtils.getObjectFullId(sourceDatacontainer));
                    }
        return true;

    public void setOnDuplicateKeyInsertMethodId(String onDuplicateKeyInsertMethodId) {
        return ignoreDuplicateRows;
    }
                }
    private int multiRowInsertBatch = 500;
    }
        return onDuplicateKeyInsertMethodId;
        this.ignoreDuplicateRows = ignoreDuplicateRows;

        settings.put("disableReferentialIntegrity", disableReferentialIntegrity);
    public void setSkipBindValues(boolean skipBindValues) {
            DBSDataContainer sourceDatacontainer = dmc.getSource();
        }
    }
            }
        eventProcessors.remove(descriptor.getId());
                        container = DBUtils.getAdapter(DBSObjectContainer.class, dbObject);
                        DBSObject dbObject = producer.getDatabaseObject();
        // Load all data mappings
        // is used only for old tasks

        return disableUsingBatches;
    public boolean hasEventProcessor(@NotNull String id) {

        }
 * Copyright (C) 2010-2025 DBeaver Corp and others
    }
                    if (producer != null) {

    public boolean isOpenNewConnections() {

package org.jkiss.dbeaver.tools.transfer.database;
    public void setMultiRowInsertBatch(int multiRowInsertBatch) {

        return dataMappings;
        settings.put("truncateBeforeLoad", truncateBeforeLoad);
                DBSDataContainer sourceObject = (DBSDataContainer) pipe.getProducer().getDatabaseObject();
        for (String processor : processors.keySet()) {
            try {
    private final Map<String, Map<String, Object>> eventProcessors = new HashMap<>();
                DBWorkbench.getPlatformUI().showError(DTMessages.database_consumer_settings_title_init_connection,
        if (!eventProcessors.isEmpty()) {
    public void setOpenNewConnections(boolean openNewConnections) {
                            }
    }
                    mappingContainer.loadSettings(context, dmcSettings);
    public void setEnableQmLogging(boolean enableQmLogging) {
                    DTMessages.database_consumer_settings_message_error_connecting, e.getTargetException());

    @Override
        useTransactions = CommonUtils.getBoolean(settings.get("useTransactions"), useTransactions);
        final Map<String, Object> settings = dataTransferSettings.getNodeSettingsMap(dataTransferSettings.getConsumer());



import org.jkiss.dbeaver.model.DBPDataSourceContainer;
            // Load settings
                Map<String, Object> dmcSettings = (Map<String, Object>) mappings.get(DBUtils.getObjectFullId(dataContainer));
                    } catch (DBException e) {
    private String entityId;
    public void setIgnoreDuplicateRows(boolean ignoreDuplicateRows) {
        return skipBindValues;
                        }
    private transient Map<String, Object> dialogSettings;
        }
    public boolean isTransferAutoGeneratedColumns() {
import org.jkiss.dbeaver.tools.transfer.registry.DataTransferEventProcessorDescriptor;
    public boolean isCompleted(Collection<DataTransferPipe> pipes) {
    private static final Log log = Log.getLog(DatabaseConsumerSettings.class);
}
import org.jkiss.dbeaver.model.struct.DBSDataContainer;
        if (settings != null) {
            return null;
        if (container != null) {
        openNewConnections = CommonUtils.getBoolean(settings.get("openNewConnections"), openNewConnections);
import org.jkiss.dbeaver.DBException;
            } catch (InterruptedException e) {
        }
    }
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_skip_bind_values, skipBindValues);
        settings.put("multiRowInsertBatch", multiRowInsertBatch);
            checkContainerConnection(runnableContext);
import org.jkiss.utils.CommonUtils;
                            DBUtils.initDataSource(monitor, (DBPDataSourceContainer) container, null);
    public Map<String, Object> getEventProcessorSettings(@NotNull String id) {
import org.jkiss.dbeaver.model.DBPDataSource;
    }
        transferAutoGeneratedColumns = CommonUtils.getBoolean(settings.get("transferAutoGeneratedColumns"), transferAutoGeneratedColumns);
    }
    public void setUseTransactions(boolean useTransactions) {
                // ignore
        this.disableReferentialIntegrity = disableReferentialIntegrity;
    }

    }
        return dataMappings.get(dataContainer);
                if (containerMapping == null ||
        return eventProcessors.containsKey(id);

    }
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_use_bulk_load, useBulkLoad);
                            dmc.loadSettings(runnableContext, dmcSettings);
        return useTransactions;
import org.jkiss.dbeaver.model.navigator.DBNNode;
        skipBindValues = CommonUtils.getBoolean(settings.get("skipBindValues"), skipBindValues);


                        this.container = (DBSObjectContainer) targetObject.getParentObject();
            }
    }
    @Deprecated // entityId is used from database consumer
            }
    }
    private boolean disableUsingBatches = false;
        this.truncateBeforeLoad = truncateBeforeLoad;
        this.useMultiRowInsert = useMultiRowInsert;

                                dataMappings.put(sourceDC, dmc);
    public DBSObjectContainer getContainer() {
        if (container == null && (!CommonUtils.isEmpty(containerNodePath) || !CommonUtils.isEmpty(entityId) || producerContainer != null)) {
    public int getMultiRowInsertBatch() {
 * DBeaver - Universal Database Manager
            return container.getDataSource();
        disableReferentialIntegrity = CommonUtils.getBoolean(settings.get("disableReferentialIntegrity"), disableReferentialIntegrity);
    public void removeEventProcessor(@NotNull DataTransferEventProcessorDescriptor descriptor) {
        this.dialogSettings = settings;
            }



        }
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_use_multi_insert, useMultiRowInsert);
        if (useTransactions) {
        settings.put("commitAfterRows", commitAfterRows);
        this.useTransactions = useTransactions;
                settings.getState().addError(e.getTargetException());
        return transferAutoGeneratedColumns;
    }
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_use_transactions, useTransactions);
    }

                    monitor -> {


                        DBSObject dbObject = null;
                    if (sourceDatacontainer != null) {

    }
            final String entityId = CommonUtils.toString(settings.get("entityId"));

    public void setCommitAfterRows(int commitAfterRows) {
                            Map<String, Object> dmcSettings = (Map<String, Object>) mappings.get(DBUtils.getObjectFullId(dbObject));
        }
        enableQmLogging = CommonUtils.getBoolean(settings.get("enableQmLogging"), enableQmLogging);

        entityId = CommonUtils.toString(settings.get("entityId"), entityId);
    @Nullable
    }
        return openNewConnections;
import org.jkiss.dbeaver.tools.transfer.internal.DTMessages;
        if (container instanceof DBPDataSourceContainer && container.getDataSource() == null) {
            eventProcessors.put(processor, JSONUtils.getObject(processors, processor));
        }
    public void setTruncateBeforeLoad(boolean truncateBeforeLoad) {
    }
                    }
    @Override

 * Licensed under the Apache License, Version 2.0 (the "License");
    @Nullable

                            if (dmcSettings != null) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
import java.lang.reflect.InvocationTargetException;
            try {
                runnableContext.run(true, true,

    @NotNull
    }

    public Map<String, Map<String, Object>> getEventProcessors() {
 * limitations under the License.
    private boolean ignoreDuplicateRows;

    public void setContainer(DBSObjectContainer container) {
                    } else if (consumer.getTargetObjectContainer() instanceof DBSObjectContainer) {
import org.jkiss.dbeaver.model.runtime.DBRRunnableContext;
    private void checkContainerConnection(DBRRunnableContext runnableContext) {
 *
 *
    public void loadSettings(DBRRunnableContext runnableContext, DataTransferSettings dataTransferSettings, Map<String, Object> settings) {
    public void setOpenTableOnFinish(boolean openTableOnFinish) {
import org.jkiss.dbeaver.model.DBUtils;
        settings.put("openTableOnFinish", openTableOnFinish);
    private String onDuplicateKeyInsertMethodId;
        List<DataTransferPipe> dataPipes = dataTransferSettings.getDataPipes();
    public boolean isUseMultiRowInsert() {
                for (DataTransferPipe pipe : dataPipes) {
                    DBSDataContainer sourceDatacontainer = dmc.getSource();
        }
    public boolean isEnableQmLogging() {

                if (consumer instanceof DatabaseTransferConsumer) {
        DBSObjectContainer container = getContainer();
                // ignore
    public void addDataMappings(DBRRunnableContext context, DBSDataContainer dataContainer, DatabaseMappingContainer mappingContainer) {

    }
        eventProcessors.putIfAbsent(descriptor.getId(), new HashMap<>());
    @NotNull

    @Override
        dataMappings.put(dataContainer, mappingContainer);

    public boolean isDisableReferentialIntegrity() {


        return summary.toString();
        }

 * you may not use this file except in compliance with the License.
    private boolean transferAutoGeneratedColumns = true;
            }
        return disableReferentialIntegrity;

                        }
    public void setDisableReferentialIntegrity(boolean disableReferentialIntegrity) {
                Map<String, Object> dmcSettings = new LinkedHashMap<>();
 * DatabaseConsumerSettings
    }
    public DatabaseMappingContainer getDataMapping(DBSDataContainer dataContainer) {
                        }
        return eventProcessors;
import org.jkiss.dbeaver.model.struct.DBSObject;
        }
    public int getCommitAfterRows() {
        ignoreDuplicateRows = CommonUtils.getBoolean(settings.get("ignoreDuplicateRows"), ignoreDuplicateRows);
                checkContainerConnection(runnableContext);

    }
    }
    }
        this.multiRowInsertBatch = multiRowInsertBatch;

        openTableOnFinish = CommonUtils.getBoolean(settings.get("openTableOnFinish"), openTableOnFinish);
                }

    public void loadObjectContainer(DBRRunnableContext runnableContext, DataTransferSettings settings, @Nullable DBSObjectContainer producerContainer) {
    }
        this.enableQmLogging = enableQmLogging;

    private DBSObjectContainer container;
import org.jkiss.dbeaver.model.data.json.JSONUtils;
    }
        this.commitAfterRows = commitAfterRows;
    public Map<DBSDataContainer, DatabaseMappingContainer> getDataMappings() {
        settings.put("entityId", DBUtils.getObjectFullId(container));
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_truncate_before_load, truncateBeforeLoad);
        for (DatabaseMappingContainer dmc : dataMappings.values()) {
import java.util.*;
    }
    public void setUseMultiRowInsert(boolean useMultiRowInsert) {
 */


                                dbObject = ((DBNDatabaseNode) node).getObject();
 *
        settings.put("transferAutoGeneratedColumns", transferAutoGeneratedColumns);
                runnableContext.run(true, true, monitor -> {
import org.jkiss.dbeaver.model.struct.DBSDataManipulator;
 */
                if (dmcSettings != null) {
                                dmc.loadSettings(runnableContext, dmcSettings);
    public boolean isOpenTableOnFinish() {
    }
    public static DBPDataSourceContainer getDataSourceContainer(@NotNull DataTransferSettings dataTransferSettings) {
                }
        return useBulkLoad;
    }
    private boolean useBulkLoad = false;
                }
                    }
    @Override
                    if (targetObject != null && targetObject.getParentObject() instanceof DBSObjectContainer) {
/**
                for (DatabaseMappingContainer dmc : dataMappings.values()) {
                dmc.saveSettings(dmcSettings);
    public void setTransferAutoGeneratedColumns(boolean transferAutoGeneratedColumns) {
    @Nullable
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_multi_insert_batch, multiRowInsertBatch);
                        }
            }
        settings.put("mappings", mappings);
            } else if (!dataPipes.isEmpty()) {
                });
                            }
                        if (container == null) {
import org.jkiss.dbeaver.runtime.DBWorkbench;
                    });
        // Load mapping for current objects

/*
                            dbObject = DBUtils.findObjectById(monitor, settings.getProject(), entityId);
                        if (dmcSettings != null) {
            if (!dataPipes.isEmpty()) {
        settings.put("useTransactions", useTransactions);
        }
        truncateBeforeLoad = CommonUtils.getBoolean(settings.get("truncateBeforeLoad"), truncateBeforeLoad);
    public String getOnDuplicateKeyInsertMethodId() {
@SuppressWarnings("unchecked")
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_disable_batches, disableUsingBatches);
    private boolean useMultiRowInsert;
        settings.put("useMultiRowInsert", useMultiRowInsert);
import org.jkiss.code.Nullable;
    }
                        this.container = (DBSObjectContainer) consumer.getTargetObjectContainer();
    }
    }
        settings.put("enableQmLogging", enableQmLogging);

                    try {
                log.error("Error getting container node", e.getTargetException());

    }
        return commitAfterRows;
import org.jkiss.dbeaver.model.navigator.DBNDatabaseNode;
        DTUtils.addSummary(summary, DTMessages.data_transfer_wizard_output_checkbox_new_connection, openNewConnections);
    private boolean openTableOnFinish = true;
            } catch (InvocationTargetException e) {

        return multiRowInsertBatch;

                        if (dbObject instanceof DBSDataContainer sourceDC) {
        } else if (attrMapping.getTarget() != null) {
            }
import org.jkiss.dbeaver.model.struct.DBSObjectContainer;
        return useMultiRowInsert;
    }
    private boolean enableQmLogging;
import org.jkiss.dbeaver.tools.transfer.*;
                        } else if (!CommonUtils.isEmpty(containerNodePath)) {
 * Unless required by applicable law or agreed to in writing, software
            if (mappings != null) {
                        } catch (DBException e) {
        return truncateBeforeLoad;
            if (CommonUtils.isNotEmpty(entityId)) {
    @Override
        } else {
            } catch (InvocationTargetException e) {
        for (DataTransferPipe pipe : pipes) {
        settings.put("useBulkLoad", useBulkLoad);

                }
    private final Map<DBSDataContainer, DatabaseMappingContainer> dataMappings = new LinkedHashMap<>();

                        if (dbObject instanceof DBPDataSourceContainer) {

        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_ignore_duplicate_rows, ignoreDuplicateRows);
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_on_duplicate_key_method_label, onDuplicateKeyInsertMethodId);
            } catch (InterruptedException e) {
    public void setDisableUsingBatches(boolean disableUsingBatches) {
                            if (node instanceof DBNDatabaseNode) {
                IDataTransferConsumer<?, ?> consumer = dataPipes.get(0).getConsumer();
 * You may obtain a copy of the License at
    }
            }
        this.container = container;

                            container = producerContainer;
    }
    private int commitAfterRows = 10000;

    }
                mappings.put(DBUtils.getObjectFullId(sourceDatacontainer), dmcSettings);
    }
                        }
import org.jkiss.dbeaver.Log;
    public String getSettingsSummary() {
                            DBUtils.initDataSource(monitor, (DBPDataSourceContainer) dbObject, null);
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_transfer_auto_generated_columns, transferAutoGeneratedColumns);
                    containerMapping.getMappingType() == DatabaseMappingType.unspecified ||
        {

                        try {
    private boolean openNewConnections = true;
                    final DBSDataManipulator targetObject = ((DatabaseTransferConsumer) consumer).getTargetObject();
        StringBuilder summary = new StringBuilder();
    private boolean disableReferentialIntegrity;
    }
        settings.put("disableUsingBatches", disableUsingBatches);
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_disable_referential_integrity, disableReferentialIntegrity);
                    }
                    !containerMapping.isCompleted()) {
    private boolean useTransactions = true;
        multiRowInsertBatch = CommonUtils.toInt(settings.get("multiRowInsertBatch"), multiRowInsertBatch);
    public DBPDataSource getTargetDataSource(DatabaseMappingObject attrMapping) {
            if (sourceDatacontainer != null) {
            return attrMapping.getTarget().getDataSource();
    public void saveSettings(Map<String, Object> settings) {
        settings.put("onDuplicateKeyMethod", onDuplicateKeyInsertMethodId);
        this.transferAutoGeneratedColumns = transferAutoGeneratedColumns;
                DatabaseMappingContainer containerMapping = dataMappings.get(sourceObject);

 * distributed under the License is distributed on an "AS IS" BASIS,
        }
    public boolean isIgnoreDuplicateRows() {

        settings.put("skipBindValues", skipBindValues);
        return eventProcessors.computeIfAbsent(id, x -> new HashMap<>());

        this.openTableOnFinish = openTableOnFinish;

        final Map<String, Object> processors = JSONUtils.getObject(settings, "eventProcessors");
    }
    private boolean truncateBeforeLoad = false;
        this.useBulkLoad = useBulkLoad;

    public boolean isUseBulkLoad() {
        settings.put("ignoreDuplicateRows", ignoreDuplicateRows);
        return container;
        disableUsingBatches = CommonUtils.getBoolean(settings.get("disableUsingBatches"), disableUsingBatches);
import org.jkiss.code.NotNull;
        Map<String, Object> mappings = (Map<String, Object>) settings.get("mappings");
            Map<String, Object> mappings = (Map<String, Object>) dialogSettings.get("mappings");

        this.skipBindValues = skipBindValues;
        // then we need to check connection
    private String containerNodePath;

 * See the License for the specific language governing permissions and
    }
    public boolean isSkipBindValues() {

                        if (!CommonUtils.isEmpty(entityId)) {
        useMultiRowInsert = CommonUtils.getBoolean(settings.get("useMultiRowInsert"), useMultiRowInsert);
        this.disableUsingBatches = disableUsingBatches;
                            throw new InvocationTargetException(e);
    }

            settings.put("eventProcessors", eventProcessors);
            if (pipe.getProducer() != null) {
        commitAfterRows = CommonUtils.toInt(settings.get("commitAfterRows"), commitAfterRows);
            if (!dataMappings.isEmpty()) {
        useBulkLoad = CommonUtils.getBoolean(settings.get("useBulkLoad"), useBulkLoad);
        DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_enable_qm_logging, enableQmLogging);
    }
 *     http://www.apache.org/licenses/LICENSE-2.0

                    return false;
    public void addEventProcessor(@NotNull DataTransferEventProcessorDescriptor descriptor) {
            DTUtils.addSummary(summary, DTMessages.database_consumer_settings_option_commit_after, commitAfterRows);
    }
        if (mappings != null) {
        return enableQmLogging;
                                DatabaseMappingContainer dmc = new DatabaseMappingContainer(this, sourceDC);
    }
        Map<String, Object> mappings = new LinkedHashMap<>();
                    IDataTransferProducer producer = pipe.getProducer();

                        }
        return openTableOnFinish;
    public boolean isTruncateBeforeLoad() {
        this.onDuplicateKeyInsertMethodId = onDuplicateKeyInsertMethodId;
        // If container node is datasource (this may happen if datasource do not support schemas/catalogs)
