        return SQLiteUtils.readMasterDefinition(monitor, trigger, SQLiteObjectType.trigger, trigger.getName(), (GenericTableBase) trigger.getParentObject());
        return new GenericTableTrigger(genericTableBase, triggerName, null);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
            return new SQLiteView(container, tableName, tableType, dbResult);
    @Override
            + (forParent != null ? " AND tbl_name=?" : ""));
                ) AS TABLES
            return null;
            JDBCUtils.queryString(session, "SELECT 1 FROM " + getFullyQualifiedName(container, "sqlite_sequence"));
        return table.getName().startsWith("sqlite_");
        }
        @NotNull DBRProgressMonitor monitor,
    @NotNull
 * limitations under the License.
                WHERE
 */
                }
import org.jkiss.dbeaver.model.struct.DBSEntityReferrer;
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
    @Override
                NULL AS TABLE_SCHEM,
                UNION ALL
        String columnName,
    }
    }
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger trigger) throws DBException {
    @Override
        return value;
        boolean autoGenerated
    }
    }
        long charLength,
            return new SQLiteTable(container, tableName, tableType, dbResult);
import org.jkiss.dbeaver.model.DBUtils;
        boolean autoIncrement,
        if (CommonUtils.isEmpty(name)) {
            sql += "WHERE TABLE_NAME = ?";
    public GenericTrigger createTableTriggerImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer genericStructContainer, @NotNull GenericTableBase genericTableBase, String triggerName, @NotNull JDBCResultSet resultSet) throws DBException {
        return true;
import java.util.ArrayList;

                    'sqlite_schema' AS NAME,
    }
            """;
        try {
                SELECT
    public GenericTableColumn createTableColumnImpl(
import java.sql.SQLException;
    ) {
        return table.getName().startsWith("sqlite_autoindex_");
        return false;
    }

    @Override
        return null;
            return new QueryTransformerLimit(false);
    public DBCQueryTransformer createQueryTransformer(@NotNull DBCQueryTransformType type) {
        }
        }
            typeName = matcher.group(1);
        return true;

        }
import org.jkiss.code.Nullable;
                    NAME,
        Integer scale,
    @NotNull
    @Override

        }
        return session.prepareStatement("SELECT * FROM "  + getFullyQualifiedName(container, "sqlite_sequence"));
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

                TABLES.NAME AS TABLE_NAME,
                UNION ALL
                WHERE
        String defaultValue,
    @Override
            SELECT
        if (forParent != null) {
                NULL AS REMARKS,

import org.jkiss.dbeaver.model.DBPDataSourceContainer;
                JDBCPreparedStatement dbStat = session.prepareStatement(
    public GenericSequence createSequenceImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
            }
import org.jkiss.dbeaver.model.exec.DBCQueryTransformType;
    }
        JDBCPreparedStatement dbStat = session.prepareStatement("SELECT name as TRIGGER_NAME, tbl_name as OWNER FROM "
            log.debug("Error loading SQLite sequences.", error);
    public SQLiteDataTypeCache createDataTypeCache(@NotNull GenericStructContainer container) {
    }
        return "ANY"; //$NON-NLS-1$
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;

                    NAME NOT LIKE 'sqlite\\_%' ESCAPE '\\'


    @NotNull
                    NAME,
            columnSize = charLength = -1;
        if (object != null || objectName != null) {

        return dbStat;
        String sql = """
                SELECT
                NULL AS REF_GENERATION,
    public JDBCStatement prepareTableLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase object, @Nullable String objectName) throws SQLException {
        boolean notNull,
/*


        }
import org.jkiss.dbeaver.model.struct.rdb.DBSForeignKeyModifyRule;
        // Check for type length modifier
            columnSize = charLength = Integer.parseInt(matcher.group(2));
                NULL AS TYPE_CAT,
        } else {
    @Override
    protected String getDefaultTypeName() {
import org.jkiss.dbeaver.model.exec.DBCQueryTransformer;
                        "sqlite_master") + " WHERE type='trigger' AND tbl_name=?")
            return super.prepareTableLoadStatement(session, owner, object, objectName);


                        String name = JDBCUtils.safeGetString(dbResult, 1);
    public String getAutoIncrementClause(GenericTableColumn column) {
                LEFT OUTER JOIN pragma_table_list AS INFOS
                NULL AS TABLE_CAT,

 * See the License for the specific language governing permissions and
    }

                    sqlite_schema
        if (column.isAutoIncrement()) {
                SELECT
 * DBeaver - Universal Database Manager
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
        }

        }
                    }

        if (type == DBCQueryTransformType.RESULT_SET_LIMIT) {

    }
        return new SQLiteTableForeignKey(table, name, remarks, referencedKey, deleteRule, updateRule, deferability, persisted);
        Integer precision,
        }
    }

                    NAME LIKE 'sqlite\\_%' ESCAPE '\\'
                        result.add(new GenericTableTrigger(table, name, null));

            throw new SQLException("Error loading SQLite sequences. Probably sqlite_sequence info table doesn't exist yet. Please create table with AUTOINCREMENT column first.", e);
                    'SYSTEM TABLE' AS TYPE
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
        String indexesDDL = SQLiteUtils.readMasterDefinition(monitor, sourceObject, SQLiteObjectType.index, null, sourceObject);
    }
    public boolean supportsDatabaseTriggers(@NotNull GenericDataSource dataSource) {
            + getFullyQualifiedName(genericStructContainer, "sqlite_master") + " WHERE type='trigger'"
 *
        int ordinalPos,
    @Override
        if (tableType != null && isView(tableType)) {
    public GenericTableForeignKey createTableForeignKeyImpl(@NotNull GenericTableBase table, String name, @Nullable String remarks, DBSEntityReferrer referencedKey, DBSForeignKeyModifyRule deleteRule, DBSForeignKeyModifyRule updateRule, DBSForeignKeyDeferability deferability, boolean persisted) {
                FROM
                dbStat.setString(1, table.getName());
                return result;

        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
                    ON INFOS.NAME = TABLES.NAME
 *
        }
            dbStat.setString(1, forParent.getName());
        return tableDDL + "\n" + indexesDDL;
                    'SYSTEM TABLE' AS TYPE
                    sqlite_temp_master


        int radix,
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
        return new GenericSequence(container, name, null, value, 0, Long.MAX_VALUE, 1);
    @Override
    @Override
                NULL AS TYPE_NAME,

        if (!(session.getDataSource() instanceof SQLiteDataSource dataSource) || ! dataSource.supportsStrictTyping()) {
        } catch (SQLException e) {
import java.util.List;
    public JDBCStatement prepareSequencesLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    public boolean isUtilityTable(@NotNull GenericTableBase table) {

import org.jkiss.utils.CommonUtils;
            return tableDDL;
/**
        }
import org.jkiss.dbeaver.model.exec.DBCQueryTransformProvider;
        String typeName,
                NULL AS TYPE_SCHEM,
import java.util.Collections;
        String tableDDL = SQLiteUtils.readMasterDefinition(monitor, sourceObject, SQLiteObjectType.table, sourceObject.getName(), sourceObject);
        String remarks,
    @Override
        return SQLiteUtils.readMasterDefinition(monitor, sourceObject, SQLiteObjectType.view, sourceObject.getName(), sourceObject);
    @Override
    }
            try (
    @Override
        long value = JDBCUtils.safeGetLong(dbResult, 2);

    @Override
        String name = JDBCUtils.safeGetString(dbResult, 1);
                List<GenericTrigger> result = new ArrayList<>();
        if (CommonUtils.isEmpty(triggerName)) {

import java.util.Map;
 * SQLiteMetaModel
        // Autoindex tables - are some kind of index tables? No information about them. But they broke our ERD diagrams.

import org.jkiss.dbeaver.DBException;
    @Override
    @NotNull
                UNION ALL
    private static final Pattern TYPE_WITH_LENGTH_PATTERN = Pattern.compile("(.+)\\s*\\(([0-9]+)\\)");
}
                    UPPER(TYPE) AS TYPE
        return false;
    @NotNull
    }
            return Collections.emptyList();
    public boolean handleSequenceCacheReadingError(Exception error) {
    private static final Log log = Log.getLog(SQLiteMetaModel.class);
        if (object == null && objectName == null) {
        if (CommonUtils.isEmpty(indexesDDL)) {
    public SQLiteMetaModel() {
 * You may obtain a copy of the License at
        }
        int sourceType,
    @Override
        return dbStat;
                    "SELECT name FROM " + getFullyQualifiedName(container,
    }
    @Override
    @Override
                TABLES.TYPE AS TABLE_TYPE,
        if (error.getCause() instanceof SQLException) {
 * Copyright (C) 2010-2026 DBeaver Corp and others
                    NAME,
    @NotNull
        return null;
            return true;
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
import java.util.regex.Pattern;
        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
        Matcher matcher = TYPE_WITH_LENGTH_PATTERN.matcher(typeName);
        int valueType,
        }
        } else {
    }
            throw new DBDatabaseException(e, container.getDataSource());
        super();
        return new SQLiteDataTypeCache(container);
                NULL AS SELF_REFERENCING_COL_NAME,
                FROM

                    while (dbResult.next()) {
 * you may not use this file except in compliance with the License.
                    AND UPPER(TYPE) IN ('TABLE', 'VIEW')
    public boolean hasProcedureSupport() {
 * Unless required by applicable law or agreed to in writing, software
            sql += "ORDER BY TABLE_TYPE, TABLE_NAME";
            return "PRIMARY KEY AUTOINCREMENT";
    }
    @Override
        } catch (SQLException e) {
        } else {
    @Override
            triggerName = JDBCUtils.safeGetString(resultSet, 1);
import org.jkiss.dbeaver.DBDatabaseException;
        @NotNull GenericTableBase table,
        return false;
            FROM
    }
import org.jkiss.dbeaver.ext.sqlite.SQLiteUtils;
import java.util.regex.Matcher;
    @Override
    @Override
        if (table == null) {
        }
        // The sqlite_sequence table is created and initialized automatically whenever a normal table that contains an AUTOINCREMENT column is created. Not earlier
    @NotNull
    public List<? extends GenericTrigger> loadTriggers(@NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws DBException {
    public boolean isSystemTable(@NotNull GenericTableBase table) {
    }
        JDBCResultSet dbResult,
 * Licensed under the Apache License, Version 2.0 (the "License");
 * distributed under the License is distributed on an "AS IS" BASIS,
    }
    }
        return new SQLiteTableColumn(table, columnName, typeName, valueType, sourceType, ordinalPos, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
 *     http://www.apache.org/licenses/LICENSE-2.0
package org.jkiss.dbeaver.ext.sqlite.model;
            dbStat.setString(1, (object != null ? object.getName() : objectName));
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.struct.rdb.DBSForeignKeyDeferability;
    }
    }
        return false;

                    'GLOBAL TEMPORARY' AS TYPE
    }
    @Override
        }
    }
        long columnSize,
    protected String getFullyQualifiedName(@NotNull GenericStructContainer genericStructContainer, String value) {



                (
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {
                    sqlite_schema
    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, @Nullable String tableName, @Nullable String tableType, @Nullable JDBCResultSet dbResult) {
import org.jkiss.dbeaver.Log;
        if (matcher.matches()) {
    }
import org.jkiss.dbeaver.model.impl.sql.QueryTransformerLimit;

        return new SQLiteDataSource(monitor, container, this);
    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject, @NotNull Map<String, Object> options) throws DBException {
    public JDBCStatement prepareTableTriggersLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer genericStructContainer, @Nullable GenericTableBase forParent) throws SQLException {
    }
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
 */
import org.jkiss.code.NotNull;
    @Override
 *
            ) {
    @Nullable

        // Let's hide these "tables" deeper.
public class SQLiteMetaModel extends GenericMetaModel implements DBCQueryTransformProvider {
                SELECT
    public boolean supportsTableDDLSplit(@NotNull GenericTableBase sourceObject) {
                INFOS.STRICT AS STRICT
                FROM
import org.jkiss.dbeaver.ext.generic.model.*;
