public class FireBirdTableColumn extends GenericTableColumn implements DBPNamedObject2, DBSTypedObjectExt4<FireBirdDataType> {
    }
 */
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt4;
    @Property(viewable = true, editable = true, updatable = true, order = 40)
 * Copyright (C) 2010-2025 DBeaver Corp and others
        return super.getDefaultValue();
    @Override
}
    @Property(order = 21)
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    @Override
        if (table instanceof FireBirdTableBase) {
        return null;
        super(table);
        } else {
        if (dataType != null) {
    @Override
    }
import org.jkiss.code.NotNull;
    private String computedDefinition;
    @Property(order = 22, viewable = true)

    private FireBirdDataType dataType;
        }

                    dbStat.setString(2, getName());
 * You may obtain a copy of the License at
    public FireBirdTableColumn(GenericTableBase table) {
    public String getComputedDefinition(@NotNull DBRProgressMonitor monitor) throws DBException {
import org.jkiss.dbeaver.model.meta.PropertyLength;
    {
        return super.getDescription();
 * DBeaver - Universal Database Manager

    }
    @Property(viewable = true, editable = true, updatable = true, length = PropertyLength.MULTILINE, order = 100)
import org.jkiss.dbeaver.model.DBUtils;
    public long getMaxLength() {
    @Property(viewable = true, editable = true, order = 52, visibleIf = FireBirdColumnIncrementValueValidator.class)
 *
    @Override
    }
                        } else {
        return dataType == null ? super.getDataKind() : dataType.getDataKind();
    @Override
    public void setComputedDefinition(@Nullable String computedDefinition) {
            dataType = (FireBirdDataType) table.getDataSource().getLocalDataType(domainTypeName);
    }
    public GenericTableBase getTable() {

                try (JDBCPreparedStatement dbStat = session.prepareStatement(
import org.jkiss.dbeaver.model.DBPDataKind;
    @Nullable
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
                            computedDefinition = CommonUtils.notEmpty(JDBCUtils.safeGetString(dbComputedResult, "COMPUTED_SOURCE"));
import org.jkiss.dbeaver.DBException;
 *

    }
            dataType = (FireBirdDataType) table.getDataSource().getLocalDataType(typeName);
 *
                        if (dbComputedResult.next()) {
    }
    }
        this.dataType = dataType;


        return computedDefinition;
                    "SELECT F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE FROM RDB$RELATION_FIELDS RF,RDB$FIELDS F\n" +
    }
 * Licensed under the Apache License, Version 2.0 (the "License");
    public String getDefaultValue()
import org.jkiss.code.Nullable;
    public boolean isAutoIncrement() {
    public String getCharset() {

    @Property(viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
        }


    @NotNull
        GenericTableBase table = getTable();
    {
    public boolean isAutoGenerated() {
    public String getTypeName()
        if (computedDefinition == null && isAutoGenerated()) {
                        "WHERE RF.RDB$RELATION_NAME = ? AND RF.RDB$FIELD_NAME = ? AND RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME"
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
    }
        this.typeName = dataType.getTypeName();
        return super.isAutoGenerated();
                            computedDefinition = "";
                    dbStat.setString(1, getTable().getName());
            return ((FireBirdTableBase)table).getColumnDomainType(monitor, this);
        public boolean isValidValue(@NotNull FireBirdTableColumn column, @Nullable Object value) throws IllegalArgumentException {
                )) {
        @Override
    }
 * Unless required by applicable law or agreed to in writing, software

    }
                }
import org.jkiss.utils.CommonUtils;
 * you may not use this file except in compliance with the License.
 * limitations under the License.
        return null;


                } catch (SQLException e) {
    @Override

    public String getDomainTypeName(DBRProgressMonitor monitor) throws DBException {
            return dataType.getCharsetName();
    @Property(viewable = true, editable = true, updatableExpr = "object.table.dataSource.isServerVersionAtLeast(2, 5)", order = 75)

    {
                    try (JDBCResultSet dbComputedResult = dbStat.executeQuery()) {
    @Property(viewable = true, editable = true, updatable = true, order = 70)
        return super.getTable();

        return super.getMaxLength();
import org.jkiss.dbeaver.model.meta.Property;
package org.jkiss.dbeaver.ext.firebird.model;
        }
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
        String domainTypeName = getDomainTypeName(monitor);
    public String getComputedDefinition() {
                        // Generated columns are columns that either are computed or identity.
                    throw new DBException("Error reading computed definition", e);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
        return super.isAutoIncrement();
import java.sql.SQLException;
                        // If it's the identity columns indeed, the result set will be empty
    @Override
    @Override
    @Nullable
import org.jkiss.dbeaver.model.DBPNamedObject2;
        if (domainTypeName != null) {
        return computedDefinition;
 *     http://www.apache.org/licenses/LICENSE-2.0
            }
    @Nullable
            return column.getDataSource().isServerVersionAtLeast(3, 0);
    public DBPDataKind getDataKind() {
        }
    }
        }
                        }
    public void setDataType(@NotNull FireBirdDataType dataType) {
/*
    public FireBirdTableColumn(DBRProgressMonitor monitor, JDBCResultSet dbResult, GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) throws DBException {
    }

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        this.computedDefinition = computedDefinition;
    }
                    }

            try (JDBCSession session = DBUtils.openMetaSession(monitor, getTable(), "Load computed definition")) {
import org.jkiss.dbeaver.model.meta.IPropertyValueValidator;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    public String getDescription()

    @NotNull

import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;

    }
    public static class FireBirdColumnIncrementValueValidator implements IPropertyValueValidator<FireBirdTableColumn, Object> {
    }
    @Override
        return super.getTypeName();
