        try {
        int type = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_TYPE");
import org.jkiss.utils.CommonUtils;
                "RC.RDB$RELATION_NAME TABLE_NAME," +
        if (hasIdentityColumns(session)) {
            "F.RDB$COMPUTED_BLR AS COMPUTED_BLR,\n" +
    public GenericTableColumn createTableColumnImpl(@NotNull DBRProgressMonitor monitor, JDBCResultSet dbResult, @NotNull GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPos, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) throws DBException {
    @NotNull

                            sequence,
        if (object != null || objectName != null) {
            triggerName = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$TRIGGER_NAME");
    private static int getRelationType(@NotNull JDBCResultSet dbResult) {
                            description,
import java.sql.SQLException;
    }
        return new FireBirdTable(
                List<GenericTrigger> result = new ArrayList<>();
    public boolean supportsUniqueKeys() {
        @NotNull GenericStructContainer container,
                "RC.RDB$CONSTRAINT_NAME as PK_NAME," +
        boolean isSystem = true;
        }
    }
 *
                    "WHERE RDB$RELATION_NAME" + (table == null ? " IS NULL" : "=?"))) {
    @Override
            "cast(RF.RDB$RELATION_NAME as varchar(" + OBJECT_NAME_LENGTH + ")) AS TABLE_NAME,\n" +

        return dbStat;
        int sequence = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_SEQUENCE");
    @Override

    }
                "CAST(NULL AS VARCHAR(10)) AS JB_IDENTITY_TYPE\n" +
        GenericTableBase table;
            tableType,
    }
    public List<GenericTrigger> loadTriggers(@NotNull DBRProgressMonitor monitor, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws DBException {
                "FROM RDB$RELATION_FIELDS RF,RDB$FIELDS F");
        String message = error.getMessage();
                DBPErrorAssistant.ErrorPosition pos = new DBPErrorAssistant.ErrorPosition();
    @Override
 * You may obtain a copy of the License at

            return new FireBirdView(

    @Override

    }
                            FireBirdTriggerType.getByType(type),

        return new FireBirdProcedure(container, procedureName, specificName, remarks, procedureType, functionResultType);
        if (CommonUtils.isEmpty(triggerName)) {
 * Copyright (C) 2010-2026 DBeaver Corp and others
            return CommonUtils.toInt(odsVersion) > 12;
        boolean isSystem = JDBCUtils.safeGetInt(dbResult, "RDB$SYSTEM_FLAG") != 0;
            return false;
public class FireBirdMetaModel extends GenericMetaModel
                "RDB$RELATION_CONSTRAINTS RC " +
                default:
    }
        if (relType == 1) {
                case 4:
import org.jkiss.dbeaver.DBException;
import java.util.regex.Matcher;
        }
                        String name = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$TRIGGER_NAME");
    public JDBCStatement prepareContainerTriggersLoadStatement(@NotNull JDBCSession session, @Nullable GenericStructContainer forParent) throws SQLException {
    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, @Nullable String tableName, @Nullable String tableType, @Nullable JDBCResultSet dbResult) {
                        "WHERE RDB$RELATION_NAME" + (table == null ? " IS NOT NULL" : "=?"));
                        }
        JDBCPreparedStatement dbStat = session.prepareStatement(
    }
            String tableType;
 * Licensed under the Apache License, Version 2.0 (the "License");
            sql += "\nORDER BY RDB$RELATION_NAME";
        boolean isSystem = systemFlag > 0; // System flag value 0 - if user-defined and 1 or more if system
        if (systemFlag == 0) { // System flag value 0 - if user-defined and 1 or more if system
                        int systemFlag = JDBCUtils.safeGetInt(dbResult, "RDB$SYSTEM_FLAG");

        }
    @Override
            return null;
            charLength, scale, precision, radix, notNull,
    }
        }
        sql.append("\nORDER BY RF.RDB$RELATION_NAME, RF.RDB$FIELD_POSITION");
        } else {
            "F.RDB$FIELD_TYPE AS DATA_TYPE,\n" +

import org.jkiss.dbeaver.ext.firebird.FireBirdUtils;
    }
            tableName,
                pos.line = Integer.parseInt(matcher.group(1)) - 1;
 * limitations under the License.
    @Override
        }
        } else {
        int systemFlag = JDBCUtils.safeGetInt(dbResult, "RDB$SYSTEM_FLAG");
                    container,
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
 * Unless required by applicable law or agreed to in writing, software
                return result;
 * FireBirdDataSource
            "select " +
    public FireBirdMetaModel() {
                    break;
                "where RC.RDB$CONSTRAINT_TYPE IN ('PRIMARY KEY','UNIQUE') " +
                sequence,
                        String description = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$DESCRIPTION");
        try {
            1,

    @Override
                "ORDER BY ISGMT.RDB$FIELD_NAME ");
        return table;
        @NotNull
    }
        return new FireBirdDataTypeCache(container);
                (forParent == null ? "" : "AND RC.RDB$RELATION_NAME = '" + forParent.getName()) + "' " +

        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
    public boolean isSystemTable(@NotNull GenericTableBase table) {
    public GenericProcedure createProcedureImpl(
    @Override
        } catch (SQLException e) {
        String description = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$DESCRIPTION");
                "INNER JOIN RDB$INDEX_SEGMENTS ISGMT ON RC.RDB$INDEX_NAME = ISGMT.RDB$INDEX_NAME " +

    public String getProcedureDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericProcedure sourceObject) throws DBException {
                    tableType = "TRANSACTION-LEVEL GTT";
        return true;
    // Copied from Jaybird sources
    public boolean isTrimObjectNames() {
            }
                }
/*
    public JDBCStatement prepareTableColumnLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase forTable) throws SQLException {
    @Override

    @NotNull
    @Override
            "RF.RDB$FIELD_POSITION + 1 AS FIELD_POSITION,\n" +
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
        tableName = tableName.toUpperCase(Locale.ENGLISH);

    @Override
                case 5:
                        int sequence = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_SEQUENCE");
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;
        return new FireBirdTableTrigger(
import org.jkiss.dbeaver.ext.generic.model.*;
        DBSProcedureType procedureType,
            dbStat.setString(1, (object != null ? object.getName() : objectName));
    }
            container,
    @Override
    @Override
            DatabaseMetaData metaData = session.getOriginal().getMetaData();
 */
            dbStat.setString(1, forTable.getName());
        if (forTable != null) {
                description,

        if (dataSource.isServerVersionAtLeast(3, 0)) {
            "NULL as TABLE_CAT,NULL as TABLE_SCHEM,\n" +
            columnSize,
            table = new FireBirdView(owner, relationName, isSystem ? "SYSTEM VIEW" : "VIEW", dbResult);
        GenericFunctionResultType functionResultType
    @NotNull
        return session.prepareStatement("SELECT * FROM RDB$GENERATORS");
        if (triggerName == null) {
import java.util.Locale;
    public boolean supportsEqualFunctionsAndProceduresNames() {
    }
    @Override
 *
import java.util.Map;
    @Override
                    tableType = "MONITORING TABLE";
                return pos;
            }
    public JDBCStatement prepareUniqueConstraintsLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase forParent) throws SQLException {
            sql.append("AND RF.RDB$RELATION_NAME=? ");
        int sequence = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_SEQUENCE");
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
package org.jkiss.dbeaver.ext.firebird.model;
                        int type = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_TYPE");

                triggerName,
        return JDBCUtils.safeGetBytes(dbResult, "RDB$VIEW_BLR") == null ? 0 : 1;
                "RC.RDB$CONSTRAINT_TYPE as CONSTRAINT_TYPE " +
    public DBSEntityConstraintType getUniqueConstraintType(@NotNull JDBCResultSet dbResult) throws DBException, SQLException {
        return null;
        } catch (Exception e) {
    public JDBCStatement prepareTableTriggersLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @Nullable GenericTableBase table) throws SQLException {
        if (object == null && objectName == null) {
        return new FireBirdSequence(
        if (forTable != null) {
        }
            dbStat.setString(1, table.getName());

        String specificName,
        return new FireBirdDatabaseTrigger(
        @NotNull String procedureName,
        return true;
        return new FireBirdDataSource(monitor, container, this);
    @Override
        }
            "RF.RDB$FIELD_SOURCE,\n");


    private Pattern ERROR_POSITION_PATTERN = Pattern.compile(" line ([0-9]+), column ([0-9]+)");
import org.jkiss.dbeaver.model.DBPErrorAssistant;
        return null;
 *     http://www.apache.org/licenses/LICENSE-2.0
                pos.position = Integer.parseInt(matcher.group(2)) - 1;
    @Override
        int relType = getRelationType(dbResult);
        boolean isSystem = JDBCUtils.safeGetBoolean(dbResult, "RDB$SYSTEM_FLAG");
    @Override
    }
            isSystem = false;
                "CAST((ISGMT.RDB$FIELD_POSITION + 1) as SMALLINT) as KEY_SEQ," +
import org.jkiss.dbeaver.DBDatabaseException;
                        result.add(trigger);
        }
import org.jkiss.dbeaver.model.DBUtils;
        String sql = "SELECT * FROM RDB$RELATIONS";
        }
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    @Override
            "RF.RDB$DESCRIPTION AS REMARKS,\n" +

            0,
        table.setSystem(isSystem);
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
            description,

            sql.append("'NO' AS IS_IDENTITY,\n" +
import java.util.List;
        String remarks,
                    description,
                    sequence,
                    break;
    public GenericTrigger createTableTriggerImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull GenericTableBase parent, String triggerName, @NotNull JDBCResultSet dbResult) throws DBException {
            throw new DBDatabaseException(e, container.getDataSource());
    public boolean supportsSequences(@NotNull GenericDataSource dataSource) {
    @Nullable
    ) {
import org.jkiss.code.NotNull;
    }
            -1,
        String tableName = table.getName();
*/
{
                        boolean isSystem = systemFlag > 0; // System flag value 0 - if user-defined and 1 or more if system
                parent,
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
            switch (relType) {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, container, "Read triggers")) {
                    while (dbResult.next()) {
        return FireBirdUtils.getViewSource(monitor, sourceObject);
    public GenericTrigger createContainerTriggerImpl(@NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) throws DBException {
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType;
    }
import org.jkiss.code.Nullable;
    }
            "F.RDB$NULL_FLAG AS SOURCE_NULL_FLAG,\n" +
                    FireBirdTriggerType.getByType(type),
            typeName, valueType, sourceType, ordinalPos,
                isSystem);
    @Override
            return null;


    @Override
    @Override
        if (table != null) {
    }
            return i;
        }
                    dbStat.setString(1, table.getName());
    public String getAutoIncrementClause(GenericTableColumn column) {
    }


                dbResult);
    @Override
                            continue;
        table.setDescription(JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$DESCRIPTION"));
            "F.RDB$FIELD_PRECISION AS COLUMN_SIZE,\n" +
                case 2:
    }
                    }
            null,
    @Override
        String description = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$DESCRIPTION");
    }
                    break;
        return true;

                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            "RF.RDB$NULL_FLAG AS NULL_FLAG,\n" +
        int type = JDBCUtils.safeGetInt(dbResult, "RDB$TRIGGER_TYPE");
        super();
                    tableType = "EXTERNAL TABLE";
 * DBeaver - Universal Database Manager
                            table,
        return session.prepareStatement(

        return true;
                    isSystem);
            return null;
            name,
            if (matcher.find()) {

    public FireBirdDataTypeCache createDataTypeCache(@NotNull GenericStructContainer container) {
        if (CommonUtils.isEmpty(name)) {
                }
                case 3:
                container,
/**
 */
    @Override
            "F.RDB$DEFAULT_SOURCE AS DOMAIN_DEFAULT_SOURCE,\n" +
        String relationName = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$RELATION_NAME");

    }
    @Override
            sql.append("CASE WHEN RF.RDB$IDENTITY_TYPE IS NULL THEN CAST('NO' AS VARCHAR(3)) ELSE CAST('YES' AS VARCHAR(3)) END AS IS_IDENTITY,\n" +
                "FROM " +
}
    private boolean hasIdentityColumns(JDBCSession session) throws SQLException {
    @Override
    }
 *
 * you may not use this file except in compliance with the License.
                tableName,
            Object odsVersion = metaData.getClass().getMethod("getOdsMajorVersion").invoke(metaData);
    public GenericTableBase createTableImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @NotNull GenericMetaObject tableObject, @NotNull JDBCResultSet dbResult) {
            "F.RDB$CHARACTER_LENGTH AS CHAR_LEN,\n" +
        sql.append("\nWHERE RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME ");
        }

            "F.RDB$FIELD_LENGTH AS DECIMAL_DIGITS,\n" +
    }
        if (name == null) {
        return true;
    }
    public JDBCStatement prepareTableLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer owner, @Nullable GenericTableBase object, @Nullable String objectName) throws SQLException {
    public boolean supportsTriggers(@NotNull GenericDataSource dataSource) {
        return FireBirdUtils.getProcedureSource(monitor, sourceObject);
        JDBCPreparedStatement dbStat = session.prepareStatement(sql.toString());

                if (table != null) {
        );
 * distributed under the License is distributed on an "AS IS" BASIS,
        if (tableType != null && isView(tableType)) {
/*
        return true;

import java.util.ArrayList;
            remarks, defaultValue, autoIncrement, autoGenerated
                    tableType = "CONNECTION-LEVEL GTT";

                "SELECT * FROM RDB$TRIGGERS\n" +
                    name,

import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
        String name = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$TRIGGER_NAME");
    @Override
                    break;
            container,
    public DBPErrorAssistant.ErrorPosition getErrorPosition(@NotNull Throwable error) {
        return dbStat;
    // [dbeaver/issues/10492]
    public boolean supportsDatabaseTriggers(@NotNull GenericDataSource dataSource) {
        return "PRIMARY KEY".equals(constraintType) ? DBSEntityConstraintType.PRIMARY_KEY : DBSEntityConstraintType.UNIQUE_KEY;

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            Matcher matcher = ERROR_POSITION_PATTERN.matcher(message);
    }
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
    @Override
            isSystem
    public JDBCStatement prepareSequencesLoadStatement(@NotNull JDBCSession session, @NotNull GenericStructContainer container) throws SQLException {
    public String getTriggerDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTrigger trigger) throws DBException {
                "FROM RDB$RELATION_FIELDS RF,RDB$FIELDS F");
            columnName,

    }

    }
                            name,
                "CASE RF.RDB$IDENTITY_TYPE WHEN 0 THEN CAST('ALWAYS' AS VARCHAR(10)) WHEN 1 THEN CAST('BY DEFAULT' AS VARCHAR(10)) ELSE NULL END AS JB_IDENTITY_TYPE\n" +
            "RF.RDB$DEFAULT_SOURCE AS DEFAULT_SOURCE,\n" +
            return "GENERATED BY DEFAULT AS IDENTITY";
    private static int getRelTypeFromViewBLR(@NotNull JDBCResultSet dbResult) {
        return dbStat;
        table.setPersisted(true);
        return FireBirdUtils.getTriggerSource(monitor, (FireBirdTrigger)trigger);

            dbResult);
import java.util.regex.Pattern;
        }
    }
                return getRelTypeFromViewBLR(dbResult);
        String constraintType = JDBCUtils.safeGetString(dbResult, "CONSTRAINT_TYPE");
    public boolean isTableCommentEditable() {
        return true;
                tableType,
    @Override
            return getRelTypeFromViewBLR(dbResult);
        if (!CommonUtils.isEmpty(message)) {
    }
        GenericDataSource dataSource = column.getDataSource();
        StringBuilder sql = new StringBuilder();
            sql += "\nWHERE RDB$RELATION_NAME=?";
        }

        return new FireBirdTableColumn(monitor, dbResult, table,
                        FireBirdTableTrigger trigger = new FireBirdTableTrigger(

            "F.RDB$FIELD_SUB_TYPE AS TYPE_NAME,\n" +
                FireBirdTriggerType.getByType(type),

    }
            }
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {

        }
            table = new FireBirdTable(owner, relationName, tableType, dbResult);
    @NotNull
    }
    @NotNull
        return tableName.startsWith("RDB$") || tableName.startsWith("MON$");    // [JDBC: Firebird]
                    break;
    }
        sql.append("SELECT " +
                        if (name == null) {
            "cast(RF.RDB$FIELD_NAME as varchar(" + OBJECT_NAME_LENGTH + ")) AS COLUMN_NAME,\n" +
        } else {
        String name = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$GENERATOR_NAME");
            "F.RDB$CHARACTER_SET_ID,\n" +
    public GenericSequence createSequenceImpl(@NotNull JDBCSession session, @NotNull GenericStructContainer container, @NotNull JDBCResultSet dbResult) {
        }
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaObject;
    private static final int OBJECT_NAME_LENGTH = 63;
                            isSystem);
                "ISGMT.RDB$FIELD_NAME as COLUMN_NAME," +
        } catch (SQLException e) {

    }
        );
            if (i == null) {
        }
        return session.prepareStatement("SELECT * FROM RDB$TRIGGERS WHERE RDB$RELATION_NAME IS NULL");
            }
    }
            Integer i = dbResult.getObject("RDB$RELATION_TYPE", Integer.class);
        int systemFlag = JDBCUtils.safeGetInt(dbResult, "RDB$SYSTEM_FLAG");
                    tableType = isSystem ? "SYSTEM TABLE" : "TABLE";
                "SELECT RDB$TRIGGER_NAME AS TRIGGER_NAME, RDB$RELATION_NAME AS OWNER, T.* FROM RDB$TRIGGERS T\n" +
        String description = JDBCUtils.safeGetStringTrimmed(dbResult, "RDB$DESCRIPTION");
        }
        }
            "F.RDB$FIELD_SCALE AS BUFFER_LENGTH,\n" +
