    @NotNull
 * Copyright (C) 2010-2025 DBeaver Corp and others
    }
 *
        if (fullTypeName.toUpperCase().contains("ARRAY")) {
    private final Map<String, Integer> enumEntries;
import org.jkiss.code.NotNull;
    }
    public ClickhouseTableColumn(GenericTableBase table, String columnName, String typeName, int valueType, int sourceType, int ordinalPosition, long columnSize, long charLength, Integer scale, Integer precision, int radix, boolean notNull, String remarks, String defaultValue, boolean autoIncrement, boolean autoGenerated) {
 * distributed under the License is distributed on an "AS IS" BASIS,
    public Map<String, Integer> getEnumEntries() {
    @Override
 * you may not use this file except in compliance with the License.
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize, charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
        this.fullTypeName = fullTypeName;

            super.setFullTypeName(fullTypeName);

    @Override
 * Unless required by applicable law or agreed to in writing, software

        return fullTypeName;
public class ClickhouseTableColumn extends GenericTableColumn {
        }
    }
}
            setTypeName(fullTypeName);
 *

import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
 *
        this.enumEntries = ClickhouseTypeParser.tryParseEnumEntries(typeName);
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

        this.fullTypeName = typeName;
 * Licensed under the Apache License, Version 2.0 (the "License");
import java.util.Map;

 * See the License for the specific language governing permissions and
 */
 * DBeaver - Universal Database Manager
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;

    public String getFullTypeName() {
import org.jkiss.dbeaver.DBException;
    private String fullTypeName;
        } else {
        return enumEntries;
    public void setFullTypeName(@NotNull String fullTypeName) throws DBException {
 * limitations under the License.
    @NotNull
import org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser;
 *     http://www.apache.org/licenses/LICENSE-2.0
 * You may obtain a copy of the License at
package org.jkiss.dbeaver.ext.clickhouse.model;
    }
/*
