
 * you may not use this file except in compliance with the License.
    public boolean supportsNotNullColumnModifiers(DBSObject object) {
    }
    @Override
        );
            table, columnName, typeName, valueType, sourceType, ordinalPos,
import org.jkiss.code.NotNull;
        long columnSize,
    @Override
        GenericSchema schema =  sourceObject.getSchema();
                container,
        @NotNull GenericStructContainer owner,
                "SHOW CREATE TABLE " + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL)))
    public String getTableDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericTableBase sourceObject, @NotNull Map<String, Object> options) throws DBException {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
        String columnName,
        int declEnd = ddl.indexOf(") ENGINE");
    public ClickhouseMetaModel() {
        String defaultValue,
    public boolean isSystemSchema(GenericSchema schema) {
    @Nullable
    }
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            "WHERE database = ?" + (table != null || CommonUtils.isNotEmpty(tableName) ? " and name=?" : "");
    @Override
    private String normalizeDDL(String ddl) {
                    while (dbResult.next()) {
 */
/*

 * Licensed under the Apache License, Version 2.0 (the "License");
    public boolean supportsTableDDLSplit(@NotNull GenericTableBase sourceObject) {
        }
            ddl.substring(0, declStart) + "(\n" +
        boolean notNull,
                    String ddl = sql.toString();
 * You may obtain a copy of the License at
    }

    public GenericTableBase createTableOrViewImpl(@NotNull GenericStructContainer container, @Nullable String tableName, @Nullable String tableType, @Nullable JDBCResultSet dbResult) {

 * distributed under the License is distributed on an "AS IS" BASIS,
        dbStat.setString(1, owner.getName());
    }
    public GenericDataSource createDataSourceImpl(@NotNull DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBException {
            (schema != null && schema.getName().equals("system"))
    @Override
            dbStat.setString(2, table != null ? table.getName() : tableName);
        Integer precision,
        int ordinalPos,
    }
                        }

        return dbStat;

import org.jkiss.dbeaver.model.DBUtils;
    }
        String typeName,
            {

                tableType,
        }
 *
        return new ClickhouseCatalog(dataSource, catalogName);
        boolean autoIncrement,
    }
import org.jkiss.utils.CommonUtils;
    ) throws DBException {
    @Override
    @Override
        int sourceType,
public class ClickhouseMetaModel extends GenericMetaModel implements DBCQueryTransformProvider
            ddl.substring(declStart + 1, declEnd).replace(",", ",\n") + "\n" +
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read Clickhouse view/table source")) {

 *
        super();
            remarks, defaultValue, autoIncrement, autoGenerated
import org.jkiss.dbeaver.model.DBPEvaluationContext;
        }
/**
    }
        return new ClickhouseDataTypeCache(container);
import org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel;

import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache;
            return new QueryTransformerLimit(true, true);
import org.jkiss.dbeaver.model.exec.DBCQueryTransformer;
    @Override
import org.jkiss.code.Nullable;
                dbResult);
        int valueType,
 */
            throw new DBDatabaseException(e, dataSource);
        JDBCPreparedStatement dbStat = session.prepareStatement(sql);
    }
        } else {
        @NotNull JDBCSession session,
    public GenericSchema createSchemaImpl(@NotNull GenericDataSource dataSource, @Nullable GenericCatalog catalog, @NotNull String schemaName) throws DBException {
    public GenericCatalog createCatalogImpl(@NotNull GenericDataSource dataSource, @NotNull String catalogName) {
        }
    public JDBCStatement prepareTableLoadStatement(
            "FROM system.tables\n" +

        return new ClickhouseTableColumn(
                tableName,
 * ClickhouseMetaModel
 * Unless required by applicable law or agreed to in writing, software

                    }
    @Override
        return null;
 *     http://www.apache.org/licenses/LICENSE-2.0
import org.jkiss.dbeaver.ext.generic.model.*;
        if (type == DBCQueryTransformType.RESULT_SET_LIMIT) {
            declEnd = ddl.length() - 1;
        return false;
        ) {
            ddl.substring(declEnd);
                        String line = dbResult.getString(1);
        int declStart = ddl.indexOf("(");
            "SELECT name as TABLE_NAME, engine as TABLE_TYPE, database as TABLE_SCHEM," +
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
                    return normalizeDDL(ddl);
    public boolean supportsUniqueKeys() {
        }
    }
 * DBeaver - Universal Database Manager
    @NotNull
        @NotNull DBRProgressMonitor monitor,

import java.util.Map;
 * See the License for the specific language governing permissions and
                (((ClickhouseDataSource) owner.getDataSource()).isSupportTableComments() ? "comment as REMARKS," : "") + " * " +
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
    public DBCQueryTransformer createQueryTransformer(@NotNull DBCQueryTransformType type) {
        long charLength,
        String remarks,
}
                        sql.append(line).append("\n");
        if (tableType != null && isView(tableType)) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
        @Nullable GenericTableBase table,
    @Override
    public GenericTableColumn createTableColumnImpl(
        if (table != null || CommonUtils.isNotEmpty(tableName)) {
    @NotNull
        GenericCatalog catalog =  sourceObject.getCatalog();
        @Nullable String tableName) throws SQLException {
{
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.impl.sql.QueryTransformerLimit;
import org.jkiss.dbeaver.model.DBPDataSourceContainer;
import java.sql.SQLException;

    @Override
            return new ClickhouseView(container, tableName, tableType, dbResult);
    @Override
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType;

                    StringBuilder sql = new StringBuilder();


import org.jkiss.dbeaver.model.exec.DBCQueryTransformProvider;
    }
            return new ClickhouseTable(

import org.jkiss.dbeaver.model.exec.DBCQueryTransformType;
        return getTableDDL(monitor, sourceObject, options);
        return new ClickhouseSchema(dataSource, catalog, schemaName);
    @Override
    public JDBCBasicDataTypeCache<GenericStructContainer, ? extends JDBCDataType> createDataTypeCache(@NotNull GenericStructContainer container) {
                }
        return new ClickhouseDataSource(monitor, container, this);
    @Override
        GenericDataSource dataSource = sourceObject.getDataSource();
        }
    }
        int radix,
    @Override
                            continue;
    public String getViewDDL(@NotNull DBRProgressMonitor monitor, @NotNull GenericView sourceObject, @NotNull Map<String, Object> options) throws DBException {
        return
        return false;

    }
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
        @NotNull GenericTableBase table,

            || (catalog != null && catalog.getName().equals("system"))
 * Copyright (C) 2010-2026 DBeaver Corp and others
import org.jkiss.dbeaver.DBDatabaseException;
        Integer scale,
            columnSize, charLength, scale, precision, radix, notNull,
        return true;
    }
import org.jkiss.dbeaver.model.struct.DBSObject;
        @Nullable JDBCResultSet dbResult,

            }
        String sql =
    }
package org.jkiss.dbeaver.ext.clickhouse.model;
        } catch (SQLException e) {
        if (
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
import org.jkiss.dbeaver.DBException;
 * limitations under the License.
        boolean autoGenerated
    }
            return super.getTableDDL(monitor, sourceObject, options);
        return schema.getName().equalsIgnoreCase("INFORMATION_SCHEMA") || schema.getName().equals("system");
 *
        if (declEnd == -1) {
                        if (line == null) {
        // engine can be View or MaterializedView, we can read this field instead table_type
