
        Object propertyId
     */

                object = cache.getObject(
        try (JDBCPreparedStatement dbStat = session.prepareStatement(qry)) {

            dbStat.setString(1, schemaName);
        
                    && !line.stripLeading().startsWith("--")) {
        if (AltibaseConstants.OBJ_TYPE_MATERIALIZED_VIEW.equals(tableType)) { 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                        monitor,

        for (i = getEffectiveSqlLineNumber(lines); i < length; i++) {
    /**
import org.jkiss.dbeaver.DBException;
            if (monitor != null) {
    /**
    public static boolean getViewStatus(JDBCSession session, String tableType, String schemaName, String objName) throws DBCException {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
                return reference;
import org.jkiss.utils.CommonUtils;
            throw new DBCException(e, session.getExecutionContext());
        PARENT parent,
    }
            if ((line != null) && (line.trim().length() > 0) 
        }
            return "UNKNOWN_OBJECT_TYPE";
            i++;
 */
            ddl.append(lines[i]).append(AltibaseConstants.NEW_LINE);
        int length = lines.length;
     */
        return i;


                    isValid = JDBCUtils.safeGetBoolean(dbResult, 1, "0"); // 0 is Valid, 1 is invalid
                object = cache.getCachedObject((String) reference);
                    + " AND u.user_name = ? AND t.table_name = ?";
        int i = 0;
        
                }
 * Copyright (C) 2010-2024 DBeaver Corp and others
            try (JDBCResultSet dbResult = dbStat.getResultSet()) {
        }
import org.jkiss.dbeaver.Log;
        }
            }
            }

            }
        } catch (SQLException e) {
 *
        
                if (dbResult != null && dbResult.next()) {
        
        last = ddl.length() - AltibaseConstants.NEW_LINE.length();
        return objTypeName.replaceAll(" ", "_");
 *     http://www.apache.org/licenses/LICENSE-2.0
            }

    /*
    static final Log log = Log.getLog(AltibaseUtils.class);
                    + " AND u.user_name = ? AND m.mview_name = ?";
        final Object reference = referrer.getLazyReference(propertyId);
package org.jkiss.dbeaver.ext.altibase;
     * DBMS_METADATA: Object type name
import org.jkiss.dbeaver.model.struct.DBSObjectLazy;


import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
                        (String) reference);
        } else {
     * Generic function to get view/mview status: valid or invalid
        if (reference instanceof String) {
     * In case of space in the name, DBMS_METADATA requires replace space to underscore.
            qry = "SELECT v.status FROM system_.sys_users_ u, system_.sys_materialized_views_ m, system_.sys_views_ v"
                        parent,

 * See the License for the specific language governing permissions and
    
        String qry = null;
        int last;
    
     */
        int i = 0;
 *
 */
        return isValid;
/*
            } else {

                    + " WHERE u.user_id = t.user_id AND u.user_id = v.user_id AND v.view_id = t.table_id"
    }
 * limitations under the License.
                    + " WHERE u.user_id = m.user_id AND u.user_id = v.user_id AND v.view_id = m.view_id"
        return ddl.substring(0, last);
    
    public static String getEffectiveSql(String script) {
    }
        DBSObjectCache<PARENT, ?> cache,
                return i;
    public static String getDmbsMetaDataObjTypeName(String objTypeName) {
    }
import org.jkiss.dbeaver.model.exec.DBCException;
        boolean isValid = false;
        ) throws DBException {
    private static int getEffectiveSqlLineNumber(String[] script) {
     */
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    }

 * Unless required by applicable law or agreed to in writing, software
 *
        }
import org.jkiss.dbeaver.model.struct.DBSObject;
    
     * Remove View source comments generated by DBStrucUtils.java
        DBRProgressMonitor monitor,
import java.sql.SQLException;
     * e.g. -- SYS.SQ_VIEW1 source or empty line
        if (CommonUtils.isEmpty(objTypeName)) {
 * DBeaver - Universal Database Manager
/**
     * from SQL string array.
        String[] lines = script.split("\\R");
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    public static <PARENT extends DBSObject> Object resolveLazyReference(
     * Get the first index of SQL that is not start with comment and has value
import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;

        // Materialized View
        for (String line : script) {
 * You may obtain a copy of the License at
        } else {
            dbStat.executeStatement();
            qry = "SELECT v.status FROM system_.sys_users_ u, system_.sys_tables_ t, system_.sys_views_ v"
 * you may not use this file except in compliance with the License.
            dbStat.setString(2, objName);
        StringBuilder ddl = new StringBuilder();
        DBSObjectLazy<?> referrer,
                log.warn("Object '" + reference + "' not found");
}
                return object;
    /**
            if (object != null) {
        // View
        }
 * distributed under the License is distributed on an "AS IS" BASIS,
        }
            Object object;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
 * Licensed under the Apache License, Version 2.0 (the "License");
public class AltibaseUtils {

            } else {
 * Altibase utils

            return reference;
