                if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
    }
                } else {
 * See the License for the specific language governing permissions and
import org.jkiss.code.NotNull;
        }
 *
                sql.append(DBUtils.getObjectFullName(attr, DBPEvaluationContext.DML));
                if (hasAttr) sql.append(", ");

 * Unless required by applicable law or agreed to in writing, software
    @Override

import org.jkiss.dbeaver.model.data.DBDResultSetDataProvider;
 * Copyright (C) 2010-2026 DBeaver Corp and others
        return true;
 */
        return true;
        @NotNull DBRProgressMonitor monitor,
                }
public class SQLGeneratorInsertFromData extends SQLGeneratorResultSet {
 *     http://www.apache.org/licenses/LICENSE-2.0
import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
            sql.append("INSERT INTO ").append(getEntityName(dataProvider.getSingleSource()));
 *

import org.jkiss.dbeaver.model.data.DBDAttributeBinding;
    @Override
            for (DBSAttributeBase attr : allAttributes) {
                hasAttr = true;
import org.jkiss.dbeaver.model.data.DBDValueRow;
    protected void generateSQL(
 * You may obtain a copy of the License at

    ) throws DBException {
                    continue;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            hasAttr = false;
    }
                if (binding == null) {
package org.jkiss.dbeaver.model.sql.generator.resultset;
    }
            boolean hasAttr = false;
                }
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
 * distributed under the License is distributed on an "AS IS" BASIS,
                if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {
            sql.append(")").append(getLineSeparator()).append("VALUES(");
 *
        @NotNull StringBuilder sql,
 * DBeaver - Universal Database Manager
 * limitations under the License.
import org.jkiss.dbeaver.model.DBUtils;
 * Licensed under the Apache License, Version 2.0 (the "License");
            }
            Collection<? extends DBSAttributeBase> allAttributes = getAllAttributes(monitor, dataProvider);
    @Override
            }
    public boolean isDMLOption() {
                    continue;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
                    continue;

                }
}
 * you may not use this file except in compliance with the License.
import org.jkiss.dbeaver.DBException;
                }
                    continue;
        @NotNull DBDResultSetDataProvider dataProvider
                hasAttr = true;
                }
                DBDAttributeBinding binding = DBUtils.findBinding(dataProvider.getAttributes(), attr);
                if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
    public boolean isInsertOption() {
                    appendDefaultValue(sql, attr);
                if (hasAttr) sql.append(", ");
            sql.append(getLineSeparator()).append("(");
/*
                    appendAttributeValue(dataProvider, sql, binding, firstRow, false);
                if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {

            sql.append(");\n");
        for (DBDValueRow firstRow : dataProvider.getSelectedRows()) {
import java.util.Collection;
            for (DBSAttributeBase attr : allAttributes) {
