        return false;
        } catch (DBException e) {


        }
        return useSeparateForeignKeys;
    /**
    }
        this.excludeAutoGeneratedColumn = excludeAutoGeneratedColumn;
    public void setShowPermissions(boolean showPermissions) {
    }

    public List<OBJECT> getObjects() {
    private final Map<String, Object> generatorOptions = new LinkedHashMap<>();
        options.put(DBPScriptObject.OPTION_SCRIPT_FORMAT_COMPACT, isCompactSQL());

    public boolean isShowCastParams() {
    public boolean hasOptions() {
        options.put(DBPScriptObject.OPTION_CAST_PARAMS, isShowCastParams());

import org.jkiss.dbeaver.model.sql.registry.SQLGeneratorConfigurationRegistry;
    private boolean useCustomDataFormat = false;

    private boolean showPermissions = false;
    public boolean isUseCustomDataFormat() {
    public boolean isDMLOption() {
    public boolean isShowPartitionsDDL() {
    protected List<OBJECT> objects;
                }

    protected abstract void generateSQL(DBRProgressMonitor monitor, StringBuilder sql, OBJECT object)
    private boolean fullyQualifiedNames = true;
        this.useCustomDataFormat = useCustomDataFormat;

    }
    }
import org.jkiss.dbeaver.model.sql.registry.SQLGeneratorDescriptor;
package org.jkiss.dbeaver.model.sql.generator;
import org.jkiss.dbeaver.model.DBUtils;

    private boolean showFullDdl = false;
        this.showComments = showComments;
        } else {
    }


    }
    public void setShowCastParams(boolean showCastParams) {
        return false;
    public boolean isIncludePermissions() {
    public boolean isExcludeAutoGeneratedColumn() {
                if (!(object instanceof DBPObject) || descriptor.appliesTo((DBPObject) object)) {
    public boolean isShowComments() {

    }
        return useCustomDataFormat;
    }
        if (value == null) {
        result = sql.toString().trim();
        return true;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
            generatorOptions.put(name, value);
        try {
        return compactSQL;
    }
    }
        } else {
            for (OBJECT object : objects) {
        return showComments;
    }
}
    public boolean isCompactSQL() {

        return showFullDdl;


        return excludeAutoGeneratedColumn;
import java.lang.reflect.InvocationTargetException;
    public boolean isUseSeparateForeignKeys() {
        this.showPartitionsDDL = showPartitionsDDL;
    }
    protected String getEntityName(DBSEntity entity) {
        options.put(DBPScriptObject.OPTION_SCRIPT_EXCLUDE_AUTO_GENERATED_COLUMN, isExcludeAutoGeneratedColumn());
    @Override
    public void setShowFullDdl(boolean showFullDdl) {
    }
    }
    }
import org.jkiss.dbeaver.model.DBPObject;
        options.put(DBPScriptObject.OPTION_INCLUDE_PERMISSIONS, isIncludePermissions());
        options.put(DBPScriptObject.OPTION_SCRIPT_USE_CUSTOM_DATA_FORMAT, isUseCustomDataFormat());
        this.fullyQualifiedNames = fullyQualifiedNames;
        return showPermissions;
        return objects;

        return false;
    public void setFullyQualifiedNames(boolean fullyQualifiedNames) {
    private boolean showCastParams = false;

    }
    }
import java.util.Map;
        return showPartitionsDDL;
        StringBuilder sql = new StringBuilder(100);
 * You may obtain a copy of the License at
    public void setUseSeparateForeignKeys(boolean useSeparateForeignKeys) {
        return fullyQualifiedNames;
 */
        this.showCastParams = showCastParams;
        SQLGeneratorDescriptor descriptor = SQLGeneratorConfigurationRegistry.getInstance().getGeneratorDescriptor(this);
 * Copyright (C) 2010-2024 DBeaver Corp and others
    public void initGenerator(List<OBJECT> objects) {
    }
/*
        }

            }
        this.showFullDdl = showFullDdl;
    }
    public boolean supportCastParams() {
    protected void addOptions(Map<String, Object> options) {
import org.jkiss.dbeaver.model.runtime.DBRRunnableWithResult;


 * DBeaver - Universal Database Manager
 *     http://www.apache.org/licenses/LICENSE-2.0
        return generatorOptions.get(name);
 * you may not use this file except in compliance with the License.
 *
        this.useSeparateForeignKeys = useSeparateForeignKeys;
    }
    public void setGeneratorOption(String name, Object value) {
        options.put(DBPScriptObject.OPTION_FULLY_QUALIFIED_NAMES, isFullyQualifiedNames());
        options.put(DBPScriptObject.OPTION_DDL_SOURCE, true);

import org.jkiss.dbeaver.model.struct.DBSEntity;
    private boolean compactSQL = false;
        options.put(DBPScriptObject.OPTION_INCLUDE_COMMENTS, isShowComments());
import org.jkiss.dbeaver.DBException;

            return DBUtils.getObjectFullName(entity, DBPEvaluationContext.DML);
    }
        return showCastParams;

 * distributed under the License is distributed on an "AS IS" BASIS,

 *
    }
    }
        return false;
        this.compactSQL = compactSQL;
    }
 * See the License for the specific language governing permissions and
        this.showPermissions = showPermissions;
    protected String getLineSeparator() {

import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    private boolean useSeparateForeignKeys = true;
 * limitations under the License.
    public void setShowPartitionsDDL(boolean showPartitionsDDL) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

        }
            generatorOptions.remove(name);
    public Object getGeneratorOption(String name) {
import java.util.LinkedHashMap;
        return compactSQL ? " " : "\n";


 * Licensed under the Apache License, Version 2.0 (the "License");
    public void setCompactSQL(boolean compactSQL) {
        options.putAll(generatorOptions);
        if (fullyQualifiedNames) {


        options.put(DBPScriptObject.OPTION_INCLUDE_PARTITIONS, isShowPartitionsDDL());
    }

    public void setShowComments(boolean showComments) {
    {
        throws DBException;
    public boolean isDDLOption() {

    
import java.util.List;
    }
    private boolean excludeAutoGeneratedColumn = false;
        this.objects = objects;
    }
    }
    private boolean showComments = true;
public abstract class SQLGenerator<OBJECT> extends DBRRunnableWithResult<String> {

            return DBUtils.getQuotedIdentifier(entity);
    public boolean isFullyQualifiedNames() {
    public boolean isInsertOption() {
 *
                    generateSQL(monitor, sql, object);
    }
     */
    public boolean isShowFullDdl() {
     * if yes, additional checkbox in the SQL dialog will be shown
    public void run(DBRProgressMonitor monitor) throws InvocationTargetException, InterruptedException

        options.put(DBPScriptObject.OPTION_INCLUDE_NESTED_OBJECTS, isShowFullDdl());
 * Unless required by applicable law or agreed to in writing, software
    }
import org.jkiss.dbeaver.model.DBPScriptObject;

        options.put(DBPScriptObject.OPTION_DDL_SEPARATE_FOREIGN_KEYS_STATEMENTS, isUseSeparateForeignKeys());
    }
     * Set whether generator supports 'cast parameters' (or not) feature -

    }
    public void setExcludeAutoGeneratedColumn(boolean excludeAutoGeneratedColumn) {


    public void setUseCustomDataFormat(boolean useCustomDataFormat) {
            throw new InvocationTargetException(e);
    }
    private boolean showPartitionsDDL = false;
