            if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
            }
            if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {
    }
                continue;
 * Unless required by applicable law or agreed to in writing, software
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    @Override
        return true;
        sql.append(")").append(getLineSeparator()).append("VALUES(");
        hasAttr = false;
            if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {
                continue;
 * See the License for the specific language governing permissions and
}
import org.jkiss.dbeaver.model.struct.DBSEntity;

            if (hasAttr) sql.append(", ");
/*
import org.jkiss.dbeaver.model.DBPEvaluationContext;
    }
 *
        }
 * limitations under the License.
            sql.append(DBUtils.getObjectFullName(attr, DBPEvaluationContext.DML));

import org.jkiss.dbeaver.DBException;
    public void generateSQL(DBRProgressMonitor monitor, StringBuilder sql, DBSEntity object) throws DBException {
 * Copyright (C) 2010-2024 DBeaver Corp and others
                continue;
        sql.append("INSERT INTO ").append(getEntityName(object)).append(getLineSeparator()).append("(");
 * you may not use this file except in compliance with the License.
 * distributed under the License is distributed on an "AS IS" BASIS,

 */
        for (DBSEntityAttribute attr : getAllAttributes(monitor, object)) {
 * You may obtain a copy of the License at
                continue;
            if (hasAttr) sql.append(", ");
 * Licensed under the Apache License, Version 2.0 (the "License");
public class SQLGeneratorInsert extends SQLGeneratorTable {
            }
        sql.append(");\n");
 * DBeaver - Universal Database Manager
        }
            appendDefaultValue(sql, attr);
 *
        for (DBSEntityAttribute attr : getAllAttributes(monitor, object)) {
    @Override
            if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        boolean hasAttr = false;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
 *
            }

    public boolean isInsertOption() {


            hasAttr = true;
import org.jkiss.dbeaver.model.DBUtils;
            hasAttr = true;
package org.jkiss.dbeaver.model.sql.generator;
 *     http://www.apache.org/licenses/LICENSE-2.0
            }
