        }
    }

        OracleTableBase table,
        return super.isRequired();
        }
 *
    @NotNull
        }
        if (getDataSource().resolveDataType(new VoidProgressMonitor(), typeName) == null) {
 */
    }
    public boolean isAutoGenerated()
        this.comment = comment;
    @Override
import java.sql.Types;

    @Override
    void cacheComment() {
        setRequired(!OracleConstants.RESULT_YES_VALUE.equals(JDBCUtils.safeGetString(dbResult, "NULLABLE")));

    }
import java.util.ArrayList;
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 70)
                dataTypes.add(column.getDataType());
    public Integer getScale()

        DBRProgressMonitor monitor,

    private OracleDataType type;
            return dataTypes.toArray(new DBSDataType[0]);
        @Override
        this.type = OracleDataType.resolveDataType(
    public OracleDataSource getDataSource()
    public String getComment(DBRProgressMonitor monitor) {
    {
 * distributed under the License is distributed on an "AS IS" BASIS,
        setDefaultValue(JDBCUtils.safeGetString(dbResult, "DATA_DEFAULT"));
    @Nullable
import org.jkiss.dbeaver.DBException;
    @Nullable
        @Nullable
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        }
    @Override
    }
        }
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
        return type;
public class OracleTableColumn extends JDBCTableColumn<OracleTableBase> implements
            }
    @Property(viewable = true, editable = true, updatable = true, length = PropertyLength.MULTILINE, order = 100)
            this.comment = "";
        }
    {
    public Integer getPrecision()
    public long getMaxLength()
    }

    @Property(viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
        return getTable().getDataSource();
 * you may not use this file except in compliance with the License.
    @Property(viewable = true, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 50)
import org.jkiss.code.NotNull;
        return false;
 * Unless required by applicable law or agreed to in writing, software
        if (this.type != null) {
 */

    @Override
import org.jkiss.code.Nullable;
    }
    }
        public boolean isPropertyCached(@NotNull OracleTableColumn object, @NotNull Object propertyId)

        this.typeName = type == null ? "" : type.getFullyQualifiedName(DBPEvaluationContext.DDL);
        @Override
    public String getDescription(@NotNull DBRProgressMonitor monitor) {
import org.jkiss.dbeaver.model.struct.DBSTypedObjectEx;
/*
import org.jkiss.dbeaver.model.*;
        super(table, false);
    }
import org.jkiss.dbeaver.model.struct.DBSDataType;
    }
        this.hidden = JDBCUtils.safeGetBoolean(dbResult, "HIDDEN_COLUMN", OracleConstants.YES);
            if (!dataTypes.contains(column.getDataType())) {
    public OracleTableColumn(OracleTableBase table)
    {

    public static class CommentLoadValidator implements IPropertyCacheValidator<OracleTableColumn> {
        return comment;
    @NotNull
import org.jkiss.dbeaver.model.struct.rdb.DBSTableColumn;
 * limitations under the License.
    @LazyProperty(cacheValidator = CommentLoadValidator.class)


    }
        return getComment(monitor);

            getTable().loadColumnComments(monitor);
    {



 *
    {
        return comment;
 *
    public static class ColumnDataTypeListProvider implements IPropertyValueListProvider<OracleTableColumn> {
    @Override

        @Override
    //@Property(viewable = false, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 21, listProvider = ColumnDataTypeListProvider.class)
    {
        public Object[] getPossibleValues(OracleTableColumn column)

    {
/**
    }
        {
    @NotNull

    //@Property(name = "Data Type", viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
{
    @Override
    @Nullable
    {
    }
        return super.getPrecision();
    @Override
            // Scale can be null in case when type was declared without parameters (examples: NUMBER, NUMBER(*), FLOAT)
    }
import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
    }
    @Property(viewable = false, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 41)
        return super.getScale();
        }
    }
package org.jkiss.dbeaver.ext.oracle.model;
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt3;
 * Copyright (C) 2010-2025 DBeaver Corp and others
    {
    }
    protected void validateTypeName(String typeName) throws DBException {
            monitor,
        if (typeMod == OracleDataTypeModifier.REF) {
        this.typeMod = OracleDataTypeModifier.resolveTypeModifier(JDBCUtils.safeGetString(dbResult, "DATA_TYPE_MOD"));
 * DBeaver - Universal Database Manager
        if (isPersisted() && comment == null && !DBWorkbench.getPlatform().isUnitTestMode()) {

    private String comment;
        return super.getTypeName();
    {
    }
        Integer scale = JDBCUtils.safeGetInteger(dbResult, "DATA_SCALE");
        {
        this.typeName = JDBCUtils.safeGetString(dbResult, "DATA_TYPE");
    @Override

        throws DBException
    {
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    @Override
    }
    @Override
 * You may obtain a copy of the License at
        }
            return false;
    DBSTableColumn, DBSTypedObjectEx, DBSTypedObjectExt3, DBPHiddenObject, DBPNamedObject2, DBSTypedObjectExt4<OracleDataType>, DBPObjectWithLazyDescription
            getDataSource(),
            this.valueType = Types.REF;
        // Read default value first because it is of LONG type and has to be read before others
        {
    public void setDataType(@NotNull OracleDataType type)

    @Property(viewable = false, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 42)
import org.jkiss.dbeaver.model.meta.*;

 * Licensed under the Apache License, Version 2.0 (the "License");
 *     http://www.apache.org/licenses/LICENSE-2.0
    }
 * OracleTableColumn

    @Override
    }
import org.jkiss.dbeaver.runtime.DBWorkbench;
            JDBCUtils.safeGetString(dbResult, "DATA_TYPE_OWNER"),
    @Property(viewable = false, editableExpr = "!object.table.view", updatableExpr = "!object.table.view", order = 40)
            List<DBSDataType> dataTypes = new ArrayList<>(column.getTable().getDataSource().getLocalDataTypes());
        @NotNull ResultSet dbResult)
    public String getDefaultValue()
    @Override
        return hidden;
    public String getDescription() {
        return super.getMaxLength();
import java.sql.ResultSet;
            this.typeName);
    @Override
        return super.getDefaultValue();
        }
    public String getTypeName()
}
    @Override


    public OracleDataType getDataType() {
        if (this.comment == null) {
        public boolean allowCustomValue()
    public void setComment(String comment)
    public OracleTableColumn(
    }
            this.typeName = type.getFullyQualifiedName(DBPEvaluationContext.DDL);

    public OracleDataTypeModifier getTypeMod()
        setMaxLength(JDBCUtils.safeGetLong(dbResult, "C".equals(charUsed) ? "CHAR_LENGTH" : "DATA_LENGTH"));
            return object.comment != null;
    }
    {
    private OracleDataTypeModifier typeMod;
    @Property(viewable = true, order = 30)
 * See the License for the specific language governing permissions and
        return typeMod;
        setPrecision(JDBCUtils.safeGetInteger(dbResult, "DATA_PRECISION"));
    {
        return DBUtils.getFullTypeName(this);
                scale = this.type.getScale();
        setScale(scale);


            }
    @Nullable

    public boolean isHidden()
        setName(JDBCUtils.safeGetString(dbResult, "COLUMN_NAME"));
        setOrdinalPosition(JDBCUtils.safeGetInt(dbResult, "COLUMN_ID"));
    public String getFullTypeName() {
import org.jkiss.dbeaver.model.struct.DBSTypedObjectExt4;
        this.type = type;
    public boolean isRequired()

    }
            if (this.type != null && this.type.getScale() != null) {
    @Override
        super(table, true);
        String charUsed = JDBCUtils.safeGetString(dbResult, "CHAR_USED");
            this.valueType = type.getTypeID();

        if (scale == null) {
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    {
    private boolean hidden;
import java.util.List;
            dataTypes.sort(DBUtils.nameComparator());
            // Load comments for all table columns
            throw new DBException("Bad data type name " + typeName);
