        this.length = JDBCUtils.safeGetInteger(dbResult, "LENGTH");

 *     http://www.apache.org/licenses/LICENSE-2.0
    private final Integer scale;

    @Override
    implements DBSEntityAttribute, DBSTypedObjectEx {
    public DBPDataKind getDataKind() {

    }
    @Property(viewable = true, order = 2)
    @Override
        return DBUtils.getFullTypeName(this);
import java.sql.ResultSet;
        this.precision = JDBCUtils.safeGetInteger(dbResult, "PRECISION");
        return precision == null ? 0 : precision;
        if (attrTypeMod == OracleDataTypeModifier.REF) {
        this.scale = JDBCUtils.safeGetInteger(dbResult, "SCALE");
        super(dataType, dbResult);
package org.jkiss.dbeaver.ext.oracle.model;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBUtils;

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    @Property(viewable = true, editable = true, order = 4)
 *
        return attrType.getFullyQualifiedName(DBPEvaluationContext.DDL);
public class OracleDataTypeAttribute
 */
        return false;
    }
        this.attrType = OracleDataType.resolveDataType(
        return length == null ? 0 : length;
 * See the License for the specific language governing permissions and
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    @NotNull

        return 0;
        this.name = JDBCUtils.safeGetString(dbResult, "ATTR_NAME");
    @Override
    private final Integer length;
            return DBPDataKind.REFERENCE;
import org.jkiss.code.NotNull;
            // Explicitly say that we are reference

/**
    }
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
    }
        }

        return getParentObject().getFullyQualifiedName(DBPEvaluationContext.UI) + "." + getName();
    @NotNull
        return attrTypeMod;
    public OracleDataTypeModifier getAttrTypeMod() {
    public boolean isAutoGenerated() {
 * Oracle data type attribute
    public long getMaxLength() {
        return attrType.getDataKind();
        return null;

    }
    }
        return attrType;
    @Override

    public String getFullTypeName() {
import java.sql.Types;
    public int getTypeID() {

import org.jkiss.dbeaver.model.DBPEvaluationContext;
/*
        this.attrTypeMod = OracleDataTypeModifier.resolveTypeModifier(JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_MOD"));
 * you may not use this file except in compliance with the License.
 */
    @Property(viewable = true, editable = true, order = 7)
            // Explicitly say that we are reference
    @Override


    }
 * Unless required by applicable law or agreed to in writing, software
    @Override
    public int getOrdinalPosition() {
    }
    private final Integer precision;
    @Override
        this.number = JDBCUtils.safeGetInt(dbResult, "ATTR_NO");

 * limitations under the License.
            monitor,

 * Copyright (C) 2010-2024 DBeaver Corp and others

    @Override
    public OracleDataType getDataType() {
    @Override
        if (attrTypeMod == OracleDataTypeModifier.REF) {

    public Integer getScale() {
    }
 * distributed under the License is distributed on an "AS IS" BASIS,
            JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_NAME"));
 *
            JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_OWNER"),
import org.jkiss.dbeaver.model.meta.Property;
    @Nullable
    public String toString() {
    }
            getDataSource(),
        // Number is 1 based
    public boolean isRequired() {
    @Nullable
    }

        return number - 1;
 * You may obtain a copy of the License at
        }
    @Property(viewable = true, editable = true, order = 5)
 *
            return Types.REF;
import org.jkiss.dbeaver.model.struct.DBSTypedObjectEx;
        return attrType.getTypeID();

    }
    extends OracleDataTypeMember
    private final OracleDataTypeModifier attrTypeMod;
    }
    public String getTypeName() {
    private final OracleDataType attrType;
}
    }
    @Override
    @Override
    }
    public String getDefaultValue() {
 * Licensed under the Apache License, Version 2.0 (the "License");
    public OracleDataTypeAttribute(DBRProgressMonitor monitor, OracleDataType dataType, ResultSet dbResult) {

        return false;
    public long getTypeModifiers() {
    }
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.code.Nullable;
 * DBeaver - Universal Database Manager
    @Override
    @Property(viewable = true, editable = true, order = 3)
    @NotNull
    @Override
        return scale == null ? 0 : scale;
    @Property(viewable = true, editable = true, order = 6)
    public Integer getPrecision() {

