productType=community
productBrandText=Universal Database Manager
appTitle=DBeaver
productDescription=Universal Database Manager and SQL Client
packageName=dbeaver
productTrademark=DBeaver is a trademark of DBeaver Corp
productBundleId=org.jkiss.dbeaver.core.product
appName=DBeaver
productLicense=ASL 2.0
productWebSite=https://dbeaver.io/
productEmail=support@dbeaver.com
productRepository=dbeaver/dbeaver
productModifier=ce
productCompany=DBeaver Corp
productEclipseId=org.jkiss.dbeaver.core.product
productCopyright=DBeaver Corp
productName=DBeaver Community
