
            }
    @NotNull
        @Override
    @Override
    @NotNull

import org.jkiss.dbeaver.DBException;
        this.objectId = JDBCUtils.safeGetLong(dbResult, "column_id");
 * Copyright (C) 2010-2025 DBeaver Corp and others
    }
    public static class DataTypeListProvider implements IPropertyValueListProvider<SQLServerTableColumn> {
        String dv = JDBCUtils.safeGetString(dbResult, "default_definition");
    }
        this.computedPersisted = JDBCUtils.safeGetInt(dbResult, "is_persisted") != 0;
    @Nullable
import org.jkiss.code.NotNull;
        @Override

    public SQLServerTableColumn(SQLServerTableBase table) {
import org.jkiss.dbeaver.model.meta.*;
            throw new DBCException("Data type '" + userTypeId + "' not found for column '" + getName() + "'");
 * distributed under the License is distributed on an "AS IS" BASIS,
                return new Pair<>("Table", getTable());
        return extendedPropertyCache;
        super.setAutoGenerated(identity);
    @Property(viewable = true, editable = true, updatable = true, length = PropertyLength.MULTILINE, order = 100)

    @Override

            try {
    public long getObjectId() {
    public IdentityInfo getIdentityInfo(DBRProgressMonitor monitor) throws DBCException {
    @Property(viewable = true, editable = true, updatable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 43)
import java.util.Collection;
import org.jkiss.dbeaver.model.*;
        }
        super(table, false);
            }
        return getObjectId();
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
            } catch (DBException e) {
    @Property(viewable = true, editable = true, updatable = true, order = 75)
/*
        return defaultConstraintName;
    public SQLServerDataSource getDataSource() {
 * you may not use this file except in compliance with the License.
        return dataType;
                log.debug("Error getting schema data types", e);
            // Remove redundant brackets
                    if (dbResult.next()) {
import org.jkiss.dbeaver.model.struct.*;
 * Unless required by applicable law or agreed to in writing, software
        }
        }
    public SQLServerTableColumn(
 * DBeaver - Universal Database Manager

                return new Pair<>("Column", this);
        return super.getPrecision();
    }

        this.userTypeId = JDBCUtils.safeGetInt(dbResult, "user_type_id");

            try (JDBCPreparedStatement dbStat = session.prepareStatement(
                        .stream().filter(type -> !type.isTableType()).toList(); //do not show table types in types list
        return computedPersisted;
                List<SQLServerDataType> schemaTypes = object.getTable().getSchema().getDataTypes(new VoidProgressMonitor())
import org.jkiss.dbeaver.Log;
    public String getDefaultValue() {
    }
        public Object[] getPossibleValues(SQLServerTableColumn object) {


 *
                throw new DBCException(e, session.getExecutionContext());
    @NotNull
    public Integer getPrecision() {
    }
            }
                return null;
    }
    }
                if (typeName.equals(SQLServerConstants.TYPE_NVARCHAR) || typeName.equals(SQLServerConstants.TYPE_NCHAR)) {
    SQLServerExtendedPropertyOwner {
    }
    @PropertyGroup()
        SQLServerTableBase table,
        return super.getDefaultValue();
    }
    @Property(editable = true, order = 76)
        setValueType(dataType.getTypeID());
    public Integer getScale() {
        return identityInfo;
        return SQLServerObjectClass.OBJECT_OR_COLUMN;
            this.maxLength = JDBCUtils.safeGetInt(dbResult, "max_length");
        }
        @Override
    @NotNull
    private IdentityInfo identityInfo = new IdentityInfo();
    @Nullable
                "SELECT seed_value,increment_value,last_value FROM " +
            // Copy
    public SQLServerTableColumn(
    public SQLServerDatabase getDatabase() {
    public void setComputedPersisted(boolean computedPersisted) {
    @NotNull
            return String.valueOf(userTypeId);

                dbStat.setLong(1, getTable().getObjectId());
        // Mark all identity columns as unique keys
import org.jkiss.dbeaver.model.impl.DBPositiveNumberTransformer;
    public void setDataType(@NotNull SQLServerDataType dataType) {
        setName(JDBCUtils.safeGetString(dbResult, "name"));
    public DBSObject refreshObject(@NotNull DBRProgressMonitor monitor) throws DBException {
    @Property(viewable = true, editable = true, updatable = true, order = 41)


    @Property(viewable = true, editable = true, order = 55)
    public boolean isComputedPersisted() {
                    identityInfo.loaded = true;
    @Nullable


        }
 * See the License for the specific language governing permissions and
    private int userTypeId;
    @Nullable
    }
        return description;
            this.defaultConstraintName = JDBCUtils.safeGetString(dbResult, "default_constraint_name");
    }
    public long getMaxLength() {
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
    }
 * limitations under the License.
    }
        public long getIncrementValue() {

import org.jkiss.dbeaver.ext.mssql.SQLServerConstants;
            default:
    public String getDefaultConstraintName() {
    private String description;
    // Extended Properties
    public Collection<SQLServerExtendedProperty> getExtendedProperties(@NotNull DBRProgressMonitor monitor) throws DBException {

                        identityInfo.incrementValue = CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "increment_value"));
        return getTable().getDataSource();
    private boolean hidden;
    public static class IdentityInfo {
    public String getFullTypeName() {
            return false;
    @Override
    @NotNull

    }
        if (!identityInfo.loaded) {
    private String defaultConstraintName;
    }

                dv = dv.substring(1, dv.length() - 1);
    SQLServerObject, JDBCColumnKeyType, DBSTypedObjectExt4<SQLServerDataType>, DBPRefreshableObject,
    @Property(viewable = true, editable = true, updatable = true, valueRenderer = DBPositiveNumberTransformer.class, order = 44)
        private boolean loaded;

            case 0:
    }
    }
        return typeModifiers == null ? typeName : (typeName + CommonUtils.notEmpty(typeModifiers));
        this.computedPersisted = computedPersisted;
    public boolean isHidden() {
    @Override
        public long getLastValue() {
    protected JDBCColumnKeyType getKeyType() {
        return hidden;
    public DBSDataType getDataType() {
    public static class IdentityInfoValidator implements IPropertyCacheValidator<SQLServerTableColumn> {
    @Override
        return super.isAutoGenerated();
            }

    @Override
        if (source instanceof SQLServerTableColumn) {
        String typeModifiers = SQLUtils.getColumnTypeModifiers(getDataSource(), this, typeName, dataType.getDataKind());

    }
        return false;
import java.util.List;
    @Override
                allTypes.addAll(schemaTypes);
 *

        }
    @Override
        SQLServerTableBase table,
        setPrecision(JDBCUtils.safeGetInteger(dbResult, "precision"));
        this.dataType = dataType;
    }
        private long lastValue;
        return isIdentity();
    @Property(viewable = false, order = 80)
    public void setCollationName(String collationName) {
    @Override
        return getTable().getDatabase();
        return dataType.getName().equals(SQLServerConstants.TYPE_TIMESTAMP);
    private boolean computedPersisted;
        this.description = source.getDescription();
        return this;
        return collationName;
    public String getDescription() {
    @LazyProperty(cacheValidator = IdentityInfoValidator.class)
    }

            this.setDefaultValue(dv);

        this.computedDefinition = JDBCUtils.safeGetString(dbResult, "computed_definition");
            } catch (SQLException e) {
        DBSEntityAttribute source)
        }


            case 2:
        return dataType == null ? DBPDataKind.UNKNOWN : dataType.getDataKind();
        return objectId;
    @Override
        setAutoGenerated(JDBCUtils.safeGetInt(dbResult, "is_identity") != 0);
    @Property(editable = true, order = 77)
    private String computedDefinition;
    @Override

import org.jkiss.dbeaver.model.sql.SQLUtils;
        this.description = description;
        if (this.maxLength == 0) {
    public SQLServerExtendedPropertyCache getExtendedPropertyCache() {
                identityInfo.loaded = true;
        return extendedPropertyCache.getAllObjects(monitor, this);
    }

    }
    @Override
    public boolean isTimestamp() {
    }
    }
    private SQLServerDataType dataType;
            SQLServerTableColumn mySource = (SQLServerTableColumn) source;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
            return object.identityInfo.loaded;
        // We have to do that to avoid treating computed column as an identity column (see #isAutoGenerated)

                        identityInfo.seedValue = CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "seed_value"));
 *     http://www.apache.org/licenses/LICENSE-2.0
    }




        if (dataType == null) {
import java.sql.SQLException;


        return this;
    }
    }
        try (JDBCSession session = DBUtils.openMetaSession(monitor, this, "Load column identity info")) {
        public boolean allowCustomValue() {

    }
        }
    @NotNull
    public boolean isInUniqueKey() {
    public boolean isInReferenceKey() {

        this.description = JDBCUtils.safeGetString(dbResult, "description");
    @Property(viewable = true, editable = true, updatable = true, order = 40, listProvider = DataTypeListProvider.class)
    }
            return seedValue;

    private void loadInfo(DBRProgressMonitor monitor, ResultSet dbResult)
    public String getTypeName() {
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
    @Override

        return getTable().getObjectId();

    }
            } else {
    @Nullable
    }
            case 1:
        if (!CommonUtils.isEmpty(dv)) {
    @Override
                    this.maxLength /= 2;
        loadInfo(monitor, dbResult);
    }
 * Licensed under the Apache License, Version 2.0 (the "License");

        super(table, source, false);
        extendedPropertyCache.clearCache();
        }
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

    @Property(viewable = false, order = 80)
    private void loadIdentityInfo(DBRProgressMonitor monitor) throws DBCException {
        return super.isAutoGenerated() || isTimestamp() || CommonUtils.isNotEmpty(getComputedDefinition());
    public boolean isRequired() {

        switch (level) {
            return incrementValue;
    }
package org.jkiss.dbeaver.ext.mssql.model;
        // Computed columns are "auto-generated" (from supplied definition)
    public void setIdentity(boolean identity) {
    }
    }
        if (getDataSource().supportsColumnProperty()) {
import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
            return lastValue;
    public long getMinorObjectId() {
    public long getMajorObjectId() {
    //////////////////////////////////////////////////
        if (this.dataType == null) {
    @Override
    }
 * You may obtain a copy of the License at
        throws DBException {
    }
    }
    @Property(viewable = true, editable = true, updatable = true, order = 70)
    private final SQLServerExtendedPropertyCache extendedPropertyCache = new SQLServerExtendedPropertyCache();
        }
        this.dataType = getTable().getDatabase().getDataTypeByUserTypeId(monitor, userTypeId);
    public void setDescription(String description) {
    @Override
    public boolean isAutoGenerated() {
    public Pair<String, SQLServerObject> getExtendedPropertyObject(@NotNull DBRProgressMonitor monitor, int level) {
    @Association
    public DBPDataKind getDataKind() {
                    SQLServerUtils.getSystemTableName(getTable().getDatabase(), "identity_columns") + " WHERE object_id=?")) {
        this.collationName = collationName;
        throws DBException {
        private long seedValue;

        }
        this.collationName = JDBCUtils.safeGetString(dbResult, "collation_name");
        return super.getMaxLength();
    private static final Log log = Log.getLog(SQLServerTableColumn.class);

    }
        public boolean isPropertyCached(@NotNull SQLServerTableColumn object, @NotNull Object propertyId) {
        }
                    // https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql#arguments
/**
        return dataType == null ? String.valueOf(userTypeId) : dataType.getTypeName();
        setRequired(JDBCUtils.safeGetInt(dbResult, "is_nullable") == 0);
    public void setComputedDefinition(String computedDefinition) {
    }
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.exec.DBCException;
        private long incrementValue;
    //@Property(viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
    @Override
                loadIdentityInfo(monitor);
import org.jkiss.utils.Pair;
        super(table, true);
            List<SQLServerDataType> allTypes = new ArrayList<>(object.getDataSource().getLocalDataTypes());
    public String getCollationName() {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
    private String collationName;

        throws DBException {
            if (maxLength > 0 && SQLServerUtils.isUnicodeCharStoredAsBytePairs(getDataSource())) {
        ResultSet dbResult)
    // Copy constructor
        return computedDefinition;
        this.hidden = JDBCUtils.safeGetInt(dbResult, "is_hidden") != 0;
    @Override
        @Nullable
import org.jkiss.dbeaver.ext.mssql.SQLServerUtils;
                    }
        }
 *
            while (dv.startsWith("(") && dv.endsWith(")")) {
        @Property(viewable = false, order = 60)
    public boolean isIdentity() {
        }


    }
    }
        return super.getScale();
        public long getSeedValue() {
 * SQLServerTableColumn
        String typeName = dataType.getName();

                        identityInfo.lastValue = CommonUtils.toLong(JDBCUtils.safeGetObject(dbResult, "last_value"));
    @Override
        this.typeName = dataType.getTypeName();

    @Override

}
        this.computedDefinition = computedDefinition;
import java.util.ArrayList;
    @Property(viewable = true, editable = true, updatable = true, order = 50)
import org.jkiss.utils.CommonUtils;


    }
    @Override
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    }
    @Override
                final String typeName = getTypeName();
import java.sql.ResultSet;
        setScale(JDBCUtils.safeGetInteger(dbResult, "scale"));
    }
    @NotNull
    public SQLServerObjectClass getExtendedPropertyObjectClass() {

        return super.isRequired();

        DBRProgressMonitor monitor,
public class SQLServerTableColumn extends JDBCTableColumn<SQLServerTableBase> implements
    DBSTableColumn, DBSTypedObjectEx, DBPNamedObject2, DBPOrderedObject, DBPHiddenObject,
        DBRProgressMonitor monitor,

        setOrdinalPosition(JDBCUtils.safeGetInt(dbResult, "column_id"));
        }

 */

    @Override
            return allTypes.toArray();
    private long objectId;
 */
import org.jkiss.dbeaver.model.struct.rdb.DBSTableColumn;
            }
                }
    }
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCColumnKeyType;
                }

    public String getComputedDefinition() {
            if (!isIdentity()) {
import org.jkiss.code.Nullable;
            this.maxLength = JDBCUtils.safeGetLong(dbResult, "char_max_length");
                return new Pair<>("Schema", getTable().getSchema());

    @Override
