
            defaultValue = JDBCUtils.safeGetString(dbResult, "default_value");
import org.jkiss.code.Nullable;
    }
        this.maxLength = JDBCUtils.safeGetInt(dbResult, "max_length");
        boolean isCursor = JDBCUtils.safeGetInt(dbResult, "is_cursor_ref") != 0;
    @Property(viewable = true, order = 2)
 * Licensed under the Apache License, Version 2.0 (the "License");

        boolean readonly = JDBCUtils.safeGetInt(dbResult, "is_readonly") != 0;
    private String defaultValue;
    @NotNull
    @NotNull
    }

    public SQLServerProcedureParameter(
    @Override

    public String getFullTypeName() {
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
/*
    @Override
    }
    private int precision;

    @Override
 * limitations under the License.
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;

    }
        return true;

    public String getName() {
        return false;

        this.paramName = JDBCUtils.safeGetString(dbResult, "name");
        return defaultValue;
    }
                (readonly ? DBSProcedureParameterKind.IN : DBSProcedureParameterKind.INOUT));
        int typeID = JDBCUtils.safeGetInt(dbResult, "user_type_id");
    public int getOrdinalPosition() {
}
    public boolean isPersisted() {
        this.defaultValue = defaultValue;
 *
    @Override
        return dataType.getTypeName();
 * DBeaver - Universal Database Manager
    @Override
    }

        return procedure.getDataSource();
    public long getMaxLength() {
    @Override

    private DBSProcedureParameterKind parameterKind;
/**
    public boolean isAutoGenerated() {

 */
 * Unless required by applicable law or agreed to in writing, software


    }
    }
    @Override
    public Integer getPrecision() {
        throws DBException
    {
        return paramName;
    public long getTypeModifiers() {
        return parameterKind;
    }

        return maxLength;
    }
    public DBSProcedureParameterKind getParameterKind() {
    public int getTypeID() {
    public DBPDataKind getDataKind() {
        if (JDBCUtils.safeGetInt(dbResult, "has_default_value") != 0) {
    @Override
    @NotNull
    private String paramName;
        return !nullable;
        this.precision = JDBCUtils.safeGetInt(dbResult, "precision");
    public String getDefaultValue() {
    @Override

        DBRProgressMonitor monitor,
 * you may not use this file except in compliance with the License.
    public SQLServerProcedure getParentObject() {
    }

        boolean isOutput = JDBCUtils.safeGetInt(dbResult, "is_output") != 0;
import org.jkiss.dbeaver.DBException;
    public SQLServerDataType getParameterType() {
        return dataType.getTypeID();
    @Override
 * distributed under the License is distributed on an "AS IS" BASIS,
        return dataType;

import org.jkiss.dbeaver.model.DBUtils;

    private SQLServerDataType dataType;
 * You may obtain a copy of the License at
        return scale;
            (isOutput ? DBSProcedureParameterKind.OUT :
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

        return ordinalPosition;
    @Nullable
    private int ordinalPosition;
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameterKind;
    @NotNull
    }
    @Property(viewable = true, order = 4)
    @NotNull
        nullable = JDBCUtils.safeGetInt(dbResult, "is_nullable") != 0;
    private int scale;
        return dataType.getDataKind();
        JDBCResultSet dbResult)
import org.jkiss.code.NotNull;
        this.parameterKind = isCursor ? DBSProcedureParameterKind.RESULTSET :
        return DBUtils.getFullTypeName(this);

    }
    public String getTypeName() {
    @Override
    private int maxLength;
    @Nullable
    }
    }

    private SQLServerProcedure procedure;

    @Property(viewable = true, order = 5)
 *     http://www.apache.org/licenses/LICENSE-2.0

        this.scale = JDBCUtils.safeGetInt(dbResult, "scale");
    @Override
import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
    }
public class SQLServerProcedureParameter implements DBSProcedureParameter, DBSAttributeBase, DBSObject {
    @NotNull
import org.jkiss.dbeaver.model.DBPDataKind;
 *

    public void setDefaultValue(String defaultValue) {
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
        return 0;
 * Copyright (C) 2010-2024 DBeaver Corp and others
        SQLServerProcedure procedure,
    public String getDescription() {
import org.jkiss.dbeaver.model.struct.DBSObject;
        return null;
    }
 */
    }
    @Property(viewable = true, order = 3)
    @Override
    public SQLServerDataSource getDataSource() {
 * See the License for the specific language governing permissions and
    }

    }
 * SQLServerProcedureParameter
    @Override

        this.dataType = procedure.getContainer().getDatabase().getDataTypeByUserTypeId(monitor, typeID);

        return procedure;
    }
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameter;
    @NotNull
package org.jkiss.dbeaver.ext.mssql.model;
 *
    public boolean isRequired() {
        }
        this.procedure = procedure;
        this.ordinalPosition = JDBCUtils.safeGetInt(dbResult, "parameter_id");
    public Integer getScale() {
    @Override
        return precision;
    @Override
    @Property(viewable = true, order = 1)
    @Override
import org.jkiss.dbeaver.model.meta.Property;
    private boolean nullable;

    @Override
