    @Property(viewable = true, order = 8)
        @NotNull SQLServerSchema catalog,
    @Nullable

            }
    }
        }
    private String typeDescription;
import org.jkiss.dbeaver.model.impl.AbstractExecutionSource;
        return getContainer().getTableCache().getChild(monitor, getContainer(), this, attributeName);

        }
        throws DBException
                }
    }
    }
        extendedPropertyCache.clearCache();
        }
        return getContainer().getTableCache();

                this);
    }
            return DBUtils.getFullQualifiedName(getDataSource(),
            enableIdentityInsert(session, false);
    }
        } catch (DBException e) {
        return false;
    public void afterDataChange(@NotNull DBCSession session, @NotNull DBSManipulationType type, @NotNull DBSAttributeBase[] attributes, @NotNull DBCExecutionSource source) throws DBCException {
        List<SQLServerTableColumn> columns = new ArrayList<>(childColumns);
        }
    }
    public SQLServerObjectClass getExtendedPropertyObjectClass() {

    private String type;
import org.jkiss.dbeaver.model.struct.*;
    private static final Log log = Log.getLog(SQLServerTableBase.class);
                this);
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable;
            }
        for (SQLServerTableTrigger trigger: schema.getTriggerCache().getAllObjects(monitor, schema)) {
    public SQLServerTableIndex getIndex(DBRProgressMonitor monitor, long indexId) throws DBException {
    @Override
        } else {
    @Property(viewable = true, order = 7)
                }
    /**
        for (SQLServerTableIndex index : getIndexes(monitor)) {
    public SQLServerTableColumn getAttribute(@NotNull DBRProgressMonitor monitor, @NotNull long columnId)
 *     http://www.apache.org/licenses/LICENSE-2.0
 * distributed under the License is distributed on an "AS IS" BASIS,
import org.jkiss.dbeaver.ext.mssql.SQLServerUtils;
            }

        if (rowCount != null || !isPersisted()) {
        return objectId;
 * Unless required by applicable law or agreed to in writing, software
        if (!supportsTriggers()) {
        super(schema, false);
                if (index.getIndexType() == DBSIndexType.CLUSTERED && index.isColumnStore()) {
    private boolean hasIdentityInsert(@NotNull DBSManipulationType type, @NotNull DBSAttributeBase[] attributes) {
    protected SQLServerTableBase(SQLServerSchema schema)
    public String getFullyQualifiedName(@NotNull DBPEvaluationContext context)
        } catch (SQLException e) {

    }
public abstract class SQLServerTableBase extends JDBCTable<SQLServerDataSource, SQLServerSchema>
    {
    }
        this.objectId = JDBCUtils.safeGetLong(dbResult, "object_id");
import org.jkiss.dbeaver.DBException;

    }
            getContainer().getTriggerCache().clearChildrenOf(this);
            }
        throws DBException
        Collection<SQLServerTableIndex> indexes = getIndexes(monitor);
        @NotNull ResultSet dbResult,
    @Override
    public String getTypeDescription() {
                "SET IDENTITY_INSERT " + getFullyQualifiedName(DBPEvaluationContext.DML) + " " + (enable ? " ON" : "OFF"));
            return Collections.emptyList();
        this.description = description;
        return SQLServerObjectType.S.name().equals(type);
    }
        }
    @Property(viewable = true, editable = true, updatable = true, length = PropertyLength.MULTILINE, order = 100)
 * Licensed under the Apache License, Version 2.0 (the "License");
    }
    protected SQLServerTableBase(
    private Date lastUpdate;
                } else if (attr.isAutoGenerated()) {
    @Override
    }
        if (supportsTriggers()) {
        if (rowCount == null) {
            if (index.getObjectId() == indexId) {
            case 0:
        return typeDescription;
    }
    }
    // Extended Properties
        return columns;
        try (DBCSession session = DBUtils.openMetaSession(monitor, this, "Read row count")) {
        rowCount = null;
        return null;
        }

        return null;
    }
    @Override
    public List<SQLServerTableTrigger> getTriggers(@NotNull DBRProgressMonitor monitor) throws DBException {
    public SQLServerDatabase getDatabase() {
    public long getObjectId() {
        try {
    {
    @Property(viewable = false, editable = false, order = 5)

 * Copyright (C) 2010-2025 DBeaver Corp and others

            log.debug("Can't fetch row count", e);
    public String getDescription() {

                triggers.add(trigger);
import org.jkiss.dbeaver.model.*;

    public boolean isSystem() {
    @Override
                getSchema(),
{
            if (CommonUtils.equalObjects(name, index.getName())) {
                return col;
            return Collections.emptyList();
    // Data manipulation handler
        }
    public long getMajorObjectId() {
    private String description;
import org.jkiss.code.NotNull;
        super(catalog, source, false);

    }
     * Returns true only in case the table is a table and has clustered columnstore index
    @NotNull
        return getSchema().getDatabase();
    @Association
     */
 *
    public DBSObject refreshObject(@NotNull DBRProgressMonitor monitor) throws DBException {
        return getObjectId();
        return extendedPropertyCache;
    }

    ////////////////////////////////////////////////////////
    @NotNull
    {
    public String getType() {
        return 0;
        }
/**
    {
        if (hasIdentityInsert(type, attributes)) {
        this.typeDescription = JDBCUtils.safeGetString(dbResult, "type_desc");

        return createDate;
    public SQLServerTableColumn getAttribute(@NotNull DBRProgressMonitor monitor, @NotNull String attributeName)
    @Association
    public void beforeDataChange(@NotNull DBCSession session, @NotNull DBSManipulationType type, @NotNull DBSAttributeBase[] attributes, @NotNull DBCExecutionSource source) throws DBCException {
        for (SQLServerTableIndex index : getIndexes(monitor)) {
        return lastUpdate;
    protected Long rowCount;

        return getContainer().getTableCache().refreshObject(monitor, getContainer(), this);
    }

    }
        if (!SQLServerUtils.supportsCrossDatabaseQueries(getDataSource())) {
        if (type == DBSManipulationType.INSERT) {
        if (!CommonUtils.isEmpty(indexes)) {
import org.jkiss.utils.CommonUtils;
import org.jkiss.dbeaver.model.struct.rdb.DBSIndexType;
import org.jkiss.dbeaver.model.exec.DBCExecutionSource;
            return DBUtils.getFullQualifiedName(getDataSource(),

        return getContainer();
    }
                if (attr instanceof SQLServerTableColumn && ((SQLServerTableColumn) attr).isIdentity()) {
        return extendedPropertyCache.getAllObjects(monitor, this);
    }
            return DBUtils.getFullQualifiedName(getDataSource(),
            if (col.getObjectId() == columnId) {
            JDBCUtils.executeStatement(
                this);
            for (DBSAttributeBase attr : attributes) {
package org.jkiss.dbeaver.ext.mssql.model;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
 *
        }
    }
            }
        if (childColumns == null) {


    @Override
    private void enableIdentityInsert(DBCSession session, boolean enable) throws DBCException {
    {
    //////////////////////////////////////////////////
                    return true;
 * you may not use this file except in compliance with the License.
        this.description = JDBCUtils.safeGetString(dbResult, "description");
        super(catalog, name, true);

    public Date getCreateDate() {
    // Copy constructor
        if (isView()) {
import java.sql.ResultSet;
                return index;
    private long objectId;
    @Override
    @Property(viewable = true, order = 6)
    }
    @Override
            if (this == trigger.getTable()) {
    @NotNull
import org.jkiss.dbeaver.model.exec.DBCException;
            return false;
 */
    {
            case 1:
        }
import org.jkiss.utils.Pair;
    }

        }
    @Override
        return SQLServerObjectClass.OBJECT_OR_COLUMN;

            throw new DBCException(e, session.getExecutionContext());

            for (SQLServerTableIndex index : indexes) {
    }
            // Older Azure doesn't support database name in queries
            return rowCount;
    public SQLServerSchema getSchema() {
        List<SQLServerTableTrigger> triggers = new ArrayList<>();
 * DBeaver - Universal Database Manager
        return rowCount;

    public SQLServerTableIndex getIndex(DBRProgressMonitor monitor, String name) throws DBException {

import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.Log;
        throws DBException
}
    }
import org.jkiss.dbeaver.model.exec.DBCSession;
    }
        this.createDate = JDBCUtils.safeGetTimestamp(dbResult, "create_date");
    public long getMinorObjectId() {
            default:
import org.jkiss.dbeaver.model.meta.PropertyLength;

    @NotNull
import org.jkiss.dbeaver.model.meta.Association;
        switch (level) {
            rowCount = -1L;
        log.error("Index '" + indexId + "' not found in table '" + getFullyQualifiedName(DBPEvaluationContext.DML) + "'");

    @Override
        return null;
        }
    public Pair<String, SQLServerObject> getExtendedPropertyObject(@NotNull DBRProgressMonitor monitor, int level) {
        return type;
    public JDBCStructCache<SQLServerSchema, ? extends JDBCTable, ? extends JDBCTableColumn> getCache()
    }


    }

    @Override
            rowCount = countData(new AbstractExecutionSource(this, session.getExecutionContext(), this), session, null, DBSDataContainer.FLAG_NONE);
    @NotNull
        if (isView() && context == DBPEvaluationContext.DDL) {
import org.jkiss.dbeaver.model.struct.rdb.DBSManipulationType;
        this.type = JDBCUtils.safeGetStringTrimmed(dbResult, "type");
    }
import org.jkiss.code.Nullable;
    }
    @Override
import java.sql.SQLException;
    public Collection<SQLServerTableIndex> getIndexes(@NotNull DBRProgressMonitor monitor)
        this.lastUpdate = JDBCUtils.safeGetTimestamp(dbResult, "modify_date");

    public Long getRowCount(DBRProgressMonitor monitor) throws DBCException
        }
    public void setDescription(String description) {

 * MySQLTable base
                (JDBCSession)session,
    private final SQLServerExtendedPropertyCache extendedPropertyCache = new SQLServerExtendedPropertyCache();
    }
                return new Pair<>("Table", this);
    @NotNull
import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache;
        }
import java.util.*;

        @NotNull String name)
    public Collection<SQLServerExtendedProperty> getExtendedProperties(@NotNull DBRProgressMonitor monitor) throws DBException {

    @Override
        List<SQLServerTableColumn> childColumns = getContainer().getTableCache().getChildren(monitor, getContainer(), this);
        return triggers;
 */
            }

        throws DBException
                return index;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
    public SQLServerExtendedPropertyCache getExtendedPropertyCache() {
    @Property(category = DBConstants.CAT_STATISTICS, viewable = false, expensive = true, order = 23)
    @Override

    public List<SQLServerTableColumn> getAttributes(@NotNull DBRProgressMonitor monitor)
    }


 *
        SQLServerSchema schema = getSchema();
    implements SQLServerObject, SQLServerExtendedPropertyOwner, DBPNamedObject2, DBPRefreshableObject, DBSObjectWithScript, DBPScriptObjectExt2, DBPSystemObject, DBSDataManipulatorExt
 * limitations under the License.
        return false;
        log.error("Column '" + columnId + "' not found in table '" + getFullyQualifiedName(DBPEvaluationContext.DML) + "'");
    }
        if (hasIdentityInsert(type, attributes)) {
    protected SQLServerTableBase(DBRProgressMonitor monitor, SQLServerSchema catalog, SQLServerTableBase source) throws DBException {
            enableIdentityInsert(session, true);
    {

/*
 * You may obtain a copy of the License at
        // Query row count
                    return true;
        }
    @Override
    private Date createDate;

        return description;
        log.error("Index '" + name + "' not found in table '" + getFullyQualifiedName(DBPEvaluationContext.DML) + "'");
    {
                getSchema(),
    @Override
    abstract boolean supportsTriggers();
        for (SQLServerTableColumn col : getAttributes(monitor)) {
                getDatabase(),

                getSchema(),
    public Date getLastUpdate() {
    @Override
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
                    return true;
        return this.getContainer().getIndexCache().getObjects(monitor, getSchema(), this);
        }
    {
    }
        }

 * See the License for the specific language governing permissions and
    @Association

        columns.sort(DBUtils.orderComparator());
        }
    boolean isClustered(@NotNull DBRProgressMonitor monitor) throws DBException {
        }
                return null;
                return new Pair<>("Schema", getSchema());
