package org.jkiss.dbeaver.ext.postgresql.model;
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/**
    PostgreAttributeIdentity(String code, String name, String definitionClause) {
 * Copyright (C) 2010-2025 DBeaver Corp and others
    @Override
 * You may obtain a copy of the License at
        return code;
 * you may not use this file except in compliance with the License.

    }

import org.jkiss.dbeaver.model.DBPNamedObject;
    private String name;
    private String definitionClause;

        this.definitionClause = definitionClause;
 * DBeaver - Universal Database Manager
        }
    public static PostgreAttributeIdentity getByCode(String code) {
    }
    public String getCode() {
 * distributed under the License is distributed on an "AS IS" BASIS,
 *
    }
    }
            }
        return null;
            if (id.code.equals(code)) {
import org.jkiss.code.NotNull;
 * Licensed under the Apache License, Version 2.0 (the "License");

    @NotNull

 * PostgreAttributeIdentity
 * Unless required by applicable law or agreed to in writing, software
 *     http://www.apache.org/licenses/LICENSE-2.0
    public String getName() {
        for (PostgreAttributeIdentity id : values()) {
    GENERATED_BY_DEFAULT("d", "By Default", "GENERATED BY DEFAULT AS IDENTITY");
 * See the License for the specific language governing permissions and
        return name;

 *
 */
    }
    GENERATED_ALWAYS("a", "Always", "GENERATED ALWAYS AS IDENTITY"),

}

        this.code = code;
 * limitations under the License.
/*
        return definitionClause;
public enum PostgreAttributeIdentity implements DBPNamedObject {
                return id;
 */
    public String getDefinitionClause() {
        this.name = name;
 *
    private String code;
