        return procedure;
        return defaultValue;
    public PostgreProcedure getParentObject()
    public PostgreProcedureParameter(
    public int getTypeID() {
    }
    }

    }
    public boolean isAutoGenerated() {
    @Property(viewable = true, order = 2)
    public int getOrdinalPosition() {

    @NotNull
    }
    @NotNull
    @Override

 */

    {
    @Override
        String paramName,
        return false;
    @Nullable
    public String getFullTypeName() {
    private PostgreDataType dataType;
        return dataType.getFullTypeName();
    @Override
    @Property(viewable = true, order = 3)
        @NotNull PostgreProcedure.ArgumentMode argumentMode,
 * DBeaver - Universal Database Manager
        return dataType.getScale();
    private PostgreProcedure procedure;
        this.defaultValue = defaultValue;
    @NotNull
    public PostgreDataType getParameterType() {
    }
    }
    }
    @Override
    public long getMaxLength() {

import org.jkiss.dbeaver.model.struct.DBSAttributeBase;
    }
    @Override
    {
        return procedure.getDataSource();

    public DBSProcedureParameterKind getParameterKind()
 * See the License for the specific language governing permissions and
    @NotNull
        this.ordinalPosition = ordinalPosition;
    public String getDescription() {
    @Override

    private String defaultValue;
/*
    public String getName() {
    public DBPDataKind getDataKind() {
        return null;
        return paramName;
 * Copyright (C) 2010-2024 DBeaver Corp and others
import org.jkiss.dbeaver.model.struct.DBSObject;
import org.jkiss.dbeaver.model.meta.Property;

    }



    @NotNull
import org.jkiss.code.NotNull;
 * Unless required by applicable law or agreed to in writing, software
    @Override

    public void setDefaultValue(String defaultValue) {
        return dataType.getMaxLength();
    @Property(viewable = true, order = 1)

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameterKind;
        return dataType.getTypeName();

    @Override
}
 * You may obtain a copy of the License at
    @Override
        return argumentMode;
    {
    @Override
package org.jkiss.dbeaver.ext.postgresql.model;
        PostgreDataType dataType,
 *     http://www.apache.org/licenses/LICENSE-2.0
    public PostgreDataSource getDataSource()
    @NotNull
    }
    private String paramName;
    public boolean isPersisted() {
 *

    private int ordinalPosition;


    }
    }
    {
 */
    @NotNull
 * you may not use this file except in compliance with the License.

        return dataType.getPrecision();
        return dataType;
    @Override
    public PostgreProcedure.ArgumentMode getArgumentMode() {
    public long getTypeModifiers() {
    public String getDefaultValue() {
    }
import org.jkiss.dbeaver.model.DBPDataKind;
 *
    @Override
    }
 * Licensed under the Apache License, Version 2.0 (the "License");
    @Nullable
        return true;
{

        return argumentMode.getParameterKind();
    public Integer getScale() {
    }
 * distributed under the License is distributed on an "AS IS" BASIS,
    public String getTypeName() {
/**
 * limitations under the License.
    }
        this.argumentMode = argumentMode;
    @Override
    }
        return 0;

        return false;
    public boolean isRequired() {
    @Property(viewable = true, order = 4)
    @Override
    @Override
        return ordinalPosition;
    }
        int ordinalPosition)
    @Property(viewable = true, order = 5)
    @Override
    private PostgreProcedure.ArgumentMode argumentMode;
        return dataType.getTypeID();
    @Override

        this.paramName = paramName;
 * PostgreProcedureParameter
import org.jkiss.code.Nullable;
    @Override
    }
        this.procedure = procedure;

        PostgreProcedure procedure,
public class PostgreProcedureParameter implements DBSProcedureParameter, DBSAttributeBase, DBSObject
    }
    public Integer getPrecision() {
        this.dataType = dataType;
    }

    }
import org.jkiss.dbeaver.model.struct.rdb.DBSProcedureParameter;
    @NotNull

 *
        return dataType.getDataKind();
